### ISSUE TITLE
 Issue 84:	persistentni identifikator pro generovana pdf a cachovani vygenerovanych pdf

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#1]
Reported by zabicka, Apr 3, 2011
Tento pozadavek vznikl z diskuse v rámci NDK:

Kramerius by mel podporovat generovana pdf v podobe perzistentniho linku (tohle mozna uz je ted?) ktery bude cachovany - takze casto pozadovane dokumenty by nemusely byt generovane porad dokola. Mozna by k tomu slo vyuzit memcached, ktery stejne pouzivame v image serveru? Asi by to melo smysl hlavne u pdf generovanych pro nejake logicke celky (celé svazky/čísla). 
Apr 7, 2011 Delete comment Project Member #1 pavel.stastny
Myslim, ze by pozadavek sel spojit se statickym exportem, ktery ma prave tu vlastnost, ze se provadi po logickych castech (periodikum, rocnik, vytisk, atd..).  Pokud by byl nad danou casti proveden export, objevila by se polozka v kontextovem menu "Stahnout jako PDF..".  

Persistentni pdf url by pak mohlo vypadat "../search/export?uuid=uuid:abcddee" nebo  ".../search/export/uuid:abcdeee" 

Slo by to takto ? 

Status: Accepted 
Aug 12, 2011 Delete comment Project Member #2 vlahoda
Šlo :-)
Owner: pavel.stastny 
Labels: -Priority-Medium Priority-Low 
Mar 27, 2012 Delete comment Project Member #3 vlahoda
Požadavku nebyla ani původním zadavatelem v současné diskusi o dalších prioritách přiřazena žádná váha, navíc by jeho implementace přinesla řadu komplikací, např. při změnách přístupových práv. V dohledné době není na pořadu dne.
Status: OnHold

**Comment by pavel-stastny** [comment]
Zatim nepodporovano...
