### ISSUE TITLE
K7 / Nelze vytvářet nové samostatné sbírky

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius#1000]
Verze: 7.0.29

Po kliknutí na "Vytvořit" novou sbírku mi to vyhodí nespecifikovanou chybu a sbírka se nevytvoří. Po downgrade na 7.0.27 mi sbírka jde normálně vytvořit.

Používám Docker image ceskaexpedice/kramerius:7.0.29. Ani v Adminclientovi, ani v logách nevidím žádný error.

**Comment by pavel-stastny** [comment]
@SPXcz Dobrý den, 

jako verzi admin klienta používáte a došlo k updatu schématu solr jádra search ?

**Comment by SPXcz** [comment]
Verze Adminclienta: 1.4.1

Solr MZK se měnil naposledy 19.7.

Ještě bych mohl zmínit, že importy fungují bez problémů. Problém je pouze u sbírek.

**Comment by pavel-stastny** [comment]
Je potřeba mít admin klienta verze [1.4.3](https://github.com/ceskaexpedice/kramerius-admin-client/releases/tag/v1.4.3), upgradovat shéma v solru  a přeindexovat sbírky.

**Comment by pavel-stastny** [comment]
@SPXcz Je možno zavřít ?

**Comment by zabak** [comment]
@SPXcz zavírám, pokud je stále problém, tak to zase otevři.
