### ISSUE TITLE
K5 / Chyba při nastavení Public v 5.8

### ISSUE THREAD

**Issue by klodner** [ceskaexpedice/kramerius#1002]
Úloha
 Priznak  'public pro titul uuid:6a442468-e369-4079-9d1e-bdb06913f880  Set public

končí chybou  java.lang.NoSuchFieldError: REFLECTION

Což je pravděpodobně nějaký konflikt knihoven v K5.8 (v 5.7 funguje)
https://stackoverflow.com/questions/25765238/java-lang-nosuchfielderror-reflection

> Zář 15, 2023 3:17:26 ODP. cz.incad.kramerius.processes.impl.ProcessStarter main
> SEVERE: null
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:124)
> Caused by: java.lang.NoSuchFieldError: REFLECTION
> 	at com.sun.xml.ws.model.WrapperBeanGenerator.&lt;clinit&gt;(WrapperBeanGenerator.java:72)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:264)
> 	at com.sun.xml.ws.model.RuntimeModeler.&lt;clinit&gt;(RuntimeModeler.java:1645)
> 	at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:658)
> 	at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:649)
> 	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:343)
> 	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:326)
> 	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:308)
> 	at javax.xml.ws.Service.getPort(Service.java:119)
> 	at org.fedora.api.FedoraAPIAService.getFedoraAPIAServiceHTTPPort(FedoraAPIAService.java:52)
> 	at cz.incad.kramerius.impl.FedoraAccessImpl.initAPIA(FedoraAccessImpl.java:774)
> 	at cz.incad.kramerius.impl.FedoraAccessImpl.getAPIA(FedoraAccessImpl.java:751)
> 	at cz.incad.kramerius.service.impl.PolicyServiceImpl.setPolicyDC(PolicyServiceImpl.java:89)
> 	at cz.incad.kramerius.service.impl.PolicyServiceImpl.setPolicyForNode(PolicyServiceImpl.java:83)
> 	at cz.incad.kramerius.service.impl.PolicyServiceImpl.setPolicy(PolicyServiceImpl.java:73)
> 	at cz.incad.kramerius.service.impl.PolicyServiceImpl.main(PolicyServiceImpl.java:206)
> 	... 5 more

**Comment by pavel-stastny** [comment]
@klodner Dobrý den, 

potřebovali bychom upřesnit: 

1. Zda používáte docker image nebo se jedná standardní instalaci? 
2. Verzi javy.

**Comment by klodner** [comment]
Je to starší instalace

Server version: Apache Tomcat/8.0.14 (Debian)
Server built:   Sep 15 2017 03:02:58
Server number:  8.0.14.0
OS Name:        Linux
OS Version:     3.16.0-4-amd64
Architecture:   amd64
JVM Version:    1.8.0_144-b01
JVM Vendor:     Oracle Corporation

**Comment by vlahoda** [comment]
Kramerius je od verze 5.8.0 kompilovan pod JDK 11, proto dochazi k tomu konfliktu knihoven JAXB, o kterem pisete. Zkuste prejit na JDK 11 nebo pouzijte docker image ceskaexpedice/kramerius:5.8.3, ktery bezi pod JDK 11

**Comment by pavel-stastny** [comment]
@klodner Bohužel s tím takto na dálku nedokážem nic udělat.  Můžeme uzavrít ?

**Comment by klodner** [comment]
Jenom si nejsem jistý jestli to v popisu instalace (JDK 1.6) odpovídá
https://github.com/ceskaexpedice/kramerius/wiki/Instalace-verze-K5

V Changelogu 5.8 je "support for Java 11" - mělo by být že je vyžadováno
https://github.com/ceskaexpedice/kramerius/releases/tag/v5.8.0

Jinak děkuji za odpověď samozřejmě a může být uzavřeno.

**Comment by pavel-stastny** [comment]
Díky, wiki změněna.  Zavírám
