### ISSUE TITLE
K7 / Import METS balčků  - po ukončení procesu smazat data z adresáře converted

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#1005]

**Comment by pavel-stastny** [comment]
@mduda100871  Řízeno proměnnou `convert.deleteContractSubfolders`. Defaultní hodnota je `true`

**Comment by mduda100871** [comment]
Vyzkoušeno, vypadá to zatím dobře.

Propertu jsem uložil do konfiguračního souboru `~/.kramerius4/migration.properties`.

S hodnotou true to maže, s hodnotou false konvertovaná data zůstávají v pracovním adresáři `~/.kramerius4/convert-converted`.

MD

**Comment by pavel-stastny** [comment]
#908
