### ISSUE TITLE
K7/ solr 9 core logs necommituje

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius#1008]
Ahoj, 
včera sme prešli zo Solr 8 na Solr 9 a dnes keď som kontroloval či sa v poriadku odoslali NKP logy, tak som narazil na to, že sa vygenerovali logy iba od polnoci do 9 rána. Následne som skontroloval či funguje správne logovanie, a ukázalo sa, že solr core logs sa včera od 9 rána do dnes do 17tej ani raz necommitol. Tak som ho commitol manuálne a pribudlo 62000 záznamov. Novo vygenerované štatistiky už obsahujú záznamy z celého dňa.

Róbert, MZK - OSDD

**Comment by pavel-stastny** [comment]
@r2it-git  Do konfigurace pro jádro logs doplněna konfigurace. Autocommit pro jedné minutě.
