### ISSUE TITLE
Licence u sbírek

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#1015]
V K7 při použití zobrazování podle licencí nejsou vidět když filtruju na nějakou konkrétní licenci. Sbírky totiž by default žádnou licenci nemají, takže volbou jakékoli licence ve fasetách zmizí z výsledků vyhledávání. Dá se to řešit tím že se jim explicitně nějaká licence nastaví, ale pokud bereme sbírku jako objekt, tak by měla mít automaticky label public. Lepší by bylo, kdyby dědila všechny licence v ní obsažených objektů.

Jak tohle nejlépe řešit?

**Comment by pavel-stastny** [comment]
No, ona ta dědičnost tady funguje obráceně.  Nadřazený objekt je sbírka. Navíc zde se nejedná o licenci ve smyslu přístupu ale způsobu filtrovaní v klientovi.  Toto bude na domluvu s @honza-rychtar

**Comment by zabak** [comment]
@pavel-stastny je nutné ty sbírky nějak reindexovat? Honza to řešil v https://github.com/ceskaexpedice/kramerius-web-client/issues/538 a zdá se mi, že v těch sbírkách jen chybějí v solru příslušná pole, která by tam mělo dávat jádro.

**Comment by sonaves26** [comment]
Dobrý den,

prosím smažte mě z odebírání zpráv tohoto vlákna. Už v národním muzeu
nepracuji.
Děkuji.

S pozdravem
Soňa Veselá

čt 1. 2. 2024 v 14:21 odesílatel Petr Žabička ***@***.***>
napsal:

**Comment by zabak** [comment]
@sonaves26 odběr si musíte zrušit sama, protože jste si to sma musel zapnout.

In the left sidebar, under the list of repositories, select the "Manage notifications" dropdown menu and click Subscriptions. Select the notifications you want to unsubscribe from. In the top right, click Unsubscribe.

**Comment by zabak** [comment]
duplicitní s #873, tohle zavírám
