### ISSUE TITLE
Globální licence pro osiřelá díla

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#1026]
Prosím o zařazení licence pro osiřelá díla (`orphan`) mezi globální licence distribuované v rámci buildu.

Text k licenci je zde:[https://github.com/ceskaexpedice/kramerius/wiki/Osi%C5%99el%C3%A1-d%C3%ADla](https://github.com/ceskaexpedice/kramerius/wiki/Osi%C5%99el%C3%A1-d%C3%ADla). Zároveň je tam odkaz na podrobnější informace určené pro knihovny.

Děkuji!

**Comment by pavel-stastny** [comment]
@kerschfilip Je součástí releasu 7.0.31

**Comment by pavel-stastny** [comment]
@kerschfilip Je součástí distribuce 

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/096cdd63-c86f-4192-8631-cb958ece9c9c)


V případě potřeby znovu otevři.
