### ISSUE TITLE
Přehrávání zvukových souborů na pozadí

### ISSUE THREAD

**Issue by katerinasirova** [ceskaexpedice/kramerius#1028]
Při přehrávání zvukových souborů umožnit prohlížení dalšího obsahu digitální knihovny. Zachovat možnosti ovládání přehrávačky - viz funkcionalita na Kramerius Music.

**Comment by vlahoda** [comment]
Toto patri spis do projektu web klienta, presunul jsem to tam: https://github.com/ceskaexpedice/kramerius-web-client/issues/693
