### ISSUE TITLE
Detekce nevalidních titulů v úložišti

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1031]
Při importu nevalidních dat, při reimportu pozměněnýho titulu bez předchozího odmazání toho původního nebo při ručním odmazávání objektů může dojít k tomu, že v úložišti zůstanou viset tituly, který se odkazujou na neexistující objekty. Hodil by se proto nástroj, kterej projde celý úložiště, ověří validitu všech titulů a vypíše identifikátory (uuid, signatura) kořenových objektů těch nevalidních, aby je administrátor mohl odmazat a reimportovat.

**Comment by pavel-stastny** [comment]
Pro potřeby MZK vyřešeno, bude přítomno v rámci lednového release.
