### ISSUE TITLE
Špatně se nám indexují roky vydání u některých dokumentů

### ISSUE THREAD

**Issue by kvetjo** [ceskaexpedice/kramerius#1033]
Zdravím,

na Ústřední knihovně UK jsme objevili v našem Krameriu problém, který se týká indexace dat do SOLRu. Tento problém se pak dále projevuje tím, že Kramerius nenachází dokumenty po filtrování/vyhledávání, které by nacházet měl.
Konkrétně se náš problém týká indexace roků vydání. Problematické tvary jsou zpravidla následující: [mezi 1935 a 1939], [1937], [ca 1920] a podobně. (nicméně našel jsem i několik příkladů jednoduchého tvaru zápisu letopočtu například zde: [https://kramerius.cuni.cz/uk/uuid/uuid:8c5807b8-a6b2-11ec-964f-fa163e4ea95f](https://kramerius.cuni.cz/uk/uuid/uuid:8c5807b8-a6b2-11ec-964f-fa163e4ea95f). Většinu tvoří však ty komplikovanější tvary.)
V záznamu MODS bývají datumy zapsané správně :
```
<mods:dateIssued>[mezi 1935 a 1939]</mods:dateIssued>      
<mods:dateIssued encoding="marc" point="start" qualifier="questionable">1935</mods:dateIssued>      
<mods:dateIssued encoding="marc" point="end" qualifier="questionable">1939</mods:dateIssued>
```
problém tak nastává, když se tyto MODSový data překlápějí do SOLRu, kde to vypadá následovně:
```
"datum_begin": 0,   
"datum_end": 0,
"datum_str": "[mezi 1935 a 1939]",
```
Všechny problematické dokumenty, kterých se to týká, je možné najít zde:
[https://kramerius.cuni.cz/search/api/v5.0/search?q=fedora.model:map+AND+datum_begin:0&wt=xml&start=0&rows=10&fl=PID,datum_str,rok,datum_begin,datum_end](https://kramerius.cuni.cz/search/api/v5.0/search?q=fedora.model:map+AND+datum_begin:0&wt=xml&start=0&rows=10&fl=PID,datum_str,rok,datum_begin,datum_end)

Chtěl bych se zeptat především na to, jak tento problém můžeme vyřešit? Případně i čím to může být způsobený? Zkoušel jsem obyčejnou reindexaci, to bohužel nezabírá. V tuto chvíli se problém týká více než 14369 dokumentů, především se jedná o mapovou sbírku, ale ne výlučně. 

Děkuji moc za pomoc,

S pozdravem
Jonáš Květ
Ústřední knihovna Univerzity Karlovy

**Comment by zabak** [comment]
Doporučuji přejít na K7, tam je tohle řešené líp.

**Comment by mjtecka** [comment]
> Doporučuji přejít na K7, tam je tohle řešené líp.

Nás by právě zajímalo jestli je tam vyřešené i tohle konkrétně, nebo jen něco podobného (a když přejdeme na K7, tak se nám to stejně neopraví:-) ).

**Comment by zabak** [comment]
Je to popsané tady: https://github.com/ceskaexpedice/kramerius/wiki/Vyhled%C3%A1vac%C3%AD-index - konkrétně ta rozmezí byla už v indexeru v. 4.
