### ISSUE TITLE
K7 - statistiky pro NIPOS (was: stahování csv se statistikami pro všechny dokumenty)

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1039]
Zdravím,

kolega, který v MKP zpracovává statistiky z Kraméria, prosí o přidání možnosti stažení csv pro všechny dokumenty zobrazené za určené období s následujícími hodnotami:

uuid, model, count, title_name

Splní to nejdůležitější požadavek na odevzdávání počtu všech stažení za určené období (stačí posčítat count), přes uuid se provazují starší statistiky (například z doby před K7) a sloupec model umožní filtrovat statistiky podle modelů.

Určitě nevadí, když bude hodnot na řádku víc (například viditelnost/licence), sloupce navíc jde při zpracování snadno odfiltrovat.

Souvisí s #515, nejspíš i #394.

Výhledově by bylo fajn zahrnout to do automatizace zasílání statistik e-mailem (#732).

**Comment by vlahoda** [comment]
Vsechny pozadovane informace jsou k dispozici v zalozce Generovani logu pro NK, v prave casti je tlacitko ke stazeni vygenerovanych logu. Jediny rozzdil oproti vasemu pozadavku je, ze logy jsou ve formatu JSON a ne CSV.
 
<img width="1575" alt="image" src="https://github.com/ceskaexpedice/kramerius/assets/1308698/ab2b1dfe-9eb3-4184-bccf-fa82ef19334d">

**Comment by zabak** [comment]
@svetlym doporučuji zapojit se do aplikace statistiky NDK, navrhuji toto zavřít

**Comment by svetlym** [comment]
Statistiky jsme probírali na včerejší vývojářský schůzce a panoval tam názor, že možnost jednoduchýho a standardizovanýho generování statistik pro NIPOS by měla bejt přímo v adminovi Kraméria.

Možná by šlo přejmenovat issue, aby to z něj bylo jasnější?

**Comment by pavel-stastny** [comment]
@svetlym Až budete mít nainstalováno, dejte vědět zda statistiky odpovídají tomu co je potřeba vykazovat pro NIPOS.  Je to ta samá funkcionalita co byla v K5.

**Comment by svetlym** [comment]
Dobrý den,

já jsem na vás nezapomněl. Zeptal jsem se na to kolegů, kteří statistiky používají, bohužel se z toho ale vyvinula obecná debata o statistikách a nedaří se mi vypáčit z nich jasnou odpověď, jestli je výkaz pro NIPOS v pořádku nebo ne. Takže se omlouvám, pravděpodobně je to ok, ale jednoznačně to potvrdit nemůžu.
