### ISSUE TITLE
v K7 se neloguje IP adresa

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#1043]
Při logování se do SOLR posílá záznam, který (zkrácený) vypadá nějak takto:
```
<?xml version="1.0" encoding="UTF-8"?>
<add>
    <doc>
        <field name="id">f9a12e2b-2efd-4ad7-8185-ba40fb3ccc23</field>
        <field name="pid">uuid:0738b5a5-64b4-4480-b7c1-10bb52e13fae</field>
        <field name="ip_address"/>
        <field name="requested_url">http://tomcat.kramerius.trinera.cloud/search/api/client/v7.0/items/uuid:0738b5a5-64b4-4480-b7c1-10bb52e13fae/image</field>
        <field name="root_title">[Brno: dům U tří kohoutů]</field>
    </doc>
</add>
```
Jde o prázdnou hodnotu ip_address.
Při exportu logů to pak znamená prázdné pole _remoteAddr_, protože v NKPLogReport se děje tohle:
`map.put("remoteAddr", obj.optString("ip_address"));`

Ten xml záznam pro import do SOLR se vyrábí mmj. v třídě cz.incad.kramerius.statistics.accesslogs.LogRecord.
Je tam setter `public void setIpAddress(String ipAddress)`

Když doplním v _cz.incad.kramerius.statistics.accesslogs.solr.SolrStatisticsAccessLogImpl.reportAccess()_ tohle:
``` 
logRecord.setIpAddress(requestProvider.get().getRemoteAddr());
``` 
už se začne ip_address při logování plnit, jenže takto:
`<field name="ip_address">127.0.0.1</field>`

To ještě pořád není ono, za tohle může reverzní proxy (zde Apache).
Když ale povolím předávní hlavičky X-Forwarded-For (u Apache přes remoteip) a změním kód takto:
```         //logRecord.setIpAddress(requestProvider.get().getRemoteAddr());
        if(requestProvider.get().getHeader("X-Forwarded-For")!=null){
            String remoteIp = requestProvider.get().getHeader("X-Forwarded-For");
            logRecord.setIpAddress(remoteIp);
        }
``` 
už dostanu v ip_address skutečnou adresu:
`<field name="ip_address">2a06:98c0:3600::103, 172.68.213.87</field>`
Není mi teda jasné, kde se bere ta hodnota **2a06:98c0:3600::103**, ale **172.68.213.87** je správně.

**Comment by pavel-stastny** [comment]
@rzeh4n Mělo by stačit využít metody `cz.incad.kramerius.utils.IPAddressUtils.getRemoteAddress`, která očekává parametry HttpServletRequest a objekt Configuration: 
```
IPAddressUtils.getRemoteAddress(this.provider.get(), KConfiguration.getInstance().getConfiguration())
```

Reveznní proxy pak musí být povolena konfigurační proměnnou: 
```
x_ip_forwared_enabled_for=<adresa_proxy_regexp>
```

Komitnes zmenu ?
