### ISSUE TITLE
K7 / problém s migrací public/private příznaků na licence v případě nasazení indexu v SolrCloudu

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#1053]
Zdravím,

narazil jsem na problém s migrací public/private příznaků na licence v případě použití SolrCloudu.

Pokus o vyvolání příslušného procesu v admin rozhraní K7 končím chybou:

![migrace-00](https://github.com/ceskaexpedice/kramerius/assets/8750622/4de6fc10-33b9-44a0-bdea-0ea6cb24c7e3)

[process_695_err.txt.zip](https://github.com/ceskaexpedice/kramerius/files/14791607/process_695_err.txt.zip)

Je potřeba upravit dotaz tak, aby se v poli `sort` použila hodnota `compositeId`, příklad simulace z příkazové řádky:
```
curl 'http://<IP adresa / jmeno SolrCloudu>:8983/solr/search/select?q=model%3A%28monograph+OR+monographunit+OR+periodicalvolume+OR+manuscript+OR+soundrecording+OR+convolute+OR+map+OR+sheetmusic+OR+graphic+OR+archive+OR+convolute%29+AND+accessibility%3A*&rows=1000&cursorMark=*&sort=compositeId+asc&fl=pid+root.pid+accessibility+model&wt=xml'
```
V původním dotazu, který je určen pro single instanci Solru, obsahuje pole `sort` hodnotu `pid`.

MD

**Comment by pavel-stastny** [comment]
Jenom dodám, jedná se o podporu pro solr cloud.
