### ISSUE TITLE
K7 / chyba pri dávkových procesoch - batch token violates unique constraint

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius#1056]
Ahoj,

vo verzií 7.0.34 som narazil na bug. Niektorým import procesom sa nastaví príznak FAILED aj keď skončia bez chyby. Je to viditeľné napríklad pri týchto 2och procesoch [895876](https://admin.kramerius.mzk.cz/processes/standard-output/895876) a [895878](https://admin.kramerius.mzk.cz/processes/standard-output/895878) (celkovo som to za dnes narátal pri 6tich import procesoch). V logoch procesov žiadna chyba nie je.

Z logov Kraméria je vidno, že to spôsobuje toto:
```03-Apr-2024 14:49:27.563 WARNING [cz.incad.kramerius.processes.impl.GCSchedulerImpl-thread] cz.incad.kramerius.processes.GCCheckFoundCandidatesTask.run changing state of process 'fd8e41c7-0ab7-4789-ba9a-345f00138a22' to FAILED```
A predtým chyba:
```03-Apr-2024 14:48:15.349 SEVERE [http-nio-8080-exec-28] cz.incad.kramerius.processes.impl.DatabaseProcessManager.updateLongRunningProcessName ERROR: duplicate key value violates unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(0c32bc16-f259-4351-b427-7e33b622e0bd) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
        batch_state(processes.status) AS batch_state,
        count(*) AS process_count,
...
PL/pgSQL function refresh_process_batch() line 17 at SQL statement
	org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "process_batch_pkey"
  Detail: Key (batch_token)=(0c32bc16-f259-4351-b427-7e33b622e0bd) already exists.
  Where: SQL statement "INSERT into process_batch
    SELECT
        processes.token AS batch_token,
...
```

UUID 0c32bc16-f259-4351-b427-7e33b622e0bd je identifikátor dávky (batch), v ktorej sa nachádza proces fd8e41c7-0ab7-4789-ba9a-345f00138a22.

To by teda dávalo zmysel, akurát ma zarazila jedná vec a to, že počet chýb `duplicate key value violates unique constraint ` je v Kramérius logoch vyšší ako je počet procesov, ktorým sa nastaví FAILED. 

Prikladám logy z Kraméria a z tých dvoch spomínaných procesov.

[catalina.2024-04-03_cropped.log](https://github.com/ceskaexpedice/kramerius/files/14855286/catalina.2024-04-03_cropped.log)
[895876_out.txt](https://github.com/ceskaexpedice/kramerius/files/14855309/895876_out.txt)
[895877_out.txt](https://github.com/ceskaexpedice/kramerius/files/14855310/895877_out.txt)
[895878_out.txt](https://github.com/ceskaexpedice/kramerius/files/14855312/895878_out.txt)
[895879_out.txt](https://github.com/ceskaexpedice/kramerius/files/14855313/895879_out.txt)

Róbert Randiak, MZK - OSDD

**Comment by pavel-stastny** [comment]
@r2it-git Myslím, že to je stejný problém jako je popsaný zde: #897

**Comment by vlahoda** [comment]
Fixed in [4075ed0](https://github.com/ceskaexpedice/kramerius/commit/4075ed00d747b7e18873bb02b7c6dbf6334f95f4)
