### ISSUE TITLE
Neexistující stránky v Krameriu

### ISSUE THREAD

**Issue by synkver** [ceskaexpedice/kramerius#1057]
Dobrý den,

náhodou jsme si všimli, že nám v Krameriu visí nějaké neexistující stránky. Vyhledají se, ale po kliknutí na stránku se zobrazí, že stránka nebyla nalezena. 
![image](https://github.com/ceskaexpedice/kramerius/assets/166374598/cba2e7c4-cf39-4003-8e50-cb52ea71e8fc)
![image](https://github.com/ceskaexpedice/kramerius/assets/166374598/25d75d2f-02cf-446a-a1e2-9c9f54495db7)

Podle UUID sice mohu stránku vyhledat v administraci, ale při pokusu o zobrazení metadat se nezobrazuje nic, jen tam "běhá kolečko", že se systém snaží. 
![image](https://github.com/ceskaexpedice/kramerius/assets/166374598/80b43562-9074-4063-b69d-21a5ccf25cc8)

Prosím o radu, jak vyhledat všechny takové stránky a jak zjistit, jak je v Krameriovi opravit nebo odstranit. Takhle mi to na první pohled připadá, že je buď špatně nahraná stránka do Krameria, nebo byla stránka smazaná a to zřejmě jen z Fedory a nikoliv v indexu. Ale nevím, jak jedno nebo druhé ověřit a co s tím dál. Předem děkuji za pomoc. 

VS

**Comment by pavel-stastny** [comment]
Vyřešeno separátně přes maily. @synkver Je možné zavřít?
