### ISSUE TITLE
tlačítko "hledání v dokumentu" - chování šipek, kláves Home, End

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#106]
Pokud při zobrazení stránky přepnu v levém menu na "hledání uvnitř dokumentu" a v rámci vstupního pole pro zadání výrazu pro vyhledávání použiju klávesy Home nebo End, nebo dokonce šipky, tak se nepohybuje kurzor ve vstupním poli, ale hýbe se obrázek v panelu náhledů zleva doprava a naopak.
Jde o stránky, pro které se použije OpenLayers.
Např. tento dokument:
http://kramerius.mzk.cz/search/handle/uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22

Chrome 35.0.1916.153

**Comment by pavel-stastny** [comment]
tyka se admin rozhrani - bude pristi rok reimplementovano
