### ISSUE TITLE
K7 v7.0.33 a výše - problém při komunikaci s imageserverem přes Zoomify na některých systémech

### ISSUE THREAD

**Issue by tomik13** [ceskaexpedice/kramerius#1068]
Dobrý den,
instaluji Kramerius 7 v Národí technické knihovně.

Od verze 7.0.33 nám na některých systémech nefunguje správně načtení souboru ImageProperties.xml z imageserveru.
Když je klient nastavený na používání Zoomify, nenačítají se obrázky stran:
![Screenshot from 2024-07-16 15-09-50](https://github.com/user-attachments/assets/7290a134-cce5-4240-8828-ad598e5b4acc)

A samotné jádro Krameria na endpointu `/api/client/v7.0/items/<uuid>/image/zoomify/ImageProperties.xml` vrací chybu:
```
org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
	org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
	org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
	org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	cz.incad.kramerius.rest.apiNew.client.v70.ZoomifyHelper$1.write(ZoomifyHelper.java:273)
	com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:67)
	cz.incad.kramerius.auth.thirdparty.ExtAuthFilter.doFilter(ExtAuthFilter.java:67)
	cz.incad.kramerius.keycloak.KrameriusKeycloakFilter.doFilter(KrameriusKeycloakFilter.java:186)
	cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:31)
	cz.incad.kramerius.auth.basic.AuthFilter.basicAuth(AuthFilter.java:123)
	cz.incad.kramerius.auth.basic.AuthFilter.doFilter(AuthFilter.java:87)
	cz.incad.Kramerius.XSSFilter.doFilter(XSSFilter.java:36)
	cz.incad.Kramerius.ClientClosedRequestFilter.doFilter(ClientClosedRequestFilter.java:25)
```

Imageserver při přímém dotazu vrací soubor ImageProperties.xml bez problémů, Kramerius naopak vrací stejnou chybu i při připojení na jiný imageserver.

Při používání protokolu iiif vše běží bez problémů.

**Popis prostředí:**

OS: RHEL9
8GB RAM
2 jádra CPU

Tomcat 9.0.89
Java: OpenJDK Runtime Environment (Red_Hat-11.0.23.0.9-2)

Instalace na jiných strojích fungují různě. Na testovacím serveru s RHEL8 a čtyřmi jádry funguje vše správně, na pokusné instalaci na laptopu s Fedorou nastává stejný problém.

**Comment by vlahoda** [comment]
Dobry den, domnivam se, ze ve verzi 7.0.35 je to uz vyreseno. V kazdem pripade ale doporucuji pouzivat protokol IIIF.

**Comment by tomik13** [comment]
Zdravím a děkuji. Provedl jsem update a opravdu to funguje, omlouvám se za spam.

**Comment by vlahoda** [comment]
Dekuji za potvrzeni - pri prechodu na nove API v7.0 se nam "podarilo" nekolik chyb, trefili jste bohuzel jednu z nich. V kazdem pripade ale pouzivejte IIIF, nektere funkce GUI bez toho vubec nebudou k dispozici, podpora Zoomify je tam jen kvuli zpetne kompatibilite.

**Comment by tomik13** [comment]
Děkuji a beru na vědomí, používání IIIF plánujeme, zoomify jsem zkoušel hlavně kvůli tomu, že se teď zdá, že na něm funguje ČDK.
