### ISSUE TITLE
K7 - crash

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1069]
5\. 7. 2024 nám crashnul Kramérius 7 (verze 7.0.31). Podle logů to vypadá, že došla paměť.

Přikládám i log z následnýho startu (8. 7.). Je tam pár zpráv ve stylu "This is very likely to create a memory leak", možná to souvisí.

[Crashlog.zip](https://github.com/user-attachments/files/16266663/Crashlog.zip)

**Comment by vlahoda** [comment]
Ano, spadlo to s OutOfMemory error. Mozna by stalo za to pridat RAM nebo alespon zvetsit heap pro Tomcat. Podle logu mate 8GB RAM a 2GB max heap. Take by bylo vhodne aktualizovat Krameria na soucasnou verzi 7.0.35.
Ty hlasky "This is very likely to create a memory leak" patri jeste do faze, kdy se zastavoval ten havarovany Tomcat a nejsou pricinou toho padu, ale az nasledkem.

**Comment by svetlym** [comment]
Děkuju za odpověd.

Předpokládám, že velikost heapu se nastavuje v docker-compose.yml přidáním `- JAVA_OPTS="-Xmx4G"` pro Kraméria?

Jakou hodnotu doporučujete pro velikost heapu a pro velikost RAMky?

Verzi už jsme aktualizovali.

**Comment by vlahoda** [comment]
Ano, muzete take zvysit pocatecni heap pomoci -Xms. Velikosti pameti je potreba sledovat za provozu, krome Tomcatu Krameria je take potreba doladit heap pro Solr a pripadne nastaveni procesu importu nebo indexace, pokud se pracuje s vetsimi dokumenty.

**Comment by svetlym** [comment]
Pro solr jste nám při instalaci nastavili `- JAVA_OPTS="-Xms2G -Xmx4G"`. Pro kramerius nebylo nastaveno nic, dám to teda stejně jako pro solr.

S velkými dokumenty určitě pracujeme (například mamutí Večerní Praha). To se nastavuje kde?
