### ISSUE TITLE
Textace hlášení DNNT v Krameriovi

### ISSUE THREAD

**Issue by jankanka** [ceskaexpedice/kramerius#1081]
Považuji za poměrně něšťastnou textaci hlášky, která se zobrazí při pokusu o zobrazení stránek z dokumentů licence DNNT. Zejména první nejsilnější informace - je negativní, varovná, vlastně nepravidvá a v kontextu se zbytkem textu v rozporu. Celkově je to info velmi těžko srozumitelné i pro odbornou, neřkuli laickou veřejnost. Pokud se správně domnívám, není navíc textace tohoto hlášení lokálně nastavitelná.

**K tomuto dokumentu nemáte přístup**
Dokument je dostupný pod licencemi:
Díla nedostupná na trhu - online (1)
Pro jeho zobrazeni:
(1)
[se přihlaste](https://www.digitalniknihovna.cz/mzk/terms) účtem některé z partnerských knihoven.

Tento dokument není možné volně prohlížet v souladu se zákonem č. 121/2000 Sb. (autorský zákon). Autorský zákon připouští zpřístupnění děl 70 let po smrti všech autorů (včetně překladatele, ilustrátora apod.) a 50 let od vydání díla.

![dnnt_info](https://github.com/user-attachments/assets/8a72ee24-d10c-4006-ace9-0978eeb8be1e)

**Comment by zabak** [comment]
Tohle se řešilo zde: https://github.com/ceskaexpedice/kramerius-web-client/issues/658 - problém je, že text může být dostupný pod různými licencemi, takže ta hláška je sestavená z několika částí, které popisují, jak se k dokumentu dostat. Jestli máš nápad, jak to líp otextovat, tak si to můžete v konfiguraci svého Krameria vyzkoušet, na konečné podobě textu bychom se ale měli shodnout, protože zrovna v případě DNNT by měl být ve všech DNNT knihovnách stejný.
