### ISSUE TITLE
K7 - kód instituce v názvu logovaných souborů

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#1082]
Generování logů pro Národní knihovnu vytváří soubory pojmenované ve tvaru `statistics--none--2024.05.24.log`, kde místo "none" by měl být kód instituce. Dá se to někde nastavit? Hledal jsem v adminovi, v dokumentaci na githubu a v configuration.properties, ale marně.

**Comment by pavel-stastny** [comment]
v configuration.properties  `acronym=mkp`

**Comment by svetlym** [comment]
Díky.
