### ISSUE TITLE
Získávání obsahů zvukových datastreamů přes API

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#109]
Zvukové datastreamy (WAV, OGG, MP3) se dají přes API získat stejně, jako všechny ostatní datastreamy:
`GET http://localhost:8080/search/api/v5.0/item/<pid>/streams/<stream_id>`

Nicméně nejen pro WAV platí, že ty soubory můžou být dost velké a pokud se při přehrávání uživatel přesune dál v záznamu, takhle by musel čekat, až se celý soubor načte. 
Tohle se obecně řeší pomocí HTTP Range hlaviček, což Fedora (alespoň ve verzi 3.5 nepodporuje). 
Proto byl při podpoře audio záznamů a integraci javascriptové přehrávačky vytvořen servlet AudioProxy, který Range podporuje a přeposílá data mezi backendovým audio serverem (Apache) také podporujícím Range a klientem. 
Ve Fedoře pak zvukové datastreamy vypadají takto:

```xml
<foxml:datastream ID="WAV" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
<foxml:datastreamVersion ID="WAV.0" LABEL="Wav version of this audio track" CREATED="2014-06-19T10:49:01.000Z" MIMETYPE="audio/wav">
<foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/001/252/585/df6c2a49-d9f6-40fe-9533-8c96f67fa229.wav"/>
</foxml:datastreamVersion>
</foxml:datastream>
<foxml:datastream ID="MP3" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
<foxml:datastreamVersion ID="MP3.0" LABEL="Mp3 version of this audio track" CREATED="2014-06-19T10:49:01.000Z" MIMETYPE="audio/mpeg">
<foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/001/252/585/df6c2a49-d9f6-40fe-9533-8c96f67fa229.mp3"/>
</foxml:datastreamVersion>
</foxml:datastream>
<foxml:datastream ID="OGG" STATE="A" CONTROL_GROUP="E" VERSIONABLE="true">
<foxml:datastreamVersion ID="OGG.0" LABEL="Ogg Vorbis version of this audio track" CREATED="2014-06-19T10:49:01.000Z" MIMETYPE="audio/ogg">
<foxml:contentLocation TYPE="URL" REF="http://audioserver.mzk.cz/mzk01/001/252/585/df6c2a49-d9f6-40fe-9533-8c96f67fa229.ogg"/>
</foxml:datastreamVersion>
</foxml:datastream>
```
(Url typu `http://audioserver.mzk.cz/mzk01/001/252/585/df6c2a49-d9f6-40fe-9533-8c96f67fa229.ogg` nejsou zvenku dostupná, podobně jako dlaždice imageServeru nebo API Fedory.)
AudioServlet kontroluje přístupová práva, použití Range není nutné - bez něj je vrácen celý soubor.
Operace `GET http://localhost:8080/search/api/v5.0/item/<pid>/streams/<stream_id>` by tak měla pro OGG, WAV, MP3 použít kód z AudioServletu namísto získávání datastreamu z Fedory.

**Comment by pavel-stastny** [comment]
Vyreseno v #250 

komity:
a9cd6db2c6616026d9b554dd919565cdb4c24a6c
76951f0cbca4d21058ee5f1b051ff3dcf4b51c69
b0e8dd50da0660ca7649c6a7cbfc282232a346c3
