### ISSUE TITLE
Issue 351:	Tlačítka nedrží jazykovou konvenci

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#11]
Reported by Martin.Barton@nkp.cz, Jun 18, 2012
Bylo by dobré, kdyby se v aplikaci objevovala tlačítka s jednotným pojmenováním. Na různých místech nacházím v české verzi jednou "close" (Více ..., ) pak zas "Close" (Editor rolí, Správa dlouhotrvajících procesů, ...) jindy zase "Zavřít" (Import periodik, Import monografií, Indexace dokumentů, ...).
Mimo jazyka by se mělo ujednotit i psaní prvního velkého písmena, sice je to prkotina, ale nedělá to dobrý dojem.

Jul 25, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by slapakovai** [comment]
řešeno v K5
