### ISSUE TITLE
Image server - neexistující vs. nedostupná stránka

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#110]
Objekt uuid:bc6c7800-ebb5-11e3-b72e-005056827e52 je stránka, pro kterou jsou práva nastavena tak, že není mimo budovu MZK přístupná. Následující http request  Http get request vrátí kód 403 Forbidden:
`http://krameriusndktest.mzk.cz/search/zoomify/uuid:bc6c7800-ebb5-11e3-b72e-005056827e52/ImageProperties.xml`

Pokud vytvořím podobný dotaz na neexistující objekt, např:
`http://krameriusndktest.mzk.cz/search/zoomify/uuid:neco/ImageProperties.xml`
taky dostanu 403. Nelze tak jednoduše zjistit, jestli uuid patří stránce, ke které existují dlaždice (i když je aktuálně nepřístupná), nebo k ní dlaždice nejsou a bude potřeba získat obrázek z datastreamu IMG_FULL. Hodil by se tady spíš kód 404 Not found. Anebo existuje jiný způsob, jak tohle zjistit?

**Comment by zabak** [comment]
Prosím o odpověď - má to faktický dopad - nemáme přes API jak zjistit jestli je obrázek dostupný v zoomify nebo ne a dělat naslepo dotazy na imageproperties.xml je nesystémové. Mělo by se řešit jinak. A na základě odpovědi by mělo dojít předpokládám k nějaké úpravě API.
