### ISSUE TITLE
Nový tisk - tisk potomků

### ISSUE THREAD

**Issue by leiblix** [ceskaexpedice/kramerius#117]
Tisk by se měl chovat konzistentně jako generování PDF. Když si otevřu monografii, tak v případě generování PDF dostanu celou monografii, v případé nového tisku pouze titulní stranu.

Celoá monografie se nevytiskne, ani když zaškrtnu kořenový uzel ve stromu (opět se mi vytiskne pouze titulní stránka)

**Comment by zabak** [comment]
Tohle řeší skupina issues kolem pdf a tisku z web klienta, navrhuji zavřít.
