### ISSUE TITLE
Issue 357:	Ikony FB, G+, Twitter zmenšují prostor

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#12]
Reported by Martin.Barton@nkp.cz, Jun 21, 2012
Umístění ikon pro Facebook, G+, Twiter je nešťastné.
Jednak se zmenšilo okno pro střední náhled a protože pro migraci je nastavena výška tak, aby to bylo vidět celé bez ikon FB, G+ a Twitter (výška se nastavovala, když tu tyto ikony ještě nebyly, ale u toho jsem nebyl, nevím, kde se vzala), stane se to, že náhled není celý, objeví se vpravo rolovací lišta a ikonky u náhledu (vlevo nahoře) se dostanou „do autu“ (viz. obrázek). 
Druhým důvodem je skutečnost, že takto uživatel automaticky předpokládá, že to je Like pro aplikaci, nikoliv pro titul (což má být to hlavní). Inspiraci je možné najít třeba zde: http://cdr.cz/clanek/lulzsec-vznik-a-pad-tymova-zrada
Prosím otevřeme diskuzi na téma umístění ikon pro sociální sítě. Zatím by asi šlo dát tyto ikony na jeden řádek s textem ©2008-2011. Developed under GNU GPL by Incad, NKČR, KNAV and MZK a zmenšit mezeru mezi touto patičkou a oknem aplikace.

```
ikony_FB_zmensuji_prostor.jpg 
```

48.9 KB   View   Download   

Jun 21, 2012 Delete comment Project Member #1 pavel.kocourek@incad.cz
Už je upraveno po té diskuzi v NK ... jsou na jedné řádce. Bude v následujícím buildu.
Jun 21, 2012 Delete comment Project Member #2 Martin.Barton@nkp.cz
Jak jsem napsal. Toto umístění obecně je velmi nešťastné a asi by stálo opravdu za to věnovat této záležitosti větší pozornost a širší diskuzi. Proto přikládám i nějaké návrhy.
    kniha_navrh.jpg 
86.9 KB   View   Download   

```
zahlavi_navrh.png 
```

81.9 KB   View   Download   

Jul 25, 2012 Delete comment Project Member #3 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by slapakovai** [comment]
Řešeno v K5
