### ISSUE TITLE
Hledání v konkrétním jednom dni

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius#120]
Při hledání v K v MZK a omezení na jeden den našlo záznamy za celý rok. Proč? Přikládám printscreen
![chyba u k5](https://cloud.githubusercontent.com/assets/7532753/4026964/7c39b120-2c25-11e4-9f38-0f4630fae6c3.jpg)

**Comment by albertoh** [comment]
Hledani podle casove osy bude doplneno moznosti hledat presne podle konkretniho dne.
Budou dohledane jen dokumenty, ktere maji v matadatech presne uvaden ten den.

**Comment by BrozekAles** [comment]
A kdy ta moznost bude doplnena?

**Comment by pavelkocourek** [comment]
Navrhujeme přidat nové pole Datum s Kalendářem pro výběr konkrétního dne. 
U stávajících polí pro zadání rozsahu odstranit kalendář - budou používána na YYYY. 
Bude tak rozdíl mezi zadáním rozmezí roků a konkrétním datumem. 
Prostor by se zvětšil vertikálně nad osou.
Je toto řešení, které očekáváte?

**Comment by BrozekAles** [comment]
Ano, z mého pohledu je to ideální. Díky.
Zdravím
__________________________________________________

			 - Ing. Aleš Brožek
			ředitel

  m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045
  f: + 420 475 200 045
  e: knihovna@svkul.cz
  w: www.svkul.cz
----------------původní zpráva-----------------
Od: pavelkocourek [notifications@github.com ]
Komu: "ceskaexpedice/kramerius" [kramerius@noreply.github.com ]
Kopie: BrozekAles [brozek@svkul.cz ], Author [author@noreply.github.com ]
Datum: Wed, 19 Oct 2016 02:07:54 -0700
----------------------------------------------------------

**Comment by albertoh** [comment]
Pridan checkbox pro hledani v konkretnim dni. V tomto pripade bude hledat pres pole datum_str, ktere ma hodnotu tak jak je napsano v datech (nemusi byt platny format pro datum)
