### ISSUE TITLE
Funkce generování PDF jako globální akce

### ISSUE THREAD

**Issue by jrihak** [ceskaexpedice/kramerius#131]
Uvítali bychom, kdyby funkce "Generování PDF" byla předělána jako "globální akce" a aby u ní bylo možné nastavit viditelnost v uživatelském menu u dokumentů stejným způsobem, jako je to u funkce "Tisk".

Důvodem je snaha zpřístupnit dokumenty s policy:private na co nejvíce počítačových terminálech v NTK bez nutnosti zabezpečovat terminály proti ukládání souborů a přístupu na web mimo doménu techlib.cz.

V současné chvíli nemůže zpřístupňovat private dokumenty na nezabezpečených terminálech, protože uživatelé stále mají možnost vygenerovat si z private dokumentů PDF a uložit si jej na disk nebo sdílet ho například na Uložto.

Motivace:
Pokud by se dalo zobrazení odkazu na funkci Generování PDF vypnout podobně jako se dá vypnout zobrazení odkazu na Tisk dokumentu, zlepšilo by to možnosti zpřístupnění private dokumentů bez omezení funkcionality počítačových terminálů (které naši zákazníci využívají i pro běžnou "kancelářskou" práci - musí tedy mít přístup na web mimo doménu techlib.cz a musí mít možnost ukládat soubory na disk).

Jakub Řihák
NTK

**Comment by zabak** [comment]
Proběhl už ten pull request? Je to pořád otevřené...

**Comment by pavel-stastny** [comment]
Nyni jsou pritomne dve akce: 

1. **show_client_pdf_menu**  
2. **pdf_resource**


Prvni ma vliv na zobrazeni | nezobrazeni polozky, druha pak na prava k endpointu, ktery se stara o samotne generovni.
