### ISSUE TITLE
K5client - obecně - pohyb v úrovních dokumentu

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#141]
Z dokumentu se nedá vyskákat zpět na výsledky vyhledávání jinak, než zběsilým klikáním na zpět, což je neúnosné, pokud jsem předtím prošla hodně stránek nebo úrovní. Tlačítko o úroveň nahoru funguje jen v rámci dokumentu, ale ne dál. Mělo by to jít vyskákat ze strany zpět na číslo, dále zpět na ročník, na časopis, na výsledky hledání, na titulní stranu.

**Comment by slapakovai** [comment]
Schváleno, prosím udělat.
