### ISSUE TITLE
K5client - obecně - skrolování v časové ose a virt. sbírkách

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#146]
Jak v časové ose, tak ve virtuálních sbírkách se skroluje v jednotlivých řádcích zprava doleva, naopak nejde skrolovat nahoru dolu po jednotlivých řádcích, kde mi to přijde logičtější, než klikat na šipky

**Comment by slapakovai** [comment]
Když je ukazatel myši na filmovém pásu, tak scrollovat v něm a když je ukazatel mimo filmový pás, tak scrollovat nahoru/dolů.

**Comment by pavel-stastny** [comment]
neaktualni
