### ISSUE TITLE
K5client - obecně - zrušit úroveň seznamu stránek

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#147]
Po kliknutí na monografii očekávám, že se mi otevře přímo monografie, ne seznam stránek, který:
a) stránky jsou strašně maličké, pokud je jich hodně
b) načítá se pekelně dlouho a v mezičase nemůžu nic dělat
c) nenašla jsem smysluplné využití této úrovně
d) ani z toho seznamu nepoznám, co to jsou za čísla stránek jinak, než najetím kurzoru na stranu

Celou tuto úroveň bych zrušila a místo toho přidala do úrovně prohlížení dokumentu náhled miniatur nebo vyjížděcí páseček, jak jsem psala, že je v Poloně, viz obrázky. I s popiskem, co to je za číslo strany.

![snimek obrazovky 2014-11-06 v 16 29 35](https://cloud.githubusercontent.com/assets/3939120/4938220/d714fc98-65c9-11e4-978b-d6b0568a646a.png)
![snimek obrazovky 2014-11-06 v 16 29 50](https://cloud.githubusercontent.com/assets/3939120/4938225/ded30e34-65c9-11e4-9f99-c8c6c11c5df6.png)

**Comment by slapakovai** [comment]
Schváleno na schůzce, zrušit úroveň stránek ve vyhledávání.

**Comment by pavel-stastny** [comment]
neaktualni
