### ISSUE TITLE
K5client - obecně - seznam ročníků a čísel

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#148]
Ročníky a čísla by neměly mít velikost podle toho, kolik jich je, ale jednu, protože u hodně čísel/ročníků z toho člověk nic nevyčte a u málo čísel/ročníků jsou obrázky ošklivě rozmazané. Takže sjednotit na jednu "normální velikost" a přidat popis rok a číslo ročníku/čísla k obrázku, ne až po najetí myši.

**Comment by slapakovai** [comment]
Udělat jednotnou velikost náhledů ve všech úrovních vyhledávání.
