### ISSUE TITLE
K5client - obecně - vyhledávací pole

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#149]
Všeobecné vyhledávací pole by mělo být přítomno ve všech úrovních v horní liště, ne jen v některých úrovních a ještě v některých tak nějak nenápadně vpravo.

**Comment by slapakovai** [comment]
Vyhledávací pole v celém obsahu digitální knihovny umístit do horního modrého panelu tak, aby tam bylo pořád. Vedle něj by měla být ikonka lupy pro klikače. Text uvnitř "Hledej v digitální knihovně". Jestli je text moc dlouhý, tak můžeme ještě vymyslet něco kratšího.
