### ISSUE TITLE
Issue 367:	propojení K4 a Aleph

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#15]
Reported by brodani.dusan, Jun 26, 2012
Chybí nám v K4 propojeni na Aleph, v dokumentaci je propojení uvedeno jen jako požadavek s poznámkou, že řešení bude převzato z verze 3. Je možné očekávat v dohledné době implementaci do K4?
Jun 26, 2012 Delete comment Project Member #1 vlahoda
Ve verzi 4.6 bude u titulů s vyplněným ISSN nebo ISBN doplněn odkaz na vyhledávání záznamu v Aleph, které se otevře v novém okně. Základní URL Aleph bude konfigurovatelné (configuration.properties).
Status: Accepted 
Owner: alberto.en.vlasim 
Jun 26, 2012 Delete comment #2 brodani.dusan
Náš K4 na VŠE obsahuje především staré monografie ze sbírky "zlatý fond České ekonomické literatury", kde převažná část publikací ISBN nemá. V předchozím systému jsme propojení na Aleph řešili prostřednictvím systémového čísla, bylo by proto dobré, kdyby se pamatovalo i na publikace bez ISBN/ISSN. Je možný alespoň přibližný odhad, kdy se verze 4.6 dostane ven? Děkuji
Jun 26, 2012 Delete comment Project Member #3 vlahoda
Problém je v tom, že systémové číslo není součástí exportního formátu dat z Krameria 3 a data K4 jej tedy neobsahují. Pokud víte, odkud systémové číslo vzít, můžeme upravit konvertor K3->K4 tak, aby data K4 systémové číslo obsahovala a pak samozřejmě propojení do Aleph nebude problém. 
Verze 4.6 je předběžně plánována na přelom srpna a září.
Jun 26, 2012 Delete comment #4 brodani.dusan
Systémová čísla jsme do Krameria 3 vkládali dodatečne (teď si už nevybavuju, zda to bylo po jednom nebo to šlo i nějak hromadně), důležité bylo, že se pak myslím objevili v exportu OAI, z kterého se pak udělala i opačná vazba Aleph-Kramerius. Předpokládám tedy, že požadavek na propojení v K4, který vychází z manuálu k systému Kramerius 3, bude taky řešit vložení systémového čísla jako náhrady za ISBN až dodatečne, co by nám v podstatě jako prvotní řešení i stačilo. Nevím, jak se jmenovalo pole se SYSNO v systému Kramerius 3, pro K4 je dle poznámky zvažováno "AlternateID", proto k exportu a konverzi mezi verzemi nemám fundovanou představu.
## část popisu, z které vycházime:

Propojení z ALEPH do systému Kramerius pro Monografie

Propojení je na úrovni monografií a volných částí monografií, jako identifikátor je při propojení použito ISBN nebo systémové číslo. Toto řešení je zvoleno proto, že ISBN je nepovinné a mnoho monografií ho nemá. Pokud tedy monografie ISBN nemá, je pro propojení na ALEPH třeba použít systémové číslo.

Systémové číslo není součástí metadat, ale lze ho zadat v administrativní části aplikace. Předpokládá se že tímto číslem bude SYSNO z ALEPHu. 

Poznámky k technickému řešení:

Implementace bude převzata z verze Kramerius 3. Systémové číslo pro ALEPH by bylo možné ukládat do pole AlternateID 

(http://code.google.com/p/kramerius/wiki/Administrace#Propojen%C3%AD_na_extern%C3%AD_syst%C3%A9my_%28ALEPH,_DODO%29)
Aug 17, 2012 Delete comment Project Member #5 alberto.en.vlasim
This issue was updated by revision r3945.

Pridane nove vlastnosti do souboru search.properties pro linkovani do alephu. 
search.aleph.baseURL.ISSN=http://aleph.techlib.cz/F/?func=find-b&find_code=SSN&local_base=STK02&request=
search.aleph.baseURL.ISBN=http://aleph.nkp.cz/F/?local_base=nkc01&func=find-c&ccl_term=ISN=
search.aleph.baseURL.CNB=http://aleph.nkp.cz/F/?func=find-c&local_base=nkc01&ccl_term=cnb=

Vychozi hodnoty jsou predvzata z registru digitalizazi. 
Hodnota tech pole se nachazeji v MODS tagu identifier:

mods:identifier[@type='issn']
mods:identifier[@type='isbn']
mods:identifier[@type='ccnb']
Jan 29, 2013 Delete comment #6 brodani.dusan
V prosinci a lednu jsem importoval další várku monografií do našeho K4 (kramerius.vse.cz, version: 4.6.0, revision: 4446) abychom se pak dostali i k propojení do Alephu, ale ani mezitím vydaná nová verze K4 a revize r3945 náš problém ohledně SYSNO nevyřešila. Je tedy nějaká šance, že by v admin rozhraní přibyla možnost jednoduše k záznamu SYSNO nebo nějaké AlternateID přidat?
Tady je ale postřeh od našeho správce katalogu Aleph, který objevil, že v MZK to v jisté formě funguje (?): 

Ahoj,

v těch issues a zmíněné revizi r3945 se řeší

mods:identifier[@type='issn']
mods:identifier[@type='isbn']
mods:identifier[@type='ccnb']

což je fajn ale sysno to není - použitelné by bylo to čČNB, které většinou 
v záznamech v Alephu máme, ale zase ne vždy...

Když se podívám do krameria MZK, tak mají třeba v

http://kramerius.mzk.cz/search/handle/uuid:fa900826-7e67-11e1-a7ce-0050569d679d

<mods:identifier type="urn">urn:sys:000717983 
fa900826-7e67-11e1-a7ce-0050569d679d/mods:identifier

což kdybysme měli, tak by bylo výborné - odpovídající záznam v jejich 
Alephu pak je

https://aleph.mzk.cz:443/F?func=direct&doc_number=000717983&local_base=MZK01&format=999

kdežto u nás třeba

http://kramerius.vse.cz/search/handle/uuid:cda20b10-af35-11de-be43-0013d398622b

<mods:identifier 
type="urn">cda20b10-af35-11de-be43-0013d398622b/mods:identifier

máme vždycky jenom to uuid,

v metadatovém formátu "ese" mi to dokonce posílá extid, což je podle 
manuálu určené pro sysno z Alephu, ale

   dc:identifierextid:42/dc:identifier

ale sysno je 000025442

plus samozřejmě

   mods:shelfLocatorZF27/mods:shelfLocator

ve formátu drkramerius4, což je taky jediná možnost, přes kterou se vazby 
dají dohledat.

Tak nevím...

J.R.

Jan 30, 2013 Delete comment Project Member #7 vlahoda
Ve specifikaci formátu metadat pro NDK je uvedeno, že v tagu mods:identifier může být vyplněno: "permalink záznamu z katalogu NK ČR, např.http://aleph.nkp.cz/F/?func=direct&doc_number=002186258&local_base=NKC". Můžeme tedy do K4 kromě podpory typů issn, isbn a ccnb doplnit analogickou podporu pro typ mods:identifier[@type='permalink']. 

Jul 4, 2013 Delete comment Project Member #8 vlahoda
(No comment was entered for this change.)
Status: OnHold 
Sep 25, 2013 Delete comment #9 filip.kriz
Už někomu to propojení na katalog funguje?

**Comment by zabak** [comment]
Upozorňuji, že uplynula spousta času. Tohle by mělo být součástí klienta a spousta knihoven buď používá před Alephem VuFind nebo má jiný systém než Aleph.

**Comment by honza-rychtar** [comment]
Založil jsem k tomu issue ke klientovi https://github.com/ceskaexpedice/kramerius-web-client/issues/217

@zabak Pokud chceme v případě MZK odkazovat přímo do VuFindu - ne jen vyhledat, tak potřebujeme sysno a bázi.
Sysno je buď v **identifier type="sysno"** nebo v **recordIdentifier**.
V případě **recordIdentifier** se vyskytují ruzné problémy

-  **recordIdentifier** chybí
-  **recordIdentifier** obsahuje jen sysno (bez báze)
-  **recordIdentifier** obsahuje bázi zřetězenou se sysnem <- tenhle případ je ok
-  **recordIdentifier** odkazuje přes source do NKP na neexistující bázi

**Comment by dkindl** [comment]
Existuje možnost využití čísla CNB pro odkaz do Souborného katalogu 
 <mods:identifier type="ccnb"> cnb001710208 </mods:identifier>
odkaz: https://aleph.nkp.cz/F/?func=find-c&ccl_term=CNB=cnb001710208&local_base=SKC.

**Comment by JanMeritus** [comment]
Smeroval by som to primarne na klienta. Ide o prepojenie klienta a suborneho katalogu, ktory funguje ako resolver pre lokalne katalogy a ich fyzicke jednotky digitalnej manifestacie.

**Comment by dkindl** [comment]
Ano,
pokud se jedná o titul české produkce, pak má přidělené číslo CNB, přes číslo CNB lze vytvořit odkaz do SKC CR. Součástí bibliografického záznamu o knize v SKC CR je pole 910, které obsahuje siglu knihovny (vlastníka dokumentu) a systémové číslo záznamu  katalogu dané knihovny. Uživatel má tak možnost a) zjistit, v které pro něj nejlépe dostupné knihovně se titul nachází, b) pomocí tlačítka odkazu na lokální záznam se přepnou do jejich katalogu a knihu si fyzicky vypůjčit.

**Comment by honza-rychtar** [comment]
@dkindl Souhlasím.
Pojďme to dál řešit v issue u klienta - https://github.com/ceskaexpedice/kramerius-web-client/issues/217

**Comment by zabak** [comment]
Návrh implementace: správce může vytvořen seznam dvojic uuid titulu + link do katalogu a přes API ho naimportuje do Krameria. Link se bude zobrazovat v pravém panelu v metadatech. Bylo by umožněno importovat více linků pro jedno uuid. V tom případě bude v importovaném souboru více řádků se stejným uuid.

**Comment by pavel-stastny** [comment]
Pokračování issue je na githubu  klienta [217](https://github.com/ceskaexpedice/kramerius-web-client/issues/217).  Zde uzavírám.

@zabak @honza-rychtar @vlahoda V případě potřeby je možné zde znovu otevřít.
