### ISSUE TITLE
K5client - titulní strana

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#151]
Titulní stranu bychom si přestavovali spíše jako tu z Polony. Když člověk přijde poprvé do Krameria, tak chce vidět nějaký výběr. Takhle netuší, co má dělat, nejde na nic pomalu kliknout... V Poloně to je v podstatě mix vybraných dokumentů, novinek, virtuálních sbírek, typů dokumentů atd. Je to pěkné a moderní.
http://polona.pl/
![snimek obrazovky 2014-11-06 v 16 44 30](https://cloud.githubusercontent.com/assets/3939120/4938497/e57a6c80-65cb-11e4-93fa-f65af5dc048c.png)

**Comment by slapakovai** [comment]
Bude řešeno jinak, issue je možné uzavřít.
