### ISSUE TITLE
K5client - titulní strana - nejnovější, vybrané apod.

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#153]
Takhle umístěné dole jsem je fakt nenašla. Navíc dole očekávám patičku, kde budou nějaké typicky "patičkové" informace. Nejnovější a vybrané bych umístila buď do boku nebo nahoru, ale rozhodně ne dolu. Navíc mám na počítači dole vyjížděcí pruh s nabídkou a ten inteligentně vyjíždí zároveň s náhledy.

Navíc nejžádanější stejně mají nějaký divný algoritmus, takže to moc nefunguje. Mělo by si jít jako nyní vybrat, které záložky budu svým čtenářům zobrazovat.

**Comment by slapakovai** [comment]
Po otevření úvodní stránky by měly být otevřené náhledy ze záložky vybrané a po pár sekundách zajet dolů. Po najetí na vybrané, nejnovější, nejžádanější otevřít náhledy bez nutnosti klikání. Modrý pás s touto nabídkou udělat vyšší.

**Comment by slapakovai** [comment]
A ještě v anglické verzi změnit "Cool" na "Selected".

**Comment by jrihak** [comment]
Možná by stálo za to nazvat tuhle položku spíš "Featured" (je to řekl 
bych obvyklejší)...

JŘ

**Comment by slapakovai** [comment]
Jasně, to by asi bylo lepší :)
