### ISSUE TITLE
K5client - procházení

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#159]
Po kliknutí na procházet dlouho čekám a pak se mi objeví nahoře smutných pár rámečků. Neměl by se objevit abecední seznam už teď bez nutnosti vybrání modelu? Vždyť to je všecko v jednom poli, omezení na model by mělo být jako přídavná filtrovací funkce.

Neměla by zůstat prázdná strana, už by se mohly načíst alespoň nějaké záznamy.

**Comment by slapakovai** [comment]
Může se uzavřít
