### ISSUE TITLE
K5client - procházení - abeceda

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#160]
Asi by stačila prostá abeceda a ne třípísmenné záložky, když člověk není knihovník zběhlý v abecedě, tak při vynechání některých písmen chvíli trvá, než si to člověk "dopočítá". 

A zase je prázdná obrazovka, místo toho by se měl objevit aspoň seznam z první záložky.

**Comment by slapakovai** [comment]
Schváleno na schůzce, prosím udělat.
