### ISSUE TITLE
K5client - procházení - ikonky plus a minus

### ISSUE THREAD

**Issue by pavluska** [ceskaexpedice/kramerius#161]
Ikonky plus a mínus nereprezentují funkci, co dělají. Plus a mínus bych pochopila jako zoomovaní, ne přidávání sloupců. Navíc jsou na blbém místě, kde jsme si jich vůbec nevšimli. Měly by být někde v tom poli se záznamy. Výrazné a výstižné.

Navíc lze přidávat sloupců donekonečna :)

**Comment by slapakovai** [comment]
Asi by bylo dobré omezit maximální možný počet přidaných sloupců. Při větším počtu se sloupce začínají slévat dohromady.

**Comment by albertoh** [comment]
Tlacitka byla zrusena
