### ISSUE TITLE
Issue 395:	Editor uživatelů – zapomenuté heslo

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#17]
Reported by Martin.Barton@nkp.cz, Aug 13, 2012
Je zvykem uživatelům nabídnout možnost si nechat poslat na registrovaný mail (někdy i po kontrolní otázce uživatelem předvyplněnou a CAPTCHA) nové heslo, když to platné zapomene. Pokud uživatel heslo nyní zapomene, těžko bude hledat pomoc, možná ho napadne, že "Zpětná vazba" by mohlo být to pravé, ale spíš asi ne. Možná si se zaregistruje pod novým jménem a mailem.
Nebude-li se aplikovat funkce automatického zaslání nového hesla, měl by být na místě pro přihlášení nějak zřetelně uveden kontakt tam, kde mu to heslo znovu nastaví.

Přimlouváme se pro řešení se zasláním hesla.

Prosíme o zařazení k projednání na další schůzku vývojového týmu.
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Pro noveho klienta uz neaktualni.
