### ISSUE TITLE
Issue 397:	Editor uživatelů – změna hesla

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#18]
Reported by Martin.Barton@nkp.cz, Aug 13, 2012
Bylo by dobré, pokud si uživatel změní heslo, aby mu to aplikace nějak potvrdila. Nyní se neděje nic, nicméně heslo se změní.

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
V admin rozhrani a klientovi implementovano. V novejsim klientovi polozka prihlaseni  neni.
