### ISSUE TITLE
Issue 398:	Identifikovat přihlášení

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#19]
Reported by Martin.Barton@nkp.cz, Aug 13, 2012
Uživatel nikde nevidí, pod jakým jménem je zrovna přihlášen, je-li vůbec. Hodilo by se mu nějak dát vědět, že je/není přihlášený.
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by slapakovai** [comment]
Vyřešeno v K5
