### ISSUE TITLE
Použití zástupných znaků při vyhledávání

### ISSUE THREAD

**Issue by MarekFiser** [ceskaexpedice/kramerius#205]
Dobrý den. V K4 (verze 5.0) na rozdíl od K3 prakticky není možné využívat zástupné znaky \* a ? pro pravostranné (levostranné) rozšiřování výrazu a pro nahrazování jednoho znaku. Respektive použití znaku "*" pro pravostranné rozšíření funguje pouze při zadání do hlavního vyhledávacího okna, a to pouze za předpokladu, že zde nepoužívám kapitálky. Při vyhledávání v konkrétním dokumentu nefunguje ani to. Při prohledávání fulltextu je tak vyhledávání (s ohledem na nutnost využívání těchto znaků při nedokonalém OCR) značně omezené.

**Comment by FoxKyong** [comment]
Kdy to asi bude opraveno? Právě jsme narazili na stejný problém. Celkem se to hodí kvůli špatnému OCR a já se divil, proč to tak blbne.

**Comment by zabak** [comment]
vyřešeno v novém klientovi (konkrétně to jabl??ko funguje hezky, ja*ko, dává už solru zabrat), navrhuji zavřít

**Comment by KarolinaKostalova** [comment]
Taky jsem zjistila, že na novo*ý umí najít i knížku s názvem "_Novo_fundlandsk_ý_ pes".
Platí tedy, že hvězdička zastupuje více znaků a otazník jeden? A oba znaky je možné použít na konci slova i uvnitř?

**Comment by pavel-stastny** [comment]
Dobry den,  pozadavky na hledani byly samostane reseny v ramci klienta.  Zde zavirame.  V pripade potreby, muzete znovu otevrit.
