### ISSUE TITLE
Chybné řazení ve stromu - dvojčísla, čísla zvláštní/mimořádná, ročníky bez čísla ročníku a ročníky, zahrnující více ročníků

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#207]
5.0.2

Máme problém s řazením některých čísel a ročníků ve stromu.

1. Dvojčísla se nám v ročníku chybně řadí až na konec za "normální" čísla. Viz třeba č. 7-8 u Náchodského zpravodaje 1977 se č. 7-8 zařadí až za č. 12, ne mezi 6 a 9. Viz http://kramerius4.svkhk.cz/search/handle/uuid:2a4a4384-67a8-4ab7-b78d-e9ff07fe5a0e. Nebo několik dvojčísel na konci roku 1974 u titulu Nový čas - viz http://kramerius4.svkhk.cz/search/handle/uuid:72de8920-0320-4509-b223-534329c4b019 .
V logu je "Cannot sort relation for invalid numeric value:7-8". Dvojčísla ale nejsou nic neobvyklého, popsáno máme v souladu s pravidly NDK ("...pokud je daný výtisk dvojčíslo, budou uvedena obě čísla výtisku oddělena pomlčkou (bez mezery), např. 17-18."). 

2. Čísla, kde je v partnumber místo čísla "zvláštní", "mimořádné", "na ukázku" se nám řadí až na konec za "normální" čísla. V logu: "Cannot sort relation for invalid numeric value:zvláštní (uuid:67ab4d75-6fa0-4350-8e49-2a51331f0994)", "Cannot sort relation for invalid numeric value:mimořádné (uuid:d915d09b-ff55-4cb0-b8a7-66feb8184e9d)". Popsáno je v souladu s pravidly "Pokud se vyskytne případ, že mimořádné (zvláštní) číslo nemá žádné číslování, pak „mimořádné*“, „zvláštní*“, „na ukázku*“ apod. se zapíše místo čísla ..."
Tyhle výtisky se ve stromu v ročníku zařadily až na konec, po normálních číslech - viz Nové Hradecko 1968 http://kramerius4.svkhk.cz/search/handle/uuid:8fd3a808-1180-41b1-8018-ef4120c64f64 (správně měla všechna ta zvláštní/mimořádná čísla být mezi č. 8 a 9, ne až na konci).

3. Ročníky, kde není uvedeno číslo ročníku, jen rok, se řadí chybně. V logu je Cannot sort relation for invalid value: . Viz např. Náchodský zpravodaj - roky jsou pak napřeskáčku: http://kramerius4.svkhk.cz/search/handle/uuid:5c245474-a87d-4269-b92e-ae0d69db660d . 
U spousty titulů ročníkování neznáme, nelze to dopočítat ani zjistit, takže (v souladu s pravidly) v metadatech číslo ročníku prostě není.

4. Ročníky, které zahrnují více ročníků, se nám řadí chybně. Např. Opera corcontica, rok 1971, ročník 7-8 se zařadil úplně na konec až za 1990, 27 - místo toho, aby byl mezi 1969, 6 a 1972, 9. Viz http://kramerius4.svkhk.cz/search/handle/uuid:f0373840-1e94-11e2-a61d-005056827e52 .

**Comment by vlahoda** [comment]
Problém neumím vyřešit lépe. Funkce automatického třídění vyžaduje, aby hodnota, podle které se má třídit, byla buď numerická nebo abecední. Položky, které nelze pro třídění správně vyhodnotit, jsou řazeny na konec seznamu. Hodnota, podle které se třídí, je určena výrazem XPath v konfigurační property sort.xpaths - pokud tedy nemůžete pro třídění ročníků využít pole partNumber, můžete doplnit jiné s jednoznačným indexem. Popis automatického třídění je na stránce wiki https://github.com/ceskaexpedice/kramerius/wiki/NovinkyVeVerzi47 , odstavec Automatické třídění součástí dokumentů.  
Případně je možno součásti seřadit manuálně pomocí "Editoru částí".
