### ISSUE TITLE
Issue 414:	Možnost importovat – přístupné pouze pro Administrátora.

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#21]
Reported by pavel.kocourek@incad.cz, Sep 17, 2012
Po kontrole dokument zpřístupní administrátor. 
Feb 15, 2013 Delete comment Project Member #1 pavel.kocourek@incad.cz
Na základě automatického zpřístupnění - přebrání dat z databáze Autorit, potvrdit uživatelem. 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
implementovano
