### ISSUE TITLE
typy při serializaci do JSON

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#211]
Obsah pole title by měl být vždy uložený jako text, ale když název obsahuje hranaté závorky (časté u názvů stránek), vrací API místo textu pole.

Dobře je to vidět ve wiki u popisu získání potomků: https://github.com/ceskaexpedice/kramerius/wiki/ClientAPIDEV

[1]  se serializuje jako pole čísel, [1a] jako pole stringů

**Comment by MartinRumanek** [comment]
Je možné toto dořešit? Občas to způsobí vážné problémy při deserializaci.

Je to možné vidět třebas na tomto api url: http://kramerius.mzk.cz/search/api/v5.0/item/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3
V title by se rohozdně nemělo vracet pole.

**Comment by Jenyk** [comment]
A nejde jen o title, ale i např. o pagenumber, partnumber, volumenumber a date v Details (prostě všechno by se mělo explicitně serializovat jako string).

**Comment by pavel-stastny** [comment]
Zmena z json-lib na org.json : https://github.com/ceskaexpedice/kramerius/commit/49f7e5bba30d22cf0cd12b6340d780a58f68f637 (z duvodu sjednodecni a predchazeni automaticke konverze stringu)
