### ISSUE TITLE
Export METS

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#215]
Ve stracike (oranzove verzi) byla moznost exportu do formatu METS xml 
(https://github.com/ceskaexpedice/kramerius/wiki/MenuAdministrace#export-mets). Ta se pri prechodu verzi vytratila z kontextove menu, pridat ji tam.

**Comment by pavel-stastny** [comment]
zatim odlozeno

**Comment by zabak** [comment]
Je nějaký důvod, proč zavírat odložené issue? Očekával bych spíše přídání labelu postponed nebo podobného.

**Comment by pavel-stastny** [comment]
V oranzove verzi se jednalo o typ exportu z fedory 3, kdy se foxml se 'obalilo' METs elementy. Fedora 4 tento typ exportu nema.
