### ISSUE TITLE
Vybrat a tisknout - posun výběru oblasti tažením myši

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#216]
U "Vybrat a tisknout" nám schází možnost posunout celou oblast tažením myši (štelování jen taháním za rožky není úplně ideální).
5.0.2

**Comment by krizovj** [comment]
Může se zavřít? Je to stále aktuální?

**Comment by pavelkocourek** [comment]
Zavírám, týkalo se předchozího klienta
