### ISSUE TITLE
Ve stromě periodika se nezobrazuje číslo ročníku

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#217]
U všech instalací Krameria, které jedou podle NDK standardu se ve stromě periodika nezobrazují čísla ročníků (pouze rok, nikoliv pořadí). Týká se to samozřejmě i Client API a [Kramerius pro Android](https://play.google.com/store/apps/details?id=cz.mzk.kramerius.app) tuto informaci používá.

Dle nového standardu (podle kterého jede NDK) je uloženo číslo ročníku v  MODS na pozici 
mods:titleInfo - mods:partNumber (viz napr. http://krameriusndktest.mzk.cz/search/api/v5.0/item/uuid:f6f27d20-80e1-11e2-80e3-005056825209/streams/BIBLIO_MODS)

Toto není zohledněno v indexační šabloně do SOLR. Museli bychom k vyřešení problému tuto šablonu změnit a reindexovat všechna periodika.  Vzhledem k objemu stran, které v periodikách máme, není úplně vhodné se pouštět do takové hurá akce (a navíc netýká se to jenom MZK). 

Je to možné provést i nějak jinak?
V K5 se bude přecházet na SOLR4 - bude nutné provádět reindexaci všeho, nebo se migrace provede jiným způsobem?

**Comment by albertoh** [comment]
Pridam do vychozi sablony zmenu.
Bohuzel, bez reindexace se neobejdeme.
Ano, je v planu prechod na novejsi SOLR (SolrCloud).
Novy indexer bude muset umet posilat dokumenty na ruzne servery spravnym zpusobem, takze, reindexace bude nutna
