### ISSUE TITLE
Výhledávání dle víceslovných klíčových slov

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#219]
Dobrý den,
máme verzi 4.8.5 K4 a když zkoušíme vyhledat víceslovné klíčové slovo v Pokročilém vyhledávání, tak máme nulový výsledek. Zkoušeli jsme dát slova do uvozek, ale bez výsledku.
Můžete nám poradit v čem je problém?
Děkuji
A. Drahotušský

**Comment by albertoh** [comment]
Klicova slova nejsou analyzovana, tj, kazde z nich predstavuje jeden slozeny vyraz.
To znamena, ze pri hledani podle klicovych slov musi byt tento vyraz zadan presne tak, jak je uveden v datech.
Napriklad hledani
Ostravsko-karvinský revír (Česko) vrati 71 vysledku, co odpovida poctu dokumentu s tim klicovym slovem
Ale hledani Ostravsko-karvinský revír vrati jeden dokument s tim klicovym slovem
