### ISSUE TITLE
Issue 439:	CSS nastavit všude

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#22]
Reported by Martin.Barton@nkp.cz, Oct 1, 2012
Ne všechny texty v K4 (např div id="securityError") pracují s nastaveným CSS. Nevypadá to hezky, bylo by dobré to zkontrolovat a všude doplnit.
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
neaktualni
