### ISSUE TITLE
(Ne)zobrazení strany při dvou stranách se stejným indexem v NDK balíčku

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#223]
Když mám v NDK balíčku chybně u dvou různých stran shodný index, import proběhne, ale v K5 (5.0.2) se zobrazí jen ta druhá strana, první zmizí.

**Comment by vlahoda** [comment]
Problém se mi nedaří reprodukovat. Pokud jsou stránky pouze importovány, nedochází k jejich třídění a duplicitní indexy ničemu nevadí, je zachováno pořadí, ve kterém byly deklarovány v elementu structMap v METS. Při případném setřídění stran jsou položky s duplicitním indexem zařazeny na konec setříděného seznamu. Není tedy ta první, zmizelá strana zařazena na konci seznamu? Případně prosím o zpřístupnění importního balíčku (stačí bez obrázků)

**Comment by luckajirku** [comment]
Nám to takhle bohužel nefunguje. Jak jsme vypozorovali, tak když mají dvě strany stejný index, K5 vždycky tu v pořadí první zahodí a zobrazí až tu druhou. Třeba Jiskra Rychnovska, rok 1987, č. 31. Má 4 strany, chybně máme s indexem 1 stranu 1 i stranu 4 (viz níž). V K5 je pak na místě strany 1 strana 4 - a strana 1 chybí (viz http://kramerius4.svkhk.cz/search/handle/uuid:67237fea-3f4a-4651-8c56-4d95f2cddaab). Balíček vám hned nasdílím.

-<mets:div TYPE="ISSUE" LABEL="31" ID="DIV_P_0000" DMDID="MODSMD_ISSUE_0001">

-<mets:div TYPE="TitlePage" ID="DIV_P_PAGE_0001" ORDERLABEL="[1]" ORDER="1">
... 
-<mets:div TYPE="NormalPage" ID="DIV_P_PAGE_0002" ORDERLABEL="[2]" ORDER="2">
...
-<mets:div TYPE="NormalPage" ID="DIV_P_PAGE_0003" ORDERLABEL="[3]" ORDER="3">
...
-<mets:div TYPE="NormalPage" ID="DIV_P_PAGE_0004" ORDERLABEL="[4]" ORDER="1">

**Comment by vlahoda** [comment]
Chyba není způsobena duplicitním indexem stránky, ale duplicitní první a čtvrtou vazbou v bloku mets:structLink:
<mets:structLink>
        <mets:smLink xlink:to="DIV_P_PAGE_0004" xlink:from="ISSUE_0001"/>
        <mets:smLink xlink:to="DIV_P_PAGE_0002" xlink:from="ISSUE_0001"/>
        <mets:smLink xlink:to="DIV_P_PAGE_0003" xlink:from="ISSUE_0001"/>
        <mets:smLink xlink:to="DIV_P_PAGE_0004" xlink:from="ISSUE_0001"/>
    </mets:structLink>

Konvertor přesně podle tohoto předpisu zapíše stejné duplicitní vazby do RELS-EXT a Kramerius pak bere v úvahu jen první z nich.
