### ISSUE TITLE
K5Client - konfigurace se neprojeví

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#224]
Po deploynutí client.war se mi vytvořil správně mezi ostatními konfiguračními soubory "client.properties", nastavil jsem do něj:
<pre>
## URL to your admin kramerius application
k4.host=http://kramerius.mzk.cz/search
## URL to your admin kramerius API
api.point=${k4.host}/search/api/v5.0
</pre>
Ale vypadá to, že klientská aplikace na toto nereaguje (ani po restartu tomcatu). Podle konzole prohlížeče se snaží klient připojovat na špatnou url (např. http://kramerius.mzk.cz/client/api/feed/newest)

**Comment by pavel-stastny** [comment]
Zmente si, prosim, propertu nasledovne:  `api.point=${k4.host}/api/v5.0`

**Comment by MartinRumanek** [comment]
Díky, pomohlo.
