### ISSUE TITLE
Api - item deepzoom url

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#226]
Je nějaký důvod k tomu, aby u API ve volání na item bylo url na deepZoom? Minimálně u nás volání na deepZoom není funkční a všechny aplikace - včetně K5 klienta používají zoomify. Je možné toto v api nahradit za zoomify? 

Co jsem se koukal, tak K5 klient deepzoom nijak nepožívá, zoomify url si získává nahrazením: url.replace("deepZoom","zoomify");

{....,"zoom":{"url":"http://kramerius.mzk.cz/search/deepZoom/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3","type":"zoomify"},....}
(http://kramerius.mzk.cz/search/api/v5.0/item/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3)

Kromě toho by se nám hodilo, kdyby ještě přibyla informace o rozlišení obrázku, takže by to vypadalo takhle:

{....,"zoom":{"url":"kramerius.mzk.cz/search/zoomify/uuid:afdd8ea1-ad6f-474c-9611-152cfd3a14b3","type":"zoomify", "width":2167, "height":2886}

Udělám to sám jako pull-request, ale předtím než api změním, žádám o schválení jestli to tak může být.

**Comment by pavel-stastny** [comment]
Komitnuta oprava v ItemResource, kdyz tak poslete ten pullrequest tykajici se rozliseni obrazku.

**Comment by MartinRumanek** [comment]
Rozlišení si budeme v budoucnu řešit na úrovni IIIF presentation API.
