### ISSUE TITLE
Chyba pri konverzi z NDK METS formatu se zapnutou direktivou convert.imageServerSuffix.removeFilenameExtensions=true

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#228]
V případě streamů IMG_FULL a IMG_THUMB se direktiva zohlední správně, v případě streamu IMG_PREVIEW přípona .jp2 uprostřed výsledného URL zůstane.

Příklad části chybného zkonvertovaného FOXML:

    <foxml:datastream ID="IMG_FULL" CONTROL_GROUP="E" STATE="A" VERSIONABLE="false">
        <foxml:datastreamVersion ID="IMG_FULL.0" CREATED="2015-03-24T11:21:33" MIMETYPE="image/jpeg">
            <foxml:contentLocation TYPE="URL" REF="http://imageserver.mlp.cz/imageserver/PSP/abg001-000002/UC_abg001-000002_0002/big.jpg"/>
        </foxml:datastreamVersion>
    </foxml:datastream>
    <foxml:datastream ID="IMG_THUMB" CONTROL_GROUP="E" STATE="A" VERSIONABLE="false">
        <foxml:datastreamVersion ID="IMG_THUMB.0" CREATED="2015-03-24T11:21:33" MIMETYPE="image/jpeg">
            <foxml:contentLocation TYPE="URL" REF="http://imageserver.mlp.cz/imageserver/PSP/abg001-000002/UC_abg001-000002_0002/thumb.jpg"/>
        </foxml:datastreamVersion>
    </foxml:datastream>
    <foxml:datastream ID="IMG_PREVIEW" CONTROL_GROUP="E" STATE="A" VERSIONABLE="false">
        <foxml:datastreamVersion ID="IMG_PREVIEW.0" CREATED="2015-03-24T11:21:33" MIMETYPE="image/jpeg">
            <foxml:contentLocation TYPE="URL" REF="http://imageserver.mlp.cz/imageserver/PSP/abg001-000002/UC_abg001-000002_0002.jp2/preview.jpg"/>
        </foxml:datastreamVersion>
    </foxml:datastream>

Nastavení v souboru migration.properties:

convert.useImageServer=true
convert.imageServerTilesURLPrefix=http://imageserver.mlp.cz/imageserver
convert.imageServerImagesURLPrefix=http://imageserver.mlp.cz/imageserver
convert.imageServerSuffix.tiles=
convert.imageServerSuffix.big=/big.jpg
convert.imageServerSuffix.thumb=/thumb.jpg
convert.imageServerSuffix.preview=/preview.jpg
convert.imageServerSuffix.removeFilenameExtensions=true
convert.imageServerDirectory=/home/kramerius/.kramerius4/convert-converted/
convert.files=external
convert.previews=external
convert.thumbnails=external
convert.txt=encoded
convert.ignoreMissingFiles=false
ingest.skip=true

**Comment by vlahoda** [comment]
Jako dočasné řešení   prosím nastavte navíc ještě property convert.imageServer.removeFilenameExtensions=true, chyba bude opravena v příštím buildu.
