### ISSUE TITLE
Issue 456:	Editor poradi - problem s razenim rocniku pri pouziti popisu dle NDK

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#23]
Reported by duda@lib.cas.cz, Oct 24, 2012
Zdravim,

s pripravou importu clankovych metadat dle predpisu NDK, jsem narazil na problem s editorem poradi. Dle predpisu NDK neobsahuje prislusna sekce <titleInfo/> polozku <title/>, resp. tomu odpovidajici polozku dc:title/, ktera by obsahovala cislo rocniku. Vede to k tomu, ze pokud se na takto importovane dig. objekty (volumes) spusti editor poradi s cilem seradit je podle roku, editor poradi sice zobrazi nahledy, ktere lze preskupovat, ale v popisce kazdeho nahledu je misto cisla rocniku (nebo roku) pouze uuid. Nejlepe to demonstruje screenshot v priloze, kde jsem to nasimuloval tak, ze jsem u jednoho dig. objektu rocniku rucne ve fedore pridal dc:title46/dc:title a ostatni dig. objekty nechal. Je jasne, ze takto popsane nahledy pri vetsim mnozstvi rocniku neni mozne setridit, protoze uuid je v tomto kontextu zcela nepouzitelne. Zrejme se tedy bude muset bud upravit predpis NDK pro rocnik, nebo se bude muset upravit editor poradi tak, aby treba ukazoval rok...

Duda

P.S.: testovano na posledni stabilni verzi K4 a alfe.

```
volume.png 
```

63.3 KB   View   Download   

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold 
Owner: vlahoda

**Comment by zabak** [comment]
@mduda100871 je tohle issue stále relevantní?

**Comment by zabak** [comment]
@mduda100871 Vzhledem k tomu že tohle zůstává bez reakce, tak zavírám.
