### ISSUE TITLE
Editor částí nejede v Tomcatu 8

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#230]
Editor částí zjevně není kompatibilní se servlet specifikací 3.1. Ta je obsažená v Tomcat 8, proto v něm není možné tuto aplikaci provozovat. Ostatní aplikace jsou bez problému.

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [67] in the generated java file: [/usr/local/tomcat/work/Catalina/localhost/editor/org/apache/jsp/login_jsp.java]
The method getDispatcherType() is undefined for the type HttpServletRequest

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:198)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:450)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:570)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:356)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by vlahoda** [comment]
Problém se mi nedaří reprodukovat, editor na Tomcatu 8 funguje. 

Můžete mi poslat obsah toho generovaného souboru /usr/local/tomcat/work/Catalina/localhost/editor/org/apache/jsp/login_jsp.java ? 
V mé verzi žádný odkaz na metodu getDispatcherType nevidím.

V každém případě je ale použití Krameria na Tomcatu 8 problematické, protože na něm správně neběží fedora, ani poslední verze 3.8, konkrétně modul risearch.

**Comment by MartinRumanek** [comment]
```
/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-03-26 17:36:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cz.incad.kramerius.utils.ApplicationURL;
import cz.incad.kramerius.utils.conf.KConfiguration;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("cz.incad.kramerius.utils.conf.KConfiguration");
    _jspx_imports_classes.add("cz.incad.kramerius.utils.ApplicationURL");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("Copyright (C) 2010 Jan Pokorsky\n");
      out.write("\n");
      out.write("This program is free software: you can redistribute it and/or modify\n");
      out.write("it under the terms of the GNU General Public License as published by\n");
      out.write("the Free Software Foundation, either version 3 of the License, or\n");
      out.write("(at your option) any later version.\n");
      out.write("\n");
      out.write("This program is distributed in the hope that it will be useful,\n");
      out.write("but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
      out.write("MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
      out.write("GNU General Public License for more details.\n");
      out.write("\n");
      out.write("You should have received a copy of the GNU General Public License\n");
      out.write("along with this program. If not, see <http://www.gnu.org/licenses/>.\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("Delegates login to the search web app.\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");


    String aurl = response.encodeURL(ApplicationURL.getServerAndPort(request)+"/search/");

    KConfiguration kconfig = KConfiguration.getInstance();
    String query = "welcomeUrl=" + kconfig.getEditorURL();
    String ssoUrl = aurl
            + "singleSignOn.jsp?" + query;

    response.sendRedirect(response.encodeRedirectURL(ssoUrl));

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
```

Nevím jestli to má na to vliv, ale Javu nemám od Oraclu:
root@d5847ffb9e1d:/usr/local/tomcat# java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-2)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

mám to na odvozeném obrazu z https://registry.hub.docker.com/_/tomcat/

S tou Fedorou jsem si to nevšiml, díky, její kontejner si tedy downgraduju na 7. Ale indexace dokumentu v Krameriovi z ní prošla - to asi protože se Kramerius umí podívat do tabulky ritriples sám, že?

Dělám teď Krameria do Dockeru s oddělenýma komponentama. Až to budu mít hotové, zdokumentuju to a dám vám vědět. Tomcat 8 se mi právě hodí, protože umí [rewrite pravidla](https://tomcat.apache.org/tomcat-8.0-doc/rewrite.html), takže můžu vypustit apache...

**Comment by vlahoda** [comment]
Testoval jsem to na Tomcatu 8.0.3 a ten pro JSP generuje trochu jiný kód, který to volání Servlet API 3.1 ještě neobsahuje. Proto mi to funguje. Problém je v chybě v pom.xml, maven do editoru přibaluje soubor servlet-api-2.5.jar. Ostatní aplikace už jsou buildovány pomocí gradle a tam už tato chyba není. 
Zkuste prosím z adresáře webapps/editor/WEB-INF/lib smazat soubor servlet-api-2.5.jar, mělo by to začít fungovat (skript samozřejmě také opravím).

Ohledně indexace a risearch: problém nijak nesouvisí s databází riTriples, chyba je přímo ve fedoře (neplatné cesty k resource) a projevuje se i při použití implementace resource indexu Mulgara, který databázi vůbec nepoužívá. Oprava je poměrně triviální, ale musíte si připravit vlastní build fedora.war.

Indexace vám prošla proto, že samotný indexer tuto chybnou část API resource indexu nepoužívá. Ale pokud z hlavního menu otevřete dialog Indexace dokumentů, budete mít prázdnou rozevírací nabídku se seznamem modelů a v logu tomcatu najdete příslušný stacktrace. 

A ještě na vysvětlenou: do databáze riTriples se "nedívá" Kramerius, ale jediná samostatná třída, která implementuje API resource indexu a pro MPTStore doplňuje chybějící funkcionalitu SPARQL, kterou Kramerius potřebuje (MPTStore nabízí jen základní rozhraní SPO). Tato třída je ale fyzicky přibalena v souboru search.war, odtud zřejmě pochází ta legenda, že Kramerius obchází API a přistupuje přímo do databáze, kterou z MZK pravidelně slýcháme.

**Comment by MartinRumanek** [comment]
Díky, do pom.xml jsem si přidal servlet jako provided depedency
```
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.5</version>
            <scope>provided</scope>
        </dependency>
```
a vypadá to, že to funguje (nemám to ještě úplně otestované, nefunguje mi JAAS, ale to není problém editoru).

Co se týče Fedory, tak mi teda fungovala i ta rozevírací nabídka (s Fedorou 3.6.2). Jediné co jsem si všiml, že nefunguje je to GUI pro risearch....ještě si to otestuju.

Není to legenda :-), viděl jsem to v konfiguračním souboru, tak mě to zaujalo. Nevěděl jsem, že jste to s někým od nás řešil. Nemám všechny maily od předchozích kolegů (proto by bylo lepší, kdyby se všechny takovéto problémy řešili třeba zde).

Díky za rychlou odpověď a vysvětlení.
