### ISSUE TITLE
Dokumenty po reindexaci zmizí ze záložky Tituly

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#235]
Dokumenty nám s reindexací mizí ze záložky Tituly - nezobrazují se v abc seznamu ani nejdou vyhledat přes hledání v "Hlavní název" na záložce Tituly. Dají se najít jen při hledání nahoře. Na http://kramerius4.svkhk.cz/search/#intro5 např. Statistická ročenka okresu Náchod, Náchodský zpravodaj nebo Noviny Jičínska.

**Comment by vlahoda** [comment]
Ty reindexační procesy doběhly bez chyby? Máte případně jejich logy?

**Comment by luckajirku** [comment]
Ano, bez chyby. Ještě jsem zkoušela reindexovat u dalšího titulu na ročníku, a to je v pořádku, děje se to při reindexaci na titulu.

log u té Statistické ročenky:
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-mets-5.1.1-SNAPSHOT&#039; to &#039;migration.properties&#039;
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;k5indexer-5.1.1-SNAPSHOT&#039; to &#039;k5indexer.properties&#039;
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;import-cmdtool-5.1.1-SNAPSHOT&#039; to &#039;migration.properties&#039;
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;static-export-5.1.1-SNAPSHOT&#039; to &#039;static_export.properties&#039;
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;common-5.1.1-SNAPSHOT&#039; to &#039;configuration.properties&#039;
IV 15, 2015 1:45:29 ODP. cz.incad.kramerius.utils.conf.KConfiguration findAllConfigurations
INFO: Replacing configuration file name from &#039;indexer-5.1.1-SNAPSHOT&#039; to &#039;indexer.properties&#039;
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.Main main
INFO: process args: [fromKrameriusModel, uuid:89b5bcd1-075e-4c6f-b5fc-7bdfc2e940f8, Statistická ročenka okresu Náchod]
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.processes.impl.ProcessStarter updateName
INFO: requesting url :http://localhost:8080/search//lr?action=updateName&amp;uuid=ac7cb4ec-a3ff-4535-9120-9d33b3b8a4f5&amp;name=Indexace+dokumentu%3A+Statistick%C3%A1+ro%C4%8Denka+okresu+N%C3%A1chod
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.Indexer &lt;init&gt;
INFO: Indexer initialized
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.Indexer run
INFO: Current index time: 15.4.15 13:45
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.Indexer update
INFO: Update index...
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.FedoraOperations updateIndex
INFO: updateIndex action=fromKrameriusModel value=uuid:89b5bcd1-075e-4c6f-b5fc-7bdfc2e940f8
IV 15, 2015 1:45:30 ODP. cz.incad.kramerius.indexer.SolrOperations deleteDocument
INFO: deleting document with &lt;delete&gt;&lt;query&gt;pid_path:uuid\:89b5bcd1\-075e\-4c6f\-b5fc\-7bdfc2e940f8*&lt;/query&gt;&lt;/delete&gt;
IV 15, 2015 1:45:32 ODP. cz.incad.kramerius.indexer.FedoraOperations getFoxmlFromPid
INFO: getFoxmlFromPid pid=uuid:89b5bcd1-075e-4c6f-b5fc-7bdfc2e940f8
IV 15, 2015 1:45:34 ODP. cz.incad.kramerius.indexer.SolrOperations indexByPid
INFO: indexing -&gt; uuid:89b5bcd1-075e-4c6f-b5fc-7bdfc2e940f8; count: 0
IV 15, 2015 1:45:34 ODP. cz.incad.kramerius.indexer.SolrOperations indexByPid
INFO: indexing -&gt; uuid:db2f2c5f-8f59-4435-bfc6-1d7512f80b82; count: 1
IV 15, 2015 1:45:35 ODP. cz.incad.kramerius.indexer.SolrOperations indexByPid
INFO: indexing -&gt; uuid:4e7e6ced-8cd6-4585-ad81-e1e77f7d8f14; count: 2
...
IV 15, 2015 1:49:22 ODP. cz.incad.kramerius.indexer.SolrOperations indexByPid
INFO: indexing -&gt; uuid:de7f66fe-793b-11e4-ae4c-00155d010f03; count: 647
IV 15, 2015 1:49:22 ODP. cz.incad.kramerius.indexer.SolrOperations indexByPid
INFO: indexing -&gt; uuid:de7f66ff-793b-11e4-ae4c-00155d010f03; count: 648
IV 15, 2015 1:49:24 ODP. cz.incad.kramerius.indexer.SolrOperations updateIndex
INFO:  fromKrameriusModel docCount=896 920
IV 15, 2015 1:49:24 ODP. cz.incad.kramerius.indexer.SolrOperations updateIndex
INFO: insertTotal: 0; updateTotal: 649; deleteTotal: 1; warnCount: 0
IV 15, 2015 1:49:24 ODP. cz.incad.kramerius.indexer.Indexer run
INFO: Index process success
IV 15, 2015 1:49:24 ODP. cz.incad.kramerius.indexer.Indexer run
INFO: 0 hour(s) 3 minute(s) 54 second(s)
IV 15, 2015 1:49:24 ODP. cz.incad.kramerius.processes.utils.ProcessUtils closeToken
INFO:  close token for &#039;ac7cb4ec-a3ff-4535-9120-9d33b3b8a4f5&#039;

**Comment by vlahoda** [comment]
A nemáte prosím nějak předefinovanou property fedora.topLevelModels v configuration.properties nebo indexer.browseModels v indexer.properties?

**Comment by mduda100871** [comment]
Zdravim,

potvrzuji problem, projevil se i u nas - zrovna vcera jsem se na to narazil na nasem testovacim serveru. Nejdrive jsem myslel, ze je "nakopnuty" index, takze jsem spustil komplet reindexaci podle modelu, ale bez uspechu (reindex dobehl bez chyb, ale tituly proste zmizely z nabidky, pres administrativni rozhrani pro indexaci se ale vsechny tituly tvari radne indexovane - zelena "fajfka").

Nastaveni v SVKHK:

[configuration.properties]
fedora.topLevelModels=monograph,periodical

[indexer.properties]
neni uvedena, tudiz je predpokladam brana defaultni hodnota

Nastaveni v KNAV:

[configuration.properties]
fedora.topLevelModels=monograph,periodical,soundrecording,manuscript,map,sheetmusic

[indexer.properties]
indexer.browseModels= ${fedora.topLevelModels}

Duda

**Comment by mduda100871** [comment]
Jeste doplneni - verze Solru u obou instanci je:

Solr Specification Version: 3.5.0.2011.11.22.14.54.38
Solr Implementation Version: 3.5.0 1204988 - simon - 2011-11-22 14:54:38

JDK u obou instanci - 1.7.0_76-b13

Duda

**Comment by vlahoda** [comment]
Chyba se defaultně projevuje u všech typů titulů kromě monografií a je to zřejmě způsobeno chybou v použité konfigurační knihovně Apache Commons Configuration. 
Dá se to okamžitě obejít tím, že explicitně nastavíte v indexer.properties hodnotu indexer.browseModels na seznam modelů, které se mají zobrazovat v seznamu titulů, např.: indexer.browseModels=monograph,periodical,soundrecording,manuscript,map,sheetmusic
"Zmizelé" tituly je pak  třeba znovu přeindexovat.

**Comment by mduda100871** [comment]
Ano, kdyz jsem do indexer.properties vyjmenoval konkretni modely a zkusil reindex "zmizeleho" periodika, tak po skonceni reindexace se titul objevil v zalozce [Tituly].

Domnivam se spravne, ze seznam modelu nebyl spravne predan prostrednictvim promenne "${fedora.topLevelModels}" a to je ten bug v konfiguracni knihovne? 

Duda

**Comment by vlahoda** [comment]
Ano, to je přesně ta příčina. Autoři knihovny se bohužel neshodují v tom, jestli je to bug nebo feature ... takže to vyřešíme jinak.

**Comment by mduda100871** [comment]
Fajn, aspon, ze vime co to zpusobuje. Nastavim tedy prozatim vsude kde muzu seznam modelu explicitne primo v indexer.properties.

Diky

**Comment by mduda100871** [comment]
Zdravim,

tak to vypada, ze to asi ma pokracovani. Prestoze jsem nastavil prislusnou property dle doporuceni, tak se obsah zalozky [Tituly] chova zvlastne/nahodile. Mam konkretni priklad.

http://k4.svkpl.cz/search/

Naimportoval se titul (balicek ve formatu NDK). Konverze, import a indexace - vse probehlo bez problemu. Nasledne se K5 chova tak, ze kdyz se vybere zalozka [Titul], tak inkriminovany titul se v seznamu objevi 2x (musi se skrolovat koleckem, nikoliv vybrat prislusne pismenko abecedy). Naopak, kdyz se rovnou vybere prvni pismenko z nazvu (v tomto pripade "Z"), tak se ve zuzenem vyberu titul objevi pouze 1x, dle ocekavani.

Konkretne jde o titul "http://k4.svkpl.cz/search/handle/uuid:8c84acc2-1253-4012-984d-3629ff0e0daa" s nazvem "Západočeský motorista: oficielní měsíčník Ligy čsl. motoristů, skupiny Plzeň, sloužící zájmům automobilistů a motocyklistů".

Prikladam screenshoty.
![svkpl_01](https://cloud.githubusercontent.com/assets/8750622/7247828/fd44e164-e80d-11e4-8712-9f71a9a02ab9.png)
![svkpl_02](https://cloud.githubusercontent.com/assets/8750622/7247829/01bc0ccc-e80e-11e4-870f-16ccfbca8398.png)

Cely proces importu jsme opakovali dvakrat a pokzade to dopadlo stejne.

Diky

**Comment by vlahoda** [comment]
Potřebovali bychom přístup k rozhraní toho konkrétního solr indexu. Jde to zařídit?

**Comment by mduda100871** [comment]
Pokusim se to dohodnout s mistnim spravcem.

**Comment by luckajirku** [comment]
tenhle problém už jsem sem před časem dávala - https://github.com/ceskaexpedice/kramerius/issues/210

**Comment by mduda100871** [comment]
Ano, chova se to i ve vasi instanci K5. Muzu do Solru tedy pustit vyvojare? Samozrejme omezim pristup jen z jejich IP a po skonceni "akce" to zase zakazu....

**Comment by albertoh** [comment]
Ano, to je problem #210 
Nesouvisi s reindexaci ani s tou posledni zmenu. Projevi jenom pri scrollovani, a opakuje posledni titul.

**Comment by luckajirku** [comment]
Jestli je to potřeba, tak klidně, ale tohle se děje všude od 4.8.5, co jsem tak tehdy procházela K4/5 dalších knihoven.

**Comment by mduda100871** [comment]
Jasne, v tom pripade Solr resit nebudeme. Ja jsem na to tedy nikde az doted nenarazil - mozna to bude tim, ze jsem vzdy pracoval s tak rozsahlym mnozstvim dat, ze jsem nemel trpelivost tocit koleckem az nakonec.

**Comment by vlahoda** [comment]
Není to už potřeba, omlouvám se -  jen jsem podle toho původního Martinova popisu neodhadl, že je to stejný problém, jako v #210

**Comment by luckajirku** [comment]
Někdy ani není třeba trpělivost:-), třeba u nás když kliknete na Z, nevejde se Z + Ž o jediný titul do okna, tak musíte kousek scrollovat, a je zdvojeno.

**Comment by albertoh** [comment]
Duplicitní issue k #210
