### ISSUE TITLE
Rozmazaný pruh v prohlížečce

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#237]
Při maximálním zoomu je u některých obrázků na pravé straně nezaostřený pruh, přitom imageserver posílá dlaždice správně.
Př: http://kramerius.fsv.cuni.cz/search/i.jsp?pid=uuid:519701a1-7c12-4a8b-bbec-e47a8c03960b
Př. dlaždice: http://kramerius.fsv.cuni.cz/search/zoomify/uuid:519701a1-7c12-4a8b-bbec-e47a8c03960b/TileGroup0/3-4-2.jpg

**Comment by Jenyk** [comment]
Podobných problémů s prohlížečkou je mnohem víc, ale v OpenLayers ve verzi 3.x je všechno v pořádku.
Pomohla by aktualizace prohlížečky v serverové části krameria na verzi, kterou používá klient.

**Comment by pavel-stastny** [comment]
v pristim roce bude probihat reimplementace admin rozhrani  - bude pouzita novejsi prohlizecka
