### ISSUE TITLE
Stará issues z google code 

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#239]
Chtěl jsem se podívat na issue https://code.google.com/p/kramerius/issues/detail?id=333, ale to je přesměrováno na github na issue číslo 333 - což nefunguje, protože se stará issue na github nemigrovala.

Nicméně na projektové schůzce 1.2.2014 bylo domluveno, že dojde k exportu uzavřených issues a bude umístěn odkaz na GitHub. Vím je to dávno, ale bylo by možné toto doplnit, případně vymyslet jinou cestu, jak prohlížet stará issues? Někdy to může mít smysl, bylo tam hodně informací.

**Comment by vlahoda** [comment]
Původní projekt z googlecode včetně starých issues je nyní exportován na ceskaexpedice/kramerius-googlecode-backup
