### ISSUE TITLE
Issue 459:	přehlednost menu (globální i k objektu)

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#24]
Reported by Martin.Rehanek, Oct 26, 2012
Uvědomil jsem si, že se ne moc dobře orientuju v menu k vybranému objektu nebo globálnímu menu zvláště, když tam přibývá položek. A to je používám docela často.
Tak mě napadá, je ta forma vhodná? Položky vypadají téměř jako odkazy. To zvýraznění položky, nad kterou je myš, určitě přehlednosti pomáhá. Zase ty šipky po levé straně evokují "rozkliknutelnost" a podmenu. 
Co třeba vyzkoušet, jak by to vypadalo, kdyby místo toho byly tlačítka? Stejně se volá nějaký javascript. Jedná se o akce a kliknutí téměř vždy způsobí zobrazení nového okna.

Druhá věc je pojmenování a seskupení položek. Mám pocit, že by se mělo přehodnotit pojmenování a uspořádání jednotlivých akcí v seznamu a použítí oddělovačů. Jaký mají smysl tři tečky za některými akcemi? Taky by se to mohlo gramaticky sjednotit (jednou infinitiv, jindy zpodstatnělé jméno).
Konkrétně:
Menu k objektu:
Odstranit z Fedory - nebylo by lepší "trvale odstranit"? Pan Lahoda se vyjádřil proti v komentáři k  issue 285 .
Zobrazení práv - řeší se tu nejen zobrazení, ale práva je možné i přidávat. Nebylo by lepší "nastavení práv"?. To samé platí pro práva pro streamy.
Uspořádání bych viděl třeba takto:

Perzistentní URL
Zobrazit metadata
Stáhnout originál
## Generovat PDF

Přidat k oblíbeným
# Zpětná vazba

Nastavení viditelnosti 
Nastavení práv
Nastavení práv pro streamy
Upravit pořadí částí
## Reindexovat

Generovat cache pro deep zoom
## Smazat cache pro deep zoom

Odstranit z indexu
## Trvale odstranit

Exportovat FOXML
## Exportovat do PDF

Zařadit/odebrat do/z virtuálních sbírek
Poslat do tiskové fronty
(Přibyly by 4 řádky - oddělovače, což není zas tak moc. Navíc oblast menu je skrolovací)

Globální menu:

Historie hledání
Uložení profilu
# Změna hesla

Správa procesů (jsme v adm. sekci, jiné než administrativní procesy nejsou)
Indexace dokumentů
## Adminstrace virtuálních sbírek

Editor uživatelů
Editor rolí
Editor globálních práv
Editor parametrů dodatečných podmínek
## Editor pořadí částí

 Importy (tohle jen neklikatelný text, takový popis sekce)
Importovat tituly ve formátu K3
Importovat tituly ve FOXML
## Importovat tituly ve formátu NDK METS

 Replikace z K3 (taky neklikatelný nadpis)
Stáhnout seznam identifikátorů z K3
Povolit replikaci v K3
## Spustit replikaci

Replikovat záznamy z K4

(Tady by přibylo taky 5 nových řádků)
Myslím, že to mírné zvětšení menu na výšku by nemělo být problém. Pro ukázku aktuální stav:
https://dl.dropbox.com/u/7787647/Kramerius/kramerius_menu.png (vpravo relativně malý monitor 1280:1024 a pořád dost místa).

Možná by to logické přeuspořádání a větší použití oddělovačů dostatečně zpřehlednilo samo o sobě.
Jun 28, 2013 Delete comment Project Member #1 karel.kriz@nkp.cz
Tohle mi přijde jako dobrý nápad, stejně tak návrh p. Dudy na shromáždění funkcí spojených s K3 k sobě.
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Uz neaktualni
