### ISSUE TITLE
Nezobrazování názvu titulů po výběru více titulů k indexaci a při hodně titulech se indexace ani nespustí

### ISSUE THREAD

**Issue by FoxKyong** [ceskaexpedice/kramerius#241]
Když chci reindexovat více titulů a vyberu je, tak místo názvu titulů se zobrazí Null. Když dám pak, že chci indexovat, tak se dají do indexace. Pokud těch titulů ale vyberu více (třeba 60 a více najednou), tak to stále zobrazuje, že se připravuje proces spuštění indexace a na tom to skončí a procesy na indexaci to nenaplánuje.
![snimek18](https://cloud.githubusercontent.com/assets/2877720/7610467/6bc33dc2-f97d-11e4-8a0a-1b96941ff857.png)

**Comment by LenkaDamborska** [comment]
Máme podobný problém s dávkovým zařazením vybraných titulů do virtuální sbírky - jakékoliv dávkově spuštěné procesy u vybraných titulů evidentně nefungují.
