### ISSUE TITLE
Kramerius nepoužívá primární název v html <title>

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#242]
V MODS můžou být kromě primárního názvu (\<mods:titleInfo\>) i alternativní názvy (\<mods:titleInfo type="alternative"\>). Kramerius by v záhlaví stránek neměl používat alternativní názvy dokumentů.
Viz: http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:c3318d70-6f69-11e2-b9fa-005056827e52 (primární název je Čin, alternativní jsou Dětský Čin a Štika)

Problém se týká i K5 klienta, tam je alternativní název použitý na víc místech: 
http://krameriusndktest.mzk.cz/client/index.vm?q=%C4%8Din&page=search
http://krameriusndktest.mzk.cz/client/index.vm?q=%C4%8Din&page=doc#uuid:c3318d70-6f69-11e2-b9fa-005056827e52

**Comment by vlahoda** [comment]
Duplicitní issue k #122
