### ISSUE TITLE
Pohyblivá zeď

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#244]
Zámečky u nepřístupných dokumentů (resp. čtverečky u přístupných) nereflektují nastavení pohyblivé zdi. Přístupné dokumenty potom můžou pro uživatele vypadat jako nepřístupné a naopak.

Podobně není pohyblivá zeď zohledněná v klientském API - dotaz stále vrací "policy":"private", i když zeď dokument zpřístupňuje.

Ještě otázky ke zdi - dá se nastavit pouze na určitý model? Například jinak pro všechna periodika a jinak pro monografie.

**Comment by pavel-stastny** [comment]
No, on priznak policy je pouze cast metadat.  Jedna se o element v (DC  a RELS-EXT ) a je nastavovan administratorskou akci  "Zmena viditelnosti..".  V pravech je to pak pouze jedno ktriterium ("Priznak policy"). 

API tento priznak pouze predava do JSON reprezentace. Pro to, zda je titul pristupn ci nepristupny pak API vraci kod 200 ci 403 (u streamu, ktere jsou chranene IMG_FULL, TEXT_OCR). 

A kdruhe otazce.  Bohuzel nejde... respketive jde napsat a pridat nove kriterium, ktere by bralo parametry pocet let a model.

**Comment by Jenyk** [comment]
Ok, ale co například hledání veřejných dokumentů? Jak to funguje tam?
Pokud se jenom pokládá dotaz do solr na příznak dostupnost a už se neřeší další pravidla (moving wall), tak to není moc použitelné.
To bude asi podobný problém jako s těmi zámečky, ne?

**Comment by vlahoda** [comment]
Tento problém se rozebíral na mnoha schůzích projektového týmu od samého začátku projektu K4, informujte se prosím u svých kolegů, kteří se schůzí účastnili.
Jde o to, že ve výsledcích vyhledávání a v navigačním stromu v levém panelu jsou z výkonnostních důvodů využívány pouze statické informace z indexu solr, ikonky zámečků/semaforků tedy odpovídají pouze obsahu atributu policy. Dynamická pravidla pro přístupová práva, jako pohyblivá zeď nebo ip filtr, nelze z principu indexovat a pro zobrazení zámečků nejdou aplikovat - tato pravidla jsou vyhodnocována a uplatněna až při konkrétním požadavku na chráněnou akci či obsah.

**Comment by MartinRumanek** [comment]
Chápu důvody, pro ip filtr to smysl má. Ale jestli má takto fungovat moving wall, tak si troufám říci, že je to velmi nešťastné. 

Minimálně v Androidí aplikaci (@honza-rychtar)  se standardně zobrazují jenom veřejné dokumenty a uživatel tyto dokumenty zpřístupněné pohyblivou zdí vůbec nenajde. Čtverečky tedy nevadí, ale toto je závažný problém.

Řešením by bylo implementovat něco podobného, jak je naznačeno ve vašem  #38.
