### ISSUE TITLE
Generování pdf - formát stránky neodpovídá poměru stran obrázku

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#247]
Upravit generování pdf tak, aby velikost každé stránky odpovídala velikosti obrázku - nemá smysl generovat prázdné okraje. Viz např. http://kramerius.mzk.cz/search/handle/uuid:87aea16e-b81c-41eb-890f-1756110e822e

**Comment by vlahoda** [comment]
Řešení bude otáčet obrázky, jejichž šířka je větší než výška, při vkládání do PDF o 90°.

**Comment by zabak** [comment]
proč? pak se to bude blbě číst. Nemůžete generovat pdf o takovém poměru stran, jako mají obrázky?

**Comment by zabak** [comment]
je na to issue v klientovi https://github.com/ceskaexpedice/kramerius-web-client/issues/97 zde navrhuji zavřít.

**Comment by pavelkocourek** [comment]
23.4. KNAV
