### ISSUE TITLE
Přidat do zobrazení metadat v K5 client - info / logo donatora

### ISSUE THREAD

**Issue by albertoh** [ceskaexpedice/kramerius#249]

**Comment by MartinRumanek** [comment]
Je informace o donátorovi poskytována v API, nebo se to bude do něj dodělávat v rámci tohoto issue?

**Comment by pavel-stastny** [comment]
Je az ted, viz komit vyse.  Polozka "item" je nyni obohacena o klic "donator", kde je uveden pid  napr: "donator:norway".  Dotaz na logo ci texty je mozno ziskat standardne pomoci ~/item/<donatorpid>/streams/LOGO, ~/item/<donatorpid>/streams/TEXT.. atd.

**Comment by MartinRumanek** [comment]
Díky moc!
