### ISSUE TITLE
Issue 490:	Generování dvouvrstvého pdf z obrázku a ALTO

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#25]
Reported by zabak@mzk.cz, Dec 5, 2012
Pokud je u stránky přítomno i ALTO, měl by systém generovat dvouvrstvé pdf, tj. viditelný by byl obrýzek stránky jako teď a "pod ním" by byla textová vrstva generovaná z ALTO XML.
Dec 5, 2012 Delete comment Project Member #1 pavel.kocourek@incad.cz
(No comment was entered for this change.)
Labels: -Type-Defect Type-Enhancement 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold 
Owner: pasilhavy

**Comment by zabak** [comment]
Kdy můžeme čekat výsledek?

**Comment by pavel-stastny** [comment]
Byla integrovana komponenenta vyvijena v knav (commits: e9d92ba9993128e3b2a134baf7dc90115f3f9d71 a e757cddb453e13a8ad9f1a73dabe5dc9ea84d49e).  Rizeno konfiguracni promennou `"pdfQueue.useAlto"`

**Comment by kenji1322** [comment]
V configuration.properties som nastavil premnnú pdfQueue.useAlto na true no Kramerius aj tak negeneruje dvojvrstvové pdf. Kde je teda potrebné tento príznak nastaviť aby to fungovalo správne?
