### ISSUE TITLE
rekurzivní automatické třídění

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#254]
Automatické třídění nefunguje rekurzivně a ani nejde spustit hromadně (zaškrtnutím několika např. ročníků). 
Existuje na to nějaké nastavení?

**Comment by Jenyk** [comment]
Mimochodem tohle https://github.com/paour/natorder by mohlo řešit problémy popsané @luckajirku v https://github.com/ceskaexpedice/kramerius/issues/207

**Comment by vlahoda** [comment]
Žádné nastavení k tomu neexistuje. Rekurzivní třídění není žádoucí, hromadné spouštění z GUI můžeme doplnit. Jinak je proces třídění samořejmě možno pouštět dávkově přes API.

**Comment by Jenyk** [comment]
Ok, to by určitě pomohlo. I tak by se ale pro setřídění většího periodika muselo zaškrtat docela dost políček. Proč není rekurzivní třídění žádoucí?

**Comment by vlahoda** [comment]
Minimálně stránky uvnitř čísel a obvykle i čísla uvnitř ročníků jsou správně setříděna už " z výroby" a automatické třídění by je vzhledem k časté nekonzistenci číslování spíš přeházelo, než správně setřídilo. Kromě toho by to trvalo zbytečně dlouho. Případná rekurze by tedy musela být konfigurovatelná a myslím se, že ta konfigurace by byla stejně složitá, jako naklikání položek, které se mají explicitně setřídit.
