### ISSUE TITLE
Hledání několika slov, která nejsou těsně u sebe, ale v určité vzdálenosti

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius#256]
U K3 funguje stejný tip pro hledání jako u vídeňského ANNO: tedy 
Tipps zur Suche
Verbinden Sie Begriffe zu einer Abstandssuche, so werden diese Begriffe nur im angegebenen Abstand zueinander gefunden, unabhängig von der Reihenfolge!
Zum Beispiel: "Shackleton Südpol"~10

Bylo by vhodné, aby totéž bylo možné i v K4, resp. K5

**Comment by albertoh** [comment]
Tento issue uz je vyresen #88

**Comment by albertoh** [comment]
Pri napsani dotaz s prefixem SOLR: napr:
SOLR:vzácné knihy AND fedora.model:monograph 
SOLR:"kůslích ledě"~2
bude poslano primy dotaz do solr v parametru q bez dalsich zpracovani

**Comment by BrozekAles** [comment]
No, vida, ze to jde, kdyz se chce a je to drive nez do konce letosniho 
roku :-) Takže budu chválit na semináři v Chodovci :-)

Velký dík za to. "kůslích ledě" vyhledávat nepotřebuji, ale články, v 
nichž se píše o vyvěšování praporů v zemských či městských barvách, ano.
Dotaz SOLR:"prapory barvách"~5  jsem zkusil v 
http://krameriusndktest.mzk.cz/
a dostal jsem 577 dokumentů včetně textu "PRAPORY A VLAJKY ve státních 
barvách", což dříve nebylo možné najít. Problém ale je, že tento dotaz 
nefunguje (resp. nenajde se ani jeden záznam) v http://kramerius4.nkp.cz/
Proč???

Doplní někdo z vývojářů K5 text o využití SOLR do Nápovědy, aby se to 
uživatelé dozvěděli? Zatím tam máme jen text:
Velké pole uprostřed záhlaví stránky umožňuje vyhledávat v plném textu 
dokumentů v digitální knihovně - zapište hledané slovo a klikněte na 
symbol lupy. Pro hledání je možné použít zástupný znak * nahrazující 
libovolnou část slova, případně znak ? nahrazující jedno písmeno. Dále 
jsou k dispozici logické operátory AND, OR a NOT. Pokud chcete vyhledat 
přesný tvar slovního spojení, uzavřete požadovaná slova do uvozovek.

Velký dík předem.
Zdravím


   Ing. Aleš Brožek
   Severočeská vědecká knihovna, p.o.
   The North Bohemian Research Library
   W. Churchilla 3
   CZ-400 01  Ústi nad Labem
   Czech Republic
   Tel./fax (+420)475 200 045
   Mobile +420731578269
   e-mail address: brozek@svkul.cz

Please consider the environment before printing this email.
Prosím, zvažte dopad na životní prostředí před tiskem tohoto mailu.

Dne 20.7.2015 v 16:17 albertoh napsal(a):
