### ISSUE TITLE
příznak odrážející dostupnost na nižších úrovních

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#259]
V klientech dělá problémy, když je např. na úrovni periodical příznak private, ale v periodiku jsou přesto public ročníky a/nebo čísla.

Šlo by upravit proces změny příznaku tak, aby tohle respektoval? Tj. při zpřístupnění se zpřístupní i rodiče, při znepřístupnění posledního sourozence na dané úrovni se znepřístupní rodič (a podobně výš, úrovní nebývá moc).

**Comment by zabak** [comment]
Navrhuji zde taky zavřít
