### ISSUE TITLE
Issue 491:	generování fulltextového ebooku z fulltextu

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#26]
Reported by zabak@mzk.cz, Dec 5, 2012
Systém by měl umět vygenerovat nejen pdf ale pokud je přítomen fulltext, tak by Kramerius měl být schopen generovat nejen pdf ale i nějaký jiný formát pro ebooky, jen z fulltextu - konkrétně asi .mobi a .epub
Dec 5, 2012 Delete comment Project Member #1 pavel.kocourek@incad.cz
dobrý nápad - pisu do hlasovaci tabulky na rozvoj :)
Labels: -Type-Defect Type-Enhancement 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by zabak** [comment]
Řeší se mimo Kramerius
