### ISSUE TITLE
K5 - časová osa

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#261]
Zachovat časovou osu jako filtr při vyhledávání.

**Comment by krizovj** [comment]
Úplně nevím, jestli to neplatí pro klienta K6. V jádru mi filtr podle časové osy zůstává, dokud ho nezruším...
![casovaosa](https://user-images.githubusercontent.com/21309201/55063275-f0a22800-5077-11e9-9530-f12af3df9f9d.jpg)

**Comment by krizovj** [comment]
Může se zavřít
