### ISSUE TITLE
K5 - registrace nového uživatele

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#262]
Pod tlačítko "Registrace nového uživatele" přidat informaci o tom, na co je uživatelský účet.
Věta by měla znít asi takhle: "Registrovaný uživatel si může ukládat dokumenty do oblíbených." Dál přesně nevím, jestli je to přihlášení ještě na něco. Takže kdyžtak prosím doplnit.

**Comment by pavel-stastny** [comment]
K tomuto ucelu slouzi popiska nad tlacitkem a je administratorsky konfigurovatelna pomoci klientskeho bundlu a klice:

`login.registrationtext`

Pokud bude potreba jeste dalsi popiska pod tlacitko, prosim, otevrit nove issue.
