### ISSUE TITLE
K5 - výsledky vyhledávání

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#263]
Zobrazení výsledků vyhledávání:
zrušit drobečkovou navigaci
všechny rámečky stejně velké

1) na úrovni titulů:
do rámečku s výsledkem umístit vlevo obrázek a vpravo text z metadat

2) na úrovni ročníku a čísla:
do rámečku umístit uprostřed obrázek, nad ním datum vydání a pod ním ročník/číslo, včetně popisku, co to je
po pravé straně umístit panel s metadaty o titulu časopisu
do panelu s metadaty přidat také šipky o úroveň výš, předchozí a následující ročník/číslo

**Comment by slapakovai** [comment]
A ještě jsem zapomněla, že panel s metadaty nesmí překrývat rámečky s výsledky vyhledávání.

**Comment by pavelkocourek** [comment]
Drobečková navigace je nevýrazná. Nikoliv je zrušení.

**Comment by slapakovai** [comment]
Pavle, poslední dohoda, když jsi tam už nebyl zněla, že se drobečková navigace zruší. Ale klidně můžeme hlasovat.

**Comment by slapakovai** [comment]
Informace z drobečkové navigace se přesunou do panelu s metadaty, takže by byla zbytečná.

**Comment by slapakovai** [comment]
Na základě připomínek MZK prosím ponechat drobečkovou navigaci.

**Comment by albertoh** [comment]
Zobrazeni opraveno
