### ISSUE TITLE
K5 - tlačítko zobrazit informace

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#267]
Přesunout tlačítko zobrazit informace do panelu s metadaty. Po jeho stisknutí se zobrazí kompletní metadata. V panelu s metadaty bude jako "Více informací"

**Comment by MLhotak** [comment]
K tomu je třeba dodat, že pokud nebude zvoleno tlačítko "více informací" bude v pravém, panelu pouze stručnější základní informace o metadatech.
