### ISSUE TITLE
 Issue 492:	Zastavení načítání .JP2 obrázku v K4 při prohlížení v prohlížeči Google Chrome na OS Windows 7

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#27]
Reported by Jakub.Rihak, Dec 6, 2012
Dobrý den,

v NTK jsem se setkali s chybou, kdy při prohlížení digitalizovaných dokumentů v K4, které máme na image serveru ve formátu JPEG2000 se načte vždy jen kousek obrázku (jen některé dlaždice). Tato chyba se vyskytuje ale pouze v prohlížeči Google Chrome v kombinaci s OS Windows 7. Pokud prohlížím stejný dokument ve Firefoxu (rovněž ve Windows 7), obrázky se načtou bez problémů.

Testoval jsem také, jestli se podobná chyba objeví, když spustím Google Chrome v Ubuntu 12.04 s těmito výsledky: 

Google Chrome na Ubuntu: obrázky se načítají bez problémů
Chromium na Ubuntu: obrázky se načítají bez problémů
Firefox na Ubuntu: obrázky se načítají bez problémů

Chtěl bych se proto zeptat, zda se někdo z vás již s něčím podobným setkal? (screenshot je v příloze)

Zkoušel jsem to i na svém osobním PC doma, kde mám rovněž Windows 7 a prohlížeč Google Chrome a tam mi to fungovalo...

Děkuji,

Jakub Řihák
NTK

Kramerius verze 4.6 (revize 4446)

```
kramerius_NTK_bad.jpg 
```

404 KB   View   Download    

Feb 2, 2013 Delete comment #1 petrkr
Nevim jestli to s tim bude souviset, ale ume, kdyz sem generoval deep-zoom-cache a mel sem problem se spatnou kvalitou dlazdic, tak po pregenerovani z jineho JP2 zdroje to bylo porat stejne v Google chrome, presto v opere/ff to bylo OK...

Nakonec sem zjistil, ze to je z duvodu cache prohlizece... Je tedy mozne, ze toto muze bejt stejny pripad, kdy ma chrome na tomto PC nejak nakesovane prazdne dlazice... Zkusil bych tedy promazat cache...

Feb 11, 2013 Delete comment #2 Jakub.Rihak
Tak jsem zkoušel promazat cache v Google Chromu a nemá to na načítání obrázku vliv.

V příloze posílám screenshoty z konzole v Chromu.

Děkuji moc,

Jakub Řihák
NTK

```
error_console.jpg 
```

595 KB   View   Download    

```
network_console.jpg 
```

704 KB   View   Download    

Jul 4, 2013 Delete comment Project Member #3 vlahoda
(No comment was entered for this change.)
Owner: pavel.stastny 
Jul 4, 2013 Delete comment Project Member #4 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
neaktualni
