### ISSUE TITLE
K5 - fitry

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#272]
Jak bylo stanoveno, podle čeho se bude filtrovat? Jde nějak nastavit, aby se dalo filtrovat stejně jako v K4? Tedy podle:
1) Typ titulu nebo typ dokumentu (nevím, jaký je mezi nimi rozdíl)
2) Jazyk dokumentu (používat hodnotu pouze z elementu languageTerm, bez atributu objectPart="translation" )
3) Klíčová slova
4) Autoři a spoluautoři
5) Dostupnost
6) Rok vydání
7) Sbírka

Pokud se bude filtrovat podle typ dokumentu, jde z něj vybrat jenom nějaké smysluplné typy, které by se zobrazovaly ve filtrech? Teď tam je např. i stránka, podle které nemá smysl filtrovat, dále je tam třeba fedora.model.archive nebo fedora.model.supplement. To se mi zdá pro uživatele matoucí.

Pod nápis Použité fitry přidat text: "Nejsou použity žádné fitry", pokud nejsou filtry použity.

**Comment by albertoh** [comment]
Je to nastavitelne pomoci konfiguracniho souboru
.kramerius4/k5client/fields.json 
Napriklad: 
{
  "facets":["model_path", "keywords", "language", "collection", "dostupnost"]
}
