### ISSUE TITLE
K5 - filr podle virtuálních sbírek

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#274]
Ve filtrech se má virtuální sbírka zobrazit pod svým názvem, teď se zobrazuje pod uuid.

**Comment by albertoh** [comment]
duplicate #275

**Comment by slapakovai** [comment]
To není duplikát issue 275. Tohle issue je pro K5, issue 275 je pro K4. Prosím znovu otevřít.
