### ISSUE TITLE
K5 - titulní strana, hlavní vyhledávací pole

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#277]
1) přidat doprava do hlavního vyhledávacího pole ikonku lupy pro vyhledávání kliknutím (nejenom entrem)
2) text v tomto vyhledávacím poli může měnit administrátor? Pokud ne, je možné to naprogramovat?
3) šlo by pod něj přidat nějaké přepínátko hledat pouze ve veřejných dokumentech?

**Comment by albertoh** [comment]
2) tento text lze menit lokalizacnim klicem
    query.placeholder
