### ISSUE TITLE
Issue 517:	Statistiky - přidat sledování přístupnosti (public/private)

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#28]
Reported by zabak@mzk.cz, Jan 25, 2013
Součástí statistik musí být filtrace podle toho, jestli je to autorsky chráněné nebo ne (v době kdy k použití dokumentu došlo). Do budoucna zohlednit připravovaný autorský zákon.
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Owner: pavel.stastny 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by zabak** [comment]
Toto lze uzavřít, prozatím bude stačit když bude vyřešeno #394

**Comment by pavel-stastny** [comment]
Filtr viditelnosti pridan
