### ISSUE TITLE
K5 - procházení - abecední řazení

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#281]
Není podle abecedy, např. Ď se řadí před D. Prosím opravit.

**Comment by albertoh** [comment]
Ď neni před D, ale maji stejnou prioritu. Tak Ďábel je pred Daleká

**Comment by zabak** [comment]
Ale to nevyřešilo problém, že to není podle abecedy! Je jedna věc, že při vyhledávání d=ď, ale u abecedního seznamu je to špatně.

**Comment by vlahoda** [comment]
Je to podle abecedy. 
http://prirucka.ujc.cas.cz/?id=900 

Písmena s diakritickými znaménky, která ve výše uvedené řadě nejsou uvedena (tj. á, ď, é, ě, í, ň, ó, ť, ú, ů, ý), se posuzují jako prostá základní písmena bez diakritických znamének, například:

da capo 
ďábel 
dabing

ucho 
úchop 
uchopit

**Comment by zabak** [comment]
OK, to mi nedošlo.
