### ISSUE TITLE
Issue 523:	Záložka Přehled importu

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#29]
Reported by karel.kriz@nkp.cz, Jan 30, 2013
V K3 má každý import přehled informací. Obsahuje datum, čas, název importu atd. Je zde uveden i operátor, který import provedl a jaké soubory byly importovány. Myslím že by bylo vhodné mít nějaký podobný lidský log (jako má K3) i v K4. Např formou nové záložky Import, která by se mohla zobrazovat pouze správci bez práv k přístupu do celkové Správy administrátorských procesů.
    K3_prehled_importu.jpg 
398 KB   View   Download    

Jan 30, 2013 Delete comment Project Member #1 karel.kriz@nkp.cz
V případě replikace by bylo uvedeno, kdo, kdy a odkud jí provedl.
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold 
Jul 19, 2013 Delete comment Project Member #3 pavel.kocourek@incad.cz
Pravděpodobně bude sledováno z linky zpracování v NK - bude probráno na schůzce.

**Comment by pavel-stastny** [comment]
implementovano
