### ISSUE TITLE
Opakovaný import PSP balíčku

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#294]
Dobrý den,

při opakovaném importu stejného titulu z PSP formátu do K4 se duplikují stránky dokumentu.

Důvod je zřejmý, PSP balíček obsahuje pouze uuid celého dokumentu a kapitol, uuid stránek tudíž nutně musí generovat konverzní proces z PSP do foxml. Při opakované konverzi se pro stránky vygenerují nová uuid, čímž dojde k jejich duplikaci.

Korektní řešení je, při procesu konverze PSP do foxml zkontrolovat, jestli ve fedoře existuje dokument se stejným uuid a pokud ano, převzdít uuid stránek z něj.

**Comment by vlahoda** [comment]
To bohužel nejde, konverze PSP do FOXML je nezávislá na fedoře.

**Comment by svetlym** [comment]
Což je zjevně chyba.

**Comment by vlahoda** [comment]
Ano, chyba v návrhu struktury PSP.

**Comment by svetlym** [comment]
To je pravda.
Upozornil jsem na tento problém zástupce formátového výboru.
