### ISSUE TITLE
Zakázání tisku u dokumentu

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#296]
Mám dotaz, jestli je možné zakázat tisk pro konkrétní dokument. U některých dokumentů je to bohužel žádoucí, i když jich moc není (např. autorsky chráněné hudebniny).

**Comment by vlahoda** [comment]
Dokumenty, které nejsou veřejně přístupné, není možné ani zobrazit v plném rozlišení, ani tisknout.

**Comment by LenkaDamborska** [comment]
Mám ale na mysli neveřejné dokumenty, u kterých je povolený tisk v budově knihovny.

**Comment by vlahoda** [comment]
Přístupová práva chrání souhrnně jakýkoli přístup k datastreamu IMG_FULL (tedy obrazu v plném rozlišení), nerozlišují, jestli jde o prohlížení, tisk, generování PDF nebo export. Zakázat tedy zvlášť tisk jednotlivých dokumentů nejde.
