### ISSUE TITLE
Issue 139:	Náhled objektu podle titulní strany

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#3]
Reported by pokorsky, Jun 28, 2011
Náhledy pro objekty, které neobsahují IMG_FULL stream (monografie, periodikum, ...) se nyní vyhledávají průchodem hierarchie potomků a použije se náhled prvního potomka obsahujícího IMG_FULL stream.

Vybraný objekt tak může být např. prázdná stránka. Aby se zaručilo, že náhled je smysluplný, Kramerius by měl využít bibliografické údaje obsahující informace o titulní straně.

Pro rychlé vyhledání náhledu bude vhodné použít Fedora resource index a doplnit do něj informaci o titulní straně z BIBLIO_MODS (<mods:part type="TitlePage">).

Nová vazba v RELS-EXT bude kramerius:titleObject s hodnotou "true" pokud jde o titulní stránku. Pokud ne, vazba se nepoužije nebo bude "false".
Mar 27, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavelkocourek** [comment]
kopíruju z mailu info z NKP:
Pokud jde o dotaz na reprezentativní stranu, tak na tom pracujeme. Přímo ve standardu to zakotveno nemáme, alespoň ne přímo, ale existuje naše vnitřní směrnice, jak stranu identifikovat. Teď ověřujeme, zda lze tento postup nějak přesně definovat na základě metadat. Ozveme se, jakmile testování dokončíme. 
Děkuji.
S pozdravem
Zdeněk Vašek

**Comment by pavel-stastny** [comment]
@pavelkocourek @vlahoda  Pro reprezentativní stranu máme issue #626.  Pokud by tam něco chybělo, prosím o doplnění.
