### ISSUE TITLE
Issue 525:	Replikace - plánování procesu

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#30]
Reported by karel.kriz@nkp.cz, Jan 30, 2013
U replikací by bylo dobré mít možnost naplánovat proces na konkrétní čas, aby bylo možné replikovat v noci a nezatěžovat tak systém během využívání čtenáři.

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Zatim nepodporovano.. planovani je mozno pomoci api a systemoveho planovace (cron apod.)
