### ISSUE TITLE
Tisk u hudebnin

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#304]
Hudebniny (sheet music) s příznakem private by nemělo být možné tisknout ani v budově knihovny. Je to z důvodu autorské ochrany a výjimky, kterou ukládá autorský zákon pro hudební díla. Zobrazení digitální kopie na počítači v budově knihovny možné je, tisk už by ale neměl být. Krameria bude nutné nějak uzpůsobit.

**Comment by vlahoda** [comment]
V ticketu #296 jsem se Vám snažil vysvětlit, že není možné rozlišit, za jakým účelem se data v plném rozlišení na klientský počítač dostanou. Jakmile jsou data na klientu dostupná pro zobrazení, není možné  pomocí přístupových práv zabránit, aby si je uživatel vytiskl nebo uložil.

**Comment by MartinRumanek** [comment]
> Jakmile jsou data na klientu dostupná pro zobrazení, není možné pomocí přístupových práv zabránit, aby si je uživatel vytiskl nebo uložil.

Na našich "zabezpečených terminálech" samozřejmě uživatelům nedovolujeme obrázek stáhnout ani s nim nijak manipulovat. Jediné co můžou je procházet Krameria a použít Tisk z menu. To je plně legální s výjimkou právě hudebnin.
