### ISSUE TITLE
Tisk u hudebnin

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#305]
Navazuji na issue #304 a prosím NEZAVÍRAT!!! 

Nejde mi o to že to teď nejde. My to potřebujeme udělat tak, aby ten tisk zablokovat šel. Tj eskaluji toto issue na příští pracovní skupinu, kde se o tom musíme pobavit. Hledáme jak to udělat, ne proč to udělat nejde.

**Comment by pavelkocourek** [comment]
Musí se to pojmout obecně Bylo by fajn mít řešení pro prohlížeč na obecném počítači  pro i  "zabezpečený terminál", kvůli kterému se to diskutuje.
U terminálů je možným řešením specifikovat vypnutí funkcí  (v našem případě tisk a generování pdf)  a volání přes API a zakázat funkce prohlížeče.
Bude-li návrh tím lépe.
P

**Comment by honza-rychtar** [comment]
Nejlepe to vyresit na urovni prav.
Pridat pravo sheet_music_pdf a pri tisku ci generovani pdf dokumentu s modelem sheet_music overit jestli ma uzivatel sheet_music_pdf:true. Pravo by melo vetsi prioritu nez pristup k dokumentu pres povolenou IP adresu (na chranenem terminalu).
Kontrolovalo by se to na strane serveru, ne na klientovi.
Klientu je vice, muselo by se to resit i pro Android, iOS, ..

Zaroven by se takto generovani pdf neomezilo uplne. Pokud jsem napr. vydavatel hudebnin a nainstaluju si Krameria, mam admin prava, tak chci mit moznost si sve dokumenty tisknout.

Tohle by bylo obecne pro vsechny klienty a pro vsechny typy pristupu - prihlaseny/neprihlaseny uzivate, chranena sit s povolenym pristupem, admin/bezny uzivatel, ....

**Comment by pavel-stastny** [comment]
#406
