### ISSUE TITLE
Chybí procházení v nové instalaci K5 klienta

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#310]
V nové instalaci K5 klienta nemáme procházení: http://krameriusndktest.mzk.cz/client

**Comment by MartinRumanek** [comment]
procházení je možné povolit konfigurační volbou v client.properties

k5client.showbrowse=true

ale myslím, že by bylo vhodnější, kdyby byl standardní stav - procházení se zobrazuje, ale správce ho může zakázat
