### ISSUE TITLE
Klient poskytne přes zoomify i neveřejné dokumenty

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#311]
Klient používá vlastní endpoint na Zoomify dlaždice, který nehlídá autorizaci dlaždic. Na schůzkách jsme se bavili o tom, že klient bude komunikovat pouze přes API.

Správně by mělo tedy použít ten endpoint, který mu vrací API http://krameriusndktest.mzk.cz/search/api/v5.0/item/uuid:4cf1b670-048c-11e5-91f2-005056825209/

Tzn. http://kramerius/*search*/zoomify/uuid:4cf1b670-048c-11e5-91f2-005056825209/uuid:4cf1b670-048c-11e5-91f2-005056825209/TileGroup0/2-0-0.jpg

a nikoliv
http://kramerius/*client*/zoomify*/uuid:4cf1b670-048c-11e5-91f2-005056825209/TileGroup0/2-0-0.jpg

Ale především je ten servlet http://kramerius/client/zoomify/ implementován špatně, protože nehlídá práva dlaždic a je přes něj možné získávat i neveřejné dokumenty. 

Kvůli této chybě je klient momentálně nepoužitelný. V MZK jsme ho do opravení této závažné bezpečnostní chyby odstavili.

**Comment by MartinRumanek** [comment]
Bylo to způsobené naší chybou, protože jsme měli v globálních právech (v IP filtrech) povoleno, že z "localhost" lze zobrazovat všechny dokumenty.

Každopádně ta implementace je stejně špatná, protože když se každý request interpretuje jako localhost, tak jsou IP filtry prostě nefunkční (a následkem toho klienta nebudeme moci prozovovat na zabezpečených terminálech ve studovně).

**Comment by pavel-stastny** [comment]
Klientska aplikace predava ip adresu v hlavicce dotazu, pokud bezi na stejnem stroji jako hlavni 'search' aplikace, mely by ip filtry fungovat. Pokud nebezi, je treba nastavit promennou 'x_ip_forwared_enabled_for' ktera povoluje adresy ze kterych je mozno hlavicku cist.

**Comment by MartinRumanek** [comment]
Klient nám běží na stejném stroji jako hlavní 'search' a IP filtry nefungují.

Náš konfigurační soubor client.properties vypadá takto:
```
## logo image
k5.logo=images/k5.png

## URL to your admin kramerius application
k4.host=http://localhost/search
## URL to your admin kramerius API
api.point=${k4.host}/api/v5.0

## username & pswd witch communicate kramerius app
k4.admin.user=krameriusAdmin
k4.admin.pswd=*

## display or hide collection
k5client.showbrowse=true
k5client.showtimeline=true
k5client.showcollections=true

## link to help 
k5client.help=help.vm
```

direktiva 'x_ip_forwared_enabled_for' se přidává do kterého konfiguračního souboru?

**Comment by pavel-stastny** [comment]
Muzete zkusit dat do konf. souboru pro logovani nasledujici radek? 
```cz.incad.kramerius.security.impl.criteria.AbstractIPAddressFilter.level=FINE```
IP filter bude logovat prichozi IP adresu a pattern se kterym se to snazi porovnavat. 

Jinak direktiva patri  do common.properties.
