### ISSUE TITLE
Indexace root_title ignoruje verzování ve Fedoře

### ISSUE THREAD

**Issue by leiblix** [ceskaexpedice/kramerius#312]
Momentálně indexer do `root_title` dává title z DublinCoru, ale ignoruje se verzování ve Fedoře (použije se vždy nejstarší title). Tato chyba tam byla zanesena při řešení https://github.com/ceskaexpedice/kramerius/issues/298

S tím souvisí také souvisí to, že bych rád znovu otevřel issue https://github.com/ceskaexpedice/kramerius/issues/242, protože nebylo vyřešeno celé. Chyba byla vyřešena pouze ve starším rozhraní Krameria tím, že se místo `root_title` používá `title`. Ale už to nebylo vyřešené v API (resp. v datech) a v novém klientovi.

Indexer by měl do `title` a `root_title` dávat  nespecifikované titleInfo z MODS (samozřejmě v poslední verzi) a nikoliv to brát z DC (ze kterého není jasně poznat co je alternativní název). Takto to bylo požadováno v NKP tiket 2238 (které se řešilo v rámci issue https://github.com/ceskaexpedice/kramerius/issues/122)

**Comment by MartinRumanek** [comment]
Bude toto v blízké době řešeno? V našem Krameriu budeme chtít provádět větší změny v titulkách periodik, ale tento bug nás brzdí.

**Comment by albertoh** [comment]
Kdyz pisete, ze ignoruje verzovani, mate na mysli ruzne verze datastreamu ve Fedore? Pokud je tomu tak, indexer vzdy bere aktualni verze, tj nejnovejsi. 
 To reseni opravilo xpath k dc:title, nemeni nic na tom, ze metoda vrati aktualni datastream.
 Jestli do title a root_title se musi davat titleInfo z MODS nejsem si jist. Ja predplokadam, ze bude spravne zkopirovano do dc:title v Dublin Core ten titulek, ktery se chce zobrazovat. Neni to vzdy jen nespecifikovane titleInfo, ale jeste tam se pridava subtitle.

**Comment by MartinRumanek** [comment]
Tento dokument 
http://kramerius.mzk.cz/search/handle/uuid:0e66f0f3-08c8-42e2-8d9a-b19e33ade62e
jsem právě zreindexoval a to co je v indexu aktuální není.

V indexu je `Acta Latomorum`, v posledním DC je (i když šílený) kompletní název `Acta Latomorum : Beiträge zur Geschichte der Freimaurerei. Anläßlich des 175jährigen Bestehens der Großloge "Zur Sonne" herausgegeben von dem Allgemeinen Freimaurer-Museum der Großloge "Zur Sonne"`

viz volání API:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:0e66f0f3-08c8-42e2-8d9a-b19e33ade62e/streams/DC

FOXML z Fedory: 
https://gist.github.com/MartinRumanek/409c47ea82ef0917d1e0

**Comment by albertoh** [comment]
Obavam se, ze problem je jinde.
Kdyz se podivame na monografie:

http://kramerius.mzk.cz/search/api/v5.0/item/uuid:0e66f0f3-08c8-42e2-8d9a-b19e33ade62e

vidime ze root_title je to dlouhe "Acta Latomorum : Beiträge zur Geschichte der Freimaurerei. Anläßlich des 175jährigen Bestehens der Großloge \"Zur Sonne\" herausgegeben von dem Allgemeinen Freimaurer-Museum der Großloge \"Zur Sonne\"". Ale title je jen "Acta Latomorum".

Stranka te monografie, (na priklad http://kramerius.mzk.cz/search/api/v5.0/item/uuid:ba716c45-33a1-4776-8ba2-b96f9734d47d ) ma take root_title dlouhe, a "title":["1a"]

Mate zmenou indexacni sablonu K4.xslt?
Jak vypada primy vystup ze SOLRu?

**Comment by slapakovai** [comment]
@MartinRumanek Je tento problém ještě stále aktuální nebo už byl vyřešen?

**Comment by pavel-stastny** [comment]
Nove uloziste akubra nepodporuje verzovani.  Issue neni aktualni
