### ISSUE TITLE
Indexer odmaže vazbu i u jiného dokumentu

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#313]
Občas může nastat situace, že je např. ročník připojen ke dvoum periodikům. 

V takovém případě z jednoho periodika ročník "odpojím" (resp. zruším vazbu ve Fedoře) a po spuštění reindexace úspěšně vazba zmizí, ale ročník se odpojí ze všech periodik (tedy i z toho, kde jsem ho chtěl mít).

Toto působí problémy i při přetahování ročníku z jednoho čísla do jiného - musí se vždy novu spustit reindexace nad periodikem, kde chci dokument mít (a reindexace velkého periodika zabírá netriviální čas).

**Comment by black23** [comment]
Povrzuji toto chování.

**Comment by albertoh** [comment]
Nemuzu reprodukovat problem. Muzete, prosim, popsat postup jak jste prisli k tomu vysledku?
Jak jste zrusili vazbu ve Fedore, a jak nasledne jste reindexovali rocnik?

**Comment by MartinRumanek** [comment]
Postup:

**1. uměle vytvořím stav, že jeden ročník je připojen ke dvěma periodikům**

Např. připojím tento ročník https://docker.mzk.cz/search/handle/uuid:49f1ad70-8ae7-11e2-8593-005056827e52 (dále budu nazývat ročník z Činu) do kořene tohoto periodika https://docker.mzk.cz/search/handle/uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650 (dále budu nazývat Agrární obzor).

`rels-ext` *Agrárního obzoru* vypadá takto:
```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650">
    <hasModel xmlns="info:fedora/fedora-system:def/model#" rdf:resource="info:fedora/model:periodical"></hasModel>
    <itemID xmlns="http://www.openarchives.org/OAI/2.0/">uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650</itemID>
    <policy xmlns="http://www.nsdl.org/ontologies/relationships#">policy:private</policy>
    
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:d35a5589-c573-4a40-91d3-28bab6ad558a"></hasVolume>
  <replicatedFrom xmlns="http://www.nsdl.org/ontologies/relationships#">http://kramerius.mzk.cz/search/handle/uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650</replicatedFrom></rdf:Description>
</rdf:RDF>
```

Nyní (např. přes administrační rozhraní Fedory na adrese http://$URL_FEDORY/fedora/admin) do tohoto rels-ext přidám vazbu na *ročník z Činu*:
```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650">
    <hasModel xmlns="info:fedora/fedora-system:def/model#" rdf:resource="info:fedora/model:periodical"></hasModel>
    <itemID xmlns="http://www.openarchives.org/OAI/2.0/">uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650</itemID>
    <policy xmlns="http://www.nsdl.org/ontologies/relationships#">policy:private</policy>
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:d35a5589-c573-4a40-91d3-28bab6ad558a"></hasVolume>
    <--! tento radek jsem pridal-><hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:49f1ad70-8ae7-11e2-8593-005056827e52"></hasVolume>
    <replicatedFrom xmlns="http://www.nsdl.org/ontologies/relationships#">http://kramerius.mzk.cz/search/handle/uuid:aa7d9927-0836-4972-a3b2-5c9a2c329650</replicatedFrom>
  </rdf:Description>
</rdf:RDF>
```

Nyní spustím reindexaci (klasicky z GUI, volby nechám defaultní) nad *Agrárním obzorem*, počkám až doběhne a nyní mám dvě periodika, které mají připojený ročník se stejným UUID (1945). 
*Agrární obzor*
![agrární obzor](http://i.imgur.com/zYU7MoA.png)

*Čin*
![čin](http://i.imgur.com/8wmJalM.png)

**2. nyní se rozhodnu, že ročník 1945 už nechci mít dále v periodiku Čin**

z `rels-ext` *Činu* (kořenové uuid:c3318d70-6f69-11e2-b9fa-005056827e52) odstraním vazbu na *ročník z činu* 1945

```

<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/uuid:c3318d70-6f69-11e2-b9fa-005056827e52">
    <hasModel xmlns="info:fedora/fedora-system:def/model#" rdf:resource="info:fedora/model:periodical"></hasModel>
    <itemID xmlns="http://www.openarchives.org/OAI/2.0/">uuid:c3318d70-6f69-11e2-b9fa-005056827e52</itemID>
    <!-- tento řádek smažu <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:49f1ad70-8ae7-11e2-8593-005056827e52"></hasVolume> -->
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:f555f250-b622-11e2-9592-5ef3fc9bb22f"></hasVolume>
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:0ade45c0-7f26-11e2-a455-005056827e52"></hasVolume>
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:59812ca0-8af3-11e2-bf69-001018b5eb5c"></hasVolume>
    <hasVolume xmlns="http://www.nsdl.org/ontologies/relationships#" rdf:resource="info:fedora/uuid:fda6d520-87d1-11e2-b6e7-001018b5eb5c"></hasVolume>
    <replicatedFrom xmlns="http://www.nsdl.org/ontologies/relationships#">http://krameriusndktest.mzk.cz/search/handle/uuid:c3318d70-6f69-11e2-b9fa-005056827e52</replicatedFrom>
    <policy xmlns="http://www.nsdl.org/ontologies/relationships#">policy:public</policy>
    <replicatedFrom xmlns="http://www.nsdl.org/ontologies/relationships#">http://kramerius.mzk.cz/search/handle/uuid:c3318d70-6f69-11e2-b9fa-005056827e52</replicatedFrom>
  </rdf:Description>
</rdf:RDF>
```

Pustím reindexaci *Činu* a očekávám, že z něho ročník 1945 zmizel. 

Tak se skutečně stalo
![čin, odstraněný 1945](http://i.imgur.com/RcD7sMM.png)

Ale ročník zmizel i z *Agrárního obzoru*
![agrár, zmizel 1945](http://i.imgur.com/x5xU4np.png)

**Comment by albertoh** [comment]
Pri reindexaci Činu, probiha "ocistka" periodika, tj, z indexu se odstrani vsechny potomky. Pak se reindexujou. Ale ten rocnik uz neni ve strukture Činu, tim padem zmizi z indexu.
Spravne je reindexovat ten rocnik.

**Comment by MartinRumanek** [comment]
A právě by neměl zmizet indexu globálně (má zmizet pouze z činu), dříve se to tak nedělo - nedá se to nějak rozumně vyřešit?

Kdybych v tomto případě reindexoval jen ten ročník, tak zmizí skutečně pouze z Činu? Co když potom pustím reindexaci nad celým Činem, nezmizí to potom zase globálně?

**Comment by albertoh** [comment]
Fedora drzi informaci o potomkach dokumentu.
Na rozdil od Fedory index drzi vazby "nahoru", o nadranenem dokumentu, a celou cestu. I kdyz jste zmenili periodikum (tj, nadrazene), to co se meni v indexu jsou dokumenty ktere maji v cestach nahoru tu vazbu. V nasem pripade se musi reindexovat ten rocnik a vsechny jeho potomky, proto ze ony maji info o cestach jak se k nim dostat.
 Kdyz potom pustite reindexaci nad celym Cinem, ten rocnik je uplne mimo toho procesu, proto ze v indexu uz ho nenajdete pres to periodikum.

 Doufam, ze jsem se vyjadril nejak zrozumitelne

**Comment by MartinRumanek** [comment]
Aha, rozumím. Ale stejně je možné, aby se při čistce periodika ověřilo, jestli ten ročník není připojený v jiném periodiku (a v tom případě by se nemazal z indexu, ale pouze "odpojil" a připojil ke správnému periodiku)?

Když chce uživatel v MEditoru přehodit ročník z jednoho periodika, tak má k dispozici takovéto GUI
![medit](http://i.imgur.com/uG60Iql.png)

Prostě se to jeví pro něj tak, že edituje celé periodikum a potom jako celek ho publikuje. Kromě přetahování objektů může provést i změny (např. v metadatech), které vyžadují reindexaci celého periodika. Bylo by velmi těžké rozlišovat která úroveň se má reindexovat (a případně ještě zajistit správné pořadí reindexací). 

Momentálně mi přijde jednodušší mírně upravit "očistku periodika" - bylo by to náročné?

**Comment by albertoh** [comment]
Bylo by to velmi narocne strojove. To by znamenalo:
  1.- ziskat vsechny dokumenty danneho periodika z indexu
  2.- pro kazdy dokument poslat dotaz Fedore o existence.

**Comment by MartinRumanek** [comment]
Nerozumím proč by se měli načítat všechny dokumenty z indexu, naopak to že se postupně načtou všechny dokumenty z Fedory jsem bral jako normální stav.

Myslel jsem si, že mizící uzel se akorát zeptá Fedory přes ritriples, jestli náhodou nepatří ještě někomu (a jestli ne, tak fakt zmizí z indexu i celý strom pod ním). V případě, že ještě někomu patří, tak proběhne klasická reindexace (tzn. že se přečtou postupně všechny dokumenty z Fedory, tak jak je běžné).

Zatím mi prosím toto issue neuzavírejte (klidně mě zadejte do Assignee, jestli to jde). Nastuduji si "očistku" ať lépe pochopím současný stav.

Ale pokud máte nějaký tip, jak by to šlo řešit, tak budu velmi rád :-)

**Comment by albertoh** [comment]
"Myslel jsem si, že mizící uzel se akorát zeptá Fedory přes ritriples, jestli náhodou nepatří ještě někomu"
Jak se dozvite, ze zmizel? Pri indexace se prochazeji postupne vsechny dokumenty od danneho uzlu dolu. Pokud ve Fedore ta vazba zmizela, k tomu dokumentu nedojdete.
 Ocistka znamena zmazat z indexu vsechny dokumenty, ktere maji spolecnou prvni cast cestu.
 Muzete reindexovat cele periodikum parametrem "fromKrameriusModelNoCheck" (vychozi hodnota je "fromKrameriusModel"). Pri tom index se nemaze predem. Ale pokud jste odstranili dokument, nebo vazbu, danni dokument nebude reindexovan, proto, ze k nemu nedojdeme prochazeni strukturou od Fedory.

**Comment by MartinRumanek** [comment]
> Ocistka znamena zmazat z indexu vsechny dokumenty, ktere maji spolecnou prvni cast cestu.
To všechno vysvětluje. Díky i za vysvětlení parametrů reindexace, hodí se mi to.

Budu s tímto chování indexeru v Meditoru počítat.
