### ISSUE TITLE
Nefunguje registrace uživatelů

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#317]
Při pokusu o registraci systém hlásí, že "Přihlašovací jméno již existuje" (verze 5.2.0). To ale zaručeně není pravda, loginy jsou nepoužité. Je možná rychlá oprava?

**Comment by black23** [comment]
Potvrzuji stejné chvání v K5 v  5.1.1
![kramerius_5_-_2015-10-05_14 58 35 png](https://cloud.githubusercontent.com/assets/5516936/10281002/c23f55e4-6b71-11e5-9d8b-d78c71b8dfe4.jpg)

**Comment by MartinRumanek** [comment]
Došlo pravděpodobně k zanešení chyby při řešení issue https://github.com/ceskaexpedice/kramerius/issues/255. V čisté 5.1.1 by se problém neměl vyskytovat, @black23 má build z nějakého novějšího snapshotu.

**Comment by MartinRumanek** [comment]
@pavel-stastny Zkoušel jsem to a funguje to. Tak pokud s tím nemáte žádné další plány, tak issue můžete zavřít :-)

**Comment by luckajirku** [comment]
Můžu se zeptat, jak se to vyřešilo? Nám to v 5.2.0 nefunguje pořád.
