### ISSUE TITLE
Nejžádanější jsou příliš pomalé

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#318]
API dotaz http://kramerius.mzk.cz/search/api/v5.0/feed/mostdesirable trvá moc dlouho, stejný problém se vyskytuje v GUI (proto máme tuto možnost úplně skrytou).

Tyto nejžádanější dokumnety se získavají poměrně složitým SQL dotazem, který v našem případě pracuje nad velkou množinou dat.

Vhodným řešením (kromě kešování) by mohlo být omezit dotaz tak, aby pracoval například pouze nad posledním měsícem (to by zaručilo, že se nejžádanější dokumenty aspoň občas změní)

**Comment by zabak** [comment]
Taky by se dal tento dotaz (odpověď na něj) tahat přes nějakou cache. Nebo to dělat přes cron - dotaz na nejžádanější udělat jednou za týden.

**Comment by pavel-stastny** [comment]
[#318](https://github.com/ceskaexpedice/kramerius/commit/cdc9dd0d86122b8dc2bffaa8131cd7159901b078)

**Comment by pavel-stastny** [comment]
Pridana promenna `"most.mostdesirable.numberofdays"`, ktera omezuje mnozinu dat.
