### ISSUE TITLE
Kompilace distribučního balíčku (distTar, distZip)

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#319]
Od června není funkční kompilování celé distribuce přes příkaz `gradle distTar`. 

Jistě kompilace je možná po jednotlivých komponentách, ale bylo by fajn, aby všechny způsoby popsané v https://github.com/ceskaexpedice/kramerius/blob/master/BUILD-README.txt fungovaly.

Řešili jsme to už komentářích ke commitu (v červnu) https://github.com/ceskaexpedice/kramerius/commit/045d8eb7c78b12c94055718f36a5d82417c7c16a. Issue píšu, aby se na to nezapomnělo.

Mimochodem, to že release Krameria 5.2.0 proběhl zjevně jiným způsobem, mělo za následek ten, že distribuční balíček má jinou strukturu než obvykle (myslím, že v něm chybí security-core.jar).

**Comment by pavel-stastny** [comment]
https://github.com/ceskaexpedice/editor/commit/950080eddbdc6ea24447dc72517e2b0281605803
https://github.com/ceskaexpedice/rightseditor/commit/87e11d31200fdfac66ebda8a2c67dfdd07f3f0b2
