### ISSUE TITLE
Issue 532:	Oblíbené

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#32]
Reported by Martin.Rehanek, Feb 14, 2013
K 4.6.2
Některé uživatelské účty se dostaly do stavu, kdy již není možné přidávat oblíbené (aktuálně 15 oblíbených). Operace přidání/odebrání se tváří, že prošla, v logu se nic neobjeví, ale seznam se nemění. 
Začal jsem zjišťovat, jak jsou tyhle věci v databázi uložené. Objevil jsem, že opravdu zajímavě. Tabulka profiles má dvá parametry - id uživatele (cizí klíč do tabulky user_entity) a atribute profile typu text. Tam je uložen profil uživatele v JSON. Dost podivné řešení. A vypadá to, že z něj plyne několik bugů. Všiml jsem si tohohle:
1. chybné znaky a jejich množení. Tento profil:
{
    "searchHistory":[{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?offset=0&forProfile=facet&fq=document_type:%22periodical%22",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?offset=0&forProfile=facet&fq=document_type:%22periodical%22",
        "fq":["document_type:\"periodical\""]
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=atlas&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=atlas&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"atlas",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?offset=0&forProfile=facet&fq=document_type:%22encyklopedie%20fd132201%20czenas%22",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?offset=0&forProfile=facet&fq=document_type:%22encyklopedie%20fd132201%20czenas%22",
        "fq":["document_type:\"encyklopedie fd132201 czenas\""]
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschachtliche&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschachtliche&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"Wissenschachtliche",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschaftliche&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschaftliche&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"Wissenschaftliche",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschaftliche+studien&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Wissenschaftliche+studien&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"Wissenschaftliche studien",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=merkur&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=merkur&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"merkur",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=merkur+revue&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=merkur+revue&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"merkur revue",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=%C4%8Dapek&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=%C4%8Dapek&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"������������������������������������������������������apek",
        "rok":""
    }],
    "favorites":["uuid:85f7c5d0-3226-11e2-824c-005056827e51","uuid:c057c4e0-5e23-11e2-a086-005056827e51","uuid:616a9600-4051-11e2-b246-005056827e52","uuid:4aff3290-5a23-11e2-bcaf-005056827e52"]
}

Jedna z položek histori obsahuje chybné znaky. Navíc při přidání jakéhokoliv oblíbeného pod tímto účtem se velikost oblasti s chybnými znaky zdvojnásobí. Takže mě napadlo, že to se stalo i uživateli, který si nemůže přidat 15. oblíbenou položku. Že asi někde něco přetéká kvůli nadměrné délce objektu "q" některé položky historie. 

Záznam tohoto uživatele mě ale překvapil. V jeho profilu totiž chybí objekt "favorites". Kde se tak jeho oblíbení berou?
{
    "searchHistory":[{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=zapomenuta+chut+cokolady&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=zapomenuta+chut+cokolady&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"zapomenuta chut cokolady",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=bl%C3%AD%C5%BEenci+z+ledov%C3%A9+pou%C5%A1t%C4%9B&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=bl%C3%AD%C5%BEenci+z+ledov%C3%A9+pou%C5%A1t%C4%9B&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"blíženci z ledové pouště",
        "rok":""
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?author=%22Romportlov%C3%A1,%20Ludmila%22&forProfile=search",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?author=%22Romportlov%C3%A1,%20Ludmila%22&forProfile=search",
        "author":"Romportlová, Ludmila"
    },{
        "url":"http://krameriusndktest.mzk.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Bl%C3%AD%C5%BEenci+z+ledov%C3%A9+pou%C5%A1t%C4%9B&issn=&title=&author=&rok=&udc=&ddc=",
        "rss":"http://krameriusndktest.mzk.cz/search/r-rss.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=Bl%C3%AD%C5%BEenci+z+ledov%C3%A9+pou%C5%A1t%C4%9B&issn=&title=&author=&rok=&udc=&ddc=",
        "author":"",
        "title":"",
        "ddc":"",
        "issn":"",
        "udc":"",
        "q":"Blíženci z ledové pouště",
        "rok":""
    }]
}

Feb 16, 2013 Delete comment Project Member #1 pavel.stastny

> Některé uživatelské účty se dostaly do stavu, kdy již není možné přidávat oblíbené
> (aktuálně 15 oblíbených). Operace přidání/odebrání se tváří, že prošla, v logu se
> nic neobjeví, ale seznam se nemění. 

Vzdy se jedna o 15 polozek ?  Muzete poslat profil uzivetele u ktereho se to deje ? (A pripadne i verzi browseru) 

> Začal jsem zjišťovat, jak jsou tyhle věci v databázi uložené. Objevil jsem, že
> opravdu zajímavě. Tabulka profiles má dvá parametry - id uživatele (cizí klíč do
> tabulky user_entity) a atribute profile typu text. Tam je uložen profil uživatele v
> JSON. Dost podivné řešení.

Proc proboha !?  Profil je zalezitost jednoho uzivatele, nikdy se nebude  skrz ruzne profily hledat ci vytvaret spojeni, navic to umoznuje profil libovolne rozsirovat a menit bez zmen v databazi. 

> 1. chybné znaky a jejich množení. Tento profil:

Na 99 % se jedna problem s kodovanim. Podle napsaneho nedokazu rict kde, ale vetsinou to byva tak, ze nedko (mozna klient) UTF-8 stream dekoduje do sveho nativnino kodovani (osmi bitoveho), timto zpusobem se stane z jednoho znaku dva no a pak se to na strane databaze ulozi. 

K urceni by bylo jeste potreba zjistit, kde se ten profil przni... Jestli to dela klient (browser) nebo to leti spatne uz se serveru. Ale nejspis to bude browser. U jakeho browseru se to deje ? 

> Že asi někde něco přetéká kvůli nadměrné délce objektu "q" některé položky
> historie. 

Tomu nerozumim. Cely profil je ukladan jako jeden atribut. Typ sloupce je TEXT coz je dle manualu postgresq (text - variable unlimited length). Kde by to melo pretekat? 

> Záznam tohoto uživatele mě ale překvapil. V jeho profilu totiž chybí objekt
> "favorites". Kde se tak jeho oblíbení berou?

Klic "favorites" se v profilu a objevi az v momente, kdy si uzivatel neco do oblibenych prida. Do te doby tam ten klic chybi. 

Feb 22, 2013 Delete comment Project Member #2 Martin.Rehanek

> > Některé uživatelské účty se dostaly do stavu, kdy již není možné přidávat oblíbené
> > (aktuálně 15 oblíbených). Operace přidání/odebrání se tváří, že prošla, v logu se
> > nic neobjeví, ale seznam se nemění. 
> 
> Vzdy se jedna o 15 polozek ?  Muzete poslat profil uzivetele u ktereho se to deje ? >(A pripadne i verzi browseru)
> 
> Ano, stalo se nám to dvakrát pro dva různé účty. Připojím rovnou (téměř) celé ty tabulky:
> users.sql (select user_id, loginname, deactivated from user_entity) a profiles.sql (select \* from profiles)

Jinak je zajímavé, že uživatelů v tabulce je 44, z toho aktivních 41 (resp. ne-deaktivovaných. Raději se ani nebudu zmiňovat o tom, že je lepší mít active=true než deactivated=false), no a záznamů v tabulce profiles je jen 20. Podivný je ten balast v tabulce profiles, např znaky '-', mezery apod.

> > Začal jsem zjišťovat, jak jsou tyhle věci v databázi uložené. Objevil jsem, že
> > opravdu zajímavě. Tabulka profiles má dvá parametry - id uživatele (cizí klíč do
> > tabulky user_entity) a atribute profile typu text. Tam je uložen profil uživatele >
> > JSON. Dost podivné řešení.
> 
> Proc proboha !?  Profil je zalezitost jednoho uzivatele, nikdy se nebude  skrz ruzne >profily hledat ci vytvaret spojeni, navic to umoznuje profil libovolne rozsirovat a >menit bez zmen v databazi. 

Nepříjde mi jako dobrý přístup mít v jednom atributu text o obecně neomezené délce. Nejen oblíbené, ale zejména historie hledání to bude dost nafukovat. Chápu, že to bylo asi rychlé řešení, ale mám tady fakt polemizovat o kvalitě takového návrhu? Návrh by měl být pořádný také kvůli možné pružnější reakci na změny, např. pokud by bylo potřeba agregovat globálně nejoblíbenější objekty, nemělo by to znamenat nutnost razantní změny databáze. No a zpracování takových dat pak je problematické i na aplikační úrovni, jak se právě přesvědčujemě řešením tohohle problému.

> > 1. chybné znaky a jejich množení. Tento profil:
> 
> Na 99 % se jedna problem s kodovanim. Podle napsaneho nedokazu rict kde, ale >vetsinou to byva tak, ze nedko (mozna klient) UTF-8 stream dekoduje do sveho >nativnino kodovani (osmi bitoveho), timto zpusobem se stane z jednoho znaku dva no a >pak se to na strane databaze ulozi. 
> Nevypadá to, že by to bylo na naší straně, tedy v konfiguraci aplikačního/webového serveru a databáze. V databázi jsou korektně zobrazeny znaky s diakritikou, ty se v pořádku propagují i do aplikace, a na úrovni aplikací (např. diakritika ve jménech ve správě uživatelů) se to opět zobrazuje dobře.
> 
> K urceni by bylo jeste potreba zjistit, kde se ten profil przni... Jestli to dela >klient (browser) nebo to leti spatne uz se serveru. Ale nejspis to bude browser. U >jakeho browseru se to deje ? 
> 
> > Že asi někde něco přetéká kvůli nadměrné délce objektu "q" některé položky
> > historie. 
> 
> Tomu nerozumim. Cely profil je ukladan jako jeden atribut. Typ sloupce je TEXT coz >je dle manualu postgresq (text - variable unlimited length). Kde by to melo >pretekat? 
> Detailněji jsem to nezkoumal. Pokud to exponenciálně roste (2^x) tak asi brzo někde něco přeteče nebo spíš profil nabobtná do nepoužitelné velikosti. 
> 
> > Záznam tohoto uživatele mě ale překvapil. V jeho profilu totiž chybí objekt
> > "favorites". Kde se tak jeho oblíbení berou?
> 
> Klic "favorites" se v profilu a objevi az v momente, kdy si uzivatel neco do >oblibenych prida. Do te doby tam ten klic chybi. 

Dobře, ale opravdu to vypadá, že ti dva uživatelé, u kterých se bug projevil (user_id 21 a 6), nemají v profilu objekt favorites. Jakoby se použilo špatné id uživatele pro dotazy na tabulku profiles.

http://iris.mzk.cz/cache/kramerius-bugy/profiles.sql
http://iris.mzk.cz/cache/kramerius-bugy/users.sql
Jul 4, 2013 Delete comment Project Member #3 vlahoda
(No comment was entered for this change.)
Owner: pavel.stastny 
Jul 4, 2013 Delete comment Project Member #4 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
uz neaktualni
