### ISSUE TITLE
Přihlašovací heslo do Krameria

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#321]
Dobry den,
chtel bych se zeptat, zda je mozne v Krameriovi vytvorit:
1) profil, u ktereho by nebyla povolena moznost Zmena hesla
nebo
2) nastavit Zmenu hesla tak, aby se pozadalo i zadani puvodniho hesla.

Dekuji

A. Drahotussky

**Comment by pavel-stastny** [comment]
Ne, toto chovani Kramerius neumoznuje.
