### ISSUE TITLE
Formát výsledku ze solr přes api

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#322]
Při dotazu do solr se ve třídě SearchResource podle použité http hlavičky vybere metoda na xml nebo json, ale vlastní dotaz může ještě obsahovat parametr wt=xml nebo wt=json.
V případě neshody (hlavička: xml + wt=json nebo naopak) je potom vrácena chyba parsování odpovědi ze solr.

Problém vzniká hlavně v případě, že k v dotazu hlavičky nejsou - server vybere jedno zobrazení a potom podle parametru wt buď vrací správnou odpověď, nebo chybu.
Další problém je při dotazu přes prohlížeč - v hlavičce je vždy xml a dotaz s wt=json vrací chybu.

Zobrazení výsledku RESTového dotazu by se mělo vybírat buď jedním, nebo druhým způsobem.

**Comment by MartinRumanek** [comment]
Řízení podle hlaviček by mělo být zachováno, řízení formátu dle URL je specifikum SOLRu. 

Ale měla by být tato situace ošetřena rozumnou chybovou hláškou (neshoduje se hlavička a formát v URL),  teď se vypíše stacktrace.

**Comment by honza-rychtar** [comment]
Lepsi by bylo pouzivat oba zpusoby tak, ze parametr v URL by mel vyssi prioritu.
Konkretne pri pouziti pres address bar v prihlizeci se pouzije xml (pres hlavicku), ale clovek by si rad ten format menil rucne pres parametr. A prave JSON response bych rad videl, coz mi v tuhle chvili ale hodi chybu a pokud by se kontrolovala shoda parametru a hlavicky, tak by to hazelo chybu dal, jen jinou.

Tohle je klasicke chovani u sluzeb, ze si muzu nastavovat format pres parametr, aniz bych jakkoli zasahoval do hlavicek.
