### ISSUE TITLE
Generování PDF - neveřejné dokumenty

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#323]
U neveřejných dokumentů je možnost Generování PDF, přičemž se vygeneruje PDF dokument s plným počtem stran a na každé stránce je text, že dokument je neveřejný a uživatel musí přijít do knihovny (!). Chtělo by to, aby se při pokusu o generování pdf objevila stejná hláška jako u tisku, že dokument není veřejně přístupný.

**Comment by slapakovai** [comment]
@LenkaDamborska Je tenhle problém ještě aktuální? Jedná se o search nebo o clienta?

**Comment by LenkaDamborska** [comment]
@slapakovai Jednalo se o search. Zdá se, že už je to vyřešeno. Při pokusu vygenerovat PDF neveřejného dokumentu, jsem dostala hlášku Operace není povolena. Tím pádem se to může uzavřít.
