### ISSUE TITLE
Aktualizace dat v ČDK

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#325]
Jak bude ČDK řešit aktualizaci dat? Změny OCR, opravy chyb atp. se zatím v ČDK neprojevují (MZK přidala OCR i ALTO k řadě dokumentů a stále přidává).

**Comment by pavel-stastny** [comment]
Dobry den, resi to prubeznym harvestovanim nove zaindexovanych dokumentu. V nedavne dobe dochazelo ke zmene adresy serveru a harvesty byly vypnuty. Nyni by ale meli bezet. Zkontrolujeme a dame vedet.

**Comment by pavel-stastny** [comment]
Presunuto na CDK, viz 399
