### ISSUE TITLE
(Ne)zobrazení typů stran

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#328]
U dokumentů, kde jsou typy stran v MODSu s počátečním velkým písmenem (TitlePage, Advertisement), se ve stromu vedle čísla strany i nahoře u pásu náhledů při najetí myší v pořádku zobrazují. 
Když mám ale typy stran s počátečním malým písmenem (titlePage, advertisement) - jak je to v NDK specifikaci a pravidlech, nezobrazují se.
Nemělo by to brát oboje?

**Comment by Drahotussky** [comment]
Ja myslim, ze ne. Podle mne prave vadi,kdyz je to velkym pismenem. Myslim,
ze jsme s tim meli problem v predchozim Krameriovi. Mozna by se to vyresilo
upravou sablony properties, kde by se primo napsal TitlePage a jeho cesky
ekvivalent.

Dne 8. prosince 2015 14:16 luckajirku <notifications@github.com> napsal(a):

**Comment by filak** [comment]
Pomůže úprava souborů:
...\Tomcat...\webapps\search\WEB-INF\classes\labels.properties  (anglicky)
...\Tomcat...\webapps\search\WEB-INF\classes\labels_cs.properties (česky)
- musí tam být obě varianty - s velkými i s malými písmeny

************************************************
mods.page.partType.NormalPage=
mods.page.partType.FrontCover=front cover
mods.page.partType.TableOfContents=table of contents
mods.page.partType.Advertisement=advertisement
mods.page.partType.Cover=cover
mods.page.partType.Spine=spine
mods.page.partType.Map=map
mods.page.partType.Jacket=jacket
mods.page.partType.Blank=blank
mods.page.partType.FrontEndSheet=front end sheet
mods.page.partType.Index=index
mods.page.partType.FrontJacket=front jacket
mods.page.partType.ListOfIllustrations=list of illustrations
mods.page.partType.ListOfMaps=list of maps
mods.page.partType.ListOfTables=list of tables
mods.page.partType.Table=table
mods.page.partType.TitlePage=title page
mods.page.partType.FlyLeaf=fly leaf
mods.page.partType.BackCover=back cover
mods.page.partType.BackEndSheet=back end sheet

mods.page.partType.normalPage=
mods.page.partType.frontCover=front cover
mods.page.partType.tableOfContents=table of contents
mods.page.partType.advertisement=advertisement
mods.page.partType.cover=cover
mods.page.partType.spine=spine
mods.page.partType.map=map
mods.page.partType.jacket=jacket
mods.page.partType.blank=blank
mods.page.partType.frontEndSheet=front end sheet
mods.page.partType.index=index
mods.page.partType.frontJacket=front jacket
mods.page.partType.listOfIllustrations=list of illustrations
mods.page.partType.listOfMaps=list of maps
mods.page.partType.listOfTables=list of tables
mods.page.partType.table=table
mods.page.partType.titlePage=title page
mods.page.partType.flyLeaf=fly leaf
mods.page.partType.backCover=back cover
mods.page.partType.backEndSheet=back end sheet

**********************************
mods.page.partType.NormalPage=
mods.page.partType.TitlePage=tituln\u00ed strana
mods.page.partType.FrontCover=p\u0159ední deska
mods.page.partType.TableOfContents=obsah
mods.page.partType.Advertisement=reklama
mods.page.partType.Cover=desky
mods.page.partType.Spine=hřbet
mods.page.partType.Map=mapa
mods.page.partType.Jacket=obálka
mods.page.partType.Blank=prázdná strana
mods.page.partType.FrontEndSheet=přední přídeští
mods.page.partType.Index=rejstřík
mods.page.partType.FrontJacket=reprezentace
mods.page.partType.ListOfIllustrations=seznam ilustrací
mods.page.partType.ListOfMaps=seznam map
mods.page.partType.ListOfTables=seznam tabulek
mods.page.partType.Table=tabulka
mods.page.partType.FlyLeaf=volný list
mods.page.partType.BackCover=zadní desky
mods.page.partType.BackEndSheet=zadní přídeští

mods.page.partType.normalPage=
mods.page.partType.titlePage=tituln\u00ed strana
mods.page.partType.frontCover=p\u0159ední deska
mods.page.partType.tableOfContents=obsah
mods.page.partType.advertisement=reklama
mods.page.partType.cover=desky
mods.page.partType.spine=hřbet
mods.page.partType.map=mapa
mods.page.partType.jacket=obálka
mods.page.partType.blank=prázdná strana
mods.page.partType.frontEndSheet=přední přídeští
mods.page.partType.index=rejstřík
mods.page.partType.frontJacket=reprezentace
mods.page.partType.listOfIllustrations=seznam ilustrací
mods.page.partType.listOfMaps=seznam map
mods.page.partType.listOfTables=seznam tabulek
mods.page.partType.table=tabulka
mods.page.partType.flyLeaf=volný list
mods.page.partType.backCover=zadní desky
mods.page.partType.backEndSheet=zadní přídeští

**Comment by pavel-stastny** [comment]
#374

**Comment by pavel-stastny** [comment]
Vyreseno komitem aea10feb64e6bd0d6ab2bd43d3ec29f977d94655
