### ISSUE TITLE
Zjednodušení úprav UI a přidání funkcionality (viz Issue 638)

### ISSUE THREAD

**Issue by jrihak** [ceskaexpedice/kramerius#329]
Dobrý den,

rád bych navrhl úpravu uživatelského rozhraní tak, aby umožňovalo větší customizaci hlavičky digitální knihovny, bez nutnosti upravovat kód, který danou část stránky generuje. Mám tím na mysli například možnost přidat další logo (tedy logo instituce, která daného Krameria provozuje) a nastavit URL adresu, na kterou z něj bude odkazováno (například pomocí nějaké property?)

V NTK se teď objevil požadavek na to, aby odkaz z loga v našem Krameriu vedl na web NTK. To mi přijde jako vysloveně špatné řešení, vzhledem k tomu, že logo by mělo (aspoň já mám ten dojem) sloužit jako "rychlá cesta" pro návrat na hlavní stránku daného webu nebo systému. 

Vedlo to nicméně k tomu, že jsem se snažil zjistit, jak by se do hlavičky dalo přidat další logo na jiný způsob, než je úprava šablony v některém z .jsp souborů. Je to tak?

Bylo by tedy možné například při vývoji nejnovějšího uživatelského rozhraní (teď myslím to rozhraní pro ČDK využívající Bootstrap, jestli se nepletu) tuto funkcionalitu zakomponovat?

Děkuji za vaše názory a připomínky,
Jakub Řihák
NTK

**Comment by pavel-stastny** [comment]
Tyka se starsiho klienta, jiz neaktualni
