### ISSUE TITLE
Issue 540:	Úprava nadpisu nad výstupy vyhledávání (x dokumentů sbaleno)

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#33]
Reported by leos.junek@nkp.cz, Mar 6, 2013
Návrh na vylepšení vzešlý od odboru služeb Národní knihovny ČR:

Pokud hledáme v plném textu, najdeme tituly, které odpovídají dotazu, tak u každého je uvedeno např. (3 dokumentů sbaleno). Toto se nám jeví jako poměrně matoucí a rádi bychom na tomto místě měli něco více přesného. Např.:
- počet výskytů hledaného pojmu v dokumentu: xx
- dokument obsahuje hledané slovo 8x (1x, 12x)
- nalezeno x výskytů hledaného slova (tam je jen problém, že by se to muselo skloňovat (výskyt/výskyty/výskytů))
- Zadaný výraz byl v dokumentu nalezen 8x
  Vše výše uvedené je lepší než „22 dokumentů sbaleno“.

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
uz neaktualni
