### ISSUE TITLE
Vyhledávání dle sigly

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#330]
Dobrý den,
bylo by možné přidat možnost vyhledávání dle místa uložení, tedy podle sigly knihovny? Digitalizujeme pro jiné knihovny a ty by uvítaly mít moznost vyfiltrovat si,co je z jejich knihovny.

Dekuji

S pozdravem

A. Drahotušský

**Comment by pavel-stastny** [comment]
Bylo reseno v ramci #452
