### ISSUE TITLE
Nově založená virtuální sbírka se neuloží

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#333]
Verze 5.3.1., Administrace virtuálních sbírek. Zadám názvy nové VS, pluskem potvrdím, v seznamu se mi ukáže. Dám zavřít, znovu otevřu administraci - a VS už v seznamu není (u jednotlivých dokumentů přes Zařadit nebo odebrat z VS také ne). Poměrně nedávno (v 5.2.0?) ještě tímhle způsobem VS založit šla.

**Comment by pavel-stastny** [comment]
Byla zanesena chyba pri uprave virtualnich sbirek. Bude opraveno a pripravime build.
