### ISSUE TITLE
Úprava šablony vedoucí k blokovani procesu v Krameriovi

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#334]
Dobry den,
pri uprave sablony mods.xsl a label.properties, kdy se do nich vkladala dalsi sigla instituce a jeji slovni vyjadření (jako vlastnik zaznamu knihy), doslo k tomu, ze po ulozeni zmen,se kramerius automaticky prepnul do anglicke verze, z ktere neslo prepnout na ceskou verzi, nesly spoustet procesy v Krameriovi. 
Tento typ upravy sablony jsme pritom delali drive casto a zadne problemy nebyly.
Nevite prosim,kde muze byt problem?
Dekuji
S pozdravem
Ales Drahotussky

**Comment by albertoh** [comment]
Muzete, prosim, poslat upravenou sablonu?

**Comment by Drahotussky** [comment]
[mods.xsl.SPATNY1.txt](https://github.com/ceskaexpedice/kramerius/files/100501/mods.xsl.SPATNY1.txt)
[labels_cs.properties.SPATNY1.txt](https://github.com/ceskaexpedice/kramerius/files/100502/labels_cs.properties.SPATNY1.txt)

Zmena,po ktere se zablokoval kramerius se tyka sigly KAG502.
Kdyz jsme odstranili tyto upravy,Kramerius se zase objevil v cveske verzi. Stale ale nejdou spustit procesy. Co s tim prosim?

**Comment by pavel-stastny** [comment]
Ohledne nespousteni procesu: Hlasi to nejakou chybovou hlasku ?  Pres API spoustet procesy jdou ?

**Comment by Drahotussky** [comment]
zadna chybova hlaska. proces je ve stavu Planned.
API je administratorske rozhrani? jestli ano,tak tam se normalne prihlasim, nastavim proces a spustim.

**Comment by pavel-stastny** [comment]
a v logu tomcatu ? Taky zadna chyb. hlaska ?

**Comment by albertoh** [comment]
V labels_cs.properties je chyba v radkach

KAG502.name=M\u011bstsk\u00e1 knihovna Orlov\u00e
KAG502 .name=M\u011bstsk\u00e1 knihovna Orlov\u00e

posledni pismo neni spravne enkodovane: á -> \u00e1

**Comment by Drahotussky** [comment]
Dobry den,
tady je log z Krameria.
Spustit zmenu verejnosti se tykal dokumentu uuid:4264e9d0-0646-11dd-a5fa-000d606f5dc6

[localhost_access_log.2016-01-22.txt](https://github.com/ceskaexpedice/kramerius/files/102982/localhost_access_log.2016-01-22.txt)

**Comment by Drahotussky** [comment]
Poslal jsem spatny soubor
[catalina.2016-01-22(1).txt](https://github.com/ceskaexpedice/kramerius/files/106199/catalina.2016-01-22.1.txt)

**Comment by Drahotussky** [comment]
Dobrý den,
povedlo se zjistit, v cem by mohl byt problem?
Dekuji
S pozdravem
A. Drahotussky

**Comment by pavel-stastny** [comment]
Bohuzel, v prilozenem logu nic zavazneho nevidim a bez moznosti videt danou instanci asi nebudu schopen ani nic kloudneho poradit.  

Mozna jenom tip: 
Zkuste nainstalovat novou instanci krameria a postupne tam prenaset Vase zmeny.

**Comment by albertoh** [comment]
Opravili jste labels_cs.properties? nepomohlo?

**Comment by Drahotussky** [comment]
Po oprave labels_cs.properties, resp. jsme vratili puvodni sablonu pred zmenou se znovu zpristupnil Kramerius v ceske verzi. Ale procesy stale nejdou spustit. Restartoval se Kramerius i server.
Ja sam nemam pristup do vnitrnosti Krameria, to ma na starost IT (zavilova@svkos.cz). Potrebovali by jste pristup do Krameria?
