### ISSUE TITLE
K5 klient - persistentni URL

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#336]
Zdravim,

bylo by dobre, aby K5 klient "podaval" persistentni URL jednak zpatky na sebe a dale i pres vnejsi rozhrani. Nyni je to zrejme tak, ze se link generuje na zaklade nastaveni property "k4.host". Pokud je property nastavena na adresu pres loopback, objevi se v linku loopback take, takze uzivateli je odkaz k nicemu. Pokud se v property uvede verejne/vnejsi rozhrani, napr. "k4.host=http://kramerius.lib.cas.cz/search", tak uz link sice funguje, ale ukazuje na "stare" rozhrani. Bylo by potreba, aby se link v klientovi generoval ve tvaru "http://kramerius.lib.cas.cz/client/handle/uuid:XXXX".

Prepis URL by sel pravdepodobne provest prostredky webserveru, nicmene cistsi by to dle naseho nazoru bylo primo v klientovi.

Duda

**Comment by pavel-stastny** [comment]
Opraveno v  4532b854485bea5a882f62d8a5f3db442398e54c
