### ISSUE TITLE
Zobrazování partname svazků vícedílné publikace ve stromu

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#337]
Když u vícedílné publikace není vyplněné ve svazcích partnumber, nezobrazí se ve stromu ani partname. Když je partnumber vyplněné, zobrazí se oboje. Přitom partnumber není M, jen MA.
Bylo by dobré, kdyby se partname zobrazovalo nezávisle na partnumber. Jinak to pak vypadá takhle: svazek: , svazek:  a uživatel nevidí, který svazek je který.

**Comment by zabak** [comment]
Prosím otestovat ve web klientovi - není tu uveden přiklad. V každém případě navrhuji zde zavřít a otevřít případně u web klienta.
