### ISSUE TITLE
K5 client - nezobrazují se PDF dokumenty

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#339]
Například:
http://kramerius.medvik.cz/client/index.vm?q=Acupunctura+Bohemo+Slovaca&page=search&start=&rows=

Ukáže se ročník i výtisk, ale po kliknutí na výtisk se v konzoli objevují chyby 500, např. pro
http://kramerius.medvik.cz/client/api/item/uuid:19124e3c-3f9b-4677-9465-57422e21abc7@1

Při použití bez **@1**
http://kramerius.medvik.cz/client/api/item/uuid:19124e3c-3f9b-4677-9465-57422e21abc7
se normálně stáhne JSON objektu s funkčním linkem na PDF:
http://kramerius.medvik.cz/search/img?pid=uuid:19124e3c-3f9b-4677-9465-57422e21abc7&stream=IMG_FULL&action=GETRAW

**Comment by honza-rychtar** [comment]
Vase PDF dokumenty jsem zkousel ve 3 klientech a zadny je neotevre.
Probem je v tom, ze na PDF dokumenty linkujete z urovne stranky a ne z urovne, ktera stranky obsahuje.
Napr. u monografii by mel byt model monograph, ktery obsahuje link na PDF, pod monograph by melo byt N modelu page, jeden pro kazdou stranku.
Vy mate model modograph, ten obsahuje jeden model page az page obsahuje link na N-strankove PDF.

Napr vytisk z uvadeneho prikladu pres API:
http://kramerius.medvik.cz/search/api/v5.0/item/uuid:bcd01df3-69cb-11e3-93fe-d485646517a0
tady chybi link na PDF.
Kdyz si vylistuju children od tohoto vytisku:
http://kramerius.medvik.cz/search/api/v5.0/item/uuid:bcd01df3-69cb-11e3-93fe-d485646517a0/children
Tak je tam jen jedna stranka s nazvem "1 - 32"
Kdyz si zobrazim detail stranky:
http://kramerius.medvik.cz/search/api/v5.0/item/uuid:bcd01df4-69cb-11e3-93fe-d485646517a0
Tak az tady je
"pdf": {
	"url": "http://kramerius.medvik.cz/search/img?pid=uuid:bcd01df4-69cb-11e3-93fe-d485646517a0&stream=IMG_FULL&action=GETRAW"
}

Spravne by mel byt link na urovni vytisku a pod nim by melo byt 32 stranek, ne jen jedna stranka odkazujici na PDF.

**Comment by filak** [comment]
Nevim, jak to myslite - co je jako ten "link na PDF"? Kazdopadne v K5-search to funguje (http://kramerius.medvik.cz/search/handle/uuid:bcd01df3-69cb-11e3-93fe-d485646517a0), a fungovalo i v K4.

PDF soubor je prece IMG_FULL stream a jako takovy patri do objektu page (nebo pripadne i dalsich), ale nevim o tom, ze by model monograph podle dokumentace obsahoval nejake streamy.

**Comment by MartinRumanek** [comment]
>> PDF soubor je prece IMG_FULL stream a jako takovy patri do objektu page (nebo pripadne i dalsich), ale nevim o tom, ze by model monograph podle dokumentace obsahoval nejake streamy.

Nesouhlasím, PDF obvykle obsahuje více stran, tzn. prezentuje spíše množinu stran a proto by mělo být navázané o úroveň výše než to máte. Je to tak plně korektní, dělá to tak [Meditor](https://github.com/moravianlibrary/MEditor) (na kterém se podílím na vývoji) a mám za to, že i [Proarc](https://github.com/proarc/proarc).

Takže možná to v žádné dokumentaci napsané není (nevím jakou dokumentaci máte na mysli), ale je to plně korektní a nedoporučuji to dělat jinak.


Periodika s PDF v Moravské Zemské nemáme, tak aspoň ukážu jak vypadá FOXML dokumentu s PDF (http://kramerius.mzk.cz/search/handle/uuid:1f315748-ab3c-4210-b060-9633cf025c45):
https://gist.github.com/MartinRumanek/c6a9652452b9158c059a

**Comment by filak** [comment]
"PDF obvykle obsahuje více stran" - souhlasim. 

Umisteni IMG streamu v top-level modelech mi ale vzhledem k oficialnim modelum moc korektni neprijde (https://github.com/ceskaexpedice/kramerius/wiki/Data)

Navic upozornuju na to, ze realita muze byt komplikovanejsi - viz napr. born-digital dokument (puvodem zrejme ze sborniku na CD):
http://kramerius.medvik.cz/search/handle/uuid:MED00173964
- ma navic metadata zpracovana analyticky vcetne clanku (vazby isOnPage)

V tomto pripade tezko muzete mit v jednom objektu vice IMG streamu se stejnym ID.

**Comment by filak** [comment]
Nejaky pokrok v teto issue se ve verzi 5.3.4 zrejme udal, ale ne vzdy se dokument pres novou PDF "prohlizecku" spolehlive zobrazi - viz issue #449

**Comment by filak** [comment]
Toto se týká starého klienta, v novém web-client se PDF zobrazují, takže zavírám.
