### ISSUE TITLE
Issue 541:	Skrytí neaktuálního tlačítka pro jazykovou mutaci

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#34]
Reported by leos.junek@nkp.cz, Mar 6, 2013
Návrh vzešlý z odboru služeb (čtenářům) Národní knihovny ČR.

Z pohledu uživatelů se jeví být nepříliš zdařilé nabízení  obou tlačítek pro přepínání jazykové mutace. Lidé jsou zvyklí, že z české vidí tlačítko „english“ a z anglické „česky“, nikoliv obě najednou.

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
klientske aplikace maji reseno jinak.
