### ISSUE TITLE
K5 filtr na Typ titulu (search) a Typ dokumentu (client) - addFilter nefunguje správně pro ročníky a články

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#340]
addTypeFilter('periodicalvolume') se projevuje jako:
http://kramerius.medvik.cz/search/r.jsp?offset=0&forProfile=facet&fq=model_path:periodicalvolume*

ale model_path je strukturovaná shora dolů - tedy by fq parametr měl být spíš:  http://kramerius.medvik.cz/search/r.jsp?offset=0&forProfile=facet&fq=model_path:*periodicalvolume

a stejně tak článek addTypeFilter('article') může být zanořený (ve výtisku atp.):
http://kramerius.medvik.cz/search/r.jsp?offset=0&forProfile=facet&fq=model_path:article*
http://kramerius.medvik.cz/search/r.jsp?offset=0&forProfile=facet&fq=model_path:*article

Filtr na Typ dokumentu K5 client se chová stejně - stejné počty výsledků.

**Comment by albertoh** [comment]
Chovani tohoto filtru, typ titulu, je spravne. V seznamu filtru jsou videt jen dokumenty, ktere maji pole model_path zacinajici dannou hodnotou, tj, dotaz je spravne hodnota*

Filter typ dokumentu (search) filtruje podle hodnoty v dc:type, bez *
