### ISSUE TITLE
client/api/search vrací 500 pro Solr dotaz

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#342]
Pokud se v client prochazi pres fasetu Typ dokumentu, tak po kliknuti na konkretni titul server vraci status 500. Napriklad:
http://kramerius.medvik.cz/client/index.vm?q=&page=search&start=0&rows=&typ_titulu=periodical
=> Casopis lekaru ceskych (http://kramerius.medvik.cz/client/index.vm?q=&page=doc&start=0&rows=&typ_titulu=periodical#pid=uuid:MED00010976-visk)
=> vrátí 500 pro: http://kramerius.medvik.cz/client/api/search?q=*:*&rows=5000&fq=pid_path:uuid\:med00010976-visk/*&hl=true&hl.fl=text_ocr&hl.mergeContiguous=true&hl.snippets=2&fq=typ_titulu:periodical

Pozorovano i v jinych instancich K5, napr. http://kramerius.mzk.cz/client/api/search?q=*:*&rows=5000&fq=pid_path:uuid\:87f6e957-90de-11e0-a36c-0050569d679d/*&hl=true&hl.fl=text_ocr&hl.mergeContiguous=true&hl.snippets=2&fq=typ_titulu:periodical

V Tomcat logu pak je:
16.2.2016 9:53:04 org.apache.solr.common.SolrException log
SEVERE: org.apache.solr.common.SolrException: undefined field typ_titulu
	at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1254)

Problem je tedy v parametru fq=typ_titulu, a zrejme i ve fq=pid_path - takhle se neco vrati:
http://kramerius.mzk.cz/client/api/search?q=*:*&rows=5000&fq=pid_path:uuid\:87f6e957-90de-11e0-a36c-0050569d679d*&hl=true&hl.fl=text_ocr&hl.mergeContiguous=true&hl.snippets=2&fq=document_type:periodical

**Comment by pavel-stastny** [comment]
Opraveno v  8a07dd402b6bcc125cb84654baee5e5f4014d1f4  a f89fd5ab637de4fd73eb413387d3c0db7a34025b
