### ISSUE TITLE
Export do PDF

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#343]
Dobrý den,
narazili jsme na jiny problem pri generovani PDF pres funkci Export do PDF.
Pokud zadame export celeho rocniku nebo titulu, tak dochazi k tomu, ze se titulni stranka rocniku stahne hned trikrat za sebou (jindy zase nektera stranka chybi-predevsim posledni stranky), a samotny rocnik se v PDF objevi 2x. Jednou kompletni po druhe tolik stran,aby byl naplnen limit 100 MB (ale nestahne se treba titulni stranka)

Lze to vyzkouset na:
http://camea2.svkos.cz/search/handle/uuid:c5d17571-7be7-4b24-bad9-8ae446e05b68

**Comment by pavel-stastny** [comment]
Vyzkousime u nas, pripadne zahrneme do nasledujiciho buildu.   Vsechny veci tykajici se exportu pdf budou reseny v ramci issue #61
