### ISSUE TITLE
Editor částí/pořadí - Cannot save 1 objects

### ISSUE THREAD

**Issue by jrihak** [ceskaexpedice/kramerius#345]
Dobrý den,

pokoušel jsem se pomocí Editoru částí v Krameriovi změnit pořadí čísel periodika (http://kramerius.techlib.cz/search/handle/uuid:ee9621d9-79cb-4b51-9a00-6014cd3d5dc3). Jednotlivé ročníky a jejich náhledy se otevřeli v rozhraní editoru částí, když jsem ale přetažením jednoho náhledu upravil jejich pořadí a klikl na "Uložit", objevila se následující chybová hláška:

Cannot save 1 objects:
Zákonník zemský království Českého =: Landes-Gesetz-Blatt für das Königreich Böhmen(uuid:ee9621d9-79cb-4b51-9a00-6014cd3d5dc3)

Bohužel jsem nenašel žádnou bližší informaci o této chybě ani v logu tomcatu (catalina.out), fedory (fedora.log) a ani v access logu Krameria.

Mohl bych poprosit o radu, jak by se tato chyba dala řešit nebo aspoň lépe zjistit její příčina?

Děkuji,
Jakub Řihák
NTK
Kramerius 5.2.0

**Comment by pavel-stastny** [comment]
Bohuzel nedokazeme nasimulovat.
