### ISSUE TITLE
V K5 se nenačítají všechny stránky monografie

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#346]
Máme v Krameriovi monografii Das jetzt lebende Europa. Ve starém rozhraní se zobrazí normálně všechny stránky: https://kramerius.lib.cas.cz/search/handle/uuid:ddef692d-f0fb-4cc7-af0f-0056bc417900
Když si ji ale otevřu v novém rozhraní, tak se načte pouze prvních 19 stránek: https://kramerius.lib.cas.cz/client/handle/uuid:65031370-4a67-40cb-9e65-e07a33844315
Můžete mi prosím poradit, čím to může být.

**Comment by albertoh** [comment]
bug v javascriptu (undefined)

**Comment by jandera** [comment]
Těch věcí, kde se nezobrazují náhledy stránek vůbec a nebo jen část, je tam mnohem víc. Např.:
https://kramerius.lib.cas.cz/client/handle/uuid:69433312-2701-4517-abe3-e0dd37ca2d71
https://kramerius.lib.cas.cz/client/handle/uuid:e71b4fc5-2e2c-420d-a691-ce0780a00fb7
https://kramerius.lib.cas.cz/client/handle/uuid:6565ed56-2bfe-489d-9f80-fa75c67205ff
https://kramerius.lib.cas.cz/client/handle/uuid:24a1f669-dbd8-4f6a-b71d-38e4a4ec5a7f
Více zde (popis v .xls + screenshoty):
https://drive.google.com/folderview?id=0Bzsa6hCP1dJVd3BUc3pnTXZMck0&usp=sharing

**Comment by filak** [comment]
V MODSu chybi u stranek mods:parttype - a leftthumbs.js s tim nepocita - a zrejme ani itemthumbs.js
Tady je to pekne videt:
https://kramerius.lib.cas.cz/client/handle/uuid:5f07da39-824e-4eb9-a0e9-d7fa1dae516a

Chtelo by to defaultni mods.page.partType

**Comment by slapakovai** [comment]
Zjistili jsme, že tato chyba v metadatech vzniká v ProArcu.
Problém není potřeba řešit v Krameriovi.
