### ISSUE TITLE
K5 - pristupnost 

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#347]
Resit pristupnost webu. 
(napr.: vyber jazyka  CS/EN)

**Comment by pavel-stastny** [comment]
Ikony maji byt viditelnejsi. (napr.: vyberove)

**Comment by slapakovai** [comment]
viditelnější tlačítka šipek pro posouvání na spodním pásu

**Comment by pavel-stastny** [comment]
Bude reseno s novym UI

**Comment by krizovj** [comment]
Zdá se mi to už asi nerelevantní, zavírám.
