### ISSUE TITLE
K5 - nevhodné hodnoty ve facetách

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#349]
Zvážit, jak odstranit nevhodné hodnoty ve facetách.
Stále tam zůstává faceta dostupnost: neuvedeno s hodnotou 0
https://drive.google.com/open?id=0B3h-WdvT09AdOVlxS0w2WXprOGs

**Comment by pavel-stastny** [comment]
Facety s hodnotou 0 budeme v aplikaci filtrovat.
