### ISSUE TITLE
Issue 543:	reprezentace strany k K4

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#35]
Reported by pavla.svastova, Mar 13, 2013
Narazila jsem zajimavy problem, ktery se tyka tematu, ktere jsme probirali na minule schuzce.
Pokusim se ho z laickeho hlediska popsat:
Loni jsme importovali veci z ANL plus a jako reprezentace strany v seznamu periodik byla stranka s clankem, coz bylo logicke, protoze byl ve foxml jako prvni. Zmenila jsem strukturu a preskladala cisla a rocniky tak, ze reprezentativni stranka nyni je prvni strana prvniho cisla. Ale v seznamu periodik je stale ta puvodni prvni strana z nejakeho clanku uprostred cisla... Proc se mi to v seznamu nezmenilo?

Napr.
http://kramerius.mzk.cz/search/r.jsp?offset=0&forProfile=facet&fq=document_type:%22periodical%22
(druhé periodikum Acta entomologica...)
po rozkliknuti: http://kramerius.mzk.cz/search/handle/uuid:1f910b93-0d55-4a66-bebc-fb03845b35d2

To stejne mi dela napr. Agrarni obzor, ktery je v seznamu desaty.

Dekuji.
Pavla

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Owner: alberto.en.vlasim 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by zabak** [comment]
Prosím zavřít, týká se starého klienta
