### ISSUE TITLE
K5 - řazení výsledků vyhledávání

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#353]
Když vyhledávám frázi “Das jetzt lebende Europa”, tak se najdou i dokumenty, které obsahují třeba jenom “das” a řadí se na začátek výsledků. Podle čeho se řadí výsledky? Je to podle toho návrhu paní Dvořákové? Existuje nějaký seznam stop slov?
Prosím o odkaz na dokument, který specifikuje řazení výsledků podle relevance.

**Comment by pavel-stastny** [comment]
Obecne zalezi na klientovi,  jak a ktera pole vyuziva. Standardne se vyuziva pole text, ktere obsahuje nasledujici hodnoty: 

https://github.com/ceskaexpedice/kramerius/blob/master/installation/solr-6.x/kramerius/conf/managed-schema#L505-L511

V ramci prechodu na solr 6 (#458)  se resila podpora cestiny, lematizace a vyhledavani ceskych slov (s tim suvisi i seznam stop slov).  Podpora nemciny zatim nebyla implemetovana. 

Vyzivany model relavance: TF–IDF

**Comment by slapakovai** [comment]
Díky za odpověď.

Když nám použitý model relevance nevyhovuje, bylo by možné ho upravit?

Řešíme problém, že když uživatel v našem Krameriovi vyhledává časopis s nějakým obecným názvem (např. Česká literatura), tak se podle tohoto modelu časopis zařadí až jako x-tý v pořadí výsledků, protože tato slova se vyskytují příliš často v jiných dokumentech. Přitom by uživatel očekával, že se časopis Česká literatura objeví na 1. místě.

Je tedy nějak možné zvýšit váhu slov, pokud se vyskytují např. v názvu dokumentu?

**Comment by pavel-stastny** [comment]
K tomu se vyuziva parametr boost, ktery  pridava vahu na uricte pole.  Muzu poprosit o vyzkouseni v novejsi verzi administracniho  prostredi  (5.3.5 nebo 5.3.6 ) ?   Tam by melo byt vyhledavano podle dvou poli, prvni je obecne pole text, ktere obsahuje  vyse zminene plus jeste root_title, ktery je prave "oboostovan".

**Comment by slapakovai** [comment]
Zkoušela jsem vyhledat dotaz "Česká literatura" v našem Krameriovi, verze 5.3.6:
https://kramerius.lib.cas.cz/search - časopis s tímto názvem je až 24. ve výsledcích
https://kramerius.lib.cas.cz/client - časopis s tímto názvem je 11. ve výsledcích

**Comment by pavel-stastny** [comment]
To souvisi s rozdilnym zachazenim vyhledavani v ruznych aplikacich. (Stejne tak se muze lisit poradi i pocet vysledku v mobilni aplikaci vuci webove apod.)  

V pristim roce se planuje sjednoceni vyhledavani napric vsemi klienty. 

A jeste k relevanci a razeni vysledku. Byla provedena uprava schematu. Viz commit e9a5bacddc20aebd97f3a2886b7ee771f49feeaf, prosim nasadte a preindexujte data.  - Vyzadovana verze SOLRu je 6.X

**Comment by honza-rychtar** [comment]
Novy klient pouziva stejny zpusob razeni podle relevance jako Digitalni knihovna - http://www.digitalniknihovna.cz/knav/search/?q=%C4%8Cesk%C3%A1%20literatura - casopis Česká literatura je na prvnim miste.
Android i iOS klient taky prebiraji toto chovani.
