### ISSUE TITLE
ČDK - změna policy ve zdrojové knihovně

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#354]
U periodik nějak špatně funguje ten zelený roh. Na úrovni čísla je zelený roh, když si ho pak otevřu, tak se mi objeví hláška tento dokument není veřejně přístupný. Např. Časopis pro moderní filologii.

U tohoto dokumentu se pravděpodobně ve zdrojové knihovně změnila policy a změna se pak nepromítla do ČDK

**Comment by pavel-stastny** [comment]
Toto issue trochu posunu. To co jsme videli na schuzce bylo, ze pres CDK dokument nesel videt, na zdrojovem pak ano. Mate odkaz na nejaky dokument ?

**Comment by pavel-stastny** [comment]
Presunuto:  https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/7

**Comment by slapakovai** [comment]
konkrétní příklad: http://cdk.lib.cas.cz/client/handle/uuid:1e4b4d64-4048-11e1-1729-001143e3f55c
