### ISSUE TITLE
K5 - název filtru virtuální sbírky

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#357]
Virtuální sbírky ve fitrech přejmenovat jenom na "Sbírky".

Po výběru filtru virtuální sbírka se zobrazí např. “Virtuální sbírky: Muzeum Brněnska” Mělo by tam být jednotné číslo “Sbírka: Muzeum Brněnska”. Prosím opravit

**Comment by pavel-stastny** [comment]
Reseno komitem  8b49994f9bf20f36b793d686b29120f2445a2fd8
