### ISSUE TITLE
Issue 545:	Virtuální sbírky - hezká URL

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#36]
Reported by zabicka, Mar 15, 2013
Zavést podporu pro hezká URL pro linkování na virtuální sbírky - tj. kramerius.domena.cz/jmeno-sbirky. Virtuální sbírka by měla být vždy identifikována v URL, tj. při jejím prohlížení by místo "search" bylo v URL "jmeno-sbirky". Odpadnou tak i komplikace s tím, jak se dostat zpět do celého Krameria.
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
zalezitost jednotlivych klientu
