### ISSUE TITLE
ČDK - nastavení přístupnosti dokumentů

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#361]
Při listování po stránkách se mi stalo, že některé stránky se zpřístupní a některé mají hlášku “Tento dokument není veřejně přístupný”. Viz tady: http://cdk.lib.cas.cz/client/handle/uuid:a6ce9055-632d-11e3-9840-001b63bd97ba je to u každé stránky jinak.

NTK si nejprve zkontroluje data, než budeme řešit dál.

**Comment by pavel-stastny** [comment]
https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/9
