### ISSUE TITLE
K5 - metadata v pravém sloupci

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#364]
Navrhout jiná zobrazovaná metadata v pravém sloupci při zobrazování dokumentu.
KNAV dodá seznam zobrazených k diskuzi pro ostatní knihovny.

**Comment by krizovj** [comment]
Může se zavřít, bylo to myšleno pro klienta K5, metadata jsem poslali (2016) a stejně se nic nestalo. V klientovi K6 je to v pohodě.
