### ISSUE TITLE
K5 - zobrazení článků

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#365]
Nelze zobrazit články. Buď se nenačte ani jejich náhled v čísle nebo se načte, ale když na něj kliknu, tak se neotevře žádný text. Lze vyzkoušet na Lidových novinách.
náhled: https://drive.google.com/open?id=0B3h-WdvT09AdRVdTcHZ4WDRBc3M 
článek - obraz: http://cdk.lib.cas.cz/client/handle/uuid:2520ce9e-3b51-48d7-a642-30c13eb8571b
článek - pdf: http://cdk.lib.cas.cz/client/handle/uuid:580a0d3c-be79-11e2-9ddd-001e65b2b442

**Comment by pavel-stastny** [comment]
Tyka se starsiho klienta, jiz neaktualni
