### ISSUE TITLE
K5 - název článku v metadatech

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#366]
Místo názvu článku je v metadatech v pravém sloupci napsáno “null” nebo název celého časopisu. Jedná se úplně první řádek v metadatech.

**Comment by pavel-stastny** [comment]
Muzeme pozadat o priklad ?

**Comment by slapakovai** [comment]
Příklad:
http://cdk.lib.cas.cz/client/handle/uuid:53fbadfc-435f-11dd-b505-00145e5790ea
http://cdk.lib.cas.cz/client/handle/uuid:ce997b1c-d3bd-11e1-bac1-0050569d679d

Když se proklikáte na úroveň zobrazení jednotlivých článků a stran v čísle, tak tam ten název článku je, takže v metadatech určitě nechybí.

**Comment by pavel-stastny** [comment]
Tyka se starsiho klienta, jiz neaktualni
