### ISSUE TITLE
K5 - vyhledávání v dokumentu bez OCR

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#367]
Když vyhledávám v monografii bez alta, tak se buď nic nestane nebo vyskočí hláška: https://drive.google.com/open?id=0B3h-WdvT09AdS0RUcl9ZbGNmVXc

Pokud je dokument bez OCR a bez alta, tak by ve vyhledávacím okénku mělo být napsáno: “Nelze vyhledávat v plném textu. Dokument obsahuje pouze obrázky.”

Jestli bude někde použita ta chybová hláška, tak je potřeba skloňovat slovo stránka a udělat ji v designu K5 místo K4. Hláška by měla po chvíli zmizet, takhle znemožňuje pokračování v práci - musí se nejdřív kliknout.

Asi by bylo lepší zobrazovat počet výsledků než stránek

**Comment by pavel-stastny** [comment]
Dokument (byt nema plny text) obsahuje i metadata a proto byla hlaska upravena nasledovne:

> Nenalzen žádný výsledek. Může být z důvodu absence plného textu -  dokument obsahuje pouze metadata a obrázky.

Ohledne designu: Ma smysl resit az v ramci noveho klienta. Nyni je k dispozici v beta verzi.
