### ISSUE TITLE
K5 - hledání v rámci stránky

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#368]
Zvýrazní se pouze první hledané slovo, další hledané slovo už ne a zůstane to první.

**Comment by slapakovai** [comment]
Ve verzi 5.3.6 funguje zvýraznění u vyhledávání tak, že v pdf se výsledky zvýrazní, ale dost malým zeleným puntíkem, který není při implicitním přiblížení vidět. Začne být vidět teprve, když si pdf přiblížím.
Pokud probíhá vyhledávání ve skenech s ocr, tak se zvýrazní jenom stránky, na kterých byl text nalezen, ale v rámci stránky se to slovo už nezvýrazní.
Bylo by dobré, kdyby se výsledky vyhledávání zvýraznily pokaždé.

**Comment by pavel-stastny** [comment]
Tyka se starsiho klienta, jiz neaktualni
