### ISSUE TITLE
Issue 560:	Virtuální sbírky vs. externí odkazy do K4

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#37]
Reported by zabicka, May 3, 2013
Ve wikipedii ale i jinde se začínají ve větším rozsahu objevovat linky do Krameria. Pokud si ale v Krameriu zvolím nějakou virtuální sbírku, poté v jiném okně kliknu na link do Krameria, tak se mi místo knihy zobrazí jen první obrázek (obálka) a hláška "Data není možné zobrazit, můžete si stáhnout originální data." a pod tím link
"Originál" což je link na ten obrázek.

Postup vyvolání chyby: Jít na kramerius.mzk.cz/eod
v jiném okně jít třeba na http://cs.wikipedia.org/wiki/August_Sedl%C3%A1%C4%8Dek a kliknout na poslední odkaz v sekci Externí odkazy (Českomoravská heraldika) nebo přímo jít na http://kramerius.mzk.cz/search/handle/uuid:14226351-986d-11e0-bd44-0050569d679d

Návrh řešení: zabudovat název kolekce do URL. Tj. pokud pracuji s kolekcí eod, tak v URL bude místo /search/ uvedeno /eod/
Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Owner: alberto.en.vlasim 
Jul 4, 2013 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Cc: pavel.stastny 
Jul 4, 2013 Delete comment Project Member #3 alberto.en.vlasim
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Musi se resit individalne na strane klientu. Nelze vyresit obecne.
