### ISSUE TITLE
K5 - nápověda u tlačítka návrat zpět na výsledky vyhledávání

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#373]
Návrat zpět na výsledky vyhledávání ze zobrazení dokumentu.
Změnit nápovědu na: “Zpět na výsledky vyhledávání”.

**Comment by pavelkocourek** [comment]
Text je správně - na zobrazení dokumentu se lze také dostat například přes Procházení  nebo Časovou osu. "Zpět na výsledky vyhledávání” by v takovém případě neodpovídalo.
