### ISSUE TITLE
K5 - popisy v drobečkové navigaci

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#374]
Drobečková navigace - u některých typů stran se v popisu strany zobrazuje MODS popis (např. Dvanáct pohádek -> Strana [e] mods.page.partType.flyLeaf)
http://cdk.lib.cas.cz/client/handle/uuid:f58b21ab-5746-11e3-8d00-0050569d679d

**Comment by pavel-stastny** [comment]
Mate k dispozici seznam moznych variant a jejich prekladu ? 

mods.page.partType.flyLeaf, mods.page.partType.jacket, atd ?

**Comment by pavel-stastny** [comment]
Upravime dle specifikace NDK: 

https://docs.google.com/document/d/1zSriHPdnUY5d_tKv0M8a6nEym560DKh2H6XZ24tGAEw/edit?pli=1#heading=h.uxepiwxe2w5c
