### ISSUE TITLE
K5 - procházení podle abecedy

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#375]
Pokud se při procházení podle abecedy zadá do vyhledávání například slovo Živa, tak se jako první zobrazí Živá abeceda, Živá drenáž,…  a až jako poslední Živa. Správně by to mělo být opačně. Tedy že nejdřív zařadí to konkrétní slovo a až potom slovo, za kterým ještě něco následuje.

Problém spočívá v indexu - mezera je vyšší než ukončovací znak. Nelze jednoduše opravit - musí proběhnout reindexace - naplánovat při další případné reindexaci.

**Comment by krizovj** [comment]
platilo pro klienta K5, může se zavřít
