### ISSUE TITLE
K5 - registrace nového uživatele

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#380]
Po pokusu o registraci nového uživatele přestane fungovat Kramerius. Objeví se jenom bílá obrazovka. Musí se zavřít a znovu otevřít prohlížeč.

**Comment by pavel-stastny** [comment]
Jednalo se o CDK, reseno v  https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/1.
