### ISSUE TITLE
Issue 581:	Informace o importu titulu

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#39]
Reported by karel.kriz@nkp.cz, Jul 1, 2013
Pro lepší přehled o titulech by bylo dobré přidat do administrátorského menu titulu informace o importu titulu. Položka by mohla být pojmenována např. vlastnosti importu a zobrazovalo by se zde:
- účet přes který byl import proveden (u vícesvazků pouze první import, založení titulu)
- datum a čas importu titulu (u vícesvazků pouze první import, založení titulu)
- datum a čas poslední indexace titulu
- zdroj importu (replikace, import K3, import FOXML)

Jul 4, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
implementovano
