### ISSUE TITLE
K5 - zešednutí obrazovky s výsledky při scrollování

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#392]
Při načítání dalších výsledků vyhledávání vždy zešedne obrazovka (když se scrolluje dolů). Vypadá to, jako by nastala nějaká porucha nebo se Kramerius zasekl.  To dělají prohlížeče, když zamrznou. Stačil by pouze ten interaktivní náznak, že se něco děje, a barva obrazovky se nemusí nijak měnit.
Zešednutí jenom oblasti s výsledky (ne filtry a horní lišta).

Bude řešeno v novém rozhraní

**Comment by pavel-stastny** [comment]
implementovano
