### ISSUE TITLE
K5 - statistiky

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#394]
Návrh na vývoj:
rozšíření statistik - je potřeba je počítat na úrovni dokumentu, ne strany.
rozdělení podle typu dokumentu
rozdělení podle přístupnosti

MZK dodá podrobnější popis.

**Comment by zabak** [comment]
Specifikace toho, co se od knihoven požaduje vykazovat je na http://ipk.nkp.cz/docs/stat/DVK2015_2016_Silny.pdf strany 1-20
bude ale potřeba se dohodnout, jaké údaje jsou z krameria potřeba pro které položky výkazu a jak se budou daná čísla v Krameriu počítat.

**Comment by zabak** [comment]
Co je ve výkazu:
52.    Zobrazení (stažení) digitálního dokumentu
Zpřístupnění dokumentu nebo jeho části (např. časopiseckého článku, celého digitálního dokumentu, nebo jeho části typu kapitoly či vloženého vyobrazení nebo odkazu) bez ohledu na zobrazovací for­mát (např. pdf, html, ps) na neomezenou dobu.  Nezapočítává se pouhé stažení obálky, ob­sahu či jiné dopro­vodné součásti dokumentu.
53.    Počet zobrazených (stažených) digitálních dokumentů
Počet zobrazených (stažených – „download“) dokumentů z vlastních specializovaných databází a licenco­vaných elektronic­kých informačních zdrojů případně z OPAC, které jsou uživatelům k dispozici prostřednictvím lokální sítě nebo internetu

→ toto se týká Krameria, jde o jedinou kolonku ve výkazu, ale zároveň o zobrazené i stažené dokumenty, klidně můžou být oba údaje, když to změříme - ale možná stačí jen ty zobrazené (otázka, co znamená “stažené”, uživatel stahuje, i když jen prohlíží)
→ sloupec 34 ve výkazu
→ jde o celý dokument nebo jeho část - tzn. číslo, příloha i ročník periodika a periodikum samotné... 

53. a. E-výpůjčka e-dokumentu, počet e-výpůjček e-dokumentů
Přenos elektronického dokumentu (zpravidla e-knihy) jednomu uživateli na časově omezenou dobu na vlastní zařízení uživatele.
Pozn. Zahrnuje e-výpůjčky ze systémů typu eReading EBSCO, Ebrary, Nepatří sem výpůjčka čtečky (ta se započítává do řádku 0314 jako výpůjčka elektronického dokumentu).
→ toto se podle mě netýká Krameria, jde o klasické e-knihy pro čtečky
→ sloupec 34 a
→ relevantní by ale mohlo být stažení původních PDF dokumentů z Krameria, ale těžko říct..


Stačí ale to, co psala I. Šlapáková

→ to pro výkaz bude stačit; pokud budeme mít počty dokumentů podle modelů a jednotně si to knihovny posčítají, pak budou mít knihovny stejně vykonstruovaná čísla (někdo musí ale říct, jak se to bude dělat a sčítat); např. sečteme všechna periodika a články - nejen periodika, i když do nich články patří
→ ve Statistikách se použije akce prohlížení (když si to chce člověk vytisknout nebo stáhnout, musí před tím prohlížet aspoň jednu stranu)

Prosím začněte to už dělat

**Comment by pavel-stastny** [comment]
>  to pro výkaz bude stačit; pokud budeme mít počty dokumentů podle modelů a jednotně si to knihovny posčítají, pak budou mít knihovny stejně vykonstruovaná čísla (někdo musí ale říct, jak se to bude dělat a sčítat); např. sečteme všechna periodika a články - nejen periodika, i když do nich články patří
>→ ve Statistikách se použije akce prohlížení (když si to chce člověk vytisknout nebo stáhnout, musí před tím prohlížet aspoň jednu stranu)

A stavajici podoba statistik k vyse napsanemu nevyhovuje?

**Comment by LenkaDamborska** [comment]
Teď se počítají jen stránky. Knihovnám jde o celé dokumenty.. Takže je potřeba počítání i na úrovni dokumentu, jak píše @slapakovai

**Comment by pavel-stastny** [comment]
Dobry den, 

kdyz otevrete statistiky a vyberete jiny model nez page (treba monograph) a nechate si vyjet csv file, tak vyledkem prazdny csv soubor ?

**Comment by LenkaDamborska** [comment]
Aha, už možná tuším, v čem si nerozumíme. Vygenerovat csv file pro jiný model než page jde, ale potřebujeme počet dokumentů za vybrané časové období. Ideální, kdybychom si mohli sami navolit, jakého čas. období, jakých dokumentů a jakých akcí se to má týkat. Tohoto se mi nepodařilo ve Statistikách docílit.

**Comment by pavel-stastny** [comment]
Filtrovani dle data je dodano pro vsechny typy statistik.  Nyni muzete navolit cas. obdobi, akci i model, pro ktery chcete report vytvorit.

**Comment by slapakovai** [comment]
Platí ještě pořád požadavek z tohoto issue: https://github.com/ceskaexpedice/kramerius/issues/28 nebo ho můžu uzavřít?
@zabak  @LenkaDamborska

**Comment by pavel-stastny** [comment]
Podporovane typy reportu: 

- Dle modelu
- Dle autora
- Dle jazyka (definovaneho v metadatech)

Pro vsechny typy statistik lze pouzit filtry: 
- Datum (od -do)
- Akce, ktere se to tyka (READ, PDF, PRINT)
-  Dostupnost (ALL, PUBLIC, PRIVATE)
