### ISSUE TITLE
ČDK - indexování nových dokumentů z již existujících knihoven

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#399]
Jak teď probíhá doplnění nových dokumentů do čdk z knihoven, které již byly sklizené? KNAV i MZK mají nové dokumenty, které nebyly do ČDK přidány.

**Comment by LenkaDamborska** [comment]
Zadávala jsem podobný dotaz v #325

**Comment by pavelkocourek** [comment]
https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/13
