### ISSUE TITLE
Issue 159:	sjednocní textů v ./kramerius/texts

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#4]
Reported by Martin.Rehanek, Aug 15, 2011
Který text se použije na co není úplně jasné, asi by to bylo vhodné nějak konsolidovat (a asi i zadokumentovat na wiki). Obsah adresáře ~/.kramerius/text po čisté instalaci:
first_page
first_page_CZ_cs
first_page_html_CZ_cs
first_page_html
logininfo
logininfo_CZ_cs
default_intro
default_intro_EN_en
security_fail
security_fail_CZ_cs
Na krameriusdemo to vypadá trochu jinak - jsou tam navíc soubory first_page_CZ_cs a intro_CZ_cs.

Proč jsou defaultně vygenerované pro některé texty verze "default" + CZ_cs, jinde "default" + EN_en? Taky mi příjdou trochu zbytečné soubory default_intro, když se (při jejich existenci) použijí soubory intro. Ty by také mohly být generovány automaticky, podobně jako ostatní. Také moc nechápu vztah mezi first_page a first_page_html - a kde tyhle texty vůbec zobrazují?
Aug 15, 2011 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: Accepted 
Owner: pavel.stastny 
Cc: alberto.en.vlasim 
Aug 16, 2011 Delete comment Project Member #2 pavel.stastny
Pokusim se odpovedet.  First_page je hlaska, ktera se zobrazuje pri statickem exportu. First_page_html je historicka zalezitost, v nove verzi uz nebude.   Rozdil mezi default_intro a intro byl pouze v tom, ze intro(_cs nebo _en) je uz uzivatelem editovany text (tim myslim uzivatele webove aplikace), ktery se bere prednostne.  Nicmene to taky prijde pryc v nove verzi. 

Premyslim, ze by mozna stalo za to nazvy textu prefixovat dle pouziti?  

staticexport.firstpage_cs_CZ
webapp.logininfo_cs_CZ
webapp.securityfail_cs_CZ

Feb 2, 2012 Delete comment Project Member #3 Martin.Barton@nkp.cz
Chtěl jsem se přeptat, zda je toto už opravdu v nové verzi vyčištěno. Nevím, zda je to upgrady (už nevím, ze které verze jsme začínali), ale já v naší testovací verzi 4.5.0 beta 1 stále vidím First_page_html i ty další.
Jinak ano, ty prefixy jistě hodně pomohou, ještě více pak ale zmínka na wiki.
Apr 24, 2012 Delete comment Project Member #4 vlahoda
 Issue 320  has been merged into this issue.
Apr 24, 2012 Delete comment Project Member #5 vlahoda
 Issue 321  has been merged into this issue.
Apr 24, 2012 Delete comment Project Member #6 vlahoda
 Issue 322  has been merged into this issue.
Apr 24, 2012 Delete comment Project Member #7 vlahoda
Systém lokalizovaných textů bude sjednocen. Všechny lokalizovatelné texty budou mít odpovídající položku v souboru labels.properties. Výchozí hodnoty bude možné předefinovat v odpovídajících souborech v adresáři ~/.kramerius4/labels. Pro rozsáhlejší texty (introduction, atd...) bude možné odpovídající lokalizovaný text zapsat do souboru v adresáři ~/.kramerius4/texts, název souboru je identický s názvem původního klíče v bundle labels.properties. Obsah souboru v /texts má přednost před obsahem souboru v /labels a ten zase před defaultními hodnotami uvnitř search.war.
Názvy souborů pro labels a texts pro jednotlivé jazykové mutace budou dodržovat standardní konvence pro lokalizaci JDK.

Systém může být doplněn o editaci vybraných položek přímo z administrátorského GUI:
Konfigurační property editable.texts bude obsahovat seznam klíčů v základním bundle, které bude možno editovat. Administrátorské GUI bude doplnno o dialog, který bude pro každý takovýto klíč obsahovat prvky text area (pro locale en a cs), ve kterých bude možno editovat příslušnou položku. Při uložení změn bude přepsán odpovídající soubor v adresáři ~/.kramerius4/texts
Labels: -Type-Defect -Priority-Low Type-Enhancement Priority-Medium 
Apr 25, 2012 Delete comment Project Member #8 vlahoda
 Issue 219  has been merged into this issue.
Jun 29, 2012 Delete comment Project Member #9 leos.junek@nkp.cz
Stále nebyl splněn požadavek z  issue 320 , které bylo do tohoto Issue sloučeno.

"Dokumentace ke GUI neobsahuje informaci o tom, jak měnit popisek záložek, text (v případě záložky Informace) nebo obsah (záložka Vybrané), pořadí záložek, výběr defaultní záložky."

Dokumentace ke GUI (http://code.google.com/p/kramerius/wiki/UI) bohužel neobsahuje téměř nic a odkazuje na nápovědu. Tento web má obsahovat administrátorskou dokumentaci, ta nemá být součástí uživatelské nápovědy.

Prosím o nápravu.
Jun 29, 2012 Delete comment Project Member #10 leos.junek@nkp.cz
Doplnění k mému poslednímu komentáři:
Měnit pořadí a zobrazení záložek lze v souboru ${KRAMERIUS_HOME}/.kramerius4/search.properties

a to editací řádku
search.home.tabs=info,custom,mostDesirables,newest,facets,browseAuthor,browseTitle

Ale to v dokumentaci UI popsané není. Když jsem dal řetězec "search.home.tab" vyhledat na Wiki, našel jsem ho jen v Changelogu.
Jun 29, 2012 Delete comment Project Member #11 Martin.Rehanek
V http://code.google.com/p/kramerius/wiki/Instalace#Konfigurace je odkaz search.properties odkazující na http://code.google.com/p/kramerius/source/browse/trunk/search/src/java/res/configuration.properties. Možná by stačil u té konfigurace (pro každý .properties soubor, min. search.properties) seznam základních věcí, které je tam možné nastavit, třeba ve formě odrážek. Protože je pravda, že takhle to nemusí být jednoduché najít, navíc ten defaultní konfigurační soubor se může potichu změnit a přibude nová vlastnost, kterou pak člověk objeví náhodou, když řeší nějaký problém. Např. teď jsem objevil search.details.showSuggest.
Jun 19, 2013 Delete comment Project Member #12 Martin.Barton@nkp.cz
Jen se chci přeptat, zda a kdy asi můžeme čekat opravu. Issue vzniklo již téměř před dvěma lety a váží se na něj ještě další tři issue, kdy zvláště 321 (Editace textu v záložce "Informace" pomocí GUI) bychom vyřešené určitě přivítali.
Jul 4, 2013 Delete comment Project Member #13 vlahoda
(No comment was entered for this change.)
Status: OnHold 
Labels: -Priority-Medium Priority-Low 
Jul 4, 2013 Delete comment Project Member #14 vlahoda
 Issue 432  has been merged into this issue.

**Comment by pavel-stastny** [comment]
Bude reseno v ramci reimplementace admin rozhrani v pristim roce
