### ISSUE TITLE
Issue 592:	Dodávání obsahů a obálek na server obalkyknih.cz

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#40]
Reported by zabicka, Aug 1, 2013
Zprovoznit podporu pro předávání obsahů a obálek na server obalkyknih.cz. Obálky je teoreticky možné stahovat přes OAI s využitím ESE, je ale potřeba doplnit i obsahy. To by bylo možné přidáním dalších obrázků do ESE - viz sepcifikace elementu object: "If a record contains several image files, the first file that appears is used as the source." - tj. první obrázek by se považoval za obálku, všechny další za obsah a Europeana by to zpracovávala korektně. Bibliografická metadata by musela být předávána o všechny možné identifikátory (čČNB, ISBN/ISSN, číslo OCLC apod.). Zatím alespoň na úrovni titulu a u obsahů stačí obrázky, ocr text není nezbytný.

Druhá možnost je využít API obálek knih a vkládat obálky a obsahy aktivně, ale OAI je v tomto případě asi lepší cesta.
Aug 27, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by zabak** [comment]
Považuju za vyřešené ve verzi 5.7.2
