### ISSUE TITLE
K5 - zobrazení výsledků vyhledávání od určitého pořadí

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#402]
Když procházím výsledky vyhledávání a zadám nové hledání, výsledky se mi zobrazí až od určitého pořadí, v jakém procházení skončilo v předešlé akci.
Př. http://cdk.lib.cas.cz/client/index.vm?q=pes&page=search&start=120&rows= Výsledky nového dotazu se načítají až od 120. položky.

**Comment by pavel-stastny** [comment]
Bude reseno zaroven s #443
