### ISSUE TITLE
Reakce K5 na nechtěný duplicitní import

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#404]
Řešili jsme teď několikrát, že byl do K5 nechtěně naimportován stejný titul znovu. 
Občas se to stane, když se spouští importy z admin rozhraní (kde bohužel  nelze označit celou skupinu dokumentů k importu naráz, ale musí se naklikávat po jednom). A někdy se to stane, když před importem opraveného titulu není ten původní včas odmazán. Potud chyby admina - ale když se tohle stane, mohl by se K5 zachovat líp. Teď se to naimportuje i podruhé - ale ne tak, že je tam dvakrát vedle sebe stejný dokument, ale ty strany se přihrají k tomu prvnímu a jsou tam dvakrát. Je to z nějakého důvodu? 
Nešlo by, aby se v takových případech import stopnul a zahlásilo to něco ve smyslu, že dokument se stejným uuid už v K5 je?

**Comment by vlahoda** [comment]
Chování importu a možnosti jeho konfigurace jsou popsány v této části dokumentace na wiki: https://github.com/ceskaexpedice/kramerius/wiki/MenuAdministrace#import-dokument%C5%AF-ve-form%C3%A1tu-foxml-krameria-4
(vašeho problému se týkají především konfigurační property ingest.updateExisting a případně soubor update.list)

Defaultní chování se slučováním existujících a nových dokumentů je nastaveno proto, aby se automaticky spojovaly jednotlivé části periodik při postupném importu po ročnících nebo číslech. Pokud nastavíte property ingest.updateExisting na true, nebudou nová data připojena k existujícím, ale přepíšou je. Administrátor by ale v tomto případě měl pečlivě zvážit, jestli existující objekty neobsahují nějaké sloučené vazby z předchozích importů, které by pak novým importem byly odstraněny.

Ke zdvojování stran při opakovaném importu téhož titulu dochází proto, že ve stávající verzi specifikace METS NDK nemají strany přiřazené identifikátory UUID, takže jim je vytváří až konvertor do formátu Krameria - tedy pokaždé znovu a jiné. Řešení přinese zřejmě až chystaná nová verze specifikace METS NDK, která by měla identifikátory stran zavést.

Ještě k dávkovému importu více dokumentů - Importní program prochází zadaný  vstupní adresář rekurzivně, takže není potřeba naklikávat dokumenty po jednom, ale stačí je před importem umístit do jednoho nadřazeného adresáře a import spustit pro něj. Případně je možné importy spouštět dávkově jednoduchým shell skriptem přes API Krameria.
