### ISSUE TITLE
Znemozneni tisku u chranenych dokumentu

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#406]

**Comment by pavel-stastny** [comment]
Přidány 3 nové akce:

* `PDF_RESOURCE`  - určuje přístup k serverovým prostředkům generujícím PDF. 
* `SHOW_CLIENT_PRINT_MENU` - akce definuje možnost resp. nemožnost zobrazení položky tisku (reflektováno v admin i v klientském rozhraní)
* `SHOW_CLIENT_PDF_MENU` - akce definuje možnost resp. nemožnost zobrazení položky generování pdf (reflektováno v admin i v klientském rozhraní)

**Comment by LenkaDamborska** [comment]
Mám dotaz, jak se tato práva přesně nastavují. Vyzkoušela jsem různé věci, ale znemožnit zobrazení tiskového menu nebo PDF menu se mi nepodařilo. Nastavuje se to povolením akce jen pro určitou roli nebo jak jinak se dá akce znemožnit? Díky!

**Comment by pavel-stastny** [comment]
Dobry den, 

stadnardne jsou prava nastavena na urovni repozitare. Pokud chcete mit tato prava nastavena globalne, zmente prosim nastaveni v menu "Nastaveni globalnich akci.." (naprilad tim, ze pridate IP filtr).  Pokud to  chcete mit povoleno pouze u nekterych titulu, zruste, prosim, nastaveni v globalnich akcich a nastavte to primo na konretnim titulu.

**Comment by jirikrepl** [comment]
Dobrý den,
děkujeme za přidání 3 nových akcí. Zkoušeli jsme je u nás a ještě bychom potřebovali vytvořit jedno pravidlo (viz níže).

Potřebujeme, aby tyto 3 nové akce byly zakázané u dokumentů s `model:sheetmusic` a `policy:private`.

Navrhujeme vytvořit pravidlo "! model (benevolentní)", které bude brát dodatečnou podmínku - seznam modelů

Pravidlo "! model (benevolentní)" - rozhodne ANO nebo NEVIM. 
ANO rozhodne pokud model *není* obsažen v 'parametrech kriteria' (negace)
NEVIM rozhodne pokud je model obsažen v 'parametrech kriteria' a potom pokračuje dalším pravidlem

```
      objekt     role	        Akce                      Kriterium           	Parametry kriteria 
-------------------------------------------------------------------------------------------------------------------------------------------
0  REPOSITORY   všichni   SHOW_CLIENT_PRINT_MENU   ! model (benevolentní)   	   [sheetmusic] 
1  REPOSITORY   všichni   SHOW_CLIENT_PRINT_MENU   Příznak (kramerius:policy)
```

```
    pravidla       postup       výsledek
------------------------------------------
0 model:monograph     ANO	----> ANO
1 policy:private            

0 model:monograph     ANO	----> ANO
1 policy:public

0 model:sheetmusic    NEVIM
1 policy:private      NE	----> NE

0 model:sheetmusic    NEVIM
1 policy:public        ANO	----> ANO

```

**Comment by jirikrepl** [comment]
Dobrý den,
chci se zeptat, jestli budete toto issue řešit? Případně nám dát termín, kdy by to mohlo být hotovo. Děkuji

**Comment by pavel-stastny** [comment]
Dobry den, pripravime jar, ktery bude obsahovat dane kriterium.  (Nekdy behem tothoto tydne.)

**Comment by jirikrepl** [comment]
Dobrý den, jak to tedy vypadá? děkujeme

**Comment by pavel-stastny** [comment]
Muzete prosim vyzkouset?  

https://github.com/pavel-stastny/modelfilter/releases/tag/1.0

**Comment by pavel-stastny** [comment]
Pokud bude funkcionalita v poradku, pridame filter do standardni distribuce.

**Comment by MartinRumanek** [comment]
Funkcionalita v pořádku je, funguje nám to. Bude funkcionalita přidána do zdrojových kódů Krameria, nebo bude i v budoucnu distrubuována jako jar knihovna?

**Comment by pavel-stastny** [comment]
Presune se do buildu.
