### ISSUE TITLE
Virtuální sbírky - řazení dle abecedy

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#409]
Zdravím,

bylo by dobré přidat do jádra i klienta podporu řazení založených virtuálních sbírek minimálně (možná i podle počtu zařazených objektů do virtuální sbírky? vzestupně a sestupně?) dle abecedy při zobrazování. Řazení by se mělo dát, dle našeho názoru, deaktivovat/ladit v konfiguraci aplikace.

Díky, Duda

**Comment by zabak** [comment]
Nebylo by od věci ani mít možnost sbírky strukturovat do nějakého stromu. Minimálně na úrovni ČDK by mělo být vidět které virtuální sbírky spadají pod kterou knihovnu. A co když dvě knihovny pojmenují virtuální sbírku stejně? Uměla by to ČDK sloučit?

**Comment by pavel-stastny** [comment]
Viz #408

**Comment by mduda100871** [comment]
Zdravim,

jadro od verze 5.3.6 sbirky abecedne radi, to je dobre. Ale klient nikoliv. Jak vraci/melo by vracet jadro klientovi seznam sbirek pres API? Je potreba klienta take nakonfigurovat?

MD

**Comment by jandera** [comment]
Klient stále sbírky neřadí abecedně. Řešení v jádře, konfigurační proměnou, neřeší navrhované řazení dle abecedy vzestupně/sestupně. Chybí možnost řadit sbírky dle počtu dokumentů, opět vzestupne/sestupně.

**Comment by slapakovai** [comment]
Prosím o vyřešení posledních připomínek M. Dudy a T. Jandery.

**Comment by pavel-stastny** [comment]
Pridana moznost trideni dle poctu zarazenych dokumentu: 

Trideni v jadre (kofiguracni promenna  v search.properties): 

`search.collection.sort=DESC | ASC`
`search.collection.sortType=ALPHABET | NUMBER_OF_DCOUMENTS`

Trideni v kleintovi, opet rizene pomoci promenne, nyni v client.properties

`k5client.collection.sort=DESC | ASC`
`k5client.collection.sortType=ALPHABET | NUMBER_OF_DCOUMENTS`
