### ISSUE TITLE
Issue 612:	Vylepšení prohlížení IMG_FULL pro PDF soubory

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#41]
Reported by filip.kriz, Sep 23, 2013
Navrhuji vylepšení prohlížení IMG_FULL streamů pro PDF soubory. Nemohla by zde být obdobná lišta jako u obrazových souborů?

Pokud se uživatel dostane k zobrazení PDF přes nějaký web vyhledávač, nemá žádnou možnost, jak se dostat na zobrazení dokumentu v K4 (kromě toho, že ze zobrazeného PDF vydedukuje, o jaký dokument se jedná a najde si ho pak v K4 vyhledávání). Navíc nejspíš ani nepozná, odkud se vlastně PDF dokument vzal.  

Sep 23, 2013 Delete comment #1 filip.kriz
Doplnění - v liště by tedy měl být alespoň odkaz na zobrazení dokumentu v K4, např. přes název dokumentu.
Sep 25, 2013 Delete comment #2 filip.kriz
Toto se sice týká K3, ale v K4 je situace se zobrazením PDF souboru stejná.

"Dobrý deň,
zaujímam sa o dejiny lekárne... Pri svojom pátraní som našiel na vašej stránke toto pdf-ko: http://www.medvik.cz/kramerius .... Snažil som sa zistiť, z akej je to knihy, žiaľ nepodarilo sa mi to. 
Vedeli by ste mi, prosím poradiť, z akej knihy je táto kapitola a obsah? 
Srdečná vďaka."

Oct 8, 2013 Delete comment Project Member #3 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
lepsi zobrazeni pdf je reseno v klientske aplikaci
