### ISSUE TITLE
SOLR - dotaz s wildcard (*) nenajde dokumenty s UUID obsahujícím velká písmena

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#411]
Pravděpodobně se to projevuje všude, kde se v Krameriovi wildcard operátor používá při dotazech na PID nebo pid_path, když UUID obsahuje velká písmena. Například při mazání z indexu - root objekt se sice smaže, ale podřízené objekty v indexu zůstanou.

Jedná se o vlastnost SOLR - viz:
http://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#Analyzers 
a
http://wiki.apache.org/lucene-java/LuceneFAQ#Are_Wildcard.2C_Prefix.2C_and_Fuzzy_queries_case_sensitive.3F

**Comment by pavel-stastny** [comment]
Reseno v ramci prechodu na solr 6 a zmenou schematu.
