### ISSUE TITLE
Historie hledání se nenaplní při hledání přes API

### ISSUE THREAD

**Issue by leiblix** [ceskaexpedice/kramerius#412]
V API (https://github.com/ceskaexpedice/kramerius/wiki/ClientAPIDEV#clientuserresource--informace-o-u%C5%BEivateli) je možné získat (mimo jiné) historii hledání.

Bohužel tato histore se plní pouze při hledání přes staré rozhraní, ale už ne při použití API, což znemožňuje použití historie v jiných klientech.

A ješte je otázka jestli má být search history takto komplexní - myslím, že by v historii bohatě stačil seznam slov bez dalších parametrů faset.

Ono to takto úlpně nedává smysl, například když chci hledat veřejné mapy, tak prvně kliknu na mapy a potom na fasetu public - což mi v historii vytvoří dva dotazy. To první je jenom mezikrok, který mě vlastně nezajímá a je to docela matoucí.

![historie](http://i.imgur.com/5MliuEO.png)

**Comment by pavel-stastny** [comment]
@pavelkocourek @slapakovai @leiblix Uzaviram. V pripade potreby doporucuji otevrit nad K7.
