### ISSUE TITLE
API nerespektuje stav "deleted"

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#415]
K5 API vrací výsledek i pro objekty smazané s konfigurační property delete.purgeObjects=false (zůstávají ve fedoře s příznakem "deleted") místo očekávaného "{"message":"pid not found","status":404}"

**Comment by pavel-stastny** [comment]
Nova implementace Krameria 7 je postavena na ulozisti akubra. Objekty v ulozisti po smazani nezustavaji.
