### ISSUE TITLE
Reimport "deleted" dokumentů

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#416]
Opakovavý import / replikace a indexace dokumentu smazaného s konfigurační property delete.purgeObjects=false (nastavení příznaku "deleted" místo faktického smazání z fedory) proběhne v pořádku, ale dokument se nezaindexuje - i po opětovném importu do fedory objekt zůstává s příznakem deleted.
Po reimportu by měl příznak deleted zmizet.
Indexace by navíc neměla jít spustit nad "deleted" dokumentem a určitě by neměla úspěšně skončit.

**Comment by pavel-stastny** [comment]
U noveho uloziste to neni aktualni
