### ISSUE TITLE
Možnost dočasně vypnout image server při importu

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#417]
Návrh na vývoj:
možnost dočasně vypnout používání image serveru pro konkrétní ímportní proces.

**Comment by zabak** [comment]
@slapakovai je to stále potřebné?

**Comment by kerschfilip** [comment]
bylo by, prosím, možné úpravu b89e354 zahrnout i do K7, @pavel-stastny ?

**Comment by zabak** [comment]
@kerschfilip k čemu je tohle potřeba?

**Comment by kerschfilip** [comment]
Někdy to používáme při testovacích importech. V K7 to je zahrnuté:
![image](https://github.com/ceskaexpedice/kramerius/assets/57805328/c21de008-b396-4cd0-ace9-d8ea1feedffe)
