### ISSUE TITLE
Při replikaci replikovat i obrázky co nejsou uložené ve Fedoře

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#418]
Může být nastaveno volitelně, ale teď se obrázky co jsou ve filesystému nereplikují vůbec.

**Comment by pavel-stastny** [comment]
Mate na mysli streamy referencovane protokolem file:///?  
(file:///mnt/data/obrazek.jpg)

**Comment by MartinRumanek** [comment]
@LenkaDamborska  má na mysli externě referencované obrázky do imageserveru,
 
```"Pokud digitální objekt obsahuje odkaz na IIPserver, zůstává tento nezměněn."``` z dokumentace 
https://github.com/ceskaexpedice/kramerius/wiki/Replikace#pozn%C3%A1mky-k-implementaci

**Comment by MartinRumanek** [comment]
Diskuze z https://github.com/ceskaexpedice/kramerius/issues/495 patří sem, pokračujme zde:

> Zalezi jak to myslite. IMG_FULL, ktery bude obsahovat jpeg ve forme managed streamu, to pujde a to mame i vplanu. Cely zdrojovy JPEG200, ktery by se zpreplikoval z jednoho IIP serveru na druhy, to bohuzel asi nepujde. Nemame moznost se programove dostat ke zdrojovym JPEG2000 souborum.

> Neslo mi ani o pristup k filesystemu. Spis mi slo o tu tranfromraci url na fyzicke umisteni souboru na disku. (Zvlaste kdyz uvazime moznosti pouziti mod_rewrite apod. )

> Osobne bych spis navrhoval obohatit metadata o fyzickou cestu k souboru.

To je dobrá připomínka. Kramerius to skutečně neví, ale myslím si, že než obohatit metadata, bude jednodušší a systémovéjší naučit samotné instalace imageserveru vracet originální jpeg2000 obrázky (mělo by to znamenat jedno mod_rewrite pravidlo navíc).

**Comment by pavel-stastny** [comment]
> To je dobrá připomínka. Kramerius to skutečně neví, ale myslím si, že než obohatit metadata, bude
> jednodušší a systémovéjší naučit samotné instalace imageserveru vracet originální jpeg2000 obrázky
> (mělo by to znamenat jedno mod_rewrite pravidlo navíc).

Ano, s tim souhlasime. Zbyva tedy vytvorit uzus, jak dane pravidlo (dana url) bude vypadat. Mate nejaky navrh ?
