### ISSUE TITLE
Zobrazení tečky v názvu stránky (za application.title)

### ISSUE THREAD

**Issue by FoxKyong** [ceskaexpedice/kramerius#419]
Pokud je vybraný nějaký dokument, tak za názvem stránky (application.title) se vždy zobrazuje tečka, což nevypadá dobře.

![screenshot_20160511_081315](https://cloud.githubusercontent.com/assets/2877720/15172190/8b0452d4-1754-11e6-8f72-a7b54be171b2.png)

**Comment by filak** [comment]
Normálně se za tečkou zobrazuje název dokumentu, proč se tak ve vaší instalaci neděje však netuším.

**Comment by FoxKyong** [comment]
Tak jak jsem zjistil, tak nejsme jediní. Některých knihovnám se tam ten název dokumentu zobrazuje, jiným zase ne. Já teda zatím tu tečku ze zobrazení odebral.

**Comment by filak** [comment]
Je to zřejmě v metadatech. 
Teorie: Pokud v indexu chybi <str name="dc.title"> tak se pak název v hlavičce nezobrazí, v K5 clientovi se pak zobrazuje null.
2 případy, co jsem u nás našel, jsem opravil metadata a reindexoval - v indexu tedy už hodnota je, zatím se ale stejně nezobrazuje v klientech.

**Comment by FoxKyong** [comment]
Metadata jsem kontroloval a dc.title tam je, takže reindexace nepomáhá.

**Comment by filak** [comment]
Pomaha, musite ale pak restartovat Tomcat

**Comment by FoxKyong** [comment]
To jsem už taky zkoušel a nic.

**Comment by filak** [comment]
No, v K5-client se vam to ukazuje dobre:
http://kramerius.kr-olomoucky.cz/client/handle/uuid:271e7bec-03a4-4e26-a5ce-ad444a1ae742
ale K5-search mate chybne nastaveneho hosta pro API:
http://**localhost:8180**/search/api/v5.0/item/uuid:271e7bec-03a4-4e26-a5ce-ad444a1ae742
by melo byt:
http://kramerius.kr-olomoucky.cz/search/api/v5.0/item/uuid:271e7bec-03a4-4e26-a5ce-ad444a1ae742

**Comment by slapakovai** [comment]
@FoxKyong Podařilo se ten problém s tečkou vyřešit podle toho, co Vám radil Filip nebo ještě stále trvá?

**Comment by FoxKyong** [comment]
Podle toho ne, host byl nastavený dobře v konfiguraci, mezitím se Kramerius ještě upgradoval na novější verzi a to jsem si už pak ani nevšiml, že to nezobrazuje, takže je možné, že nějaká změ na tam proběhla. Tím, že to API v té konfiguraci tak bylo, tak jsem nic neměl, takže pořádně jsem si nevšiml, kdy to tu tečku přestalo zobrazovat.
Ale tím, že nezobrazuje, tak nějak vyřešené.
