### ISSUE TITLE
Issue 617:	Poskytování dat pro Europeanu (projekt eCloud)

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#42]
Reported by Jakub.Rihak, Sep 30, 2013
Dosavadní průběh příprav na poskytování dat Europeaně v rámci projektu eCloud ze strany NTK
- dodávání dat do Europeany probíhá přes The European Library (TEL)
1. fáze - vyplnění dotazníku
- dotazník slouží k popisu datasetů, které chcete do Europeany posílat + možnost výběru protokolu, který bude používán pro dodávání dat...
- k poskytnutí základních informací o organizaci a zodpovědných osobách
- dotazník je dostupný na adrese http://bit.ly/15Orqee
- následně byl zaslány testovací FOXML objekty
- FOXML celé monografie + FOXML stránek
- FOXML celého periodika + FOXML ročníku + FOXML čísla + FOXML několika stránek
- formát FOXML prý bohužel není podporován
- dostali jsme za zkusit vyexportovat objekty z Fedory ve formátu METS 
- následně jsem zaslal vyexportovaná ukázková data ve formátu METS 1.0 a METS 1.1 a bylo mi sděleno, že moc děkují a včas před plánovaným dodáním dat dají vědět, pro jaký formát dat se rozhodli
- data máme dodat do dubna 2014

TECHNICKÉ ŘEŠENÍ
- prozatím počítáme s dodávkou přes FTP (pokud se nepodaří včas vyřešit harvestování dat přes OAI-PMH)
- podle [https://wiki.duraspace.org/display/FCSVCS/OAI+Provider+Configuration+Reference#OAIProviderConfigurationReference-FedoraDriver:SetMembershipConfiguration těchto informací] je nutné ve Fedoře vytvořit objekt zastupující OAI set
- v admin rozhraní jsem ho vytvořil
- po zadání dotazu na OAI provider jsem set našel mezi výsledky

<code language="xml">
<ListSets>
<set>
<setSpec>europe_m</setSpec>
<setName>Europeana monograph collection</setName>
</set>
<set>
<setSpec>europe_h</setSpec>
<setName>Europeana historical monograph collection</setName>
</set>
<set>
</code>
- myslel jsem, že bude stačit, když do objektů, které chci přidat do OAI setu, přidám nějakou RDF trojici, která určí, do kterého setu daný dokument patří
- ukázalo se ale, že se dokumenty do nastavený OAI setů vybírají pomocí dotazů, které jsou definovány v proai.properties, tedy souboru nastavení OAI provideru
- aktuální podoba dotazu
  {{{$item info:fedora/fedora-system:def/model#hasModel $set $set http://www.openarchives.org/OAI/2.0/setSpec $setSpec}}}
- to myslím znamená, že do OAI setů se přidávají jen ty objekty, které obsahují vazbu #hasModel (?)
- [https://docs.google.com/document/d/1jkQ1-TH8KL7vTJnbOx9bOWSd5gnYc97eqpwuUyog9Ck/edit?usp=sharing poznámky] k mému snažení o vytvoření OAI setu speciálně pro objekty určené k exportu do Europeany jsou dostpné na Google Drive, stejně tak jako mé [https://docs.google.com/document/d/1jkQ1-TH8KL7vTJnbOx9bOWSd5gnYc97eqpwuUyog9Ck/edit#bookmark=id.y4swtsodbw9z otázky] na pana Pokorského a [https://docs.google.com/document/d/1jkQ1-TH8KL7vTJnbOx9bOWSd5gnYc97eqpwuUyog9Ck/edit#bookmark=id.ufb6p9x0o6vd odpovědi na ně]...

V současné chvíli jsem uvázl na mrtvém bodě a netuším, kterým směrem se hnout, protože to zatím zřejmě přesahuje úroveň mých technických znalostí o Fedoře a OAI provideru, ale byl bych vděčný za jakoukoliv pomoc. 

Napadlo mě, že bych mohl zkusit přepsat dotaz pro výběr objektů do setu v proai.properties tak, aby vybíral jen dokumenty, které obsahují vazbu "isMemberOfCollection" nebo nějakou jinou vazbu, ale to je asi tak zatím všechno, co s tím dokážu provést.

Jakub Řihák
NTK
Dec 7, 2013 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by zabak** [comment]
Předávání do Europeany řeší ČDK, navrhuji zde zavřít
