### ISSUE TITLE
Neprochází build

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#420]
V Krameriu se do teď používají mvnrepa z googlecode, který to teď už definitivně zaříznul. Takže Kramerius (^HEAD ani tag 5.3.3) není možné zbuildit.

Pro knihovnu imageio stačí posunout verzi z 1.6.1 na 1.6.5 (1.6.5 je v central repository)
```
-    compile 'com.levigo.jbig2:levigo-jbig2-imageio:1.6.1'
+    compile 'com.levigo.jbig2:levigo-jbig2-imageio:1.6.5'
```

 com.foxtrottechnologies:djvuframe:0.8.09 jsem vůbec nenašel.

**Comment by jirikrepl** [comment]
Build neprochází - jai_imageio.jar vrátí 404

Could not resolve all dependencies for configuration ':common:compileClasspath'.
Could not find jai_imageio.jar (com.sun.media:jai_imageio:1.1).
Searched in the following locations:
https://repo1.maven.org/maven2/com/sun/media/jai_imageio/1.1/jai_imageio-1.1.jar

**Comment by jirikrepl** [comment]
Díky, zvažte prosím nastavení continuous integration (např. https://travis-ci.com) pro repozitář Krameria. Mohli by jste tam vidět po každém commitu, že build neproběhl v pořádku. My máme nastavený [.travis.yml soubor](https://github.com/moravianlibrary/kramerius/blob/mzkgrafika_5.3.3/.travis.yml) takto. Děkujeme
