### ISSUE TITLE
Rozšíření funkce aplikovat pohyblivou zeď na celý repozitář

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#423]
Návrh na vývoj:
Rozšířit funkci aplikace globální pohyblivé zdi o:
- automatické spouštění - např. jednou za čtvrt roku
- přidat rozlišení podle typu dokumentu
- u periodik indexovat pouze ty ročníky, jejichž nastavení policy se aplikací mw změní
- možnost vytvořit black list dokumentů nebo typů dokumentů na které se globální pohyblivá zeď nebude vztahovat

**Comment by pavel-stastny** [comment]
V K7 již proces pohyblivé zdi není přítomen.
