### ISSUE TITLE
Zobrazení tiskaře u knih zpracovaných dle RDA

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#425]
Dobry den,
po importu balicku knihy,ktera ma bibliograficky zaznam podle pravidel RDA se zobrazuji udaje o vydavateli i tiskari souhrne pod Vydavatelskymi udaji (napr. https://camea2.svkos.cz/search/i.jsp?pid=uuid:c5f3a3c9-6823-441b-8b39-5c9231007dfa&q=).
Je to tak spravne nebo je treba upravit sablonu,aby se zobrazil kazdy z nich v samostatne "kolonce"? Dle standardu je vydavatel a tiskar rozlisen priznaky publication a manufacture.
Dekuji
A. Drahotussky

**Comment by zabak** [comment]
@Drahotussky prosím o otestování v novém klientovi

**Comment by zabak** [comment]
@Drahotussky V této chvíli je v daném záznamu

      <mods:publisher>Knihtiskárna Hejda &amp;amp; Zbroj</mods:publisher>
      <mods:publisher>Jindra Cink</mods:publisher>

Pokud jde o problém konverze z MARCu do MODSu, doporučuju řešet na úrovni standardů digitalizace. Zde zavírám.
