### ISSUE TITLE
Řazení příloh u periodik

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#426]
Vím, že se řazení příloh u periodik už někdy řešilo, ale v issues jsem to nenašla. Když ročník obsahuje čísla i přílohy, tak se seřadí pouze čísla, ale přílohy zůstávají (nejspíš) tak, jak přibývají do Krameria. Např. Brněnské noviny: http://kramerius.mzk.cz/search/handle/uuid:93c65980-6630-11e3-ac69-005056827e51
Když je málo příloh, dá se to seřadit ručně ve foxml, ale při takovém množství to nejde. Stejný problém máme u Brünner Zeitungu a dalších periodik, kde je hodně příloh.

**Comment by vlahoda** [comment]
Můžete prosím zkontrolovat, jestli nemáte v některém konfiguračním souboru (configuration.properties, migration.properties atd.) uvedenou property sort.xpaths - a pokud ano, co v ní máte nastaveno?

**Comment by LenkaDamborska** [comment]
Dobrý den, ani v jednom souboru sort.xpaths nemáme.

**Comment by LenkaDamborska** [comment]
Pardon. Tak to tam nakonec máme: configuration.properties:sort.xpaths=page;//mods:mods/mods:part/mods:detail[@type='pageIndex']/mods:number;true,\

**Comment by vlahoda** [comment]
Pokud tam skutečně máte jen tento jeden řádek, fungovalo by vám pouze třídění stránek. V sort.xpaths by měl být uveden řádek s xpath pro každý model, který má být tříděn. Defaultní hodnoty sort.xpaths vyhovují pro standardní obsah MODS pocházející jak z K3, tak z dat NDK, takže je není třeba předefinovávat ve vašem konfiguračním souboru. Předpokládám, že jste do vaší verze configuration.properties použili nastavení sort.xpaths z některé starší verze Krameria, kde ještě chyběl xpath pro model supplement. Můžete tedy prosím z configuration.properties úplně odstranit sort.xpaths a zkusit znovu přetřídit jeden ročník toho periodika?

**Comment by jirikrepl** [comment]
Konfiguraci máme tedy nastavenou správně. Nemáme předefinované hodnoty sort.xpaths a používá se výchozí nastavení z kódu Krameria. 

Debugoval jsem proces třídění a potom proces indexace.

Proces třídění proběhne správně. Ve foxml relst_ex (periodicalVolume) se nám správně seřadí uuid modelů suplement.

Vypadá to, že bude problém v následně spuštěné *reindexaci*. Pravděpodobně *update* indexu neproběhne správně. Po reindexaci nejsou v Krameriu přílohy seřazeny správně.

Pokud v indexu neexistovaly uuid suplement, tak indexace proběhla správně (dokumenty se Krameriu zobrazily ve správném pořadí).

Více jsem ještě chování nad konrétními daty popsal zde https://github.com/moravianlibrary/kramerius/issues/94

**Comment by vlahoda** [comment]
Mohli byste nám prosím někde zpřístupnit FOXML soubory toho ročníku 1898, abychom je mohli naimportovat na svůj server? Stačí bez obrázků.

**Comment by Jenyk** [comment]
Tohle už není aktuální, může se zavřít
