### ISSUE TITLE
Metadata u příloh periodik

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#427]
Přílohy periodik nemají v API datum vydání a další údaje. Hlavně datum vydání v mods:dateIssued je důležité.

**Comment by pavel-stastny** [comment]
Dobry den, 

propagovani hodnoty z dateIssued bylo reseno pro modely periodical, periodicalItem a periodicalVolume.  Pro model supplement bude soucati pristiho buildu.

**Comment by LenkaDamborska** [comment]
Dobře, díky za informaci.

**Comment by slapakovai** [comment]
@LenkaDamborska Byl tenhle problém vyřešen nebo ještě stále trvá?

**Comment by LenkaDamborska** [comment]
@slapakovai Zdá se, že ne, metadata z dateIssued u modelu supplement v API nejsou.
