### ISSUE TITLE
Ovládací tlačítka se posouvají pod spodní lištu a nejdou používat

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#428]
Tituly s delším názvem v pravém panelu mají ovladací tlačítka posunuté pod spodní lištu a nejdou ovládat, např:
http://vmkramerius.incad.cz:8080/client/handle/uuid:2461e97e-468a-4663-b152-7f38cd6f51f8
ale evidentně je to i ve starší verzi:
https://kramerius.lib.cas.cz/client/handle/uuid:2461e97e-468a-4663-b152-7f38cd6f51f8
Obrázek toho, co přeně myslím:
https://drive.google.com/open?id=0B3h-WdvT09AdckpUUTR6SWlzeDA

**Comment by slapakovai** [comment]
Problém stále trvá - verze 5.3.6

**Comment by krizovj** [comment]
Zdá se mi to už nerelevantní, zavírám.
