### ISSUE TITLE
Doba odhlášení při nečinnosti

### ISSUE THREAD

**Issue by jirikrepl** [ceskaexpedice/kramerius#430]
Doba před odhlášením je pouze 30 minut, chceme ji prodloužit na 3 hodiny

**Comment by mduda100871** [comment]
To bych rekl, ze je zalezitost nastaveni Tomcatu, nikoliv Krameria. V souboru "$CATALINA_HOME/conf/web.xml" najdete element "<session-config>" a v nem se da timeout nastavit. Defaultne je nastaven prave na 30 min. - viz screenshot.
![timeout-01](https://cloud.githubusercontent.com/assets/8750622/16452079/ea86f594-3e06-11e6-95b1-50fb20865748.png)

**Comment by jirikrepl** [comment]
Děkuji
