### ISSUE TITLE
Generování PDF - pásek ke stránce

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#432]
Máme námět, aby se v generovaném pdf zobrazoval pásek pod každou stránkou, kde by byla informace o licenci a instituci, z jejíž dig. knihovny dokument pochází. Mohou tam být příp. i jiné údaje, to by bylo na diskuzi.

**Comment by slapakovai** [comment]
Souhlasím, my bychom tam rádi zobrazovali např. licenci creative commons, pod kterou je dokument zveřejněn nebo název instituce.

**Comment by pavel-stastny** [comment]
f8001eb23a70f5a3bafe7fe6b25f2d765e9ba7c3

**Comment by pavel-stastny** [comment]
Hlavicka a paticka generovanych pdf je mozne definovat v souborech: 

-pdf_footer
-pdf_footer_CZ_cs
-pdf_footer_EN_en

-pdf_header
-pdf_header_CZ_cs
-pdf_header_EN_en
