### ISSUE TITLE
K5 - client 5.3.3 

### ISSUE THREAD

**Issue by LubosMaly** [ceskaexpedice/kramerius#434]
Zdravím,
naše knihovna (SVKUL) poskytuje přístup do krameria městskému muzeu. Jen pro tituly
které má  knihovna muzea ve fondu. Přístup jsem jim umožnil tak, že jsem vytvořil roli "muzeum"
potom uživatele které jsem přiřadil do této role. V nastavení práv pro "read" mám u daných dokumentů
nastaveno role "muzeum", IP filtr (benevolentní), a v parametrech kriteria je jejich vnější IP adresa.
Prostřednictvím rozhraní K5 si po přihlášení uživatelé přiřazení do role "muzeum" mohou bez problémů 
prohlížet z muzea tituly které jsem jim takto nastavil. Byl jsem upozorněn, že toto bohužel nefunguje
prostřednictvím klienta. U titulů které vidí v K5 jim to v klientovi píše "Přístup odepřen, V souladu se zákonem č. 121/2000 atd. 

L. Malý

**Comment by mduda100871** [comment]
Dobry den,

pripojuji stejne zjisteni. Je toto chovani vlastnost, nebo chyba?

Diky, Duda

**Comment by slapakovai** [comment]
U nás problém stále přetrvává, client zobrazuje přístupné a nepřístupné dokumenty jinak než jak je nastaveno v search.

**Comment by pavel-stastny** [comment]
Tyka se starsiho klienta, jiz neaktualni.
