### ISSUE TITLE
Problém s vyhledáním cizojazyčných překladů českých děl

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#436]
Narazili jsme při vyhledávání cizojazyčných titulů na jeden problém. Souvisí asi s řešením issue #236, kde šlo o to dostat ze hry české překlady cizích děl nevyhledáním titulů s (mods:language objectPart="translation").  Bohužel se teď nevyhledají ani opačně díla v cizím jazyce, přeložená z češtiny. Je možné tohle nějak ošetřit, nebo můžeme mít jen všechny překlady nebo žádné?

**Comment by luckajirku** [comment]
ještě dva příklady titulů nevyhledatelných přes jazyk:
od nás: http://kramerius4.svkhk.cz/search/handle/uuid:83f29b9c-6c0e-46b6-8e47-196bfe7f77ec
z KNAV: http://kramerius.lib.cas.cz/search/handle/uuid:cfbc9bc7-8f4f-4223-9baf-73e392137237

**Comment by LenkaDamborska** [comment]
Rádi bychom tento problém oživili. Vypadá to, že při reindexaci dokumentu zmizí ze SOLRU úplně celé pole <arr name="language"> a pak není dokument vyhledatelný podle jazyka. Cílem issue #236 mělo být to, že když má dokument v MODS u jazyka atribut "translation", tak tento jazyk se do indexu nedostane. V MODS element language obsahuje dvakrát subelement languageTerm, kdy v každém je ten příslušný jazyk originálu a jazyk překladu. Do SOLRU se oba jazyky vloží bez rozdílu do jednoho pole pro language a po reindexaci to pole úplně zmizí, takže už tam není žádný jazyk. Ani jedno řešení není uspokojivé, pokud chceme vyhledat pouze knihy, které jsou psané v určitém jazyce bez ohledu na to, že to jsou překlady nebo díla v původním jazyce.

Posílám názorné ukázky - uuid:9d63a020-341f-11e4-8e0d-005056827e51:
MODS (jazyk čeština, překlad z ruštiny): http://kramerius.mzk.cz/search/api/v5.0/item/uuid:9d63a020-341f-11e4-8e0d-005056827e51/streams/BIBLIO_MODS
SOLR před reindexací (jazyky čeština a ruština): 
[solr_jazyk_puvodni.pdf](https://github.com/ceskaexpedice/kramerius/files/892674/solr_jazyk_puvodni.pdf)
SOLR po reindexaci (žádný jazyk): http://kramerius.mzk.cz/search/api/v5.0/search?q=PID:%22uuid:9d63a020-341f-11e4-8e0d-005056827e51%22

U těch dvou příkladů, co posílala @luckajirku, jazyk v SOLRU taky nebude.

Dá se tento problém vyřešit jiným způsobem, než jak to bylo vyřešeno v #236 ? Informace o  jazyku dokumentu by měla v Solru rozhodně zůstat.

**Comment by zabak** [comment]
K tomu ještě procesní záležitost: Issue #236 bylo opraveno a zavřeno. Nebylo tam napsáno nic ve smyslu "Opraveno, teď ještě musíte přeindexovat všechny věci, kterých se problém týká". Navíc by bylo vhodné toto issue před zavřením nechat otestovat toho, kdo issue zadal.

**Comment by pavel-stastny** [comment]
Chyba v predeslem komitu.  Nyni se pri indexaci berou v uvahu elementy: 

1. Nemaji zadny atribut `objectPart`
2. Ty, ktere maji hodnotru atributu `objectPart` ruznou od `translation`
