### ISSUE TITLE
Opakování výsledků

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#443]
Zobrazené výsledky vyhledávání (např. když vyhledám všechny monografie) se po deseti řádcích začnou opakovat stále dokola. Opakování nastává až od dvanáctého řádku výsledků.
Děje se to pouze ve Firefoxu a v Chromu. V Exploreru se to nestalo.

**Comment by filak** [comment]
Toto se mi nejak reprodukovat nedari, ani u vas 5.3.3 ani u nas 5.3.4. Deje se to tedy v search nebo client rozhrani?

**Comment by slapakovai** [comment]
Verze 5.3.4 v rozhraní client. Teď jsem to zkoušela a děje se to pořád.

**Comment by vlahoda** [comment]
Zkoušel jsem cdk.lib.cas.cz/client i kramerius.lib.cas.cz/client z Firefoxu i Chrome a žádné opakování výsledků jsem nezaznamenal.

**Comment by krizovj** [comment]
Také jsem to znovu zkoušela a pořád se to opakuje, zkusila jsem udělat hodně zmenšený screenshot, je to tam vidět na těch barevných obálkách
![opakovani](https://cloud.githubusercontent.com/assets/21309201/19433122/b73a2fc6-945f-11e6-926e-818693839e45.jpg)

 A takhle se opakují třeba 3x a když sjedu na konec tak se teprve začnou načítat další výsledky.

**Comment by filak** [comment]
No jo, uz to taky vidim.

**Comment by slapakovai** [comment]
Problém stále přetrvává, prosím o opravu. Verze 5.3.6

**Comment by pavel-stastny** [comment]
Bude reseno v pristim verzi.
