### ISSUE TITLE
editor částí - řazení ročníků

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#445]
Pokud je potřeba setřídit ročníky periodika v editoru částí, tak je trochu problém s tím, že se v něm
nezobrazují čísla ročníku, tzn. element "mods:partNumber86/mods:partNumber".
Takže setřídit ručně titul, kde je třeba 100 ročníků je v podstatě neřešitelný problém.

Jde hlavně o postupné doimporty, pokud je titul kompletní (což stejně většinou není), tak je samozřejmě setříděný v ProArcu. Někdy se totiž stane, ze v Krameriovi se to po doimportu cele rozsype a nejde to setřídit automaticky a člověk to potřebuje setřídit ručně.

**Comment by pavel-stastny** [comment]
Editor částí již není součástí release.

**Comment by pavel-stastny** [comment]
Ještě doplním, že editace pořadí titulů je nyní v admin prostředí součástí editace sbírek, počítá se s tím, že stejná komponenta bude použita pro jakýkoliv objekt (nejenom sbírku)
