### ISSUE TITLE
řazení ročníků periodik v Krameriovi od nejnovějších

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#447]
Bylo by možné řadit periodika od nejnovějších ročníků po nejstarší. Zdá se nám, že uživatele nejspíš zajímají právě ty nové ročníky, takže by měly být seřazené jako první.
Čísla i stránky by se pořád řadili stejně - od jedničky.
Šlo by to udělat např. jako volbu řazení v editoru částí?

**Comment by zabak** [comment]
Toto by měl být přepínač, který si volí uživatel. A bylo by fajn, aby si systém pamatoval, že si uživatel toto nastavení přepnul. V uživatelském rozhraní  klasicky šipečka nahoru nebo dolů na vhodném místě.

**Comment by slapakovai** [comment]
S přepínačem pro uživatele souhlasím. Zároveň bych to ale chtěla nastavovat i jako admin a seřadit si časopisy od nejnovějších.

**Comment by zabak** [comment]
Vyřešeno v novém klientovi
