### ISSUE TITLE
Dotaz mj. na OCR a logy

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#450]
Třída LoadCustomViewObject vyhazuje výjimku při pokusu o přístup uživatele s nedostatečnými právy k chráněným datastreamům digitálních objektů. Kramerius takovou výjimku řeší výpisem stack trace do logu.
Protože k pokusu o načtení OCR dochází okamžitě při otevření jakéhokoliv dokumentu, jsou logy Krameria zaplavené hromadou stack traců a to výrazně komplikuje ladění skutečných problémů.

Kramerius tak řeší většinu výjimek - místo logování užitečných údajů (aspoň uuid problémového dokumentu) vypisuje dlouhý stack trace bez jakékoliv další informace.

**Comment by pavel-stastny** [comment]
Nyni se pri SecurityException loguje
- Typ akce
- PID objektu (pokud to byl pozadavek READ, PRINT,PDF) 
- STREAM (pokud byl pozadovany nejaky konkretni stream)
