### ISSUE TITLE
Vyhledávání podle signatury

### ISSUE THREAD

**Issue by FoxKyong** [ceskaexpedice/kramerius#452]
Bylo by možné přidat do pokročilého vyhledávání taky možnost hledat podle signatury? Celkem by se to hodilo, jelikož se podle toho často vyhledává.

**Comment by pavel-stastny** [comment]
Dobry den, 
nevime jestli je signatura soucasti dat. Kde se nachazi?  Mate nejaky priklad?

**Comment by pavel-stastny** [comment]
Jedna se o nasledujici element? 
```
<mods:location>
  ...
   <mods:shelfLocator>III 78.107</mods:shelfLocator>
</mods:location>
```

**Comment by FoxKyong** [comment]
Jj, to je ono.

**Comment by Drahotussky** [comment]
Dobry den,
pokud by se zjistilo, ze je mozne rozsirit vyhledavani podle signatury,
radi bychom, pokud by se mohlo vyhledavat i podle sigly instituce,kde je
dokument ulozen.
Digitalizujeme i pro jine pamertove instituce a hodilo by se jim moct si
vyfiltrovat sve knihy.

Jedna se o element

<mods:location>
  ...
   <mods:physicalLocation>OSA001</mods:physicalLocation>
</mods:location>


Dekuji


S pozdravem


Ales Drahotussky,MSVK Ostrava


2016-11-29 12:20 GMT+01:00 Pavel Šťastný <notifications@github.com>:

**Comment by pavel-stastny** [comment]
Bude zahrnuto v nasledujicim buildu, nicmene vyzaduje reindexaci dat aby se to projevilo.
