### ISSUE TITLE
Změna jazyka

### ISSUE THREAD

**Issue by honzaskopal** [ceskaexpedice/kramerius#453]
Pokud se přepnu do jiného jazyka, např. z cz do en, neupraví se na hlavní stránce informace pod vyhledávacím polem, zůstanou v původním jazyce, obnoví je až aktualizace stránky.

**Comment by krizovj** [comment]
Stejné je to u textu, který se zobrazuje, když nejde o veřejný dokument.

**Comment by honzaskopal** [comment]
Procházím-li dokument, nepřeloží se popisky prvních tří navigačních tlačítek pod metadaty (opustit, další, předchozí strana). Přeloží se až při obnově stránky.

**Comment by pavel-stastny** [comment]
Reseno komitem  0e4ed9 . Bude pritomno v pristim buildu.
