### ISSUE TITLE
Dostupnost v angličtině

### ISSUE THREAD

**Issue by honzaskopal** [ceskaexpedice/kramerius#455]
Zelený nebo červený roh dokumentu značící dostupnost zobrazí po najetí myši nápovědu v angličtině (public, private) bez ohledu na jazyk, ve kterém je aktuálně Kramerius zobrazen. Bylo by možné doplnit i českou verzi?

**Comment by pavel-stastny** [comment]
Zahrnuto do pristiho buildu.
