### ISSUE TITLE
Oddělení hledání v dokumentu a v celém Krameriovi

### ISSUE THREAD

**Issue by honzaskopal** [ceskaexpedice/kramerius#457]
Když hledám přes hlavní vyhledávací pole, najdou se i výsledky, které jsou obsaženy v konkrétním dokumentu a označí se také. Bylo by možné oddělit hledání v názvech dokumentů a v obsahu dokumentů?

**Comment by slapakovai** [comment]
Prosím o bližší popsání, o co se jedná? Nějak to z popisu issue nechápu.

**Comment by honzaskopal** [comment]
Upřesnění - např. pokud vyhledám "Knihy a dějiny" v clientovi Knihovny AV ČR, otevřu si ve výsledcích vyhledávání periodikum s tímto názvem, označí se černým orámováním ty výtisky, ve kterých je hledaný výraz obsažen. Po otevření určitého článku v označeném výtisku, zobrazení odskočí až na druhou nebo třetí stranu, jelikož je výraz "knihy a dějiny" v jejím záhlaví, to může uživatele zmást. Týká se to zřejmě jen vícestránkových článků v PDF.

**Comment by krizovj** [comment]
Souviselo s klientem K5, zavřít prosím
