### ISSUE TITLE
SOLR 6 - podpora

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#458]
Podpora nového solru

**Comment by MartinRumanek** [comment]
Bude zdokumentováno co migrace na SOLR 6 obnáší?

**Comment by pavel-stastny** [comment]
Bude zdokumentovano.

**Comment by pavel-stastny** [comment]
Dokumentace k prechodu https://github.com/ceskaexpedice/kramerius/wiki/P%C5%99echod-na-novou-verzi-SOLR

**Comment by MartinRumanek** [comment]
Díky, podařilo se mi to rozběhat na našem testovacím prostředí a je to funkční.

Migrace indexu zpracuje cca 2000 dokumentů za minutu.
