### ISSUE TITLE
Issue 638:	Zjednodušení úprav UI

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#46]
Reported by jirku.lucka, Dec 11, 2013
Bylo by možné pro další verze uvažovat o předělání tak, aby alespoň základní úpravy vzhledu šlo provést změnami pouze v jediném souboru (styles.css?), aby při každé aktualizaci nebylo nutné opětovně upravovat x souborů? 

Teď když chci aspoň trochu sladit vzhled K4 se stylem knihovny – OK, vyměním obrázky (hlavička, logo, lupy, podklad pod písmena v abecedě, ikona). Úprava tématu jQuery zmíněná na wiki by mohla být fajn, ale tím změním vzhled jen té neutrální šedé části, nezbavím se tím té porůznu se objevující oranžové. Celkem tam jsou 4 odstíny, kromě té „hlavní“ #e66c00 ještě #ffcc66, #ef6001 a #e75c01 (u podkladu ten jiný (světlejší) odstín asi smysl má, u ostatních mi použití nepatrně jiného odstínu přijde spíš jako nedopatření). Pro výměnu všech oranžových za knihovní barvy tak musím upravit soubory: 

search/css/styles.css
search/css/autocomplete.css
search/css/dateAxisV.css
search/css/layout-default-latest.css
search/inc/usedFilters.jsp
search/inc/results/results.jsp
search/inc/home/info.jsp
search/inc/details/fullViewer.jsp
search/inc/details/zoomifyFullViewer.jsp
search/inc/details/tree.jsp
search/inc/details/contextMenu.jsp
search/inc/details/thumbs.jsp
search/inc/admin/_processes_outputs.jsp
search/inc/admin/_processes_logs.jsp
search/inc/admin/_processes_data.jsp
search/inc/admin/_indexer_data.jsp
search/inc/admin/_change_flag.jsp

Šlo by to v nějaké budoucí verzi zjednodušit? 

Lucie Jirků
SVK HK

Dec 11, 2013 Delete comment Project Member #1 vlahoda
Ano, v připravované verzi K5 bude struktura jiná a jednodušší.
Status: OnHold

**Comment by pavel-stastny** [comment]
Tyka se admin rozhrani - bude v pristim roce reimplementovano
