### ISSUE TITLE
Logování výjimek

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#461]
V issue https://github.com/ceskaexpedice/kramerius/issues/450 jsem popisoval problém se zaplavením logu mj. hláškami z LoadCustomViewObject - v nové verzi se sice už vypisuje akce + pid + datastream, ale SecurityException pořád není správně chytaná a v logu se vypisuje celý stack trace. 
Navíc jde běžnou součást běhu krameria, ale přesto se to loguje na úrovni SEVERE.

Největší problémy zaplavující logy jsou:
1. neodchytávání SecurityException a logování jako SEVERE místo INFO.
2. to samé u BenevolentMovingWall - při neočekávaném znaku v datu vydání vyskočí stack trace na úrovni SEVERE. Tohle by nejspíš měl být WARNING a měla by se logovat jen zpráva obsahující uuid daného objektu. Viz https://github.com/moravianlibrary/kramerius/issues/145

V krameriu MZK se tyhle případy objevují řádově desetitisíckrát denně.

**Comment by pavel-stastny** [comment]
> 1. neodchytávání SecurityException a logování jako SEVERE místo INFO
Security exception se odchytavala ale logovala i se stacktracem. Nyni se vypisuje jenom zprava v urovni INFO.

> 2. to samé u BenevolentMovingWall - při neočekávaném znaku v datu vydání vyskočí stack trace na úrovni 
Opet se vypisoval i stacktrace. Nyni jenom zprava a uroven WARNING

**Comment by Jenyk** [comment]
Díky za rychlou opravu :)
