### ISSUE TITLE
Editor částí nefunguje

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#462]
V Editoru nelze nic načíst - ani přes PID ani přes hledání - výjimka:

Spojení se serverem selhalo: java.lang.IllegalArgumentException: URI is not absolute 

Verze 5.3.4

**Comment by slapakovai** [comment]
V KNAV normálně funguje.

**Comment by filak** [comment]
Nemohl by me alespon nekdo nasmerovat, zrejme je to vec nastaveni, kdyz to jinde funguje.

**Comment by filak** [comment]
OK. Z nejakeho neznameho duvodu jsem mel v configuration.properties nastaveny relativni api.point

#api.point=/search/api/v5.0
api.point=http://localhost:8084/search/api/v5.0

Prenastaveni zda se pomohlo. Zaviram tedy.
