### ISSUE TITLE
PDFBox - chybně se bere první číslovaná strana nikoli první strana PDF dokumentu

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#463]
Zkusil jsem zaindexovat [PDF dokument](https://github.com/filak/k5-test-pdfbox/blob/master/002.pdf) v nové verzi s PDFBox 2 a vypadá to, že se extrahuje první číslovaná strana (1) nikoli první strana dokumentu (obálka).

**Comment by filak** [comment]
Mohl by to (https://github.com/filak/k5-test-pdfbox/blob/master/002.pdf) prosim nekdo zkusit zaindexovat, jaky vam to udela ten nahled?

**Comment by slapakovai** [comment]
Trvá stále ještě tenhle problém?

**Comment by filak** [comment]
Máme zatím pouze verzi 5.3.4 a tam tato chyba přetrvává.
