### ISSUE TITLE
editor uživatelů - odesláným emailům chybí hlavička "From"

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#464]
I když je v mail.properties definována properti mail.from, tak email o vytvoření účtu v editoru uživatelů nemá hlavičku "From". Což je docela problém, protože některé emailové servery takové emaily nedoručí (gmail) a další je hází do spamu.

REASON550 5.7.1 [50.31.49.42 11] Our system has detected that this message is not RFC 5322 compliant: 'From' header is missing. To reduce the amount of spam sent to Gmail, this message has been blocked. Please visit https://support.google.com/mail/?p=RfcMessageNonCompliant and review RFC 5322 specifications for more information. t128si19677701oig.117 - gsmtp 

Souvisí s #444.

Mimochodem když už ten email příjde, tak vypadá nějak takhle:

Předmět: Vygenerované heslo
Tělo:
Vážený uživateli systému Kramerius,
pro Vaše přihlašovací jméno blabla bylo vygenerováno heslo XOjW49gL

Takže tam chybí zásadní informace jako url konkrétní instance Krameria. Natož nějaká možnost šablony, aby bylo možné vytvořit uživatelsky přijatelnější email s odkazem do konkrétního Krameria, nějakým dalším popisným textem a případně lokalizovanými verzemi emailů.

**Comment by vlahoda** [comment]
Chybějícího odesilatele doplním v příští verzi. Obsah a předmět mailu je možné měnit pomocí lokalizačních klíčů mail.message a mail.subject v label.properies, deafultní hodnoty jsou: 
mail.message=Vážený uživateli systému Kramerius,\n pro Vaše přihlašovací jméno {0} bylo vygenerováno heslo {1}
mail.subject=Vygenerované heslo

**Comment by pavel-stastny** [comment]
https://github.com/ceskaexpedice/rightseditor/commit/28e77d2b09435156ec94bdfe7a6ec795ae526992

**Comment by rzeh4n** [comment]
Tohle se stále děje a nelze tak používat třeba Sendgrid.
V rightseditoru je sice opraveno (otestoval jsem), ale problém je v tom, že se k distribuci Krameriua přibaluje stará verze rightseditoru - 5.1.0 z 12. 3. 2015. A několik posledních commitů se tak nezohledňuje. 
Šlo by rightseditor zvýšit na třeba 5.1.1 a závislost na něm v build.gradle krameria? Tak by se při příštím přípravě releasu nechytala starší verze rightseditoru.

**Comment by vlahoda** [comment]
aktualizoval jsem verzi rightseditoru v projektu ceskaexpedice/rightseditor na 5.1.1 (v pom.xml) i odpovidajici zavislost v build.gradle krameria v branchi kramerius5. pristi (posledni planovany)release K5 tedy snad bude ok. a v K7 uz doufam ani editor ani rightseditor nebudou
