### ISSUE TITLE
K5 client - nezobrazuje se kontext (levý panel) u PDF dokumentů

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#465]
Pokud už se podaří zobrazit dokument s PDF (#449), tak se nezobrazuje kontext-levý panel, např. zde:
http://kramerius.medvik.cz/client/index.vm?page=doc#uuid:3a3d7241-bc48-4f22-80a6-15855c45694b
(číslo je po jednotlivých PDF článcích + má článková metadata) Není tedy způsob, jak se na další části doklikat.

Přitom na Digitalniknihovna.cz a v Search rozhraních se to číslo zobrazuje správně:
http://www.digitalniknihovna.cz/nlk/uuid/uuid:3a3d7241-bc48-4f22-80a6-15855c45694b
http://kramerius.medvik.cz/search/handle/uuid:MED00011026-51189480-564f-44e7-b0e6-7cf1d4c21bb8

Projevuje se to nejen u čísel časopisů, ale i monografií, například:
http://kramerius.medvik.cz/search/handle/uuid:MED00113139
http://www.digitalniknihovna.cz/nlk/uuid/uuid:1a8bec8d-ffa2-11e4-ac0f-d485646517a0
http://kramerius.medvik.cz/client/handle/uuid:1a8bec8d-ffa2-11e4-ac0f-d485646517a0

**Comment by filak** [comment]
No tak jenom doufam, ze nove rozhrani bude fungovat v tomto smeru alespon stejne tak dobre jako Digitalniknihovna.cz

**Comment by slapakovai** [comment]
Nám se tahle chyba projevovala u PDF v předchozí verzi Krameria, teď už se to nestává. Můžeš sem prosím napsat, jestli problém stále ještě trvá a na jaké verzi Krameria jsi to zkoušel?

**Comment by filak** [comment]
Máme zatím pouze verzi 5.3.4 a tam tato chyba přetrvává.

**Comment by filak** [comment]
Vzhledem k tomu, ze se uz tesime na K6 klienta, tak toto asi muzeme zavrit.
