### ISSUE TITLE
Chybný údaj o počtu dokumentů

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius#466]
V klientu K4 se uvádí chybně počet dokumentů. Např. u jednostránkové mapy se objeví "2 dokumentů sbaleno" . Viz např. http://kramerius4.nkp.cz/search/r.jsp?language=cs&&offset=0&forProfile=facet&fq=model_path:map*
a zvolit jednostránkovou mapu, např http://kramerius4.nkp.cz/search/i.jsp?pid=uuid:fbc7ee40-2ecf-11e5-8851-005056827e51&q= což je Übersichtskarte von Europa. U map se dá počet dokumentů lehce kontrolovat, takže ta chyba je dost vidět. Bohužel to platí i o monografie a periodika. Např. monografie https://kramerius.svkul.cz/search/i.jsp?pid=uuid:fd42c8ac-b46a-49b2-9db5-6cee3ea006f8&q=&fq=model_path:monograph*  je tvořena 28 dokumenty, ale objeví se údaj "29 dokumentů sbaleno"

**Comment by slapakovai** [comment]
Dobrý den,
chybu se mi nepodařilo navodit. Můžete sem prosím přidat podrobnější popis nebo aspoň screenshot. Pokud si dobře vzpomínám, tak formulace "x dokumentů sbaleno" byla z Krameria odstraněna už před několika verzemi proto, že byla matoucí. Na jaké verzi Krameria jste to zkoušel?

**Comment by BrozekAles** [comment]
Dobrý večer,
přikládám screenshoty, snad z nich to bude jasné. Je to vidět např. na  
jednostránkové mapě "Belgie, Holandsko, Lucembursko", kde u prvního  
screenshotu se uvádí, že jsou 2 dokumenty sbaleny, ale mělo by být  
snad 1 dokument sbalen, když je to jednostránková mapa. Osobně mi tato  
chyba nevadí, nejsem takový hnidopich. Mně vadí spíše, když nefungují  
některé funkce vyhledávání, jak jsem psal včera večer...
Zdravím
__________________________________________________

			 - Ing. Aleš Brožek
  m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045 f: + 420 475 200 045
  e: knihovna@svkul.cz
  w: www.svkul.cz
----------------původní zpráva-----------------
Od:slapakovai [notifications@github.com ]
Komu:"ceskaexpedice/kramerius" [kramerius@noreply.github.com ]
Kopie:BrozekAles [brozek@svkul.cz ], Author [author@noreply.github.com ]
Datum:Thu, 27 Apr 2017 02:57:37 -0700
----------------------------------------------------------

**Comment by BrozekAles** [comment]
Ještě posílám ty přílohy :-)

__________________________________________________

			 - Ing. Aleš Brožek
  m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045 f: + 420 475 200 045
  e: knihovna@svkul.cz
  w: www.svkul.cz
----------------původní zpráva-----------------
Od:"Ing. Aleš Brožek" [brozek@svkul.cz ]
Komu:"ceskaexpedice/kramerius"  
[reply@reply.github.com ], "ceskaexpedice/kramerius" [kramerius@noreply.github.com ], slapakovai [notifications@github.com  
]
Kopie:Author [author@noreply.github.com ]
Datum:Thu, 27 Apr 2017 21:23:31 +0200
----------------------------------------------------------
>
> Dobrý večer,
> přikládám screenshoty, snad z nich to bude jasné. Je to vidět např.  
> na jednostránkové mapě "Belgie, Holandsko, Lucembursko", kde u  
> prvního screenshotu se uvádí, že jsou 2 dokumenty sbaleny, ale mělo  
> by být snad 1 dokument sbalen, když je to jednostránková mapa.  
> Osobně mi tato chyba nevadí, nejsem takový hnidopich. Mně vadí  
> spíše, když nefungují některé funkce vyhledávání, jak jsem psal  
> včera večer...
> Zdravím
> __________________________________________________
>
> 			 - Ing. Aleš Brožek
> m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká
> knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona
> Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045 f: + 420 475 200 045
  e:
> knihovna@svkul.cz
  w: www.svkul.cz

**Comment by slapakovai** [comment]
Podle přiložených obrázků se jedná o starší verzi Krameria. V aktuální verzi už se tato formulace vůbec nezobrazuje, takže bych doporučila instalaci novější verze.
Jestli i potom problém přetrvá, tak můžete issue znovu otevřít.

**Comment by BrozekAles** [comment]
Přikládám obrázek nejnovější verze, tedy verze uzivane v CDK, kde  
stále ta chyba je - viz jednostránkové mapy. U které verze se to  
opravovalo? Zdravím

__________________________________________________

			 - Ing. Aleš Brožek
  m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045 f: + 420 475 200 045
  e: knihovna@svkul.cz
  w: www.svkul.cz
----------------původní zpráva-----------------
Od:slapakovai [notifications@github.com ]
Komu:"ceskaexpedice/kramerius" [kramerius@noreply.github.com ]
Kopie:BrozekAles [brozek@svkul.cz ], Author [author@noreply.github.com ]
Datum:Tue, 02 May 2017 06:22:54 -0700
----------------------------------------------------------

**Comment by slapakovai** [comment]
Tak to je otázka spíše na @pavel-stastny, jak a kde to zobrazení vlastně předělali?

**Comment by pavel-stastny** [comment]
Ne, ne.. toto souvisi s modelovanim dat.  Mapa ani stranka nejsou reprezentovany v k5 samostane, vzdy jsou soucasti nejakeho nadrazeneho objektu. 
Ten je samostatne indexovan a obsahuje sva vlastni metadata (ktera samozrejme taky vstupuji do vyhledavani).

Uvedu to na zminene monografii: 

Odkaz na celou monografii 
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:fd42c8ac-b46a-49b2-9db5-6cee3ea006f8

Metadata (ale pouze k monografii): 
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:fd42c8ac-b46a-49b2-9db5-6cee3ea006f8/DC
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:fd42c8ac-b46a-49b2-9db5-6cee3ea006f8/BIBLIO_MODS

Dotaz na stranky monografie: 
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:fd42c8ac-b46a-49b2-9db5-6cee3ea006f8/children

Dotaz na prvni stranku 
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:5a0b80cc-0ac0-11e5-9428-001b63bd97ba

A metadata prvni stranky 
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:5a0b80cc-0ac0-11e5-9428-001b63bd97ba/DC
https://kramerius.svkul.cz/search/api/v5.0/item/uuid:5a0b80cc-0ac0-11e5-9428-001b63bd97ba/BIBLIO_MODS

Vyhledani a sbaleni dokumentu vypada tak, ze se seskupi vysledky dle sveho rodice a do celkoveho poctu je zapocitavan i ten. U monografie  to budou jednotlive stranky + samotny objekt monografie.  
Analogicky to je  u dalsich modelu/titulu  ("Periodical", "PeriodicalItem","PeriodicalIssue", "Monograph", "MonographUnit", atd... ).
