### ISSUE TITLE
Spojení do DB

### ISSUE THREAD

**Issue by Jenyk** [ceskaexpedice/kramerius#467]
Roste nám počet otevřených spojení do databáze krameria až po maximální hranici, kdy databáze přestane přijímat nová spojení, kramerius přestane reagovat a je potřeba ho restartovat.
Za poslední 2 týdny k tomu došlo 7x.

Sledujeme průběžně počty aktivních spojení a to číslo nikdy neklesá. Jak je v krameriu řešené zavírání spojení do DB?

**Comment by pavel-stastny** [comment]
Pri jakych operacich se to deje ?

**Comment by Jenyk** [comment]
To právě nevím, ale počet spojení měřený každých 5 minut neklesá nikdy.

Z otvírání nových spojení podezírám error 
SEVERE [http-nio-8080-exec-34] cz.incad.kramerius.statistics.impl.DatabaseStatisticsAccessLogImpl.reportAccess ERROR: value too long for type character varying(2048)
(dál stacktrace)

Jdu otestovat zvětšení sloupce, ale jestli je to tím, tak by to spojení stejně nemělo zůstat viset.

**Comment by filak** [comment]
Vždy když Kram. běží několik dní, tak se "namnoží" postgres procesy, na našem serveru odhadem tak celkem 100.

SELECT datname, count(*) as cnt  
    FROM pg_stat_activity
    WHERE
      datname in ('kramerius4','fedora3','riTriples') 
      AND pid <> pg_backend_pid()
      AND state = 'idle'
      AND state_change < current_timestamp - INTERVAL '30' MINUTE
    group by datname;

Aktuálně na každou z uvedených bází připadá tak 30 idle konekcí.

**Comment by filak** [comment]
Aha, tak nam tam zustavaji konekce po restartu Tomcatu, coz bude jiny pripad.

**Comment by pavel-stastny** [comment]
Dobry den, 
muzete vyzkouset zmenit velikost db sloupce  `requested_url` v tabulce `statistics_access_log`   na nejakou vetsi hodnotu ?

**Comment by Jenyk** [comment]
Zdravím, přesně to jsem včera udělal, ale nezdá se, že by to pomohlo.
Uvedený error se od té doby neobjevil, ale počet spojení se stejně od včerejšího restartu v 15:20 postupně vyšplhal na aktuálních 71, ze kterých 58 má stav idle.

**Comment by pavel-stastny** [comment]
A muzete zjistit, kolik konekci je pritomno v db poolu a pripadne o jakou databazi se jedna?

**Comment by Jenyk** [comment]
Máme postgresql 9.5, nastavení viz https://github.com/moravianlibrary/s2i-kramerius/blob/602e1a9b6892a4849aa24bbbbca345fc8767f9fe/search.xml

**Comment by pavel-stastny** [comment]
Nedari se reprodukovat.
