### ISSUE TITLE
Chybný návrat do výsledků vyhledávání

### ISSUE THREAD

**Issue by jandera** [ceskaexpedice/kramerius#469]
Možná se jedná o stejnou chybu jako tady [#402](https://github.com/ceskaexpedice/kramerius/issues/402) Dobře je to vidět např. při vyhlednání "zalužanský" - 297 výsledků vyhledávání, pokud se otevře poslední výsledek "Rudé právo - 1975" tak po návratu do výsledků je vidět pouze posledních 17 a to jak tlačítkem "Opustit dokument" tak tlačítkem prohlížeče "Zpět". Obdobně se to chová ale kdekoli po scrollování a načtení dalších výsledků vyhledávání.

**Comment by slapakovai** [comment]
Chybu se mi nepodařilo navodit. Můžu issue uzavřít, nebo se to ještě stává?

**Comment by jandera** [comment]
Chybu jsem bezproblémů navodil, stále se to děje.

**Comment by slapakovai** [comment]
Navození chyby:
1. zadat dotaz
2. scrollovat až dolů ve výsledcích vyhledávání (načte se několik stránek)
3. kliknout na jakýkoliv výsledek vyhledávání
4. opustit otevřený dokument -  buď kliknutím na zpět nebo kliknutím na opustit dokument
5. načte se jenom prvních pár výsledků vyhledávání (okolo pěti výsledků) a ty další výsledky už nelze načíst, ani nelze schrollovat dolů.

**Comment by pavel-stastny** [comment]
Tyka se starsi verze klienta. Jiz neaktualni. Zaviram.
