### ISSUE TITLE
Zahlcení tabulky session_keys

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#475]
Hromadí se nám záznamy v tabulce `session_keys`, důsledkem je pak rapidní zpomalení přihlášení do Krameria.

Pomáhá `TRUNCATE session_keys CASCADE`, nicméně záznamy v tabulce se nám za poslední týden hromadí rychlostí cca 3M záznamů denně.

Momentálně z 20.609.336 záznamů v tabulce má 20.609.016 hodnotu active nastaveno na '1' a pouze 116 na '0', přičemž active je nastavený i u záznamů z 13.12.2016, které již určitě aktivní nejsou.

**Comment by pavel-stastny** [comment]
Chyba opravena, session_keys se uz nehromadi.

**Comment by MartinRumanek** [comment]
Problém to nicméně řeší pouze částečně, bylo by dobré vyřešit https://github.com/ceskaexpedice/kramerius/issues/246

Např. tento snippet kódu začne generovat další a další session do tabulky:

```
#!/bin/sh

while true; do
  curl -u krameriusAdmin:* -X GET http://kramerius.mzk.cz/search/api/v5.0/info
done
```
