### ISSUE TITLE
Procházet - chybí překlad do angličtiny

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#481]
Ve funkci "Procházet" je hláška vedle vyhledávacího pole "Hledej v názvech a autorech" pouze v češtině. Při přepnutí do anglické verze (i po obnovení) zůstává česky.

**Comment by slapakovai** [comment]
Taky slova "Názvy" a "Autoři" v procházení jsou pouze česky bez překladu.
