### ISSUE TITLE
Zobrazování názvu dokumentů na hlavní straně

### ISSUE THREAD

**Issue by honzaskopal** [ceskaexpedice/kramerius#483]
Na hlavní stránce Krameria Knihovny akademie věd ČR, se špatně zobrazují názvy dokumentů v záložkách (Vybrané, Nejnovější, Nejžádanější). Zobrazí se číslo nebo typ strany místo názvu dokumentu, na který náhled odkazuje.

**Comment by krizovj** [comment]
Zavřít prosím - u klienta K6 už to není aktuální
