### ISSUE TITLE
řazení čísel obsahujících přílohu

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius#486]
Pokud obsahuje číslo přílohu, nelze čísla setřídit ani ručně srovnat v editoru částí. Automaticky se čísla obsahující přílohu předřadí před čísla bez přílohy. V editoru částí se potom čísla obsahující přílohou nezobrazí v záložce Issues ale pouze v záložce Internal parts - nelze je tedy rovnat ani ručně. K problematice řazení příloh jsem zaznamenal #426 a #94, nicméně v nich šlo, jestli se nemýlím, pouze o problematiku řazení samotných příloh, nikoliv čísel, která přílohy obsahují.

Příklad: http://kramerius4.nkp.cz/search/handle/uuid:7a18c630-fa27-11e4-8ded-5ef3fc9ae867

**Comment by vlahoda** [comment]
Problém je způsoben nesprávnou strukturou dat  - když se v uvedeném periodiku podíváte do datastreamu RELS-EXT ročníku 1878  (uuid:7a18c630-fa27-11e4-8ded-5ef3fc9ae867), RDF vazby na ta čísla s přílohami jsou typu hasIntCompPart, zatímco vazby na čísla bez příloh jsou typu hasItem. Proces třídění zpracovává každý typ vazeb zvlášť a editor součástí pro každý typ vazeb zobrazuje samostatnou záložku. Použijte tedy pro všechna čísla stejný typ vazby hasItem.
