### ISSUE TITLE
funkce aplikuj pohyblivou zeď nevyhodnotí mods:dateIssued

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#489]
Při použití funkce aplikuj pohyblivou zeď na periodikum, které obsahuje data ze Siria i z ProArcu se vyhodnotí a zpřístupní pouze čísla, která obsahují element mods:date. Čísla, která obsahují mods:dateIssued se nezpřístupní.
Lze vyzkoušet na na datech z KNAV - např. Nový Orient, ročník 1990 - čísla 1-5 se zpřístupní správně, číslo 6 se nezpřistupní a musím policy nastavit ručně.

**Comment by pavel-stastny** [comment]
Proce jiiž b K7 není přítomen
