### ISSUE TITLE
Špatné zobrazování metadat v novém rozhraní

### ISSUE THREAD

**Issue by honzaskopal** [ceskaexpedice/kramerius#490]
V  clientovi Krameria Knihovny AV ČR se v některých případech zobrazuje v metadatech Title i SubTitle a někdy pouze Title. Příkladem je Nový Orient rok 1991 č. 3 (Title i SubTitle) a 2004 č. 1 (pouze Title).

**Comment by pavel-stastny** [comment]
Tyka se stareho rozhrani.
