### ISSUE TITLE
Nezobrazování obrázků

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#492]
Dobrý den,
narazili jsme na problem se nezobrazovanim celeho rocniku 1899 novin Ostravsky obzor (jde o titul s konvertovanymi obrazky z DjVu). Ostatni rocniky jsou v poradku.
Obrazky se nedari zobrazit ani pres rozhrani Fedory.

Dari se mi jen ziskat hlaseni:
Failed to load resource: the server responded with a status of 404 (Not Found)

Mixed Content: The page at 'https://camea2.svkos.cz/search/i.jsp?pid=uuid:90c54bf0-0272-11de-b2f2-0013d398622b&q=' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:9080/search/api/v5.0/item/uuid:90c54bf0-0272-11de-b2f2-0013d398622b?_=1488957478079'. This request has been blocked; the content must be served over HTTPS.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

https://camea2.svkos.cz/search/zoomify/uuid:e4cb2500-04af-11de-9af2-0013d398622b/ImageProperties.xml?_=1488957484102 Failed to load resource: the server responded with a status of 400 (Bad Request)

Muzete nam prosi poradit?

P.S. Zkusil jsem dany rocnik smazat z Fedory a znovu naimportovat, ale nepomohlo to. Samotne obrazky DjVu se v pocitaci pres plugin zobrazi.

Dekuji

A. Drahotussky

**Comment by filak** [comment]
Co mate nastavene v property api.point v configuration.properties ?

Jinak ta mixed content chyba se vam objevuje u vsech dokumentu.

**Comment by Drahotussky** [comment]
V configuration.properties bohuzel nevidim nic jako property api.point. Jsou tam udaje o pristupu do Fedory, spustenych procesich, indexovani, ...
Muzete prosim napsat, jak by mel zapis v property api.point podle Vas vypadat? 
Dekuji

**Comment by filak** [comment]
https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/client/src/main/resources/res/configuration.properties

tedy:
k4.host=http://localhost:8080/search
api.point=${k4.host}/api/v5.0

Nebo pouze:
api.point= http://localhost:8080/search/api/v5.0

**Comment by Drahotussky** [comment]
Nic takoveho tam nevidim.
Jedine,co se tomu vzdalene podoba je:

_fedoraTomcatHost=http://localhost:9080
_solrTomcatHost=http://localhost:9080

**Comment by filak** [comment]
No tak si to tam zkuste nastavit.

**Comment by Drahotussky** [comment]
Myslite, ze to by melo pomoci zobrazit obrazky?

**Comment by vlahoda** [comment]
Problém je způsoben tím, že se v jedné stránce míchají URL s http a https. Pokud na stránku přistoupíte přes URL http://camea2.svkos.cz/search/i.jsp?pid=uuid:90c54bf0-0272-11de-b2f2-0013d398622b&q=, obrázky se zobrazí. Pokud byste chtěli používat přístup přes https, musíte přes https přesměrovat i všechny dotazy na API Krameria - k tomu slouží právě property api.point, která je defaultně odvozena od property _fedoraTomcatHost. V tuto chvíli vám ale https stejně nefunguje, na serveru camea2.svkos.cz je neplatný certifikát.

**Comment by Drahotussky** [comment]
O certifikatu vim, ten se resi.
I kdyz jdu na stranku pres http, tak v rocniku 1899 se stale obrazky nezobrazi, zatimco v ostatnich rocnicich ano.

**Comment by pavel-stastny** [comment]
Link http://camea2.svkos.cz/search/img?uuid=uuid:e4dbede0-04af-11de-96d1-0013d398622b&stream=IMG_THUMB&action=GETRAW haze chybu 500. Objevi se neco v logu tomcatu ?

**Comment by slapakovai** [comment]
@Drahotussky Prosím o zprávu, jestli problém ještě trvá nebo jestli se Vám podařilo ho vyřešit.

**Comment by filak** [comment]
hodnotu api.point je IMHO potřeba nastavit - vizte:
https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/client/src/main/resources/res/configuration.properties
a
https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/client/src/main/resources/cz/incad/kramerius/client/tools/k5client.properties

**Comment by filak** [comment]
@Drahotussky  - a ještě jak píšete "zkonvertované z DjVu" - obrázky ve formátu DjVu je třeba mít zkonvertované na JP2000 nebo alespoň Jpeg

**Comment by Drahotussky** [comment]
Dobry den,
problem stale trva. Zkouseli jsme pouzit navrhy z 28.3 jak ohledne https,
tak s nastavenim api.point.

Obrazky jsou zkonvertovane do jpg.





2017-04-27 13:34 GMT+02:00 filipk <notifications@github.com>:

**Comment by pavel-stastny** [comment]
Dobrý den, 

jedná se o problém s konkrétní instalací (a  konkrétního nastavení). Bez znalosti toho, co a jak bylo nainstalováno, případně přístupu na server, nedokážeme problém nasimulovat a ani poradit. 

Issue zavírám.
