### ISSUE TITLE
Výběr adresáře v Import FOXML

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#493]
Při opakovaném zadávání importu FOXML se rozbije widget pro výběr adresáře, který sice zobrazí adresářovou strukturu importní složky, nicméně při kliknutí na konkrétní adresář se neupraví adresa v Parametrech procesu.

**Comment by slapakovai** [comment]
Potvrzuji problém, taky se mi to stává. Dočasné řešení je před opakovaným importem refreshovat stránku.
