### ISSUE TITLE
Issue 221:	Vícenásobný výběr z facetů ("multisearch")

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#5]
Reported by vlahoda, Dec 6, 2011
Ve výsledcích vyhledávání by mělo být možné filtrovat podle více hodnot ze stejného facetu (např. více autorů). Facety by možná měly být zobrazeny i při jediné hodnotě?

Jul 25, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: Started 
Owner: pavel.stastny 
Jul 25, 2012 Delete comment Project Member #2 vlahoda
(No comment was entered for this change.)
Cc: alberto.en.vlasim 
Jul 4, 2013 Delete comment Project Member #3 vlahoda
(No comment was entered for this change.)
Owner: alberto.en.vlasim 
Cc: -alberto.en.vlasim 
Jul 4, 2013 Delete comment Project Member #4 alberto.en.vlasim
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
uz neni aktualni
