### ISSUE TITLE
formulář před stažením originálu [enhancement]

### ISSUE THREAD

**Issue by JanHouserek** [ceskaexpedice/kramerius#500]
Dobrý den,

je možné implementovat, nejlépe konfigurovatelný (šablonu), formulář ke "stažení originálu", aby si uživatel mohl "originál" stáhnout po jeho vyplnění? 

Funkce by se nám hodila například kvůli formulářům k reprodukčním právům do publikací, které jinak kolegové musí posílat klasickou poštou a zakládat do šanonů.

Podobně jako to má Getty http://www.getty.edu/art/collection/objects/268461/attributed-to-the-rohan-master-or-immediate-circle-leaf-from-a-book-of-hours-french-about-1410-1430/

Děkuji.

Houserek
VKOL

**Comment by zabak** [comment]
Tohle by se nám taky hodilo, souvisí to opět s dostupností obrázku na imageserveru  - už je to několikáté issue za posledních pár dní na toto téma (#499, #495 a #497), tj. je potřeba to nějak smysluplně vyřešit.

**Comment by pavel-stastny** [comment]
Pro implementaci bude potreba zpresnit zadani. Predpokladam, ze se jedna o formu prav, kdy prava pro stazeni plneho originalu ma ten ktery vyplni formular (posle data).  Tento formular (v nejake forme) by mel byt pritomny ve vsech klientech (web, mobile) a API by nemelo umoznovat stazeni do te doby, dokud uzivatel nema vyplneno. Je to tak? 

Pokud ano, jakym zpusobem by se mela data na serveru prezentovat ci uchovavat?

**Comment by zabak** [comment]
A z hlediska GDPR ještě doplňující otázka - jaká data chceme archivovat? Getty se totiž ptá po způsobu využití, ale pustí to i když řeknu že jsem for-profit a chci to for-profit. Tj. oni nevědí kdo si to stáhl (nebo jen IP adresu apod) a slouží jim to jen ke statistickým účelům. Ale mám takové tušení, že toto všechny knihovny a muzea chtít nebudou. Pokud se za komerční využití vybírá tak bychom skončili u online e-shopu pro komerční využití a formuláře obdobného tomu co má getty pro ostatní účely. Jako důležitou věc tam vidím i tu citační informaci. 

Pokud by se šlo touto cestou, tak by celá tato volba musela být konfigurovatelná (povolit/nepovolit zobrazení odkazu na stažení) a pak zobrazit/nezobrazit při kliknutí na ten odkaz ten formulář a pak případně ještě konfigurace odchodu na platební bránu. Na serveru by se měl ukkládat jen jednoduchý  log typu čas, uuid, typ uživatele, typ využití. Ale myslím, že to bude vyžadovat rozsáhlejší průzkum toho, co si od toho knihovny slibují, aby to pak nebylo řešení pro jednu knihovnu. Možná že celá ta operace s formulářem ve skutečnosti není potřeba, protože získané údaje nikdo k ničemu nebude používat.

**Comment by zabak** [comment]
Tohle je především na klienta, ale @pavel-stastny má pravdu v tom, že by to znamenalo zavést další druh oprávnění - které by se dalo předávat dál i přes iiif authentication api. Navíc by to mělo vliv nejen na stahování obrázku ale i na výřezy a iiif api jako celek. Pokud by se implementovalo, navrhuji udělat to skrze iiif authentication api. 

@JanHouserek jaké informace chcete uchovávat? jak to řešíte z hlediska GDPR?

**Comment by pavel-stastny** [comment]
Myslim, ze issue je jiz neaktualni. Pokud ano, prosim, znovu otevrit.
