### ISSUE TITLE
SOLR migrace - prenaseni non stored poli

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#507]
Migracni proces neprenasi pocitana pole "browse_authors" a "browse_titles" a po preneseni indexu jsou zalozky autori a tituly prazdne.  (Pomuze reindexace dokumentu)

**Comment by mduda100871** [comment]
Po rucnim doplneni knihovny:

https://github.com/pavel-stastny/solrmigration/releases

do distribucniho balicku search.war (verze 5.3.6 stable) a opetovnem spusteni transformace indexu, se zalozky "naplni".

Jeste jsem ale musel do schematu doplnit compositeId:
...
`<field name="compositeId" type="string"  indexed="true"  stored="true" required="true" />`
...

MD
