### ISSUE TITLE
Zpřístupnění dokumentů podle data úmrtí autora

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#508]
Přidání kódu, který napsal P. Šilhavý pro zpřístupnění dokumentů podle data úmrtí autora, staženého z autorit nebo zapsaného v metadatech.
Mělo by to být přidáno jako další položka v admistrátorském menu.

**Comment by zabak** [comment]
@MLhotak nevíš kde je ten kód?

**Comment by pavel-stastny** [comment]
@zabak @MLhotak Řekl bych, že už asi není aktuální. Asi bych uzavřel.
