### ISSUE TITLE
Možnost při importu vybrat sbírku a policy

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#514]
Při importu přidat možnost výběru sbírky a policy pro importovaný dokument.

**Comment by slapakovai** [comment]
Upřesnění - jedná se o import foxml, import NDK už obsahuje možnost výběru policy.

**Comment by zabak** [comment]
Navrhuji zavřít, řešeno novými sbírkami.

**Comment by pavelkocourek** [comment]
@gmelingerova Je s novými sbírkami ještě relevantní ?

**Comment by gmelingerova** [comment]
@pavelkocourek u sebe to mám naprogramované se starými sbírkami, ale bylo mi řečeno, že se to bude měnit, tak jsem to sem ani nenahrála. Nevím, jak vypadají "nové sbírky", udržuji u sebe verzi pro KNAV. Klidně to můžete zavřít.

**Comment by pavel-stastny** [comment]
@zabak @pavelkocourek Pro K7 to není relevantní. Zde uzavřu, pokud bude potřeba diskutovat sbírky a licence v K7, doporučuju otevřít nové issue.
