### ISSUE TITLE
Další rozvoj statistik

### ISSUE THREAD

**Issue by LenkaDamborska** [ceskaexpedice/kramerius#515]
Bylo by potřeba, aby modul Statistiky obsahoval také funkci, která spočítá všechny akce prohlížení za rok pro vybrané modely. Jde o to, aby správce dostal jedno číslo a to mohl uvést do ročního výkazu pro knihovny a aby to všechny knihovny dělaly stejně a nevznikaly chyby. Teď je nutné každý model vygenerovat zvlášť, pak sečíst počty prohlížení jednotlivých dokumentů v rámci jednoho modelu a pak až sečíst součty pro modely. 
Navrhujeme tedy, aby se tento proces ještě zautomatizoval. Ostatní části Statistik mohou zůstat tak, jak jsou.

**Comment by LenkaDamborska** [comment]
Podrobnější popis je zde (body 2-4): https://github.com/ceskaexpedice/kramerius/wiki/Statistiky#jak-z%C3%ADskat-po%C4%8Det-zobrazen%C3%BDchprohl%C3%AD%C5%BEen%C3%BDch-digit%C3%A1ln%C3%ADch-dokument%C5%AF-za-rok-ro%C4%8Dn%C3%AD-v%C3%BDkaz

Týkalo by se to těchto modelů: monograph, periodicalvolume, supplement, issue, sheetmusic, manuscript, archive, soundrecording, graphic, map. 
Otázka je, jestli započítat i periodikum samotné.
Prosím ostatní knihovny, aby se vyjádřily, zda s výčtem modelů souhlasí (resp. napsaly, pokud něco chybí).

**Comment by slapakovai** [comment]
Opravdu tam budeme započítavat najednou i číslo i ročník periodika? To tam potom bude ten samý dokument dvakrát.

**Comment by LenkaDamborska** [comment]
Řešili jsme to na předposlední schůzce a vyplynulo z toho, že bude dobré započítávat i strany.. Ale když se nad tím zamýšlím, tak bych započítala jen ročníky, jak jsem navrhovala na začátku. Je pravda, že se to akorát zduplikuje.

**Comment by slapakovai** [comment]
Já myslím, že jsme navrhovali, aby se započítávala jenom čísla a ne ročníky. Ale přesně už si to nepamatuju. Je to asi jedno, jestli se započítají ročníky nebo čísla. Kdyžtak jedno z toho vyber, ať se nám ta data neduplikují.

**Comment by LenkaDamborska** [comment]
Nakonec jsem vybrala ročníky. V minulosti se totiž mohlo stát, že se dávaly strany hned pod úroveň ročník, když se ještě nedigitalizovalo striktně podle NDK standardu. To by se do čísla nezapočítalo.

**Comment by pavel-stastny** [comment]
Pridany tlacitka pro rocni report.
