### ISSUE TITLE
"Přidat k Oblíbeným" ve vyhledaných výsledcích (bez vybraného titulu)

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#52]
4.8.0, rev. 4957. Přihlášený uživatel je ve Výsledcích, má vyhledané tituly, ale „Rámec: Vybrané položky“ má bez vybraného titulu. Když ve „více…“ klikne na „přidat k oblíbeným“, dostane hlášku „Přidáno k oblíbeným, OK“. Vypadá to, že vše proběhlo, ale v Oblíbených se logicky nic neobjeví. V takových případech by to asi mělo hodit hlášku ve smyslu "Pro přidání k Oblíbeným nejprve vyberte položku/položky".

**Comment by albertoh** [comment]
fixed by 767c3b8
