### ISSUE TITLE
problemy s prehravanim zvuku v Kramerius v iOS

### ISSUE THREAD

**Issue by filipsir** [ceskaexpedice/kramerius#522]
mam problem prehrat zvuk ve vsech prohlizecich na MacBook, Kramerius verze 5.3.6 - adresa zvuk.nm.cz

Muzete prosim zkouknout zda to funguje ci ne?

**Comment by MartinRumanek** [comment]
@filipsir Ostatní prohlížeče jedou? 

Prosím vyzkoušej jestli se ti na tvém Macbooku přehraje http://kramerius.mzk.cz/search/i.jsp?pid=uuid:59e708b6-c462-4610-90c5-ac5ca030050a#soundrecording-soundunit-track_uuid:57fffa5f-67fb-4d31-ac28-72504334a837. V MZK je téměř stejná instalace.

**Comment by filipsir** [comment]
to mi jde. ale v eng lokalizaci na chrome na macbook to nejde. pri prepnuti na cze lok to jde...

**Comment by filipsir** [comment]
v safari nefunguje ani cze ani eng verze

**Comment by vlahoda** [comment]
jen pro informaci - zkusil jsem ten Martinův link na Macu v Safari, Chromu i Firefoxu, česky i anglicky a hraje mi to všude správně

**Comment by zabak** [comment]
V Opeře na Macu nejede v eng verzi. Projeví se to tak, že se v záložce Audio Player vůbec nezobrazí ten audio player.

**Comment by zabak** [comment]
ale jen u Filipa, MZK funguje.

**Comment by filipsir** [comment]
zkuste toto http://zvuk.nm.cz/search/i.jsp?pid=uuid:d30d28de-a057-4b59-8931-72125d2a4c60 nebo cokoliv v zvuk.nm.cz

**Comment by vlahoda** [comment]
To mi naopak nefunguje nikde... ale v konzoli browseru jsem našel toto:
GET http://kramerius:8080/search/api/v5.0/item/uuid:d30d28de-a057-4b59-8931-72125d2a4c60?_=1495711910935 net::ERR_NAME_NOT_RESOLVED

To vypadá, že nemáte správně nastavenou konfigurační property api.point

**Comment by filak** [comment]
Arie vodnika se mi v posledni verzi Chrome (Verze 58.0.3029.110 (64-bit)) prehraje.

**Comment by zabak** [comment]
@filipsir může se tohle zavřít?
