### ISSUE TITLE
Použití zástupného znaku hvězdička

### ISSUE THREAD

**Issue by BrozekAles** [ceskaexpedice/kramerius#523]
U verze 5.3.6 a patrně i u starších verzí nutno psát hledaná slova malými písmeny, pokud použijeme zástupný znak hvězdičku. Je potřeba toto opravit, protože uživatel píše vlastní slova s počátečním písmenem. Pokud to nepůjde, doporučuji na tuto anomálii upozornit v nápovědě. Díky.

**Comment by MartinRumanek** [comment]
Od verze 5.3.5 je možné používat SOLR verze 6, který tento problém nemá.

Jedna z mála knihoven, která už na novější index přešla, je Česká Třebová:
https://k5.digiknihovna.cz

Můžete to prosím vyzkoušet tam? Např. dotaz `Česko*Vské noviny` v pořádku funguje.

**Comment by BrozekAles** [comment]
no u České Třebové je to o trochu lepší, na dotaz Třebíč* to naštěstí nehlásí nula nalezených záznamů (takový dotaz jsme dělali při školení v Třebíči). Při dotazování v Krameriu v Č. Třebové  ​mi to dá výsledky: 
Třebíč*   67 dokumentů  sbaleno do 4
Třebíč 44 dokumentů  sbaleno do 4
Nepříjemné ale je, že ve skutečnosti jsou mezi těmi 44 dokumenty i slova "Třebíči", což je špatné. Musím tedy nadále učit použití zástupných znaků jen na K3, kde to funguje spolehlivě :-(

**Comment by BrozekAles** [comment]
Vážený pane kolego,
no u České Třebové je to o trochu lepší, na dotaz Třebíč* to naštěstí  
nehlásí nula nalezených záznamů (takový dotaz jsme dělali při školení  
v Třebíči). Při dotazování v Krameriu v Č. Třebové mi to dá výsledky:
Třebíč*

			 - Ing. Aleš Brožek
  m: + 420 731 578 269
  t/f: + 420 475 200 045
  e: brozek@svkul.cz Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech republic

  t: + 420 475 200 045 f: + 420 475 200 045
  e: knihovna@svkul.cz
  w: www.svkul.cz
----------------původní zpráva-----------------
Od:Martin Rumanek [notifications@github.com ]
Komu:"ceskaexpedice/kramerius" [kramerius@noreply.github.com ]
Kopie:BrozekAles [brozek@svkul.cz ], Author [author@noreply.github.com ]
Datum:Mon, 29 May 2017 00:25:03 -0700
----------------------------------------------------------

**Comment by pavel-stastny** [comment]
> Nepříjemné ale je, že ve skutečnosti jsou mezi těmi 44 dokumenty i slova "Třebíči", což je špatné.

Ale to neni spatne.  S prechodem na novou verzi SOLRu byla zapracovana i podpora cestiny  - lematizace a to je duvod, proc Vam pokud zadate slovo Trebic najde i dalsi jeho tvary : Trebici, Trebicem. atd..

**Comment by BrozekAles** [comment]
Fajn, lematizaci bych bral, ale musí fungovat spolehlivě. 
Po ranním vyhledávání v Krameriu knihovny Česká Třebová, kdy byly výsledky:
Třebíč*   67 dokumentů  sbaleno do 4
Třebíč    44 dokumentů  sbaleno do 4
jsem teď večer udělal dotaz Třebíč* NOT Třebíč s výsledkem 23 dokumentů  sbaleno do 4
Mezi těmi 23 dokumenty není jen Třebíčsko, ale i Třebíči, Třebíče :-(
A jak mám postupovat, když chci najít jen 1. pád od Třebíče? Třebíč v uvozovkách, tedy "Třebíč" vede k výsledku 44 dokumentů  sbaleno do 4
Díky za radu

**Comment by zabak** [comment]
@BrozekAles Tohle vyřešil nový klient, můžeme to zavřít?

**Comment by BrozekAles** [comment]
Ano
