### ISSUE TITLE
Vyhodnocování mowing wall podle přesného data vydání

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#524]
Rozšířit funkce použití mowing wall a aplikace pohyblivé zdi o vyhodnocení přesného data vydání. Nyní se vyhodnocuje pouze rok a podle toho se dokumenty zpřístupňují. U novějších dokumentů ale máme většinou přesné datum vydání nebo aspoň měsíc vydání. Bylo by možné zpřístupňovat dokumenty podle toho?

**Comment by pavel-stastny** [comment]
Jak to myslis?  Ted se vyhodnocuje i mesic a den.  Vestavene formaty jsou popsany zde: 

https://github.com/ceskaexpedice/kramerius/wiki/Prava#pozn%C3%A1mky-k-implementaci

Pokud nevyhovuji, je moznost je rozsirit o vlastni: 

https://github.com/ceskaexpedice/kramerius/wiki/MovingWallProcess#form%C3%A1t-data

**Comment by slapakovai** [comment]
Díky za upřesnění. Asi tam mám něco špatně nastaveného. Ještě to otestuju a pak kdyžtak issue zavřu.

**Comment by krizovj** [comment]
Může se zavřít prosím
