### ISSUE TITLE
Odkazy v klientovi K5

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#528]
Při odkázání na ročník, se zobrazí ročník, ale je pojmenován jako "výtisk", tedy číslo. Je to jen u ročníků, které nejsou rozděleny na čísla. 
Příklady:
https://kramerius.lib.cas.cz/client/handle/uuid:4997f662-5625-11e1-1331-001143e3f55c
https://kramerius.lib.cas.cz/client/handle/uuid:48fe9c92-5625-11e1-1726-001143e3f55c
https://kramerius.lib.cas.cz/client/handle/uuid:4bfbaff2-5625-11e1-1726-001143e3f55c

Zároveň také není v klientovi možné vygenerovat odkazy na všechny úrovně, protože když se otevře např. číslo časopisu, lze odkázat jen na jednotlivé strany, ne na celé číslo.

**Comment by pavel-stastny** [comment]
Tyka se stareho rozhrani
