### ISSUE TITLE
nutnost znovu nacist stranku pri opakovanem importu

### ISSUE THREAD

**Issue by psenickam** [ceskaexpedice/kramerius#529]
Pokud vyberu objekt k importu a import schvalim je nutne pred vyberem dalsiho objektu znovu nacist stranu. V pripade ze stranku nenactu znovu nelze dasli objekt importovat.

**Comment by MartinRumanek** [comment]
Issue na tento bug už existuje https://github.com/ceskaexpedice/kramerius/issues/493
