### ISSUE TITLE
nefungují šipky v dialozích

### ISSUE THREAD

**Issue by MartinBarton** [ceskaexpedice/kramerius#533]
Na vícero místech v dialozích nefungují šipky ani Enter, je třeba klikat myší. (například Indexace, ...). K5.3.3

**Comment by pavel-stastny** [comment]
Mate na mysli v dialogu indexace a sipkama je mysleno sipky na klavesnici ?

**Comment by MartinBarton** [comment]
Ano, ano.

**Comment by pavel-stastny** [comment]
V pristim roce bude reimplementovano admi rozhrani.
