### ISSUE TITLE
Mohly by i ne-admini mít možnost používáš Labels v Issues?

### ISSUE THREAD

**Issue by westfood** [ceskaexpedice/kramerius#535]
#

**Comment by westfood** [comment]
Mohly by i ne-admnini mít možnost používáš Labels?

**Comment by MartinRumanek** [comment]
To nejde, labely můžou přidávat pouze uživatelé s právem zápisu do repozitáře, viz https://help.github.com/articles/repository-permission-levels-for-an-organization/
