### ISSUE TITLE
Vyhledávání rodičů a potomků

### ISSUE THREAD

**Issue by MartinBarton** [ceskaexpedice/kramerius#536]
Při opravách rozpadlých i jinak poškozených vazeb je dobré mít nástroj, který najde potomky i rodiče daného uuid.

**Comment by pavel-stastny** [comment]
Obavam se, ze to je nad ramec vyvoje pro tento rok. Pokud Vas to trapi, zkuste prosazovat primo na vyvojovych schuzkach.  Prozatim uzaviram.
