### ISSUE TITLE
Hromadná práce s daty

### ISSUE THREAD

**Issue by MartinBarton** [ceskaexpedice/kramerius#538]
Při správě větších objemů dat by se hodilo mít nástroj pro hromadnou správu. Nejlépe předložit seznam uuid v TXT souboru a nástroj by pak uměl daná uuid reindexovat, set public, set private, nebo tato uuid smazat.
Nevím, zda už je to opravené, ale nefungovalo, pokud jsem si filtrem vybral nějaké tituly a ty pak dal hromadně označit (všechny zaškrtávací čtverečky vpravo nahoře se vyberou přes navigaci nahoře vpravo - Označit vše) avšak následný povel k akci (set public atp.) mi už nezafungoval.,

**Comment by pavel-stastny** [comment]
> Při správě větších objemů dat by se hodilo mít nástroj pro hromadnou správu. Nejlépe předložit seznam uuid v TXT souboru a nástroj by pak uměl daná uuid reindexovat, set public, set private, nebo tato uuid smazat.

Pro  tyto účely bylo vyvinuto API, které umožní naplánovat jakýkoliv proces (indexace, import, export, atd...) a je  možno ho plánovat skriptem (pomocí curl, wget apod..)    Viz: https://github.com/ceskaexpedice/kramerius/wiki/RemoteAPI

> Nevím, zda už je to opravené, ale nefungovalo, pokud jsem si filtrem vybral nějaké tituly a ty pak dal hromadně označit (všechny zaškrtávací čtverečky vpravo nahoře se vyberou přes navigaci nahoře vpravo - Označit vše) avšak následný povel k akci (set public atp.) mi už nezafungoval.,

Issue jsem k tomu nenašel. Zkoušeno na poslední verzi a problém jsem nezaznamenal.
