### ISSUE TITLE
Záznam o aktivitách nad entitou

### ISSUE THREAD

**Issue by MartinBarton** [ceskaexpedice/kramerius#539]
Mimo správy LP procesů v aplikaci není nic, co by zaznamenalo, co se s entitou děje. K3 to měl a dle zadání by toto měl mít i nový kramerius, ale nemá, což je obrovský nedostatek. Není kontrola nad tím, co se s IE dělo, kdy a kdo to dělal. Nechápu, jak je možné, že tato zásadní vlastnosti v aplikaci stále není :-o
Samotné LP procesy by se neměly zaznamenávat do samostatných složek, ale tvořené logy se měly vázat v databázi s možností inteligentního zálohování a vyhledávání.

**Comment by pavel-stastny** [comment]
> K3 to měl a dle zadání by toto měl mít i nový kramerius, ale nemá, což je obrovský nedostatek. Není kontrola nad tím, co se s IE dělo, kdy a kdo to dělal. Nechápu, jak je možné, že tato zásadní vlastnosti v aplikaci stále není :-o

Historie objektů je řízená samotným repozitářem Fedora a je zaznamenávána v FOXML.

> Samotné LP procesy by se neměly zaznamenávat do samostatných složek, ale tvořené logy se měly vázat v databázi s možností inteligentního zálohování a vyhledávání.

Jedná se o standardní logy. Pro zálohu lze použít systémové prostředky (tar,  dump, atd..), pro správu pak je možno použít kombinaci logstash + kibana.
