### ISSUE TITLE
Proces synchronizace indexu - mel by odstranit z indexu neexistujici dokumenty ve Fedore

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#541]
Zdravim,

narazil jsem na nasledujici problem (po kompletnim upgradu celeho serveru s Krameriem, tedy java 8, fedora 3.8.1, search 3.5.7, solr 6.6, postgresql). Pokud kliknu na lupu hledani na hlavni strance (bez zadani do textoveho pole), tak standardne se zobrazi postupne seznam vsech dokumentu v Krameriovi. Nicmene v tomto konkretnim pripade se ale zobrazi pouze "standardni ikona" naznacujici, ze dokument neexistuje - viz screenshot:

![screen-01](https://user-images.githubusercontent.com/8750622/27819045-b35021e4-6098-11e7-8400-f980486611ac.png)

Kliknutim na nahodny nedostupny dokument toto skonci nepeknym seznamem vyjimek - viz screenshot:

![screen-02](https://user-images.githubusercontent.com/8750622/27819151-22739bdc-6099-11e7-8858-cd81d2fc61f8.png)

Znamena to tedy, ze dokument je zindexovany v solr indexu, ale neexistuje ve fedore. Overil jsem to namatkou a je to tak (solr 6.6.0) - viz screenshot:

![screen-03](https://user-images.githubusercontent.com/8750622/27819226-879772d6-6099-11e7-8407-7e02e6885401.png)

Dokument byl do noveho solr indexu prenesen migraci, existuje stejne i ve stare verzi solr indexu - viz screenshot:

![screen-04](https://user-images.githubusercontent.com/8750622/27819281-d0bbd2ea-6099-11e7-9e76-556110635f93.png)

Nasledne jsem overil existenci dokumentu ve Fedore, a tam neexistuje - viz screenshot:

![screen-05](https://user-images.githubusercontent.com/8750622/27819448-a03baa90-609a-11e7-84f9-01f3f37a2eb5.png)

Po migraci indexu ze stareho solru do noveho (podle schematu z oficialniho distribucniho balicku) jsem spustil proces kontroly integrity indexu abych odstranil prave tyto nekonsistence - viz screenshot:

![screen-06](https://user-images.githubusercontent.com/8750622/27819554-186587c0-609b-11e7-898f-04d75a5c1702.png)

Proces skoncil bezchybne, nicmene se tedy zda, ze ale neprovedl co je od nej ocekavano. Interni indexy fedory jsou take prenesene

V cem muze byt jeste problem?

Diky, MD

**Comment by mduda100871** [comment]
Doplneni - pro jistotu jsem dal jeste vyhledat dokument primo na filesystemu uloziste pro pripad, ze by byl s nim index fedory nekonsistentni. Doukment nebyl nalezen - viz screenshot:

![screen-07](https://user-images.githubusercontent.com/8750622/27820289-4d69067e-609e-11e7-8b8b-ba5cee8fb232.png)

MD

**Comment by pavel-stastny** [comment]
Z ukazky jde videt, ze se jedna o stranku.  Jsou v indexu ty nadrazene objekty?

**Comment by mduda100871** [comment]
Tezko rici, nenapada me zpusob, jak nadrazenou uroven jednoznacne dohledat - v indexu cesta zpatky neni, nebo ji nevidim - screenshot:

![screen-01](https://user-images.githubusercontent.com/8750622/27823018-f50b9730-60a7-11e7-8104-1a0c3afb2c54.png)

pole parent_pid, pid_path i root_pid obsahuji uuid dokumentu, nikoliv nadrazene urove....

**Comment by mduda100871** [comment]
Jedine dotazem do triple indexu?

**Comment by mduda100871** [comment]
Pokud zkonstruuji rucne permalink:

http://kramerius.nm.cz/search/handle/uuid:7cbee649-2c62-11e4-9fc7-005056ba013

tak Kramerius zahlasi, ze dokument neexistuje...

**Comment by pavel-stastny** [comment]
to vypada na nejakou nekonzistenci indexu. V polozce pid_path by mela byt cela cesta (od korene ke kenkretnimu uuid).  Jakoby stranka neexistovala v zadnem titulu (monografie, vytisk, atd...).   Zkus, prosim, spustit reindex proces s nasledujicimi parametry :  

`POST <adresa_serveru>/search/api/v4.6/processes?def=reindex`
`{"parameters":["checkIntegrityByModel","*page"]}`

**Comment by mduda100871** [comment]
ok, jen pro jistotu nez to spustim - definuji proces reindex - doufam, ze to nezacne s reindexaci vsech dokumentu s modelem page, ale opravdu jen kontrolu integrity...

**Comment by mduda100871** [comment]
tak na testovacim serveru se to chova "mravne", tak jsem to spustil na ostrem a uvidime co vypadne...

**Comment by mduda100871** [comment]
Vypada to, ze takto definovany proces to vycistil, viz screenshot logu:

![screen-01](https://user-images.githubusercontent.com/8750622/27825949-97590b36-60b1-11e7-8fb5-bb78f5da7752.png)

i dotaz do solru uz dokument nevraci.

Otazka zni proc to nevycistil ten proces, ktery je dostupny prostrednictvim standardniho admin rozhrani Krameria?

**Comment by pavel-stastny** [comment]
proces prochazi vrchni modely (definovane v promenne `fedora.topLevelModels`) do hloubky. 
Viz (https://github.com/ceskaexpedice/kramerius/blob/master/indexer/src/cz/incad/kramerius/indexer/SolrOperations.java#L806-L813)

Problem byl, ze stranky nebyly na nic navazene. (Na zadnou monografii, periodikum, atd...)

**Comment by mduda100871** [comment]
Jasne, mozna by tedy bylo dobre uvazit, zda-li v "klikacim" rozhrani adminum neumoznit i tuto kontrolu integrity. Nebo si to musi nastavit do property "fedora.topLevelModels="? Je rozumne tam vlozit treba rocniky a cisla?

Jinak ten proces dobehl, umazal zombiky a uz se to zacalo chovat ocekavane. Stejny test by se ale mohl spustit take na vyssi urovne - napr. cisla, i tady muze nastat situace, ze na ne nebude vazba z rocniku...

**Comment by pavel-stastny** [comment]
> Jasne, mozna by tedy bylo dobre uvazit, zda-li v "klikacim" rozhrani adminum neumoznit i tuto kontrolu integrity. Nebo si to musi nastavit do property "fedora.topLevelModels="? Je rozumne tam vlozit treba rocniky a cisla?

Slo by obohatit indexacni dialog o inputbox, ktery by umoznil rict pro ktery model se ma checkIntegrity provadet. Ale to bych videl na samostatne issue - enhancement.  Toto uz uzavru.
