### ISSUE TITLE
reindexace s parametrem ignorovat-stranky

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#542]
Při úpravě metadatového záznamu objektu na nejvyšší úrovni reindexační proces prochází všechny objekty nižší úrovně kvůli kontrole, jestli se něco nezměnilo i tam. Tedy pro každou jednu stránku se kontroluje shoda datumu poslední změny ve foxml oproti datumu v solr záznamu. A pokud je tam změna, reindexuje se i samotná stránka.
Což může trvat opravdu dlouho - např. periodikum s 50 000 stránkami na dost naddimenzovaném železe mi trvalo přes 2,5 hodiny, mluvím o režimu jen-nové.
Příjde mi tady smysluplné přidat parametr, pomocí kterého by se procházela nejvýše úroveň issue a případné změny stránek by se neřešily. Výrazně by to ušetřilo čas v těchhle situacích kdy chci opravdu změnit jen drobnost a vím, že se se stránkami nic nedělo. 
Anebo parametr neprochazet-potomky, který by zaindexoval jenom samotný objekt nejvyšší úrovně, resp. úrovně, kterou jsem změnil a chci přeindexovat (např. ročník periodika). Protože pokud opravdu jinde změna nenastala, není důvod reindexovat potomky - imho jediné, co se z rodiče na potomky přenáší, je parent_pid.

**Comment by vlahoda** [comment]
Myslím, že k tomu slouží parametr indexeru fromPid, kdy se indexuje pouze daný dokument, bez rekurze.

**Comment by rzeh4n** [comment]
díky, s fromPid se opravdu indexuje jen samotný objekt, bez jakéhokoliv prohledávání potomků
