### ISSUE TITLE
Zmazanie všetkých indexov pri mazaní jednej strany

### ISSUE THREAD

**Issue by kenji1322** [ceskaexpedice/kramerius#544]
Pri mazaní jednej strany nejakého periodika, sa vymažú všetky indexy tohoto periodika zo solru, jediné ktoré zostanú su indexy konkrétneho vydania a strany tohoto vydania. Teda je následné nutné celé periodikum reindexovať, toto je celkom problematické pri väčších periodikách ktorých reindexácia môže trvať aj niekoľko dní. Mazanie strany robím pomocou "Delete from fedora.." v rozhraní krameria a tento proces prebehne bez chyby.

**Comment by MartinRumanek** [comment]
Je nutné změnit tokenizer v managed-schema

https://github.com/ceskaexpedice/kramerius/commit/4969248df7ef4217ef6c0adbd8484e2515084814
