### ISSUE TITLE
K5 klient problem s fulltext hledanim na (zrejme) Solr6

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#545]
Zdravim,

narazili jsme na problem u fulltextoveho vyhledavani u klientu rady 5.3.6 a 5.3.7. Problem se projevuje tak, ze kdyz uzivatel chce prohledavat fulltextove a omezi podminky vyhledavani nejakym reztezcem ve vyhledavacim poli, tak po odeslani prikazu (lupa) zustane klient nekonecne "viset" (presypaci hodiny).

V pripade, ze uzivatel ponecha omezujici podminku prazdnou a odesle prikaz vyhledani (lupa), tak se mu vrati podle ocekavani nejaky "nahodny" seznam titulu.

Dale jsme zjistili, ze toto chovani se projevuje v kombinaci se Solrem rady 6.x, pokud je pod Krameriem starsi Solr (distribucni), tak to funguje. Priklad:

tady to nefunguje (Solr6):

https://kramerius.army.cz/client/index.vm?page=browse

a tady to funguje (stary distribucni Solr):

https://kramerius.lib.cas.cz/client/index.vm?page=browse

kde obe instance pouzivaji stejne jadro a klienta (5.3.7). Jediny rozdil je v Solru, takze podezreni pada na nej, resp. klienta s nim v kombinaci.

MD

**Comment by mduda100871** [comment]
chybovy vystup pri vyvolani dotazu s omezujici podminkou (catalina.out):
...

[catalina.out.txt](https://github.com/ceskaexpedice/kramerius/files/1179750/catalina.out.txt)

**Comment by MartinRumanek** [comment]
Připojte ještě prosím log samotného SOLRu (předpokládám, že běží jako standalone aplikace).

**Comment by mduda100871** [comment]
pozor, v logu jsou casove znacky posunuty cas o dve hodiny
[solr.log.zip](https://github.com/ceskaexpedice/kramerius/files/1179807/solr.log.zip)

**Comment by MartinRumanek** [comment]
Prosím ještě výstup tohoto příkazu (spustit ze stroje kde je nasazený client.war)

```
curl "http://127.0.0.1:9080/search/api/v5.0/search?q=Praha&defType=edismax&qf=text+dc.title^4.0+dc.creator^1.5&bq=(level:0)^4.5&bq=dostupnost:"public"^1.2&pf=text^10&wt=json&facet=true&fl=score,*&start=0&rows=40&facet.mincount=1&facet.field=model_path&facet.field=keywords&facet.field=collection&facet.field=dostupnost&sort=score+desc&group.field=root_pid&group.type=normal&group.threshold=1&group.facet=false&group=true&group.truncate=true&group.ngroups=true&hl=true&hl.fl=text_ocr&hl.mergeContiguous=true&hl.snippets=2"
```

Vrací se `moved permanently` nebo výsledek SOLRu?
_____

Případně vyzkoušejte nastavit v souboru `client.properties`

```
api.point=https://kramerius.army.cz/search/api/v5.0
```

**Comment by mduda100871** [comment]
curl nevraci nic - screenshot:
![curl-01](https://user-images.githubusercontent.com/8750622/28704577-94bce646-736b-11e7-857e-b730265d0fd7.png)
...
ale zmena property zafungovala - screenshot:
![k5-01](https://user-images.githubusercontent.com/8750622/28704615-c84df0fe-736b-11e7-8b0b-1cb59451ce34.png)
...

**Comment by MartinRumanek** [comment]
Zřejmě máte novou verzi Tomcatu, který nepodporuje některé znaky v URL (v tomto případě mu vadí znak `^`), proto vrací prázdný request s kódem 400. 

Podobné issue je už nahlášené zde https://github.com/ceskaexpedice/kramerius/issues/470, týká se to verzí 8.5.8, 8.0.39 a novějších.

Zajímavé, že při přístupu přes reverzní proxy vám to funguje v pořádku - nejspíš webový server Apache ty URL enkóduje sám.

___

Bude opraveno (requesty se budou posílat rovnou enkódované). Zatím to můžete provozovat se změněnou property.

**Comment by mduda100871** [comment]
Tomcat je distribucni (Debian Jessie) v8. Ano, na podobny problem uz jsem narazil i drive a tak trochu jsem ocekaval, ze to bude i tentokrat neco takoveho.

Diky, MD

**Comment by mduda100871** [comment]
Doplneni - chyba se projevuje i na RHEL 7.3 a jejich distribucnim Tomcatu7, pomuze "vycisteni" pres webserver.

**Comment by MartinRumanek** [comment]
Vyřešeno v nové verzi (5.3.8)
