### ISSUE TITLE
Client - překlad úvodního textu

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#546]
Dobrý den,
nasazujeme u nás v NTK clienta a narazil jsem na to, že se při přepínání jazyka nemění úvodní text pod vyhledáváním. 
Proměnná se bere asi odtud: `$CATALINA_HOME/webapps/client/WEB-INF/home.vm` , ale je tam pouze odkaz na default_intro a chybí "default_intro_EN_en".

Jde to zprovoznit alespoň jak je to třeba u Krameria AV (Text se změní po obnovení stránky). 

JD

**Comment by mduda100871** [comment]
anglicky text ulozte do souboru "~/.kramerius4/texts/default_intro", lze tam pouzit i html tagy

MD

**Comment by jdobiasovsky** [comment]
Tam jsem právě dal český, takže ten potom přijde kam?

**Comment by mduda100871** [comment]
do "default_intro_CZ_cs"

**Comment by jdobiasovsky** [comment]
Aha, aha! My jsme měli jenom default_intro a default_intro_EN_en. 

Funguje, děkuji a můžete zavřít
