### ISSUE TITLE
zpožděné nahrávání pdf do clienta

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#547]
Když importuji nová čísla časopisů ve formátu pdf do Krameria, tak import proběhne v pořádku. V instalaci https://kramerius.lib.cas.cz/search/ se pdf objeví hned. Ale v instalaci https://kramerius.lib.cas.cz/client/ se nové číslo s pdf objeví až za den nebo několik dnů.
Tahle prodleva je pro nás nepříjemná. Šlo by to nějak odstranit? Nebo můžete mi případně poradit, co to způsobuje?

**Comment by pavel-stastny** [comment]
> nové číslo s pdf objeví až za den nebo několik dnů.

Co to znamena? Neobjevi se v seznamu nejnovejsich nebo nejde vubec vyhledat ?

**Comment by slapakovai** [comment]
Nejde vůbec vyhledat a neobjeví se jako nové číslo v tom konkrétním ročníku.

**Comment by pavel-stastny** [comment]
To je divny...  kramerius ma pouze jeden index a ten sdili obe aplikace.  Muzu poprosit o nejaky konkretni priklad, na kterem by to slo videt?

**Comment by slapakovai** [comment]
Teď je možné se podívat třeba tady: https://kramerius.lib.cas.cz/search/handle/uuid:51f7caf1-509d-4940-9af0-43737c4d0513 ve starém rozhraní to číslo normálně je vidět, ale v novém rozhraní to bude vidět až za několik hodin/dní.

**Comment by MartinRumanek** [comment]
Ten persistentní odkaz se u mě přesměruje rovnou do nového klienta, asi máte pro vnější IP nastavené přesměrování persistentních odkazů.

Když si v novém i ve starém rozhraní otevřu takto nadřazený ročník, tak vidím zmiňované číslo v obou. Ty ne?

https://kramerius.lib.cas.cz/client/index.vm?page=doc#uuid:dccd65be-f117-44bb-a649-10f1a0896d32
https://kramerius.lib.cas.cz/search/i.jsp?pid=uuid:51f7caf1-509d-4940-9af0-43737c4d0513

**Comment by slapakovai** [comment]
Když si dám v clientovi zobrazit přehled všech ročníků časopisu e-psychologie, tak tam vidím jenom roky 2007-2016, rok 2017 tam nevidím. Ani když to otevřu v jiném prohlížeči nebo na jiném počítači.

**Comment by slapakovai** [comment]
Ale když si otevřu přímo ten tvůj odkaz do clienta, tak ten rok 2017 vidím :(

**Comment by MartinRumanek** [comment]
Fakt se to liší. V client API ročník 2017 není.

client api:
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:98280eb8-0868-44b8-b4cb-21da70d8b33b/children

kramerius api:
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:98280eb8-0868-44b8-b4cb-21da70d8b33b/children

Nemáte nakonfigurovanou na serveru nějakou cache (mduda100871)?

**Comment by pavel-stastny** [comment]
Nevidim to ani kdyz dotazuju primo solr: 

https://kramerius.lib.cas.cz/search/api/v5.0/search?q=parent_pid:%22uuid:98280eb8-0868-44b8-b4cb-21da70d8b33b%22&fl=rok

**Comment by mduda100871** [comment]
Zadna cache na serveru neni...pokud neco neimplementuje interne webserver o cem netusim...

**Comment by pavel-stastny** [comment]
Je to cache na strane klienta. Bude vyreseno v nasledujicim buildu.

**Comment by slapakovai** [comment]
OK, díky za zprávu
