### ISSUE TITLE
Možnost vyhledat neindexované objekty

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#548]
V menu - indexace dokumentů bych ocenila možnost nějak vyfiltrovat nebo vyhledat nezindexované objekty. Napadá mě přidat u jednotlivých modelů možnost je setřídit podle stavu indexace.

**Comment by MartinRumanek** [comment]
To by se musely projít všechny záznamy z Fedory a to trvá velmi dlouho (v řádu hodin, v případě samotných stránek dny). Bohužel to není možné do současného formuláře implementovat.

Nicméně v MZK mají skript, který umí vrátit seznam nezaindexovaných uuid, pomohlo by vám to?

**Comment by slapakovai** [comment]
To by mi určitě pomohlo. Byl by někdo z MZK ochotný ho poskytnout nebo na koho se tam mám obrátit?

**Comment by zabak** [comment]
@MLhotak můžeme uzavřít?
