### ISSUE TITLE
Problem s indexaci PDF

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#550]
Zdravim,

mame problem s indexaci nekterych PDF dokumentu (clanku, born-digital). Proces vyhodi vyjimku - screenshot:

![stout-01](https://user-images.githubusercontent.com/8750622/28956369-be298f3a-78ec-11e7-8816-fbc773d18055.png)

Zrejme jde o nejaky "neviditelny" ridici znak v textu. Nejprve jsme zkusili "normalizovat" originalni pdf prostrednictvim Adobe editoru na pdf-a, jen proste preulozeni apod. Nasledna reindexace nicmene vzdy skonci s vyse uvedenou vyjimkou.

V dalsim kroku jsem tedy zkusil upgradovat pdfbox na posledni verzi - stahl jsem zdrojak Krameria, upravil konfiguraci gradlu - screenshot:

![gradle-01](https://user-images.githubusercontent.com/8750622/28956520-bb7cb216-78ed-11e7-871e-bf9963b6c120.png)

a prekompiloval bez problemu. Po nasazeni custom balicku Krameria indexace opet konci stejnou vyjimkou.

Indexovaci proces zrejme i po vyjimce dobehne (skonci se statusem WARNING), nicmene to vypada, ze se fulltextove nezindexuje - screenshot:

![solr-01](https://user-images.githubusercontent.com/8750622/28956647-56b3ac58-78ee-11e7-8d17-19897a476e5e.png)

Uz nemam dalsi napad co by se s tim dalo udelat...

MD

**Comment by MartinRumanek** [comment]
Můžu vás poprosit o problémové PDF? Třeba na e-mail...

**Comment by MartinRumanek** [comment]
Chyba byla v knihovně, která escapuje XML:
https://issues.apache.org/jira/browse/LANG-955

Bude opravené v následujícím buildu.
