### ISSUE TITLE
K5 core (5.3.7) - problem se zobrazenim casove osy - spodni ikona posuvniku

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#551]
Zdravim,

po nasazeni posledni stable verze jadra Krameria se stala nedostupnou spodni ikona (sipka) posuvniku u casove osy - priklady:

- tady je posledni verze (5.3.7):

![osa-01](https://user-images.githubusercontent.com/8750622/29209369-62f35c16-7e8e-11e7-9bf1-10f64b69a132.png)

- a zde je verze starsi (5.3.6):

![osa-02](https://user-images.githubusercontent.com/8750622/29209401-9364a8f0-7e8e-11e7-845d-db6d1f0cf577.png)

Mam podezreni na pridanou funkcnost v podobe zaskrtavatka "konkretni den"....

Diky, MD

**Comment by MartinRumanek** [comment]
Správný předpoklad :-). Opraveno.

**Comment by mduda100871** [comment]
diky

**Comment by mduda100871** [comment]
hmm, rucne jsem patchnul ten kaskadovy styl, pretocil krameria, ale nezafungovalo to...

**Comment by mduda100871** [comment]
firefox a chromium to ale zobrazi..chrome nikoliv

**Comment by mduda100871** [comment]
anonymni okno chromu to zobrazi, takze nejaka kes, ted se zda, ze to funguje...jinak lepe to ve firefoxu vypada pri:
...
height: calc(100% - 56px);
...
MD

**Comment by MartinRumanek** [comment]
Jo, to je určitě keší. F5 je nékdy málo, zkuste ctrl-F5.

> anonymni okno chromu to zobrazi, takze nejaka kes, ted se zda, ze to funguje...jinak lepe to ve firefoxu vypada pri: height: calc(100% - 56px);

Pokud se to nerozbije v Chromu, tak to upravme na těch 56px. Já na Linuxu ve FF ikony na scrollbaru vůbec nemám, použije se defaultní systémový scrollbar, který je bez nich...
