### ISSUE TITLE
K5 rozbity Solr index po smazani stranky/clanku/cisla

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#556]
Zdravim,

narazili jsme na dalsi neprijemny problem. Pokud smazeme (kompletne, tedy i z Fedory) clanek/stranku pod cislem, tak dojde k tomu, ze se z indexu ztrati cela nadrazena struktura a musime reindexovat kompletne cely titul. 

Podobne, kdyz smazeme cele cislo, opet se rozbije/ztrati cela struktura a musime kompletne reindexovat.

Vypada to na problem posledni verze Krameria, v predchozich verzich tento problem nevznikal.

Kramerius je posledni stable 5.3.8 a solr 6.6.0, java 8.

MD

**Comment by pavel-stastny** [comment]
A schema indexu je taky posledni ?  (Vypada to podobne, jako issue #544, ktere se v poslednim buildu resilo)

**Comment by mduda100871** [comment]
Jo, neni, patchnu ho. Predpokladam, ze pak bude muset probehnout transformace stacajiciho indexu?

**Comment by mduda100871** [comment]
Mimochodem ale, jak to bude u instanci s novou verzi Krameria ale starym solrem ze starsich distribuci?

**Comment by pavel-stastny** [comment]
> Jo, neni, patchnu ho. Predpokladam, ze pak bude muset probehnout transformace stavajiciho indexu?

Ano

> Mimochodem ale, jak to bude u instanci s novou verzi Krameria ale starym solrem ze starsich distribuci?

U stareho SOLRu se to nevyskytuje.

**Comment by mduda100871** [comment]
ok, diky
