### ISSUE TITLE
Odkaz na anglickou verzi (Klient K5)

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#558]
Dobrý den, 
je možné linkovat na anglickou verzi Klienta podobně jako je tomu u Search? (https://k4.techlib.cz/search/**?language=en&**)

**Comment by pavel-stastny** [comment]
melo by to byt stejne jako u search tedy:

`.../client/index.vm?language=en` - anglicka verze
`.../client/index.vm?language=cs` - ceska verze
