### ISSUE TITLE
Statistiky pro virtuální sbírku

### ISSUE THREAD

**Issue by slapakovai** [ceskaexpedice/kramerius#559]
Bylo by možné generovat statistiky i pro konkrétní virtuální sbírku? Tedy pro všechny dokumenty v ní, nezávisle na modelech?

**Comment by pavel-stastny** [comment]
@slapakovai @pavelkocourek V K7 je virtualni sbirka resena pres samostatny model, doporucuju vyzkouset po releasu K7

**Comment by zabak** [comment]
Přesunuto do jádra, zde zavírám
