### ISSUE TITLE
přidání informce o policy do OAI záznamu

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#562]
Kvůli sklízení do Resolveru URN:NBN navrhuji doplnění informace o dostupnusti do OAI záznamů, alespoň pro formát drkramerius4. Např. aby bylo možné pro rezolvování volitelně preferovat přesměrování na volně dostupnou verzi dokumentu.
Nejsem si teď jistý, jestli se k tomu v Krameriu používá údaj z 
```
<foxml:datastream ID="POLICY" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
   <foxml:datastreamVersion ID="POLICY.0" LABEL="Policy Record" CREATED="2017-10-06T14:15:06.645Z" MIMETYPE="application/rdf+xml">
     <foxml:contentLocation TYPE="URL" REF="http://local.fedora.server/fedora/get/policy:public/POLICYDEF"/>
   </foxml:datastreamVersion>
</foxml:datastream>
```
nebo 
```<rel:policy>policy:public</rel:policy>``` z datastreamu RELS-EXT.
Je docela jedno, jak by to ve výsledném dokumentu vypadalo, hlavně aby šlo rozeznat private a public věci.
Stačilo by to pro oai4solr, i když nejspíš i starý oai provider používá oaiServlet na generování záznamu. Vypadá to tedy, že by se to mohlo doplnit v oaiServlet.java, resp. DrKrameriusV4Writer.java.

**Comment by vlahoda** [comment]
Informace o přístupnosti už je v tagu dc:rights v Dublin Core

**Comment by rzeh4n** [comment]
To je pravda, nicméně pokud potřebuji plnohodnotný MODS záznam a ne zjednodušenou verzi metadat v podobe DC nebo ESE, tak mi nezbývá než sklízet přes metadataPrefix=drkramerius4, kde ta informace není.

**Comment by MartinRumanek** [comment]
Implementováno.
```
<dr:uuid>1a2d4984-3074-11e0-8e0a-0050569d679d</dr:uuid>
<dr:type>MONOGRAPH</dr:type>
<dr:policy>policy:private</dr:policy>
```
http://kramerius.mzk.cz/oai/?verb=ListRecords&metadataPrefix=drkramerius4&set=monograph
