### ISSUE TITLE
Nefungujici Editor uzivatelu u https

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#563]
Dobry den,
mame Krameria verzi 5.3.3 a pouzivame protokol https.
Po prihlaseni jsem chtel jit do sekce Editor uzivatelu,ale vyskocila chybova hlaska 401, ze proces vyzaduje http (This request requires HTTP authentication). Apache Tomcat/6.0.24
Muze byt problem v tom, jakou mame verzi Krameria?

Dekuji

**Comment by pavel-stastny** [comment]
Dobry den, zadne problemy s https nepozorujeme (funguje na vice instancich i s editorem uzivatelu). Dle hlasky bych tipoval, ze nemate nastaveny  Single Signon v tomcatu.
