### ISSUE TITLE
Hudebniny - zákaz tisku - hláška

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#569]
Pokud je dokument nepřístupný a je hudebninou, měl by u něj být zakázán tisk, a to i na místě samém. Ve všech klientech Krameria by se po kliknutí na ikonu pro tisk mělo objevit okno s následující hláškou:

"Autorsky chráněné hudebniny bohužel nelze žádným způsobem kopírovat z
důvodu výjimky v Autorském zákoně." 

V současné době je to zakázané, ale hází to chyby.

**Comment by pavel-stastny** [comment]
Dobry den,
nejedna se nahodou o issue, ktere bylo reseno zde #406 ?

**Comment by LenkaDamborska** [comment]
V issue 406 šlo o to, aby byla možnost zakázat tisk. V tomto issue jde o příslušnou hlášku, která se má objevovat, když je zakázán tisk. Když chce člověk v klientovi tisknout neveřejnou hudebninu, tak mu vyskočí hláška 403 operace je zakázána. Normální člověk nepochopí, že to tak je schválně a myslí si, že máme chybu v Krameriu. Proto to chce tu smysluplnou hlášku, aby věděl, že je to tak záměrně kvůli AZ. A ta hláška musí být nastavena pro všechny klienty. Probírali jsme to na vývojových schůzkách.

**Comment by krizovj** [comment]
Dobrý den, tak částečně to s tím souvisí. Pomocí 406 jde zakázat tisk. Ale tlačítko pro tisk tam stále zůstává. A když na něj kliknu tak v jádru se objeví tohle: 

![hudebnina_tisk_kramerius](https://user-images.githubusercontent.com/21309201/34711037-0982bfe4-f51e-11e7-9b0b-3b4bfb67c61a.jpg)

což ještě jde (člověk z toho pochopí, že tisknout prostě nemůže), samozřejmě ta hláška by měla být jiná, trochu více vysvětlující (viz výše). Ale v klientovi (i v klientovi Digitální knihovna) to hodí chybu (screenshot je z klienta Digitální knihovna, až ho budu mít i z našeho klienta, tak ho sem klidně taky dám, ale myslím, že to bude to samé):

![hudebninytiskdigitalniknihovna](https://user-images.githubusercontent.com/21309201/34711341-5c5d151a-f51f-11e7-874b-05e481aebf4a.jpg)

**Comment by pavel-stastny** [comment]
> Když chce člověk v klientovi tisknout neveřejnou hudebninu, tak mu vyskočí hláška 403 operace je zakázána. Normální člověk nepochopí, že to tak je schválně a myslí si, že máme chybu v Krameriu.

Implementace zmineneho issue pokryvala 3 akce: 

* `PDF_RESOURCE` - ktery definuje samotny pristup na endpoint a ten je zodpovedny za chybovou hlasku 403. Ale nic jineho bohuzel delat nemuze. 

a
 
* `SHOW_CLIENT_PRINT_MENU`  
* `SHOW_CLIENT_PDF_MENU`.

Ty posledni dve jsou vicemene informativni (server nemuze narizovat co ma nebo nema klient zobrazit), nicmene pokud je klient reflektuje ( a v te dobe to bylo implementovano do jadra a do klientskeho rozhrani) tak muzete kombinaci vsech akci docilit  toho, aby klient, ktery nema pravo tisknout ani nevidel polozku na tisk. Tedy nedostaval chybovou hlasku..   To byl duvod, proc tam jsou ty zbyle dve akce.
