### ISSUE TITLE
RemoteAPI - import PSP balíku do Krameria s Imageserverem

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#575]
Je možné pomocí RemoteAPI zadat import PSP balíku (výstup ProArc-u) tak, aby nebylo nutné přepisovat konfigurační soubor `migration.properties` obsahující cestu k obrázkům na Imageserveru?

**Comment by MartinRumanek** [comment]
Aktuálně ne. Všechny parametry, které jdou předat jsou zde:
https://github.com/ceskaexpedice/kramerius/blob/master/import-mets/src/main/java/org/kramerius/importmets/parametrized/ParametrizedMetsNKDImport.java

Konfigurační direktiva v migration.properties slouží primárně k zadání kořenové adresy imageserveru a ne k cestě jednotlivým obrázkům. Adresáře s obrázky se standardně ukládají přímo v této kořenové adrese.

Na imageserveru MZK byl na toto vyhrazený speciální adresář (do kterého jsem akorát ještě přidával siglu knihovny). Pokud to chcete jinak, bude nutná úprava v API.

**Comment by jkremlacek** [comment]
Podle mě by bylo fajn mít možnost pomocí parametru volání API overridnut (pokud je během volání nastavena hodnota):

```
convert.imageServerTilesURLPrefix
convert.imageServerImagesURLPrefix
convert.imageServerDirectory
```

abych v rámci importu balíku z ProArc-u do Krameria nemusel řešit přepisování `migration.properties` souboru.

**Comment by svetlym** [comment]
Moc tomu dotazu nerozumím - v PSP balíku cesty k obrázkům na imageserveru nejsou. Kam si to Kramérius v rámci importu nahraje přece Proarc vůbec nemusí trápit.

Ostatně PSP balík je standardní formát podle NDK a může ho klidně vyrobit i nějaký jiný nástroj. Takže import PSP do Kraméria nutně musí být nezávislý na tom, čím byl balík vyroben.

**Comment by jkremlacek** [comment]
Řešíme možnosti zadávání požadavku na import balíku přes API Krameria (protože v současné chvílí Kramerius umožňuje specifikování cesty do imageserveru a pouze pomocí souboru migration.properties). 

ProArc a PSP balík zde byl zmíněn pouze pro uvedení do situace use-case-u.

**Comment by MartinRumanek** [comment]
> Podle mě by bylo fajn mít možnost pomocí parametru volání API overridnut (pokud je během volání nastavena hodnota).

👍

**Comment by zabak** [comment]
@jkremlacek Je to hotové? Lze zavřít?

**Comment by jkremlacek** [comment]
Ano, zapomněl jsem issue po merg-i zavřít.
