### ISSUE TITLE
Migrace Solr indexu - třídění dle PID sestupně

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#576]
Zdravím,

do migračního procesu Solr indexu přidat setřídění dle PID sestupně. Po přepnutí Krameria na jádro přemigrovaného indexu dostane záložka [Nejnovější] stejný seznam dokumentů jako s předchozím jádrem. V případě nesetřídění je tam náhodný/nechtěný obsah.

Návrh patche pro MigrationUtils.java v příloze.

MD

[MigrationUtils.java.patch.zip](https://github.com/ceskaexpedice/kramerius/files/1699413/MigrationUtils.java.patch.zip)

**Comment by mduda100871** [comment]
Oprava, lepší by bylo zřejmě setřídění dle elementu modified_date než PID.

MD

[MigrationUtils.java.patch.zip](https://github.com/ceskaexpedice/kramerius/files/1699460/MigrationUtils.java.patch.zip)

**Comment by pavel-stastny** [comment]
Byl jeste zjisten problem s prenasenim dynamickych poli  (`dc.identifier`, `mods.shelfLocator`, `mods.physicalLocation`). 

Bude pripraven patch.

**Comment by mduda100871** [comment]
OK, predpokladam, ze bude tedy stacit zbuildovat jen migracni nastroj a necekat na novy build cele aplikace?

Jinak co se tyka jiz zmigrovanych dat pri upgradu na Krameria 5.4.0 - budet tedy potreba znovu migrovat index se stejnym schematem?

MD

**Comment by pavel-stastny** [comment]
> OK, predpokladam, ze bude tedy stacit zbuildovat jen migracni nastroj a necekat na novy build cele aplikace?

Ano

> Jinak co se tyka jiz zmigrovanych dat pri upgradu na Krameria 5.4.0 - budet tedy potreba znovu migrovat index se stejnym schematem?

Znovu zmigrovat z puvodniho indexu

**Comment by mduda100871** [comment]
OK, mozna by se tato issue mela znovu aktivovat, aby ti, co uz index migrovali (a budou znovu), nezahodili ten puvodni. Sam jsem se na to uz chystal...

**Comment by mduda100871** [comment]
+ upozorneni v sekci pro stazeni instalacniho balicku...zalezi jak rychle bude oprava...
