### ISSUE TITLE
Znak \0 v OCR > chyba pri prezentaci vysledku dotazu

### ISSUE THREAD

**Issue by jankanka** [ceskaexpedice/kramerius#577]
Zjistili jsme, že sekvence "\0" (zpetne lomitko nula) v OCR (jakozto vysledek nespravneho rozpoznani) zpusobi problem pri načítání seznamu výsledků dotazu - stranka zustane částečně načtena, ale nedokončí se její zobrazení. Komentář programátora: Konkrétně některá javascriptová knihovna v starém klientovi neumí v určitých prohlížečích korektně pracovat s xml a pokládá xml obsahující uvnitř elementu řetězec "\0" za chybu a spadne na tom.

**Comment by MartinRumanek** [comment]
Ten znak máte uložený v ALTO streamu?

**Comment by jankanka** [comment]
Domnivam se, ze ne, v analyzovanem pripade slo o OCR ze starsi digitalizace, kdy se ještě ALTO nepoužívalo, ale pro jistotu davam do kopie kolegu, který to proveroval.
Jan Kanka

**Comment by rzeh4n** [comment]
Ještě upřesňuji, že se chyba projevuje ve Firefoxu a údajně v IE, v Chromu ne. Znak je z OCR datastramu. Problém byl možná v parsování odpovědi solr:
http://localhost:8983/solr/kramerius/select/?q=PID:\"uuid:9dead5e0-75d1-11dc-a83b-000d606f5dc6\"&wt=xml
a odpověď před ruční opravou a přeindexováním:
[uuid:9dead5e0-75d1-11dc-a83b-000d606f5dc6_solr.xml.txt](https://github.com/ceskaexpedice/kramerius/files/1704102/uuid.9dead5e0-75d1-11dc-a83b-000d606f5dc6_solr.xml.txt)

**Comment by zabak** [comment]
navrhuji zavřít, pokud se vyskytne znovu, tak prosím založit nové issue
