### ISSUE TITLE
Kramerius 6.0.0-alpha - nejde zaindexovat žádný dokument kromě Drobnůstek

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#580]
Všechny ostatní pokusy končí jako FAILED a zaindexuje se pouze top objekt (monograph/periodical).

cz.incad.kramerius.indexer.SolrOperations indexByPid
SEVERE: Error indexing document uuid:...
java.lang.Exception: java.lang.Exception: Fedora Object uuid:... not found. 

- přičemž objekt je page a přes Fedora4 rest API se na něj dostanu, a přes Krameria - Indexace dokumentů - Hledat ve Fedoře - se objekt page taky najde. 

Když se pokusím indexovat přímo danou stránku, tak to opět selže.

**Comment by filak** [comment]
Jiné dokumenty, co se snažím zaindexovat, mají - na rozdíl od Drobnůstek - externí streamy pro IMG_FULL (JPG nebo PDF) - nevím, zda to má na indexační proces nějaký vliv.

**Comment by pavel-stastny** [comment]
vyskytuji se v importnim procesu hlasky typu: Skipping file xxx - not an FOXML object ?  

A sel by prilozit k issue i vypis z procesu importu a indexeru ?
