### ISSUE TITLE
Kramerius 6.0.0-alpha - Indexace dokumentů - Check processing index nefunguje

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#583]
Při spuštění procesu _Check processing index_ se v GUI ukazuje "undefined" a proces skončí chybou.

Caused by: org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:**18080**/rest/data/0ea/a67/309/068/11d/d97/de0/00d/606/f5d/c6 with statusCode: -1 and message: Connect to localhost:18080 [localhost/127.0.0.1] failed: Connection refused: connect

URL je vadná - nerespektuje se nastavení fedora4Host=http://localhost:**8080/fcrepo**

**Comment by pavel-stastny** [comment]
Nedari se chybu reprodukovat. (Proces nastaveni v properties souboru respektuje)

**Comment by filak** [comment]
No kde se ale pak bere to divne cislo portu 18080 ? To musi byt nekde v kodu.

**Comment by pavel-stastny** [comment]
To souvisi s default instalaci.  Defaultne je podporovana fedora jako standalone aplikace viz  https://github.com/ceskaexpedice/kramerius/wiki/Fedora-4,-Kramerius---Instalace-a-migrace-dat#instalace-reposit%C3%A1%C5%99e   a properta je definvana v default configuration properties 
viz  https://github.com/ceskaexpedice/kramerius/blob/fcrepo4/shared/common/src/main/java/res/configuration.properties#L6

**Comment by filak** [comment]
Ano, ale tu property mam nadefinovanou jako ...localhost:8080/fcrepo

**Comment by pavel-stastny** [comment]
Myslim, ze se jedna o zalezitost konkretni instalace. To propertu mas nadefinvanou mimo home adresar uzivatele pod kterym je kramerius spusten a u vsech procesu mas predefinnou promennou  `-Duser.home=<some_tmp_config_dir>`   Tento proces je novy a propertu `user.home` predefinovanou nema, proto bere default nastaveni.
