### ISSUE TITLE
Solr migrace - strankovani 

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#588]
Pro novejsi verze solru (6.x, 7.X) by se mel  vyuzivat `cursor `misto standardniho strankovani  `&rows&start.`.

**Comment by xermak00** [comment]
Dobrý den,

v budoucnu taky bychom velmi potřebovali vyžití cursoru při migraci, viz poslední komentář https://github.com/moravianlibrary/kramerius/issues/246
