### ISSUE TITLE
Chybna reprezentace typu z METS

### ISSUE THREAD

**Issue by petrkr** [ceskaexpedice/kramerius#59]
K4 chybně (ne)zobrazuje typ stránky, například titulní strana, zadní desky apod.

Po pátrání jsme zjistili, že pokud první písmeno v atributu TYPE je velké (například TitlePage) pak to funguje.

Dle specifikace NDK se má používat první písmeno malé, tedy titlePage.

&lt;mets:div ID="DIV_P_PAGE_0000" ORDER="1" ORDERLABEL="[4a]" TYPE="titlePage"&gt;

viz specifikace https://docs.google.com/document/d/1NrMnE7IOXO_v68ISh25wosColW6YafUDvYZ_hLg6cVo/edit

pro zachování kompatibility produkcí různých producentů doporučujeme zajistit case-insensitive.

**Comment by zabak** [comment]
tohle si myslím že bude vyřešeno nasazením nového admin. rozhraní.

**Comment by petrkr** [comment]
Predpokladam, ze todle uz muzeme uzavrit? 7let s krameriem uz nepracuju tak nevim zda se to tehda vyresilo

**Comment by zabak** [comment]
Navrhuji zavřít, zde se řeší jen zobrazování ve starém rozhraní
