### ISSUE TITLE
Neobrazení obrazku celého ročníku

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#592]
Dobrý den,
u jednoho titulu periodika se nam prestal zobrazovat cely rocnik. Jde o periodikum, u nehoz doslo ke konverzi obrazku z fomatu DjVu na JPG pri prechodu na vyssi verzi Krameria. 
Zkouseli jsme smazat rocnik z Fedory  a znovu naimportovat obrazky ve formatu DjVu,ale vysledek je stejny. Pri pokusu stahnout obrazek,vyskoci hlaska:

[Nový textový dokument (5).txt](https://github.com/ceskaexpedice/kramerius/files/1824455/Novy.textovy.dokument.5.txt)

Kdyz otevreme obrazky daneho rocniku (JPG i DjVu) mimo Krameria,tak se zobrazi.
Mohlo by pomoci, kdybychom odstranili rocnik i z indexu nebo kdybychom naimportovali obrazky ve formatu JPG?

Dekuji

Ales Drahotussky

**Comment by Drahotussky** [comment]
[https://camea2.svkos.cz/search/img?uuid=uuid:e4cb2500-04af-11de-9af2-0013d398622b&stream=IMG_FULL&action=GETRAW&asFile=true](url)

**Comment by pavel-stastny** [comment]
Dobry den, 

to vypada na spatne definovany odkaz na IIPImage server.  Zkontrolujte si, prosim, url definovanou u streamu` IMG_FULL`.
