### ISSUE TITLE
Kramerius 6 - replikace a import FOXML - FAIL

### ISSUE THREAD

**Issue by zafan** [ceskaexpedice/kramerius#595]
Vyzkoušeli jsme několik veřejných i neveřejných dokumentů na K6 import i replikaci z K5.

Některé dokumenty se importovaly/replikovaly:
* v pořádku
* s varováním, ale podařilo se je zaindexovat: [policy_warning_a2e5c470.log](https://github.com/ceskaexpedice/kramerius/files/1838224/policy_warning_a2e5c470.log)
* neúspěšně: [biblio_mods_fail_df196150.log](https://github.com/ceskaexpedice/kramerius/files/1838220/biblio_mods_fail_df196150.log) a [policy_fail_2f3e6880.log](https://github.com/ceskaexpedice/kramerius/files/1838222/policy_fail_2f3e6880.log)

V případě potřeby můžeme poskytnout vzorová data i další logy.

---

### Konkrétní případ

Při neúspěšném importu se nahraje jen část dat do Fedory (platí pro replikaci i import), výsledná neúplná data ve Fedoře nemohou být zaindexována.

1. Replikace vyústí v: [cannot_create_obj_530719f5.log](https://github.com/ceskaexpedice/kramerius/files/1838245/cannot_create_obj_530719f5.log)

2. následně indexace replikovaného obsahu: [not_found_530719f5.log](https://github.com/ceskaexpedice/kramerius/files/1838241/not_found_530719f5.log)

3. Při opakovaném importu dokumentu dokument projde s varováním: [warn_already_exist_530719f5.log](https://github.com/ceskaexpedice/kramerius/files/1838275/warn_already_exist_530719f5.log)

4. Následné indexování dokumentu projde v pořádku: [succ_index_530719f5.log](https://github.com/ceskaexpedice/kramerius/files/1838281/succ_index_530719f5.log)

**Comment by pavel-stastny** [comment]
Dobry den, 

slo by ziskat foxml objektu, ktere se nepodarilo naimportovat ?

**Comment by zafan** [comment]
Dobrý den,

posílám foxml dvou dokumentů, které se nepodařilo naimportovat.

* [530719f5-ee95-4449-8ce7-12b0f4cadb22.tar.gz](https://github.com/ceskaexpedice/kramerius/files/1846702/530719f5-ee95-4449-8ce7-12b0f4cadb22.tar.gz)
* [df196150-64dd-11e4-b42a-005056827e52.tar.gz](https://github.com/ceskaexpedice/kramerius/files/1846704/df196150-64dd-11e4-b42a-005056827e52.tar.gz)

**Comment by pavel-stastny** [comment]
Dobry den, 

nedari se mi u tech dvou titulu navodit chybu.  Prvni mi prochazi bez problemu, u druheho jsem musel zmenit odkazy na image server, ale po zmene prochazi  taky prochazi bez problemu (Import i indexace).  

Jenom se chci ujistit.  Chyby Vam u techto titulu hazel i import nebo jenom replikace ?

**Comment by zafan** [comment]
U prvního se nedaří naimportovat při čisté instalaci K6, replikovat se nedaří vůbec a druhý selhává při replikaci.

**Comment by pavel-stastny** [comment]
Porad se mi to nedari navodit.  Cista instalace K6, zkousim ve dvou ruznych variantach (fedora 4 jako samostatny server, fedora 4 jako war v tomcatu) a import mi probehne. Stejne tak indexace.    Muzete mi poslat (treba mailem) log z tomcatu ? 

Dekuji

**Comment by zafan** [comment]
Log odeslán na mail.
