### ISSUE TITLE
Kramerius 6 - import NDK METS out of memory

### ISSUE THREAD

**Issue by zafan** [ceskaexpedice/kramerius#596]
Dobrý den,

nedaří se mi importovat METS balík do K6, vždy skončí s out of memory exception.

K6 verze 6.0.1-alpha rev: [7c12](https://github.com/ceskaexpedice/kramerius/commit/7c1247dc331c8ea7d160e0419412ba13f54813b7)

log: [stdout.out.log](https://github.com/ceskaexpedice/kramerius/files/1898442/stdout.out.log)

**Comment by pavel-stastny** [comment]
Dobry den,

pridejte, prosim, pameti konverznimu procesu.   Staci predefinohvat v `lp.xml` nasledujicim zpusobem: 
```
...
 <!-- Import NDK METS data  -->
    <process>
        <id>ndkmets</id>
        <description>Import NDK METs</description>
        <mainClass>org.kramerius.importmets.parametrized.ParametrizedMetsNKDImport</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <javaProcessParameters>-Xmx4096m -Xms512m</javaProcessParameters>
        
        <templates>
            <input class="org.kramerius.importmets.parametrized.input.MetsImportInputTemplate"></input>
        </templates>

        <securedaction>ndk_mets_import</securedaction>
        
    </process>
....
```

Pripadne pridat jeste vic, pokud ani ty 4GB nebudou stacit.

**Comment by pavel-stastny** [comment]
No, lze opet pridat vic pameti procesu index. Stejnym zpusobem jako u toho predchoziho, nicmene pokud je to vetsi  soubor JP2000 a pak nasledne vlozeny JPEG, je mozna lepsi vyuzit IIP server.   Jak velky je IMG_FULL ?

**Comment by pavel-stastny** [comment]
Jeste poznamku k reindexaci. Pokud chcete  predefinovat i ten proces reindexace, tak by to vypadalo nejak takto: 
```
....
    <!-- Index & Reindex process -->
    <process>
        <id>reindex</id>
        <description>Reindexace</description>
        <mainClass>cz.incad.kramerius.indexer.Main</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <javaProcessParameters>-Xmx16g -Xms512m</javaProcessParameters>

    </process>
...
```

**Comment by zafan** [comment]
Velikost toho JP2 je (mastercopy) 467 MB + (usercopy) 467 MB. 

Co se toho škálování týče, víc už ani dát nemohu...

**Comment by pavel-stastny** [comment]
> Velikost toho JP2 je (mastercopy) 467 MB + (usercopy) 467 MB.

To je strasne velky, kdyz do date do Fedory, tak si s tim zadny klient neporadi.   JP2 soubory jsou pouzivany predevsim v kombinaci s IIP Serverem, jinak to nedava moc smysl.  (Nebo konvertovat na jpeg pri ingestu. )  

> Co se toho škálování týče, víc už ani dát nemohu...

Ted nevim, co tim bylo mysleno.  Ja v tom puvodnim komentari  narvhoval zvetsit velikost procesu  `reindex`.   To je jiny proces, nez ten importni.

**Comment by MartinRumanek** [comment]
Jak je nakonfigurovaný migration.properties? Na MZK produkci se jpeg2000 standardně kopírují do imageserveru - konfiguroval jsem to spolu s @kenji1322 .

**Comment by kenji1322** [comment]
Je to tak ako vravíš, na produkcii sa JP2 kopírujú na imageserver.
Rovnaký problem sa vyskytuje ako aj u nás na produkcii tak aj na v K6 kde to @zafan tiež testoval.

**Comment by pavel-stastny** [comment]
Ted jsem z toho trosku zmateny.  Je to tak, ze na produkci pro import do ostreho  Krameria pouzivate NDK-METS balicky nebo ciste FOXML? A druha otazka:  Ten problem s OOM se Vam objevuje u tohoto jednoho balicku nebo u vsech ?

**Comment by jkremlacek** [comment]
Import do ostreho Krameria probiha jak pomoci NDK-METS, tak FOXML (duvodem je neschopnost ProArc-u vygenerovat ciste FOXML pro velké mapy, takze pro ne se pouziva NDK-METS).

Chyba se projevovala pouze u nejvetsich balicku. (> 900MB+-)
