### ISSUE TITLE
Nastavení importu - přepis metadat

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#598]
Hodilo by se, kdyby bylo možné nastavit při importu do Krameria, aby se u opětovně importovaného dokumentu dala jen přepsat metadata. Bylo by to hlavně mnohem rychlejší při opravách chyb, kdy teď se musí celý dokument smazat a znovu naimportovat, což zabírá čas. 

Problém by byl akorát s nastavením policy, takže pokud by byl dokument původně neveřejný a pak by se to třeba v ProArcu změnilo na veřejný a importovalo se do Krameria pouze s přepisem metadat, tak by v mets záznamu byly dvě různé hodnoty policy. Což by prý šlo vyřešit takto (citace p. Dudy):

"importni proces se v pripade, ze zjisti, ze uuid uz ve Fedore je, a je v modu nahrazovani, pokusi sladit policy s nastavenim v RELS-EXT, coz zrejme znamena upravu xml nekde v pameti a nasledne marshall zpatky do xml a ulozeni do datastreamu DC - vyhoda je, ze eliminujeme lidsky faktor, ale narocnejsi to bude strojove"

**Comment by pavel-stastny** [comment]
Vyresime to jako parametr importniho procesu a bude pritomny v pristim buildu Krameria.

**Comment by pavel-stastny** [comment]
- Je mozne prepisovat streamy `DC` a `BIBLIO_MODS`
- Pokud je v K5 ve streamu `DC` v elementu `rights` nejaka hodnota (public | private), pak zustava zachovana - neprepisuje se

**Comment by krizovj** [comment]
Mohl by mi prosím někdo odpovědět (pokud na to existuje odpověď a není to další náhodná věc, kterou Kramerius dělá a nikdo neví proč)? Děkuji

**Comment by pavel-stastny** [comment]
Zelezi na tom, okdud si dany klient (prepokladam ze admin) taha informaci pro zobrazeni. (Jestli primo z fedory nebo z indexu.)  Lip odpovedet nedokazu.  Kdyz mi pripravite dva balicky, ktere muzu importovat,  muzu vyzkouset a dam vedet.
