### ISSUE TITLE
Vynechávání členů v názvech cizojazyčných publikací

### ISSUE THREAD

**Issue by PavlinaKocisova** [ceskaexpedice/kramerius#599]
Dobrý den, chtěli bychom se zeptat, je normální, že Kramerius nezobrazuje členy v názvech cizojazyčných publikací? Existují nějaké stop-slovníky, které automaticky tyto slova filtrují a odstraňují? Máme ve svém Krameriu publikace, které v xml mají celý název, ale ve stromu složek dokumentu už se zobrazují bez členů. 

Dá se s tím něco z naší strany dělat? Děkujeme.
Pavlína Kočišová, NKP

příklady:
http://kramerius4.nkp.cz/search/i.jsp?pid=uuid:e07b5577-0cd8-4194-929b-e105e60ff3d4#monograph-page_uuid:0310f470-3c16-11e8-a7aa-005056825209

http://kramerius4.nkp.cz/search/i.jsp?pid=uuid:c69d23f2-2440-46b5-9491-719b305f49f9

**Comment by pavel-stastny** [comment]
Dobry den, 

ten nazev mate bez clenu vyplneny v DC metadatech.  
`<dc:title>price for peace</dc:title>`
`<dc:title>contrôle du crédit dans l'intérêt social</dc:title>`

http://kramerius4.nkp.cz/search/api/v5.0/item/uuid:c69d23f2-2440-46b5-9491-719b305f49f9/streams/DC
http://kramerius4.nkp.cz/search/api/v5.0/item/uuid:e07b5577-0cd8-4194-929b-e105e60ff3d4/streams/DC

**Comment by zabak** [comment]
týká se starého klienta, navrhuji zavřít
