### ISSUE TITLE
Editor částí - nefunkční

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#600]
Zdravím,
zjistil jsem, že editor částí přibundlovaný k distribučnímu balíčku verze 5.4.1 nefunguje. Po vybrání příslušné úrovně ve stromu titulu a vyvoláním editoru částí z kontextového menu vypadne výjimka:
...
![vyjimka](https://user-images.githubusercontent.com/8750622/40099132-033ec388-58df-11e8-83fc-a4562b93ed32.PNG)
...
podle zvýrazněného řádku to vypadá, jako by někde natvrdo v kódu editoru bylo volání neplatného linku. 
Stejné chování jsem ověřil na dvou nezávislých instancích Krameria.

MD

**Comment by mduda100871** [comment]
Zdravím,
trochu jsem se posunul. Oficiální kompilace editoru stále nefunguje. Stáhl jsem tedy aktuální zdrojový kód editoru a přeložil lokálně u sebe příkazem:
...
$ gradle war -x test
...
Po nainstalování na testovacím serveru můj lokální překlad editoru normálně funguje...dokonce se po provedené změně v pořadí vazeb a uložení automaticky spustí reindexace, což mám dojem, že se mi u starších verzí nikdy nepodařilo docílit a reindexace se musela pustit ručně.

Výše uvedené mě tedy vede k závěru, který jsem naznačil už poprvé - do oficiálního instalačního balíčku se zřejmě dostal nějaký testovací kód s "natvrdo" zakódovaným číslem portu na loopbacku.

Může to prosím někdo z vývojářů potvrdit nebo vyvrátit? Pokud se mé podezření potvrdí, bylo by dobré to co nejdříve v oficiálním balíčku opravit...

Díky, MD

**Comment by xermak00** [comment]
Dobry den,

nahodou jsem narazil na toto issue, to co ted je na [githubu editora](https://github.com/ceskaexpedice/editor) jsem opravoval v unoru, kdyz resil problem v ramci issues  moravianlibrary/kramerius#245, moravianlibrary/kramerius#237 a ceskaexpedice/kramerius#513. Zmenil jsem build editoru z Mavenu na Gradle, a ten pri spusteni stahuje a compiluje aktuální knihovny z [ceskaexpedice/kramerius](https://github.com/ceskaexpedice/kramerius). Jaka je ted verze editoru v aktualnim Krameriovi nevim, ale myslim ze je treba editor aktualizovat.

Dekuji,
Aleksei
