### ISSUE TITLE
GDPR - požadavek na anonymizaci IP při trackování statistik přes GA

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#601]
Dobrý den,

v rámci podmínek GDPR nám přišel požadavek na anonymizaci ip adresy při sbírání dat přes Google Analytics. Prosím o přidání této feature do Kraméria - myslím, že se to bude týkat všech, kdo používají GA.

Howto:
https://support.ryte.com/hc/en-us/articles/211084323-Why-is-the-google-analytics-IP-anonymization-integration-not-detected-

Mělo by tudíž stačit přidat řádek '_gaq.push(['_gat._anonymizeIp']);' do souboru webapps/search/inc/footer.jsp

**Comment by svetlym** [comment]
Dobrý den,

dodatečně jsem si uvědomil, že navrhovaná úprava by se vlastně týkala pouze starého K4 rozhraní, které už nedáváme k dispozici čtenářům, takže nemá moc velký smysl ji dělat.

Tuto issue je tedy možno uzavřít, tohle budeme muset vyřešit v klientovi.

**Comment by zabak** [comment]
řešeno v novém klientovi https://github.com/ceskaexpedice/kramerius-web-client/issues/412 zde prosím zavřít
