### ISSUE TITLE
K5 (5.4.1 - patch) problém s konfigurací / javascript

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#605]
Zdravím,

zjistil jsem, že když je jádro Krameria nakonfigurované, aby komunikovalo s Tomcatem na loopbacku napřímo, konkrétně properta "_fedoraTomcatHost=http://localhost:8080", tak se tato adresa "dostává" až do prohlížeče uživatele a způsobuje chybu, viz screenshot v příloze:
...
![k5-01](https://user-images.githubusercontent.com/8750622/41215693-d590477c-6d51-11e8-8cf4-a3e00e757bd1.png)
...

Pokud výse uvedenou propertu nastavím na "oficiální" URL serveru (např.: "_fedoraTomcatHost=https://dlib-core.lib.cas.cz/"), kde mám prostřednictvím mod_proxy_ajp zpřístupněno API Fedory, tak to funguje bez problému, viz screenshot v příloze:
...
![k5-02](https://user-images.githubusercontent.com/8750622/41215827-65870276-6d52-11e8-999c-7c69f67a8827.png)
...

A dále, v distribuci je  obsažen stále odkaz na neexistující skript mods.js, konkrétně v "inc/details/contextMenu.jsp", který způsobuje opět chybu na straně prohlížeče, viz screenshot v příloze:
...
![k5-03](https://user-images.githubusercontent.com/8750622/41216245-c5f6226c-6d53-11e8-8f38-3e292e43d1a8.png)
...
Když volání scriptu mods.js odstraním, chyba zmizí - bylo by tedy dobré to v dalším releasu odstranit natrvalo...

Díky, MD

**Comment by pavelkocourek** [comment]
Je to Martine prosím aktuální?

**Comment by zabak** [comment]
Zavírám, když tak prosím nahlásit znovu pro K7
