### ISSUE TITLE
Kramerius 6 - Admin UI

### ISSUE THREAD

**Issue by fstepanovsky** [ceskaexpedice/kramerius#607]
Dobrý den,

před plný nasazením by bylo vhodné se i podívat na ,,kosmetické záležitosti":

* - [ ] logo K5 zmenit na K6

* - [ ] při přihlašování změnit text ,,Přihlášení do systému K4" a ,, Přihlášení je určeno ... Kramerius 4"

* - [ ] ©2008-2012 v patičce

* - [ ] U plánování replikace Kramerius->Kramerius se zobrazuje text ,,Undefined"

* - [ ] V ,,Indexace dokumentů" -> ,,Další" bych navrhoval upravit název ,,index_pid" tlačítka 

* - [ ]  Rozpadlá tlačítka sociálních médií (Facebook chybí), Twitter je link

Toto issue je minoritní, ale chtělo by ho vyřešit před vydáním ostré verze.

**Comment by pavel-stastny** [comment]
Tyka se Krameria 6 - bude provedena zmena  uloziste - nyni neaktualni.

**Comment by zabak** [comment]
Je ale dobrý nápad zavírat issue které bude potřeba vyřešit? Dejte tomu spíš label postponed ale nechte to otevřené, jinak to budeme za rok řešit znova.

**Comment by fstepanovsky** [comment]
Dobrý den,

připomínám toto issue, které je stále platné.
