### ISSUE TITLE
K5 - problém s češtinou v IE11 při vyhledávání uvnitř dokumentu

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#608]
Narazil jsem na problém s českými znaky při vyhledávání uvnitř dokumentu v Internetu Exploreru 11

Např. u dokumentu http://kramerius4.nkp.cz/search/i.jsp?pid=uuid:2541c480-d3d8-11e2-92ff-001018b5eb5c&q=%C5%BEdanov%20ivan#periodical-periodicalvolume-periodicalitem-page_uuid:25716000-d3d8-11e2-92ff-001018b5eb5c při zadání "ždanov ivan" se nezobrazí žádné výsledky. V Chrome normálně vyhledá.

**Comment by pavelkocourek** [comment]
bude pravděpodobně vyřešeno s nasazením nového klienta
