### ISSUE TITLE
Rozšíření počtu snímků v exportním PDF

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#61]
Dobrý den,
zkoušeli jsme funkci Export do PDF u jednoho rocniku periodika. Zadali jsme jako medium DVD. Proces nam skončil jako Warning, ale ve výsledku se objevilo v exportnim souboru na serveru několik PDF souborů, do kterých se ročník periodika rozsekal. Do jednoho PDF se vešlo max. 36 snímků.
Lze, a pokud ano kde, nastavit větší kapacitu PDF souboru?

Přikládám chybové hlášení:
file:/usr/share/tomcat6/.kramerius4/templates//template_static_export.0.1.xslt; Line #143; Column #77; Can not load requested doc: http://localhost:8080/search//i18?action=bundle&amp;lang=cs&amp;country=CZ&amp;name=base
Jan 21, 2014 12:18:19 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system error file contains errors
    at cz.incad.kramerius.processes.impl.ProcessStarter.checkErrorFile(ProcessStarter.java:183)
    at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:125)

Děkuji

**Comment by MartinRumanek** [comment]
V MZK nám zase statický export PDF (nad monografií obsahující obrázky v imageserveru) vyhazuje chybovou hlášku

```
May 22, 2017 8:41:13 AM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cz.incad.kramerius.processes.impl.ProcessStarter.main(ProcessStarter.java:120)
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at cz.incad.kramerius.lp.PDFExport.main(PDFExport.java:79)
	at cz.incad.kramerius.lp.ParametrizedPDFExport.process(ParametrizedPDFExport.java:40)
	... 5 more
```
ačkoliv normální generování PDF (stažení nebo API) funguje v pořádku.  

V MZK ověříme, čím chyba vzniká, ale skutečně chceme do budoucna udržovat několik způsobů generování PDF?

**Comment by vlahoda** [comment]
Podle stacktrace je chyba způsobena tím, že je null šestý parametr toho procesu PDFExport - parametry jsou definované v šabloně lp.st, tak je asi něco špatně tam, jak ostatně zmiňuje Pavel o nějaký komentář výše. 
Jestli je potřeba udržovat více způsobů generování PDF musí rozhodnout knihovníci. Tzv. statický export byl vytvořen na základě jejich požadavku jako náhrada funkce statického exportu K3, kde se takto exportovaly statické HTML stránky (jakýsi offline mód K3) - to v single-page aplikaci K4 nedávalo smysl, jako kompromis tedy vznikl tento export celého titulu ve formátu PDF (na serveru), který se pak dal distribuovat na DVD. Pokud vím, používá to jen ostravská knihovna. 
Standardní PDF export má sloužit k exportu několika málo stránek pro vlastní potřebu čtenáře,  je sice také připraven na serveru, ale stahuje se na klientskou stanici.

**Comment by MartinRumanek** [comment]
Díky. Šablonu máme defaultní, chyba je nakonec trochu jinde. 
Měl jsem Kramerius přeplý do anglické lokalizace :-)

Šestý parametr je:
```
@ParameterName("country") String country
```
A některé locales nemusí mít `country` definováno (viz http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getCountry())

Mám na to připravený fix, ale pošlu to až s dalšími změnami (nechce se mi zakládat pull-request pro dvouřádkový commit).

**Comment by pavel-stastny** [comment]
Pridan parametr `static.export.filelimit=xxx`, ktery urcuje velikost jednoho souboru
