### ISSUE TITLE
K6 - Selhání replikace v případě více procesů

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#614]
Při nastavení většího (9) množství souběžných replikačních procesů (k chybě při 2 souběžných procesech nedocházelo) dojde k zablokování F4 s chybou `This store is closed`.

Log fedory v momentě nastání chyby:
https://gist.github.com/zafan/886af99116b5d4e804aa4837a171bef9

Následně spadnou všechny běžící procesy. (chyba je obdobná u všech procesů, zde dávám jednu z nich)
https://gist.github.com/jkremlacek/2eb4057359eac93a152113039c6ba0a2

----

Další problém je, že pokud s takto "zaseknutou" F4 dojde ke spuštění dalšího replikačního procesu (nechali jsme 20 minut "pauzu" od pádu předchozích replikačních procesů), tak replikační proces navzdory chybám:
```
java.lang.RuntimeException: cz.incad.kramerius.fedora.om.RepositoryException: cannot create object :500
```
běží dál, aniž by se mu podařilo cokoliv vložit do F4.

Log replikačního procesu krameria:
https://gist.github.com/jkremlacek/175831e40f1ee7a0c0085b7f89f34cda

**Comment by pavelkocourek** [comment]
Bude řešeno s novým úložištěm

**Comment by zabak** [comment]
V K7 není fedora, pokud by problém přetrvával, založí se nové issue
