### ISSUE TITLE
Problémy s autentizací na nejnovějším Tomcatu 8.5/9.0 (8.5.32)(9.0.9(?))

### ISSUE THREAD

**Issue by mjtecka** [ceskaexpedice/kramerius#617]
Dobrý den,

zkouším Kramerius 6.0.1-alpha narazil jsem na problémy s nefunkční autentizací na nejnovějším Tomcatu 8.5.32. 

Používám docker image a zatímco mi autentizace fungovala s T 8.5.31, novejší container s T8.5.32 už se přihlásit nedokázal...

Zapnul jsem si logování pomocí proměnné *-Djava.security.debug=all* a zjistil jsem, že se sice úspěšně přihlašuju:

    configparser: 	Reading next config entry: search
    configparser: 		cz.incad.kramerius.security.jaas.K4LoginModule, REQUIRED 
    configparser: 			debug=true
    configparser: 	Reading next config entry: rightseditor
    configparser: 		cz.incad.kramerius.security.jaas.K4LoginModule, REQUIRED
    configparser: 			debug=true
    Provider: MessageDigest.SHA algorithm from: SUN
     	[LoginContext]: login success 
    	[LoginContext]: commit success
...ale tím log končí a přihlášení vrací "chybu autentizace". 

Původně jsem měl za to, že to může být nějakým mým nastavením, ale nakonec jsem si všiml, že ve verzi 8.5.32 došlo k nějaké změně ohledně JAAS (https://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.32_(markt) ) Takže jsem zkusil použít Tomcat 8.5.31 a v něm autentizace s naprosto stejnou konfigurací funguje.

MJ.

**Comment by mjtecka** [comment]
.. a protože jsem si poněkud pozdě všiml, že K6-α má v požadavcích Tomcat 9, dodávám, že stejný problém zřejmě nastane při použítí Tomcat 9.0.11. Tipnul bych si, že to nepůjde od 9.0.9, kdy byla provedena stejná úprava v JAAS jako výše  (9.0.8 funguje)

**Comment by MartinRumanek** [comment]
V context.xml chybělo class name pro uživatele


> This Realm will be configured with two lists of fully qualified Java class names of classes that implement java.security.Principal - one that identifies class(es) representing a user, and one that identifies class(es) representing a security role.

http://tomcat.apache.org/tomcat-9.0-doc/api/index.html

Nevím, jestli to zafunguje v rightseditor

Opravil jsem to zatím v Krameriu 5, možná si budete muset context aplikace (search.xml) dle context.xml, který je obsažen v posledním commitu.

Pokud to bude funkční zamerguju do i do 6.

Btw. zkoušel jste i rightseditor? V Tomcatu 9.0.11 mi vrací bílou stránku, to ale bude zřejmě jiný bug.

**Comment by mjtecka** [comment]
> Btw. zkoušel jste i rightseditor? V Tomcatu 9.0.11 mi vrací bílou stránku, to ale bude zřejmě jiný bug.

Předtím jsem to nezkoušel, nicméně v kombinaci K6.0.1-alpha a Tomcat 9.0.8 mi přihlášení k rightseditoru funguje.

**Comment by rzeh4n** [comment]
U Tomcat 8.5.37 a Kramerius 5.4.2 je situace stejná, pomůže doplnění userClassNames do tomcat/conf/Catalina/search.xml takto:
```
<Context>
        <Realm  
        className="org.apache.catalina.realm.JAASRealm"
        roleClassNames="cz.incad.kramerius.security.jaas.K4RolePrincipal"
        userClassNames="cz.incad.kramerius.security.jaas.K4User"
        appName="search" 
        debug="99"
        />
</Context>
```
Ještě by bylo dobré to doplnit do dokumentace na https://github.com/ceskaexpedice/kramerius/wiki/PrikladKonfigurace

**Comment by vlahoda** [comment]
Dokumentace doplněna. Díky za upozornění.

**Comment by MartinRumanek** [comment]
@vlahoda Díky, byl jsi rychlejší. Rightseditor je v pořádku (testoval jsem to). Issue se může teda zavřít.
