### ISSUE TITLE
[Dotaz] Konfigurace Oai4Solr

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#618]
Dobrý den,
potřeboval bych poradit s konfigurací pluginu oai pro SOLR 6. Postupoval jsem podle dokumentace (https://github.com/ceskaexpedice/kramerius/tree/master/installation/oai), ale pak se setkávám s touto chybou:

java.lang.NoSuchMethodError: org.apache.solr.core.SolrResourceLoader.locateSolrHome()Ljava/lang/String;

Už mi dochází nápady, čím by to mohlo být. Ověřil jsem přístupová práva, umístění ve složkách, konfigurace by podle mě měla být také správně.

Konfigurace:
    -Djetty.home=/opt/solr/server
    -Djetty.port=8983
    -Dlog4j.configuration=file:/data/fata5/solr/log4j.properties
    -Dsolr.install.dir=/opt/solr
    -Dsolr.log.dir=/data/fata5/solr/logs
    -Dsolr.log.muteconsole
    -Dsolr.solr.home=/data/fata5/solr/data

Struktura solr_home:

/data/fata5/solr/data
├── kramerius
│   ├── conf
│   └── data
│       ├── index
│       ├── snapshot_metadata
│       └── tlog
├── lib
└── oai

Celý výstup z logu a solrconfig:
[solr.log](https://github.com/ceskaexpedice/kramerius/files/2356308/solr.log)
[solrconfig.txt](https://github.com/ceskaexpedice/kramerius/files/2356314/solrconfig.txt)

**Comment by MartinRumanek** [comment]
Ta knihovna v návodu je verze oai2-plugin-3.1.jar a je funkční pouze pro SOLR 3. 

SOLR 6 má trochu jiné API, proto vám to vyhazuje NoSuchMethodException.

Návod pro SOLR6 a plugin jsem kdysi připravil tady https://github.com/ceskaexpedice/kramerius/tree/oai4solr6/installation/oai4solr6. Vyzkoušíte to prosím?

**Comment by jdobiasovsky** [comment]
Vyzkoušeno, už nám to odpovídá. Díky moc  :thumbsup:
