### ISSUE TITLE
Reindexace uuid bez potomků - do admin rozhraní

### ISSUE THREAD

**Issue by LenkaKravecova** [ceskaexpedice/kramerius#620]
Navazuji na uzavřené issue https://github.com/ceskaexpedice/kramerius/issues/542. Bylo by dobré a velmi užitečné, aby v admin rozhraní byla možnost reindexace uuid bez potomků (tedy bez stránek / ročníků / čísel..). Využije se to třeba, když se změní jen MODS a není potřeba reindexovat stránky, anebo když se mění viditelnost u titulního uuid periodika, které má část ročníků veřejné, a nechceme, aby se reindexovalo celé periodikum. Tuto změnu by měl být schopný provádět i admin knihovník.

**Comment by vjirousek** [comment]
Ano, toto by se nám v NK též velmi hodilo, při zveřejňování titulů určitě. Jen si nejsem jistý jak by měla probíhat změna MODS. To souvisí s tímto ticketem? https://github.com/ceskaexpedice/kramerius/issues/598?

**Comment by pavel-stastny** [comment]
V admin rozhraní již řešeno volbou "Jen objekt"

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/ba4ba98e-b926-45ec-bcce-08e195cf4a0d)
