### ISSUE TITLE
Pomalé načítání admin. rozhraní virtuálních sbírek

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#621]
Při přístupu do admin. rozhraní virtuálních sbírek skrze UI ( Více... - Administrace virtuálních sbírek ... ) trvá načítání seznamu hodně dlouho (71s, 88s, 85s, 83s).

Zkoušel jsem VS načíst skrze API a došel jsem k podobným časům (81s, 69s, 81s, 78s).
(search/api/v5.0/admin/vc).

**Comment by pavel-stastny** [comment]
Dobry den, 

to bude problem.  Nacitani sbirek v admin rozhrani zavisi na rychlosti resource indexu (MPT store) a ten byva pri vetsich objemech pomaly.  V Kram 6 a naslednych verzich se uz pocita s tim, ze se od resource indexu upusti.   Jeho funkci prevezme pomocny `processing` index.

**Comment by zabak** [comment]
cca v květnu jsme vkládali k virtuálním sbírkám reprezentativní obrázky a anotace a tehdy to bylo sice pomalé, ale šlo to. Je nám divné, že se to tak zhoršilo za tak krátkou dobu.

**Comment by pavelkocourek** [comment]
Souvisí s #649

**Comment by pavel-stastny** [comment]
V nynejsi verzi Krameria je processing index jiz nahrazen standardnim solr indexem. Po prechodu by se problemy s rychlosti objevovat nemely.
