### ISSUE TITLE
Problém s indexováním mapy - severní vs jižní šířka

### ISSUE THREAD

**Issue by mjtecka** [ceskaexpedice/kramerius#622]
Dobrý den,

narážím na problém při indexaci mapy se souřadnicemi:
178°35´37" v.d.--169°27´11" v.d./083°54´18" s.š.--084°44´18" j.š.

SOLR hlásí chybu: 
```
2018-09-05 12:39:24.141 ERROR (qtp2045766957-15) [   x:kramerius] o.a.s.h.RequestHandlerBase 
org.apache.solr.common.SolrException: ERROR: [doc=uuid:99d1d37a-b108-11e8-96cd-001b63bd9
7ba] Error adding field 'range'='ENVELOPE(178.59360999999998,169.45306,83.905,84.73832999999999)' 
   msg=Unable to parse shape given formats "lat,lon", "x y" or as WKT because 
   org.locationtech.spatial4j.exception.InvalidShapeException: maxY must be >= minY: 84.73832999999999 to 83.905 input: 
   ENVELOPE(178.59360999999998,169.45306,83.905,84.73832999999999)
```

Zdá se mi, že se při tvorbě souřadnic nebere v potaz severní / jižní šířka. Je to chyba v zápisu souřadnic, nebo se to špatně zpracovává v Krameriovi (jestli správně chápu zdroják, tak by tam mělo být -84.73... u jižní šířky)?

Problém mám u verze 6.0.1-alpha

**Comment by pavel-stastny** [comment]
Tato chyba se tyka pouze verze 6.X.  Provedeme merge do vetve.

**Comment by pavel-stastny** [comment]
reseno v ramci 17f3cee3f2ffbdb2d0b5acbf53b8da10f821093e
