### ISSUE TITLE
Ignorování odpovědi serveru v případě chyby při generování PDF

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#624]
V případě, že uživatel zadá generování PDF a na serveru dojde k chybě (např 504), pak klient i nadále zobrazuje okno s `Příprava generování PDF dokumentu. Čekejte prosím...` (webový prohlížeč odpověď 504 dostane a je viditelná v network monitoru).

Stejná chyba se děje i u ostatních oken tohoto typu (např. zobrazení seznamu virtuálních sbírek)

**Comment by zabak** [comment]
Předpokládám, že toto je týká starého GUI a lze zavřít.
