### ISSUE TITLE
Návrh na úpravu v novém rozhraní/API - asynchronní zadávání požadavků

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#625]
Uživatelské funkce generování PDF, práce s virtuálními sbírkami... by mohly být zpracovávány asynchronně.

Klient by při zadání požadavku, namísto čekání na dokončení, dostal okamžitě potvrzení o přijetí požadavku s identifikátorem (podobně jako u admin. procesů) a následně by se klient mohl s daným identifikátorem dotazovat na stav požadavku (např v případě PDF na jaké straně generování momentálně probíhá) a v případě dokončeného požadavku by si mohl stáhnout jeho výstupní data. Výstupní data by mohla být např uložena v nějakém dočasném "úložišti", které by bylo podle nakonfigurovatelné doby pravidelně čištěno, aby nedošlo k zahlcení disku.

**Comment by zabak** [comment]
Souvisí s https://github.com/ceskaexpedice/kramerius-web-client/issues/50 a dalšími. Mělo by se řešit zároveň

**Comment by kazooo** [comment]
Narazil jsem na [endpoint v Krameriu](https://github.com/ceskaexpedice/kramerius/blob/master/rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/pdf/AsyncPDFResource.java), který pravděpodobně byl funkční v minulosti a generoval PDF asynchronně. Ted' je napůl okomentovaný a leží mrtvým kódem i když je [popsány ve Wiki](https://github.com/ceskaexpedice/kramerius/wiki/ClientAPIDEV#asyncpdfresource).  Dalo by se ho oživit?

**Comment by pavel-stastny** [comment]
Jo, zkusíme to zakomponovat do příštího buildu.

**Comment by pavelkocourek** [comment]
@pavel-stastny Pavle bylo to zařazeno do buildu-můžeme zavřít?

**Comment by pavel-stastny** [comment]
Již není aktuální
