### ISSUE TITLE
Reprezentativní strana - možnost zadat v Krameriovi

### ISSUE THREAD

**Issue by pavelkocourek** [ceskaexpedice/kramerius#626]
Na schůzce k ProArcu  2.11. byl přesměrován požadavek na **možnost označení reprezentativní strany** do Krameria. Může to být součásti Editace pořadí stran.

**Comment by honza-rychtar** [comment]
A rozhodnutí, že se příznak reprezentativní strany bude určovat zdola, tj. na úrovni strany zůstává?
Tohle řešení nebude fungovat pro periodika, bude složítá aktualizace a vznikne možnost konfliktů.

Když už se to bude řešit v Krameriovi, tak by se mohlo přehodnotit i určování reprezentativní strany, aby se reprezentativní strana určovala naopak shora, tj. k objektu by byla přiřazena reprezentativní strana.
Tohle je univerzální, jednodušší a bezkonfliktní. Stačí přidat RELS-EXT vazbu has_representative_page s uuid pro libovolnou stránku. Pokud vazba chybí, tak se použije nynější výchozí chování.

**Comment by pavelkocourek** [comment]
Probráno na schůzce 2.11. - souhlas. K objektu bude přiřazena reprezentativní strana.

**Comment by pavel-stastny** [comment]
Hmm.. Slo by to resit i pres obrazkove data streamy.  Uz ted, kdyz se zeptam na nahled pro monografii, tak se nejdriv diva  na to jestli objekt monografie nema prirazeny IMG_THUMB, pokud ne, vrati IMG_THUMB prvni stranky.

**Comment by honza-rychtar** [comment]
No vida, takže reprezentativní strana vlastně už funguje, jen ji není jak přiřadit.

**Comment by krizovj** [comment]
A ta rels-ext vazba se tam přidá třeba v tom editoru částí, nebo někde jinde v adminu Krameria? 
Takže pokud si určím nějakou stránku jako reprezentativní už v ProArcu (až to půjde), tak to stejně budu muset udělat ještě jednou v Krameriovi, nebo to Kramerius na základě toho MODSu stránky vyrobí sám, tu rels-ext vazbu? 
Pardon, jestli je to hloupý dotaz.

**Comment by filak** [comment]
@krizovj to myslím, že nebude třeba - pokud ten RELS-EXT půjde z ProArcu celý.

Jinak by to ale mělo jít stejně v Krameriovi-admin rozhraní někde nastavit.

**Comment by pavel-stastny** [comment]
@pavelkocourek @honza-rychtar Jak se naloží s tímto issue ?   Nyní je situace taková, že sbírky v K7 mají možnost si definovat reprezenatitvní stranu.  Pro ostatní modely platí to, že se dohledává první strana.

**Comment by zabak** [comment]
@pavel-stastny já v admin části web klienta vidím možnost nastavit si reprezentativní stranu k čemukoli. Tohle navrhuji zavřít.
