### ISSUE TITLE
Indexace autorit

### ISSUE THREAD

**Issue by leiblix** [ceskaexpedice/kramerius#627]
Pro autority v MODS existují dva způsoby zápisu (nový odděluje jméno a příjmení, podle starého způsobu je to dohromady).

```
<mods:namePart type="family">Lužick&aacute;</mods:namePart>
<mods:namePart type="given">Věnceslava</mods:namePart>
``` 

postaru:
```
<mods:namePart>Lužick&aacute;, Věnceslava</mods:namePart>
```

Indexer poté založí pro pole browser_author dva různé záznamy
Lužická, Věnceslava , 1832-1920 (liší se mezerou za příjmením) 
Lužická, Věnceslava, 1832-1920

Je potřeba to sjednotit.

**Comment by MartinRumanek** [comment]
Po diskusi s @pavel-stastny jsme přišli na to, že indexer přebírá autora z DC, které je v případě staré varianty 

```
<dc:creator>Lužická, Věnceslava , 1832-1920</dc:creator>
```

Stálo by za zvážení nově indexovat autory přímo z MODSu.

**Comment by jkremlacek** [comment]
Za nás je rozhodně preferovanější tahat data jen z MODSu, další věcí je jestli Kramerius potřebuje z DC něco, co v MODSu není - pokud ne, tak otázka jestli se ho nezbavit úplně.

**Comment by pavelkocourek** [comment]
Souvisí s "Optimalizace SOLR schematu K6", který je plánován.
Pracuje se na specifikaci.

**Comment by tumovam** [comment]
Z dnešní schůzky k VT Krameria - data se přebírají z MODSu a zde se řeší problém s Dublin Core.

**Comment by luckajirku** [comment]
> Z dnešní schůzky k VT Krameria - data se přebírají z MODSu a zde se řeší problém s Dublin Core.

Issue je zavřené, ale pro nás nevyřešené. Není nám jasné, co z toho závěru vyplývá. Bude se to řešit, nebude? Problém stále trvá, autory tam máme dvakrát a pro uživatele je to trochu matoucí.

**Comment by zabak** [comment]
Při přechodu na K7 se udělá reindexace a tím by se problém měl vyřešit.
