### ISSUE TITLE
Import foxml s příslušností do virtuální sbírky

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#630]
Při importu foxml, které obsahuje příslušnost do virtuální sbírky (neexistující na straně přijímajícího systému), projde proces ingestu do fedory (v rdf zůstane i vazba na VC), ale padne proces reindexace do solru.

Pokud by to bylo možné, tak bychom uvítali řešení jako v případě stejného problému u procesu replikace https://github.com/ceskaexpedice/kramerius/issues/495, tedy parametr určující, zda má být zachována příslušnost k VC. (+ jeho zobrazení v admin. rozhraní pro případ, že by import neprobíhal prostřednictvím API)

**Comment by pavelkocourek** [comment]
Souvisí s #649

**Comment by pavel-stastny** [comment]
@pavelkocourek @jkremlacek Souvisí se starými virtuálními sbírkami. V K7 je jiný koncept VS. Doporučuji issue zavřít.
