### ISSUE TITLE
Nové typy stran podle NDK standardů

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#631]
Ve standardech přibyly nové typy stran, které se v jádru nezobrazují vůbec:
![typstrany2](https://user-images.githubusercontent.com/21309201/48407720-c9d1fd80-e737-11e8-9013-ea1d81f01fed.jpg)

V úplně nejvíc nejnovějším klientovi takto: 
![typstrany](https://user-images.githubusercontent.com/21309201/48407729-cd658480-e737-11e8-99e0-a4adf3931b29.jpg)

A stejně i v modrém klientovi (který už se neřeší):
![typstrany3](https://user-images.githubusercontent.com/21309201/48407820-04d43100-e738-11e8-8b67-69997ea4ea7a.jpg)

Přibyly tyto nové strany. Uvádím s návrhy na to, jak by se tam měly názvy stran zobrazovat a s anglickými ekvivalenty: 

-news (cze: Zprávy, eng: News)
-abstract (cze: Abstrakt, eng: Abstract)
-introduction (cze: Úvod, eng: Introduction)
-review (cze: Recenze, eng: Review)
-mainArticle (cze: Hlavní článek, eng: Main article)
-editorial (cze: Úvodník, eng: Editorial)
-obituary (cze: Nekrolog, eng: Obituary)
-bibliographicalPortrait (cze: Medailonek, eng: Portrait)
-colophon (cze: Tiráž, eng: Colophon)
-interview (cze: Rozhovor, eng: Interview)
-anotation (cze: Anotace, eng: Annotation)

Prosím o vyjádření, jestli někomu nějaký z těch názvů vadí. Díky

**Comment by honza-rychtar** [comment]
Přidal jsem nové typy stran do nového klienta - https://github.com/ceskaexpedice/kramerius-web-client/commit/724f9684d09fa21f6b467e4a439a969d97a1cf18
