### ISSUE TITLE
Eradikace IMG_FULL_AMD / _ADM streamů ?

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#632]
Konvertoval jsem po delší době nějaké NDK PSP balíčky, a při té příležitosti jsem zaznamenal, že se pro každou stránku generuje do FOXML stream "IMG_FULL_AMD" (což je asi navíc typo, dle specifikace to je IMG_FULL_ADM).

Vypadá to, že se v Krameriovi nijak nevyužívá (https://github.com/ceskaexpedice/kramerius/search?q=IMG_FULL_ADM+IMG_FULL_ADM&unscoped_q=IMG_FULL_ADM+IMG_FULL_ADM)

Navíc je celkem objemný.

Navrhuji se tohoto streamu zbavit:
1. Nevytvářet ho při konverzi NDK balíčků
2. Odstranit ho z Fedory 3+

**Comment by pavel-stastny** [comment]
@filak @pavelkocourek Importní proces tyto streamy pouze kopíruje ze zdrojového balíčku.

**Comment by vlahoda** [comment]
Konvertor z METS do Krameria prebira vsechny soubory uvedene v elementu <mets:fileSec>. Pokud nektera data v Krameriovi nechcete, odstrante je z METS balicku. Nazev AMD neni typo, je to zkratka Administrative Meta Data, odpovida to i nazvu adresare amdsec.
