### ISSUE TITLE
Statistiky - chyba načítání se nezobrazí uživateli

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#633]
Pokud při generování statistik dojde k chybě spojení s DB, pak uživatel není o tomto stavu informován a zobrazí se pouze prázdný report. (návratový kód 200)

Log aplikace při chybě: [-zde-](https://gist.github.com/jkremlacek/52a77626681420e9b022c23d7793c99d)

**Comment by pavelkocourek** [comment]
Otestovat ve verzi 7

**Comment by pavel-stastny** [comment]
@jkremlacek @pavelkocourek Již není aktuální.
