### ISSUE TITLE
využití cpu ve virtuálním prostředí

### ISSUE THREAD

**Issue by musilmartin** [ceskaexpedice/kramerius#634]
Dobrý den, jak přinutím Krameria, aby využíval přidělené zdroje (počet cpu ve virtuálním prostředí VMWARE) na maximum? Přidělil jsem 8 procesorů a Kramerius využívá pouze dva (pracuje na 25%). Děkuji za radu. Musil Martin

**Comment by pavel-stastny** [comment]
Dobry den, 

abych se priznal, tak nevim jak na ten dotaz odpovedet. Kramerius nijak neresi pocet procesoru ve svem hostitelskem systemu.  Pokud chcete jenom testovat zatez, tak bych doporucil spustit vice procesu najednou.. (treba importnich, indexacnich atd.. )  Musite ale prve zvysit pocet soubezne bezicich procesu pomoci promenne [processQueue.activeProcess](https://github.com/ceskaexpedice/kramerius/blob/master/common/src/main/java/res/configuration.properties#L58) .

**Comment by musilmartin** [comment]
V původním stavu jsem měl přiřazené dva procesory. Když jsem pustil generování cache pro deep zoom velkému množství dokumentů, Kramerius byl dlouhodobě vytížen na 100% (CPU). Přidal jsem tedy další procesory, abych výkon systému zvýšil a rozložil zátěž, ale stále se vytěžují pouze dva procesory a zbytek zahálí. Rád bych urychlil generování cache pro 0,5 TB zdigitalizovaných dat. Zkusím tedy zvýšit počet souběžných procesů. Děkuji

**Comment by musilmartin** [comment]
Jen pro info, zvýšení počtu souběžných procesů opravdu pomohlo využít virtuální stroj na plný výkon.

**Comment by pavel-stastny** [comment]
Diky za info 👍  :-)
