### ISSUE TITLE
České názvy typů stran

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#635]
Dobry den,
v Pravidlech popisu pro periodika je u typu strany cover uveden jako cesky ekvivalent Obalka, u Jacket zase jako Prebal.
V Pravidlech pro monogragie je u typu strany cover jako cesky ekvivalent Desky, u Jacket jako Obalka.
V Krameriovi je nastaveno zobrazeni ktereho prekladu? Predpokladam, ze se neresi, zda je typ strany pouzit u periodika nebo monografie

Nam vyskakuje typ strany Jacket jako Obalka a Cover jako desky

Dekuji

**Comment by honza-rychtar** [comment]
cover: desky
jacket : obálka

Teoreticky můžou být lokalizované názvy typů stran parametrizovány typem dokumentu. V prvé řadě by ale vůbec nemělo docházet k těmto nekonzistencím na úrovni standardu.
Lepší bude sjednotit názvy ve standardu.

**Comment by rzeh4n** [comment]
Opravdu ty překlady jsou nekonzistentní napříč pravidly popisu.

http://goo.gl/wXgJDF
Na to se odkazuje standard DMF Periodika minimálně v poslední verzi 1.7.1:
https://www.ndk.cz/standardy-digitalizace/dmf_periodika_1-7-1_opravena_verze_rijen2018 

http://goo.gl/z5NA0Q
Na to se odkazuje standard DMF Monografie minimálně v poslední verzi 1.3.2:
https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2

V obou dokumentech v kapitole 1.2 znamenají cover a jacket něco jiného.

**Comment by pavelkocourek** [comment]
@honza-rychtar Lze to zavřít Honzo?

**Comment by honza-rychtar** [comment]
Tohle je problém standardu.
Klient vlastně jen zobrazuje český název identifikátoru typu strany.

**Comment by zabak** [comment]
@Drahotussky lze zavřít?

**Comment by pavel-stastny** [comment]
@Drahotussky  Uzavíram, v případě potřeby je možno znovu otevřít.
