### ISSUE TITLE
K5 API item endpoint vrací 500 pro PID s @ [jednotlivé stránky z PDF dokumentu] 

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#639]
Například:
http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/children
vrátí mj.
`"pid": "uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990@1",`

ale požadavek 
http://kramerius.medvik.cz/search/api/v5.0/item/uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990@1 
vrací
`{
"message": "Expecting ':'",
"status": 500
}`

**Comment by honza-rychtar** [comment]
Bude souviset s tím, že v solru se u PDF stránek přidává před zavináč lomítko.
[http://kramerius.medvik.cz/search/api/v5.0/search?q=PID:"uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990@1"](http://kramerius.medvik.cz/search/api/v5.0/search?q=PID:"uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990@1") - **nenajde**
[http://kramerius.medvik.cz/search/api/v5.0/search?q=PID:"uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/@1"](http://kramerius.medvik.cz/search/api/v5.0/search?q=PID:"uuid:d04b827f-d7bc-4db2-bd5e-78df14f81990/@1") - **najde**

Do item endpointu to lomítko přidat nejde, protože rozdělí cestu v url, takže se bude muset upravit na straně Krameria.

**Comment by filak** [comment]
Nevím nakolik je průchozí úprava na straně KramAPI, nedalo by se to ošetřit na straně klienta?

**Comment by pavel-stastny** [comment]
To je zalezitost api  - jadra

**Comment by filak** [comment]
Pokud API vrátí validní PID, který se pak použije ve validním požadavku a API následně vrátí status 500, tak to se, sorry jako, asi dá těžko považovat za návrh na rozšíření.

**Comment by filak** [comment]
Nějaký progres v tomto issue ?

**Comment by pavel-stastny** [comment]
@filak  @pavelkocourek V novém indexu jsou stránky indetifikovány jinak . Problém odpadne.

**Comment by pavel-stastny** [comment]
@filak @pavelkocourek Zavíram. V případě potřeby můžeš znovu otevřít.
