### ISSUE TITLE
Nelze vyhledávat v plném textu některých PDF

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#642]
Ve většině PDF nám Kramerius nevyhledává v plných textech. 

Příklady:
https://kramerius.lib.cas.cz/search/handle/uuid:1b031fa8-f4a5-45dc-b8a9-c495987642c4
https://kramerius.lib.cas.cz/search/handle/uuid:09cd379e-9a8c-472e-b0c9-ec17b09027f0
https://kramerius.lib.cas.cz/search/handle/uuid:48b9827a-d43a-45f6-9c3b-f4ec289181f9
https://kramerius.lib.cas.cz/search/handle/uuid:bdd33194-a3fb-446d-91bc-6c91763f5aa1
https://kramerius.lib.cas.cz/search/handle/uuid:7f597083-d0ef-4e07-9829-12e9ccc9f7b7
https://kramerius.lib.cas.cz/search/handle/uuid:edb7b4d3-f7f6-4307-b65f-1b69638c069a

Je jich spousta, můžu klidně poslat ještě další. 

Ve většině případů, když nahráváme balíčky s PDF do Krameria, tak vyhodí varování.
Například import tohoto čísla: https://kramerius.lib.cas.cz/search/handle/uuid:b954be30-8f5e-4010-9d24-f39f725e08f0 vyrobil varování zřejmě při indexaci:
![image](https://user-images.githubusercontent.com/21309201/50905880-1c702300-1424-11e9-891c-8082029087a3.png)

V logu byl chybový výstup:

Pro 12, 2018 9:31:49 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:50 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for b2left (1) in font UTCUYW+Wingdings3
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Gulim&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Verdana&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Verdana-Bold&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Verdana-Italic&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Consolas-Italic&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Consolas&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;Consolas-Bold&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;LucidaSansUnicode&#039;
Pro 12, 2018 9:31:51 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:52 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:53 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:54 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:55 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for b2right (2) in font UTCUYW+Wingdings3
Pro 12, 2018 9:31:55 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:56 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:31:57 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:00 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:01 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:02 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:03 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:04 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:05 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:05 DOP. org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for .notdef (135) in font Courier
Pro 12, 2018 9:32:07 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;ArialNarrow&#039;
Pro 12, 2018 9:32:07 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;ArialNarrow-Italic&#039;
Pro 12, 2018 9:32:07 DOP. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont &lt;init&gt;
WARNING: Using fallback font &#039;LiberationSans&#039; for &#039;LucidaSansUnicode&#039;
Pro 12, 2018 9:32:09 DOP. cz.incad.kramerius.processes.impl.ProcessStarter mai

**Comment by pavelkocourek** [comment]
@rzeh4n  Je to prosím ještě relevantní vzhledem ke K7?

**Comment by pavel-stastny** [comment]
@pavelkocourek @krizovj  Již by se to nemělo objevovat.
