### ISSUE TITLE
Prázdný ocr soubor z ProArcu nepřijme importní program

### ISSUE THREAD

**Issue by pavelkocourek** [ceskaexpedice/kramerius#644]
V balíčku, kde není OCR text, vzniká prázdný soubor (obsahujíící pouze mezeru nebo tečku) - ten nepřijme importní program Krameria. Nulový soubor má být pro import v pořádku.
(MN - schuzka P 17.1.)

**Comment by MartinRumanek** [comment]
Jenom doplním, že toto jsme už jednou řešili v Praorcu:

https://github.com/proarc/proarc/issues/658

Opravili jsme to tak, že Proarc vygeneruje OCR s jedním prázdným řádkem - právě aby soubor nebyl nulový. Kramerius takový soubor určitě přijme.

**Comment by pavelkocourek** [comment]
Patří k novému indexeru ...

**Comment by vlahoda** [comment]
Opraveno v  06f6f973 a dcfbade7, bude obsazeno ve verzi 5.5.1 a K7
