### ISSUE TITLE
PA 3.5.3 - Typy stran - nezobrazují se v Krameriovi #883

### ISSUE THREAD

**Issue by pavelkocourek** [ceskaexpedice/kramerius#645]
Změnil se popis stran - a nezobrazují se. 
@smejkalovaanna : Anicko popiš prosím co se tam odehrává, ať se po tom můžeme podívat. Případně příklad záznamu.
Převedeno z  "PA 3.5.3 - Typy stran - nezobrazují se v Krameriovi #883"

**Comment by SmejkalovaAnna** [comment]
Asi to bude problém klienta Krameria, nezkoušela jsem všechny nové typy stran ( ty standardní staré se zobrazují ), ale náhodně se mi nerozbrazuje ve starém klientovi typ strany Notový zápis, v novém klientovi v tom bílém se to zobrazuje jako page_typ.sheetm....

**Comment by honza-rychtar** [comment]
Napište mi kódy a české a anglické názvy nových typů stran a já je přidám do klienta.
Klient teď má tyto:
    "advertisement" : "reklama",
    "backcover" : "zadní desky",
    "backendsheet" : "zadní přídeští",
    "blank" : "prázdná strana",
    "cover" : "desky",
    "flyleaf" : "volný list",
    "frontcover" : "přední desky",
    "frontendsheet" : "přední přídeští",
    "frontjacket" : "obálka",
    "index" : "rejstřík",
    "jacket" : "obálka",
    "listofillustrations" : "seznam ilustrací",
    "listofmaps" : "seznam map",
    "listoftables" : "seznam tabulek",
    "map" : "mapa",
    "normalpage" : "strana",
    "other" : "strana",
    "spine" : "hřbet",
    "titlepage" : "titulní strana",
    "tableofcontents" : "obsah",
    "table" : "tabulka",
    "backendpaper" : "zadní předsádka",
    "dedication" : "dedikace",
    "edge" : "ořízka",
    "errata" : "errata",
    "frontendpaper" : "přední předsádka",
    "frontispiece" : "frontispis",
    "illustration" : "ilustrace",
    "imprimatur" : "povolení k tisku",
    "listofsupplements" : "seznam příloh",
    "preface" : "předmluva",
    "news": "zprávy",
    "abstract": "abstrakt",
    "introduction": "úvod",
    "review": "recenze",
    "mainarticle": "hlavní článek",
    "editorial": "úvodník",
    "obituary": "nekrolog",
    "bibliographicalportrait": "medailonek",
    "colophon": "tiráž",
    "interview": "rozhovor",
    "anotation": "anotace"

**Comment by SykoraLukas** [comment]
abstract=Abstrakt (Abstract)
advertisement=Reklama (Advertisement)
anotation=Anotace (Anotation)
appendix=Dodatek (Appendix)
backCover=Zadn\u00ed desky (BackCover)
backEndPaper=Zadn\u00ed p\u0159eds\u00e1dka (BackEndPaper)
backEndSheet=Zadn\u00ed p\u0159\u00edde\u0161t\u00ed (BackEndSheet)
bibliographicalPortrait=Bibliographical Portrait
bibliography=Bibliografie (Bibliography)
blank=Pr\u00e1zdn\u00e1 strana (Blank)
calibrationTable=Kalibra\u010dn\u00ed tabulka (CalibrationTable)
case=Pouzdro (Case)
colophon=Colophon
booklet=Booklet
cover=Desky vcelku (Cover)
dedication=Dedikace (Dedication)
edge=O\u0159\u00edzka (Edge)
editorial=Editorial
errata=Errata
flyLeaf=Voln\u00fd list (FlyLeaf)
frontCover=P\u0159edn\u00ed desky (FrontCover)
frontEndPaper=P\u0159edn\u00ed p\u0159eds\u00e1dka (Front End Paper)
frontEndSheet=P\u0159edn\u00ed p\u0159\u00edde\u0161t\u00ed (FrontEndSheet)
frontispiece=Frontispis (Frontispiece)
frontJacket=P\u0159edn\u00ed strana p\u0159ebalu (FrontJacket)
illustration=Ilustrace (Illustration)
impressum=Impressum (Impressum)
imprimatur=Povolen\u00ed k tisku (Imprimatur)
imgDisc=IMGdisc
index=Rejst\u0159\u00edk (Index)
interview=Interview
introduction=Uvod (Introduction)
jacket=P\u0159ebal (Jacket)
listOfIllustrations=Seznam ilustrac\u00ed (ListOfIllustrations)
listOfMaps=Seznam map (ListOfMaps)
listOfSupplements=Seznam oprav (ListOfSupplements)
listOfTables=Seznam tabulek (ListOfTables)
mainArticle=Hlavn\u00ed \u010dl\u00e1nek (Main Article)
map=Mapa (Map)
news=Zpr\u00e1vy (News)
normalPage=Norm\u00e1ln\u00ed strana (NormalPage)
obituary=Obituary (Obituary)
preface=P\u0159edmluva (Preface)
review=Review (Review)
sheetmusic=Notov\u00fd z\u00e1pis (Sheetmusic)
spine=H\u0159bet (Spine)
table=Tabulka (Table)
tableOfContents=Obsah (Table Of Contents)
titlePage=Tituln\u00ed strana (TitlePage)

**Comment by krizovj** [comment]
Tak mi z toho vyšlo, že chybí:

calibrationTable = kalibrační tabulka 
case = pouzdro
bibliography = bibliografie
appendix = dodatek
booklet = booklet
impressum = impressum
sheetmusic = notový zápis
imgDisc=IMGdisc (tady si nejsem jistá, co by se přesně mělo zobrazit v Krameriovi...teoreticky by to mohlo být třeba "obraz desky"???)

**Comment by pavelkocourek** [comment]
@honza-rychtar Není to již ošetřeno Honzo?

**Comment by honza-rychtar** [comment]
Doplnil jsem chybějící v klientovi Krameria i ProArcu.

**Comment by pavel-stastny** [comment]
@honza-rychtar @pavelkocourek @SmejkalovaAnna  Dle komunikace již ošetřeno v klientovi, V případě potřeby je možno znovu otevřít.
