### ISSUE TITLE
OAI Provider pro Solr 7 (Kramerius 6)

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#647]
oai4solr [nepodporuje](https://github.com/IISH/oai4solr/issues/16) Solr 7, který je potřeba pro Kramerius 6, ale používá ho už teď třeba MZK: https://github.com/moravianlibrary/kramerius/issues/294. Tak jenom, aby se o tom vědělo a bylo to někde zaznamenané, minimálně až se bude schylovat k finální verzi Kramerius 6,

**Comment by rzeh4n** [comment]
Možná by stálo za to uvažovat nad přechodem na [ResourceSync](http://www.openarchives.org/rs/toc) namísto letitého OAI-MPH, u kterého se ukazuje, že má spoustu nedostatků, jako třeba:
- informace o odstraněných položkách
- systém resumptionTokenů při sklízení velkých setů

Fakticky je sklízení větší instalace Krameria, jako je MZK, téměř nepoužitelné. A problém nemusí být nutně v implementaci OAI-PMH Repozitáře.

**Comment by svetlym** [comment]
Dobrý den,

v Městské knihovně v Praze používáme protokol OAI-PHM pro komunikaci s knihovním systémem. Pokud by se zrušilo, museli bychom implementovat jiný protokol v našem knihovním systému.

**Comment by zabak** [comment]
ResourceSnc by mohl být krok správným směrem. Opravdu funkčních a hlavně škálovatelných, rychlých a spolehlivých implementací OAI-PMH je u nás pomálu. V té souvislosti upozorňuji na draft  [IIIF Change Discovery API 0.1](https://iiif.io/api/discovery/0.1/) a na prezentaci [IIIF & ResourceSync:
Supporting discovery](https://matienzo.org/storage/2017/2017Apr-DPLAFest-IIIF-ResourceSync.pdf) která tomu draftu předcházela. Je to samozřejmě ještě [ve vývoji.](https://github.com/IIIF/discovery/issues)

**Comment by zabak** [comment]
Dalo by se využít https://github.com/resourcesync/py-resourcesync - je to v pythonu, ale má to i solr generator, takže teoreticky by to šlo přímo použít.

**Comment by svetlym** [comment]
Zkonzultoval jsem to ještě s naším IT oddělením. Na implementaci nového protokolu do našeho knihovního systému nemáme momentálně zdroje - plně nás vytěžuje nasazování RFID.

OAI-PHM v Kramériovi ovšem používáme pouze na to, abychom do našeho knihovního systému automaticky doplňovali nově zveřejněná uuid. Možná by tedy tuhle funkcionalitu bylo možné implementovat nějak jednodušeji než komplet novým protokolem.

**Comment by filak** [comment]
Kramerius by měl mít dobře implementované OAI-PMH jakožto etablovaný standardní protokol.

ResourceSync by byl fajn - třeba by se jím dala lépe vyřešit aktualizace nadstavbových systémů ČDK atp.

Zmíněný projekt již není moc aktivní
https://github.com/resourcesync/py-resourcesync/graphs/code-frequency

Někdo by musel implementovat příslušný generátor pro v Krameriovi aktuálně používanou verzi SOLRu - viz https://github.com/resourcesync/py-resourcesync#resource-metadata

**Comment by filak** [comment]
OK, souhlas. Ale jak už zmínil @svetlym - stávající knihovní systémy umí většinově spíš OAI. Takže bych OAI v Krameriovi rozhodně v současnosti nezahazoval.

**Comment by zabak** [comment]
Problém je, jestli to není kanón na vrabce. Možná že by pro daný účel stejně dobře posloužil export textového souboru obsahujícího na každém řádku několik údajů.

**Comment by JanMeritus** [comment]
@filak @svetlym  taky souhlas, zmena by mala dopad taky na nase systemy. OAI zatim stale treba podporovat, obecne by som v tomto trende nasledoval Europeanu a ArXIv.

**Comment by pavel-stastny** [comment]
@rzeh4n @zabak   OAI řešeno v rámci issue #1034.
