### ISSUE TITLE
API - umožnění reindexu konkrétního pole

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#650]
V rámci oprav dat (špatný formát datumu, ...), případně také doplnění chybějících dat do indexu (geografické souřadnice, ...) je třeba provádět hromadné reindexace velkého množství dat - změnu je často třeba propagovat až na úroveň strany.

Současné řešení vyžaduje reindexaci celého objektu, kdy dochází ke zbytečnému reindexování dat, které se nezměnily. 

SOLR umožňuje reindexaci pouze konkrétního pole, proto by bylo pro tyto účely vhodné, pokud by Kramerius API zpřístupňoval tuto funkcionalitu. Alternativou je přímé spuštění reindexu pole v SOLR-u bez použití Krameria, takové řešení je ale nevhodné, protože je náchylné na zavlečení chyb do indexu.

**Comment by pavel-stastny** [comment]
@jkremlacek Nedopručoval bych to.  V rámci indexace se mění i timestamp a na tom jsou závíslé i další procesy.  Například sklízení do ČDK.

**Comment by pavel-stastny** [comment]
Issue uzavírám v případě potřeby je možno ho znovu otevřít.
