### ISSUE TITLE
Potíže s importem monografie

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#653]
Dobrý den,

opakovaně se nám nedaří naimportovat jednu monografii. V přiloženém souboru
jsou logy z importu, PSP, které se snažíme naimportovat (obrazové soubory mají
pro účely tohoto reportu nulovou velikost, importujeme je samozřejmě v původní
podobě) a FOXML, které vytvořil importní proces.

Problémová monografie, logy a FOXML: [[ERROR]_umelecke_pamatky_prahy.zip](https://drive.google.com/open?id=1MyWdq5D_oMltLbwz35XrwklTyw1P6UY_)

Provozujeme verzi Kraméria 5.4.1, revize: 3389
PSP je vyexportované z Proarcu.

Mohli byste se, prosím, podívat, v čem by mohl být problém?

**Comment by vlahoda** [comment]
Mohl byste prosim najit i log SOLR okolo casu Jun 21, 2018 11:54:12 AM? A pripadne pribalit i FOXML soubor uuid:f765b113-6a05-4653-8d01-a50f715ea407, vytvoreny importnim procesem? (zminovane FOXML jsem v tom velkem zipu nenasel).

**Comment by svetlym** [comment]
Logy solru jsou zde (kompletní):
[solr.logs.zip](https://github.com/ceskaexpedice/kramerius/files/2851239/solr.logs.zip)

Soubor f765b113-6a05-4653-8d01-a50f715ea407 importní proces nevytvořil - adresář jsem zkopíroval celý, nic jsem z něj nemazal. Pro jistotu jsem to zkontroloval a opravdu v /convert-converted není.

**Comment by svetlym** [comment]
Ještě bych asi měl doplnit, že tuto monografii jsme se (neúspěšně) pokoušeli importovat už několikrát. Před tímto pokusem jsme ji ale znovu vytvořili pod novým uuid a znovu vyexportovali PSP, takže by snad nemělo jít o konflikty s nějakými pozůstatky z dřívějších pokusů. Ale nevím, jestli to jde úplně vyloučit.

**Comment by vlahoda** [comment]
Potreboval bych videt konzistentni data, jinak na nic neprijdu. SOLR log je dnesni, logy procesu jsou z cervna 2018. Adresar convert-converted v tom zipu nevidim vubec.

**Comment by svetlym** [comment]
> SOLR log je dnesni

V tom souboru solr.logs.zip je celý obsah adresáře /solr/server/logs. Jsou logy solru ještě někde jinde?

> Adresar convert-converted v tom zipu nevidim vubec.

Pojmenoval jsem ho FOXML. Omlouvám se, pokud je to matoucí. Obsahem adresáře FOXML v zipu je celý obsah adresáře convert-converted.

**Comment by vlahoda** [comment]
Ten log SOLR je asi v poradku, obsahuje ale jen zaznamy za posledni 3 dny (mezi 9.2. a dneskem). Logy indexacniho procesu v souboru MKP_reindex_after_import_error_report.zip jsou z 21.6.2018 a nevidim v nem zadny adresar FOXML ani nic podobneho.

**Comment by svetlym** [comment]
> Ten log SOLR je asi v poradku, obsahuje ale jen zaznamy za posledni 3 dny (mezi 9.2. a dneskem).

V logu solru se moc nevyznám, ale nebude relevantního v podadresáři /archived? Hned na začátku souboru /archived/solr_gc.log.0.current vidím záznam z 2019-02-04T12.


> Logy indexacniho procesu v souboru MKP_reindex_after_import_error_report.zip jsou z 21.6.2018 a nevidim v nem zadny adresar FOXML ani nic podobneho.

Obsah souboru [ERROR]_umelecke_pamatky_prahy.zip:
- FOXML
- logs
- PSP

**Comment by vlahoda** [comment]
Aha, jenze ten odkaz na google drive, ktery jste tu uvedl, vede na soubor MKP_reindex_after_import_error_report.zip. Mohl byste sem tedy dat ten spravny [ERROR]_umelecke_pamatky_prahy.zip?

**Comment by svetlym** [comment]
> Aha, jenze ten odkaz na google drive, ktery jste tu uvedl, vede na soubor MKP_reindex_after_import_error_report.zip

Ehm, omlouvám se a šoupu nohama - linkul jsem špatný soubor. Tohle by měl být správný odkaz:

https://drive.google.com/open?id=1MyWdq5D_oMltLbwz35XrwklTyw1P6UY_

**Comment by vlahoda** [comment]
Ted uz to dava vetsi smysl :-) Problem tedy vubec nesouvisi s indexaci a SOLRem, ale opravdu jde o konflikt s pozustatky predchozich importu. Konkretne, ve fedore je 57 objektu typu internalpart ktere maji stejna uuid jako nove importovane ( a ktere tam zustaly z predchozich importu a odkazuji na jiz neexistujici stranky). Novy import pak tyto stare dokazy slouci s novymi a spadne pri pokusu o jejich setrideni. Mohlo by tedy stacit vypnout pri importu automaticke trideni (property ingest.sortRelations=false), ale zrejme pak v tech internal parts budou znasobene odkazy na stranky a mozna stejne neprojde cela indexace. Lepsi by asi bylo nejdriv ty existujici internal parts z fedory smazat - seznam jejich uuid ziskate tak, ze v logu stout.out tohoto importniho procesu vyhledate slovo "Merging". Dalsi varianta, jak problem vyresit, by bylo vygenerovat v proarcu nova uuid uplne vsem soucastem te publikace, vcetne internal parts.

**Comment by svetlym** [comment]
> Lepsi by asi bylo nejdriv ty existujici internal parts z fedory smazat - seznam jejich uuid ziskate tak, ze v logu stout.out tohoto importniho procesu vyhledate slovo "Merging".

Udělal jsem to takhle a problém to vyřešilo. Děkuju za pomoc a za rychlou odpověď.
