### ISSUE TITLE
Kriticka feature: SOLR dotaz na fazety v uvodni stranke - treba predcachovat

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#657]
Dobry den,

tento select sa spusta pri prichode uzivatela na Kramerius. Silne to vytazuje Kram SOLR - prechadza vsetky stranky (odozva v dlhych sekundach). U velkych instancii (dlhe odozvy, resourcy), neda sa to niekde predcachovat pri prednastaveni doby - volitelne napr 10 min? (ak tieto data su bezne vobec potrebne, tak cachovat)

http://10.10.0.94:8983/solr/kramerius/select?wt=xml&q=*%3a*&qf=root_title%5e10+root_title_lemmatized%5e10+root_title_lemmatized_ascii%5e10+text+text_lemmatized+text_lemmatized_ascii&rows=0&facet.field=model_path&facet.field=document_type&facet.field=language&facet.field=rok&facet.field=keywords&f.rok.facet.limit=-1&f.rok.facet.sort=false&facet=true&facet.mincount=1&f.rok.facet.mincount=0&sort=level+asc%2c+title_sort+asc%2c+score+desc&defType=edismax

Poprosim o prehodnotnie a vydanie hotfixu ASAP. Akykolvek vacsi pocet uzivatelov to NK CR pri medializacii implementacie kramerius webclienta, ci DNNT moze zhodit.

**Comment by pavelkocourek** [comment]
Navrhujeme vyřešit nasazením nového klienta

**Comment by JanMeritus** [comment]
Nasadenie klienta neriesi problem v core, ktore pokial viem je stale supported. Kramerius by mal byt po najblizsi cas funkcne, kym nenabehnu klienti i pre editaciu. Predstavuje to zbytocnu historicku zataz. Myslim ze programatorska uprava bude jednoducha, pricom sa da brat z predcachovaneho vzoru, obnovovaneho raz za cas.

PS nie je to label otazka ale oprava/navrh na rozsirenie

**Comment by JanMeritus** [comment]
Navyse v NK bude core sluzit ako sekundarny zobrazovac este minimalne rok.

**Comment by JanMeritus** [comment]
Parada, diki, otestime.

**Comment by JanMeritus** [comment]
Este prosim otestit Jan Holomek

**Comment by pavel-stastny** [comment]
Jenom upozorňuji, že komit byl do hlavní větve a ne do dnnt.  DNNT větev se po usazení zmerguje do hlavní a dnnt bude součástí každého buildu. (Nyní je jenom pro NKP). Testovat prosím na standardním buildu.    Opět, zatím nevidím důvod, proč by toto issue mělo být otevřené.  Prozatím zavírám.
