### ISSUE TITLE
Export titulu z Krameria

### ISSUE THREAD

**Issue by SykoraLukas** [ceskaexpedice/kramerius#659]
Při exportu z Krameria je nutné exportovat také hlavní titul (titul periodika)

**Comment by krizovj** [comment]
Prosím označit issue jako chybu

**Comment by SykoraLukas** [comment]
Musí udělat někdo jiný, nemám práva pro editaci labelu

**Comment by krizovj** [comment]
Teď mě napadlo, nemohl by se Kramerius při exportu zeptat, jestli chci jen tu označenou úroveň (ročník, číslo) nebo i celý titul?

**Comment by gmelingerova** [comment]
Tenhle problém řeší nastavení v konfiguraci export.parents = true | false viz https://github.com/ceskaexpedice/kramerius/issues/520.
Přidám možnost s vyskakovacím oknem, abychom byli nezávislí od nastavení v konfiguraci.
