### ISSUE TITLE
vytvořit robots.txt

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#66]
Součástí distribuce Krameria by měl být vzorový robots.txt, zakazující robotům přistupovat na nevhodná URL v rámci jeho webu.

**Comment by MartinRumanek** [comment]
Kromě toho by bylo vhodné zakázat přístup obrázkovým robotům. Když si ty obrázky stáhnou po dlaždicích tak jim je to stejně k ničemu.

https://support.google.com/webmasters/answer/35308?hl=cs

**Comment by pavel-stastny** [comment]
Dobry den, 

rusime starsi issue. Myslime, ze toto je uz neaktualni a melo bo byt zalezitosti predrazeneho apache pripadne klienta. V pripade potreby, znovu otevrete.
