### ISSUE TITLE
Export z Krameria - změna identifikátoru

### ISSUE THREAD

**Issue by SykoraLukas** [ceskaexpedice/kramerius#660]
V případě exportu z Krameria se místo identifikátoru uuid s hodnotou XYZ vyexportuje identifikátor urn se stejnou hodnotou XYZ. Prosím o změnu identifikátoru na uuid

**Comment by krizovj** [comment]
Prosím označit issue jako chybu

**Comment by pavel-stastny** [comment]
Zdravim, 

export do FOXML probiha primo z fedory, tedy to co bylo naimportovano je pak  (v nezmenene podobe)   i vyexportovano.  Znamena to, ze ma pri exportu menit obsah foxml  ?
