### ISSUE TITLE
Časová osa v Krameriu se Solrem 7.5

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#662]
Kramerius nezobrazuje plnou časovou osu pokud běží na Solr 7 s point-based polem pro rok.

Víc na moravianlibrary/kramerius#305

**Comment by pavel-stastny** [comment]
bude reseno podporou Solr 7

**Comment by pavelkocourek** [comment]
@pavel-stastny Ještě je to relevantní Pavle?

**Comment by honza-rychtar** [comment]
Tohle můžeme obnovit v klientovi.
- chceme časovou osu?
- co má reprezentovat?
- jak má vypadat?
.....

**Comment by JanMeritus** [comment]
@honza-rychtar hlavne optimalizovanou, v jadre vzdy se pokladal hrozne siroky dotaz a na vsechno

**Comment by pavel-stastny** [comment]
@pavelkocourek  Muze se zavrit.  Souhlasim s @honza-rychtar  s tim, ze je to klientska zalezitost.

**Comment by zabak** [comment]
@JanMeritus pokud není zadaný žádný vyhledávací dotaz, musí být osa obsahovat všechno. Osa by musela být na samostatné stránce, kam se uživatel musí překliknout, podobně jako při hledání na mapě.

@honza-rychtar na časovou osu se dá vynést počet titulů (případně včetně čísel periodik), nebo počet stran. Ale nevidím to jako prioritu. Zde navrhuji zavřít.
