### ISSUE TITLE
Priznak DNNT Core v zobrazeni

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#665]
Podobne ako na #221 v kramerius-web-client pre editorov prav pridat vizualny priznak pre diela zaradene v DNNT, rovnako ako rychly filter

<img width="1188" alt="Screenshot 2019-03-29 at 15 29 26" src="https://user-images.githubusercontent.com/25201690/55335816-1d04dc80-549c-11e9-8ead-0359bab383b2.png">

**Comment by zabak** [comment]
Předpokládám, že jsi myslel tohle issue: https://github.com/ceskaexpedice/kramerius-web-client/issues/210

**Comment by pavelkocourek** [comment]
29.4. KNAV - dnnt je řešeno pouze pro nového klienta

**Comment by JanMeritus** [comment]
@pavelkocourek OK, v pripade ze bude riesene i pre noveho administracneho klienta. Inak NOK.

**Comment by pavelkocourek** [comment]
nová administrace je pomalu na řadě ...

**Comment by JanMeritus** [comment]
1. API Krameria by malo vracat kompletny zoznam UUID znacenych ako DNNT. Ci uz po blokoch, alebo naraz, pripadne to vracat kvoli rozsahu cez OAI. 

2. V Core / Administrativnom rozhrani by mal mat moznost obsahovy spravca oznacovat/odznacovat DNNT po jednotlivostiach, a preto by mal jasne vidiet ktore diela akymi pravami su opatrene.

**Comment by JanMeritus** [comment]
@pavel-stastny z commitu 3ed7160, dotyka sa nieco : 

>API Krameria by malo vracat kompletny zoznam UUID znacenych ako DNNT. Ci uz po blokoch, alebo naraz, pripadne to vracat kvoli rozsahu cez OAI.

>V Core / Administrativnom rozhrani by mal mat moznost obsahovy spravca oznacovat/odznacovat DNNT po jednotlivostiach, a preto by mal jasne vidiet ktore diela akymi pravami su opatrene.

**Comment by pavel-stastny** [comment]
Ad API:  Dnnt je priznak v solru, je mozno si ho vyhledat v ramci volani . Dostupne pres API je. 

Ad Core:  Oznacovani ci odznacovani.  Reseno procesem, ktery zpracovava csv soubor.

**Comment by JanMeritus** [comment]
Ad 2: ok
