### ISSUE TITLE
DNNT: Logovanie v procesoch

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#666]
z procesov nie je na prvy pohlad zrejme akemu UUID sa prideloval priznak DNNT, ide o uniformnu hlasku:

<img width="1321" alt="Screenshot 2019-03-29 at 15 32 23" src="https://user-images.githubusercontent.com/25201690/55335949-648b6880-549c-11e9-9c01-a33138cb540a.png">

**Comment by pavel-stastny** [comment]
Proces zpracovava celou davku pidu, ktera je definovana v csv.  Asi nema smysl pojmenovavat proces vsemi pidy, ktere jsou v soboru. Jedine kloudne reseni, ktere me napada (co by slo udelat):   
1. Vstupni csv soubor by nebyl definovany konfiguracne ale mohl by si to uzivatel vybrat (dialogem) 
2. Meli byste nejakou jmennou konvenci vstupnich cvs souboru (treba obsahujici datum) 
3. Spousteny proces by obsahoval jmeno vstupniho csv souboru. 
 
Slo by  to takto ?

**Comment by JanMeritus** [comment]
Teoreticky jo, 3. urcite jo. Kazdopadne by sme nejak potrebovali mat pri tomto procese vsetky PIDy v Error logu kde to nepreslo OK z akehokolvek dovodu, ci tam boli nejake problemy, ci ten PID uz mal priradene DNNT. Takto rozsireny log by bol vhodny i pre proces odoberanie priznakov.

**Comment by pavel-stastny** [comment]
Proces je praraleni a bere jednotlive pidy podle toho, jak ma zrovna volne thready. V logu budou napreskacku a blbe by se vam z toho delal sumar co znovu spustit.  Lepsi by bylo mit jako zakladni jednotku celou varku (tedy cely proces). Kdyz spustis proces se stejnou sadou pidu, ty ktere uz maji nastaveny DNNT preskoci a pokracuje tou casti, ktera jeste neni.

**Comment by JanMeritus** [comment]
a kdyz sa to pak nekde pripadne zasekne? bolo by fakt dobre vediet nad ktorymi vykonal proces prideleni. Tie ktore preskocil sa nemusia evidovat.  Najhorsi bude prvy import, pak bude rozdielovka myslim si, realne mala.

**Comment by pavel-stastny** [comment]
Stejne jako se tomu deje u indexace nebo u importu. Zjistis kde je problem, opravis  a nechas preindexovat cely titul. Nevyberes si pro idnexaci jenom polovinu z toho puvodniho.  Nicmene jsem pridal do procesu dve hlasky, ktere nakonec loguji bud uspech a nebo chybu. Vypisi se vzdycky pote, co thread skonci s konkretnim pidem.

**Comment by pavelkocourek** [comment]
Udelej prosim build, ať to v NK otestují. 
KNAV 16.7.

**Comment by pavel-stastny** [comment]
Přidány dialogy pro vybrání csv souboru s pidy pro který se má nastavit případně odebrat příznak dnnt.

**Comment by JanMeritus** [comment]
Prosim o prezkumanie Jan Holomek

**Comment by pavel-stastny** [comment]
Teď nerozumím tomu, proč je to issue otevřené.  Dialogy jsou přítomny.   Issue zavírám. Pokud by se objevila nějaká chyba, tak můžeš znovu otevřít případně nové issue.

**Comment by JanMeritus** [comment]
Prosim o dalsie prezkumanie @jahhoo . Do logov sa zapisuje. Spustenie procesu ale je oznaceno Alertom Undefined. Otvaram

**Comment by pavel-stastny** [comment]
Ten udenfined je myslena hlaska po spusteni spusteni procesu?  Pokud ano, nekde jsem uz psal, ze jsem komitnul popisky a nyni se mely dialogy objevovat i s nimi.    Nicmene je potreba zkouset na novem buildu.   Tedy tom co obsahuje comit  [5f105c0a5324bf963ce0fb16e261a8be1f95f84e](`https://github.com/ceskaexpedice/kramerius/commit/5f105c0a5324bf963ce0fb16e261a8be1f95f84e`)

**Comment by JanMeritus** [comment]
@pavel-stastny posles nam teda najnovsi build s danym comitem?

**Comment by JanMeritus** [comment]
otestovano vs5.45dnnt. Procesy zapisuju uuid a celkovy pocet stran objektu. Zaviram.
