### ISSUE TITLE
DNNT: Moznost odobrat

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#667]
Nie je zrejme ako sa da odobrat priznak DNNT, ked sa uz raz nastavi. Jednoduchym maznutim z csv tabulky DNNT? Alebo vedenim tabulky pre odobratie DNNT = v tom pripade treba nastavit novy proces.

**Comment by pavel-stastny** [comment]
Pridan novy proces. Pridana promenna `dnntunset.file` pro seznam objektu, u kterych se ma priznak odebrat.  Default hodnota promenne je `~/.kramerius4/dnntunset.csv`

**Comment by JanMeritus** [comment]
Proces sa spusta ako?

**Comment by pavel-stastny** [comment]
V hlavnim menu pribyla polozka `"Unset DNNT flag" `

**Comment by JanMeritus** [comment]
Proces nefunguje, konci hlaskou undefined. Zaujimave je, ze hlada narozdiel od spominaneho by default v `~/.kramerius4/import-dnnt/dnntunset.csv` @pavel-stastny  issue nie je closed

**Comment by pavel-stastny** [comment]
Je to jenom hláška spouštěcího dialogu.  Samotný proces se spustí a v seznamu všech spuštěných procesů to jde i vidět.  Nicméně při debugování jsem zjistil, že se proces spouští pouze se standardním `dnntunset.csv`.  Obojí (hlášku i předávání souboru) jsem opravil a komitnul.  Zavírám.

**Comment by JanMeritus** [comment]
Otvaram. @pavel-stastny  prosime o build @jahhoo prosim nasadit a otestovat

**Comment by JanMeritus** [comment]
funguje, zaviram. @pavel-stastny nejde o kriticku vec, ale mozno by u procesu odobratia priznaku malo byt v l logu miesto set flag DNNT, unset flag DNNT.
