### ISSUE TITLE
Rozbitá znaková sada

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#672]
Nestatické prvky admin-rozhraní špatně zobrazují české znaky, kvůli špatně zakódovaným znakům v souboru `labels_cs.properties`.

V UI se to potom projevuje [takto](https://user-images.githubusercontent.com/43028501/55493590-84a45e80-5639-11e9-92ad-d7c0d5f5f96d.png).

Chybu zavedla úprava v rámci https://github.com/ceskaexpedice/kramerius/issues/518.

**Comment by jkremlacek** [comment]
V rámci fix-u se vrátilo do souboru `labels_cs.properties` několik nekonzistencí. V rámci původního issue totiž vyjma popisované změny došlo i k nezadokumentované opravě několika textů, které obsahovaly UTF-8 varianty českých znaků.

Např: (trvá načtení, kvůli obsáhlému diff-u)

https://github.com/ceskaexpedice/kramerius/commit/afbad514a31df6b6313bf55934e32af4891afc89#diff-bbca6f9064919e0e2641fefbfc11a0abR1253

**Comment by vlahoda** [comment]
Ano, v resource bundle jsou nekonzistence, ale cílový stav je právě opačný, než se kolegyni podařil v #518 - české texty mají být v UTF-8 a ne s escape sekvencemi \u... Kramerius k to mu má upravený classloader: https://github.com/ceskaexpedice/kramerius/blob/4dff8ff13ed3179e1f213c0d65b863390e2e7361/common/src/main/java/cz/incad/kramerius/service/impl/ResourceBundleServiceImpl.java#L100

**Comment by jkremlacek** [comment]
Aha, to je dobré vědět. Udělal jsem tedy [PR](https://github.com/ceskaexpedice/kramerius/pull/675), aby došlo ke sjednocení a přihodil jsem tam ještě překlad prohlášení cookie v anglické variantě.

**Comment by vlahoda** [comment]
Diky za PR
