### ISSUE TITLE
Přiřazování PID procesům

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#678]
Dobrý den, mohl bych se zeptat jakým způsobem probíhá přiřazování PID k nově spouštěným procesům? Na našem krameriovi (kramerius.techlib.cz) se po aktualizaci tomcatu při spouštění procesu objeví tato chyba v logu:

Výstup z catalina.out:
```
line 1:225: expecting RPAREN, found 'null'
Apr 23, 2019 2:32:04 PM cz.incad.kramerius.processes.GCFindCandiatesTask run
INFO: process 4eeee7ae-eaa9-4f92-9f4c-70bc3cc5aa34 has no pid
Apr 23, 2019 2:32:14 PM cz.incad.kramerius.processes.GCCheckFoundCandidatesTask run
SEVERE: cannot find pid for process '4eeee7ae-eaa9-4f92-9f4c-70bc3cc5aa34' -> change state to NOT_RUNNING
```

Výstup z access logu:
```
10.0.1.43 - dobiasj [23/Apr/2019:16:15:34 +0200] "GET /search/lr?action=start&def=aggregate&out=text&nparams={delete;{uuid\:91f21ecd-15e4-11e7-b5ac-001b63bd97ba;uuid\:92a5a737-501a-4dc3-a847-0e37bfe07d9b/uuid\:181087ec-cc55-4f69-b71c-5c7f1ba62342/uuid\:6b6138dc-9c17-4c35-9d5d-11a6fa8e613a/uuid\:91f21ecd-15e4-11e7-b5ac-001b63bd97ba}&_=1556028935350 HTTP/1.1" 200 18 E79634E53DFC80A81B97EE10324A17B5 23 ?action=start&def=aggregate&out=text&nparams={delete;{uuid\:91f21ecd-15e4-11e7-b5ac-001b63bd97ba;uuid\:92a5a737-501a-4dc3-a847-0e37bfe07d9b/uuid\:181087ec-cc55-4f69-b71c-5c7f1ba62342/uuid\:6b6138dc-9c17-4c35-9d5d-11a6fa8e613a/uuid\:91f21ecd-15e4-11e7-b5ac-001b63bd97ba}&_=1556028935350 -
```
V složce lp se vytvoří proces s pid a složky lrErr a lrOut, ale už se do nich nic nezapíše. Na testovacím krameriovi se mi nedaří chybu replikovat, přestože je tam stejná verze tomcatu i javy. 

Verze jádra 5.4.2, tomcat 6.0.24-62, java verze "1.8.0_201"

**Comment by pavel-stastny** [comment]
Dobry den,  

> Dobrý den, mohl bych se zeptat jakým způsobem probíhá přiřazování PID k nově spouštěným procesům? 

Po naplanovani procesu kramerius pripravi pro nej envinorment a spusti ho. Samotny proces pri pak po spusteni zjisti svuj PID,  posle ho nazpet krameriovi, na strane krameria se provede svazani procesu a PIDu a ulozi se do databaze.   Scheduler pak kontroluje, zda ma kazdy spusteny proces svuj pid a pokud nema, da ho do stavu NOT_RUNNING. 

Nekdy se stava, ze se proces nemuze spustit, protoze se do jvm nastavuji parametry, ktere v dany moment nejdou nastavit.. napriklad prilis mnoho fyzicke pameti.   To ale asi nebude Vas pripad.  Deje se to u vsech procesu?

**Comment by jdobiasovsky** [comment]
Zkoušeli jsme zatím jenom reindexaci a mazání z indexu a fedory, ostatní procesy na tom asi budou stejně. 

Java opts máme nastavené takto:
```
JAVA_OPTS=" -Djava.awt.headless=true -Dsolr.solr.home=/data/fata5/solr/data -XX:MaxPermSize=512m -Xms1024m -Xmx2048m -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory"
```

**Comment by pavel-stastny** [comment]
To je nastaveni tomcatu. Spousteny proces si bere envinroment bud z mebedovaneho [lp.st](https://github.com/ceskaexpedice/kramerius/blob/master/common/src/main/java/cz/incad/kramerius/processes/res/lp.st) nebo, pokud mate predefinovane procesy, pak z `~/.kramerius4/lp.xml`.   Neni mozne, ze ta sluzba pod kterou spoustite kramerius nema na PATH definovanou cestu k jave ?

**Comment by jdobiasovsky** [comment]
Díval jsem se na lp.xml a zkoušel to i bez něj, a nezdá se mi že by tam byla chyba. V PATHU cestu k javě vidím. 
Teď se ještě dívám že ty requesty co jsem posílal nemají asi dobře závorky. Takže je možné že nám v tom někde dělá nepořádek náš webserver, zkusím se na to podívat a kdyžtak se ještě ozvu. 

Zatím díky.

**Comment by jdobiasovsky** [comment]
Už se nám podařilo napravit, chyba byla v tom že sice jsme měli napsanou správnou javu v konfiguraci kterou používá tomcat ale neměli jsme přepnuto pomocí `alternatives --config java`, která je potřeba pro spouštění procesů jestli správně chápu
