### ISSUE TITLE
Doplnění popisu procesů RemoteAPI v dokumentaci

### ISSUE THREAD

**Issue by jkremlacek** [ceskaexpedice/kramerius#681]
V návaznosti na dnešní (23.5.2019) vývojovou schůzku bych chtěl požádat o doplnění dokumentace jednotlivých procesů dostupných v RemoteAPI tak, aby API bylo možné používat bez nutnosti studia kódu Krameria. 

V základu by byl zapotřebí popis procesu, url, http metoda, popis url parametrů, popis datových/body parametrů, success kód a error kód. Jako užitečné, ale ne bezprostředně nutné by bylo vhodné uvést i příklad volání.

**Comment by pavelkocourek** [comment]
#861
