### ISSUE TITLE
DNNT - Nastavení uživatelských práv

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#682]
Chybí možnost povolit jiným uživatelským skupinám (např. obsah_admin) přiřadit DNNT příznak

**Comment by pavelkocourek** [comment]
Souvisí se Správou uživatelů.

**Comment by pavel-stastny** [comment]
Přidána security akce `dnnt_admin`, která umožňuje spouštět procesy nastavení příznaku.

**Comment by JanMeritus** [comment]
@pavel-stastny @jahhoo  potrebujeme poslat novy build so vsetkymi opravami doteraz urobenymi

**Comment by JanMeritus** [comment]
@jahhoo prosim okontrolovat @pavelkocourek tato issue nie je zatial uzatvorena

**Comment by JanMeritus** [comment]
@jahhoo  je to na tebe

**Comment by pavel-stastny** [comment]
Ahoj, zkousim u sebe a nevidim chybu.  Uzaviram.

**Comment by JanMeritus** [comment]
ahoj, proces treba este doladit. Prava pre uzivatele na spusteni procesu su ok, ale bolo by potrebne aby meli moznost z administracniho rozhrani nahrat definicni csv soubor manualne, k oznaceni i odznaceni dnnt. Primo na server je nemuzeme pustit.

**Comment by pavel-stastny** [comment]
Nyni, jak jsou procesy naimplementovany, neumoznuji upload souboru  z pracovni stanice. (Bud konfiguracni parametr nebo vyber souboru primo na disku serveru).   Pokud je toto pozadovano, muselo by se to doimplementovat.    Jestli chces, muzeme to zalozit jako nove issue, nicmene urcite bude mit priznak rozsireni.    Obecne vidim dve mozne reseni: 

1) To by byl ten upload. 
2) Soubor by byl na serveru ale ale kazdy uzivatel by mel vlastni importni slozku. 

Zatim toto issue uzaviram.  Jestli ches to rozsireni, pokracuj, prosim, v novem.
