### ISSUE TITLE
Cyklická vazba - HTTP Status 500 

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#683]
Při smazání cyklické vazby ve Fedoře se v Krameriovi při požadavku na zobrazení smazaného UUID zobrazí chybová hláška "HTTP Status 500" a úryvky zdrojového kódu. 
Vzhledem k tomu, že to může mít OAI nacechované - přivede to uživatele na tuto chybovou hlášku. Prosím tedy o vyřešení.

Určitě by nebylo špatné, kdyby existoval nástroj na mazání vazeb - viz. #537

**Comment by pavel-stastny** [comment]
Issue znam a proto doplnim.  Nejednalo se o smazani cyklicke vazby ale naopak, zobrazovani titulu, ktery mel cyklickou vazbu.  (**Periodium**  melo jednoho potomka **PeriodikumVolume**  a to melo opet potomka  **Periodikum**).  Da se to resit nejakou obecnou hlaskou, typu : Kramerius neumi zobrazit dany model. Bude reseno v ramci noveho administracniho rozhrani

**Comment by pavel-stastny** [comment]
V K7 jsou při importu a indexaci kontroly proti cyklickým vazbám.  Nemělo by k takovému případu dojít.
