### ISSUE TITLE
Výpis importovaných titulů a nastavení viditelnosti

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#686]
Dobrý den,

přece jen mě napadl návrh na vylepšení administrátorského rozhraní:

* V dialogu pro import dokumentů do Kraméria by se mohly vypisovat tituly, které se budou importovat (mohou to být třeba jména adresářů) a u každého z nich by mohlo být zaškrtávátko na public/private.

Momentálně jde nastavit viditelnost (public/private) jen pro celou importní dávku najednou. V praxi ale obvykle dávka obsahuje kombinaci veřejných a neveřejných titulů a je nutné viditelnost nastavovat dodatečně, což zdržuje.

**Comment by zabak** [comment]
@svetlym prosím o aktualizaci zadání z hlediska administrace K7

**Comment by pavel-stastny** [comment]
@svetlym @zabak Navhruji zavřít a případně otevřít nové issue s administrací K7. (Je tam hodně rozdílných věcí, rozhraní, labels, apod.. )

**Comment by zabak** [comment]
OK, prosím @svetlym aby vytvořil nové issue pro nové admin rozhraní, zde zavírám.

**Comment by svetlym** [comment]
Zdravím,

nejsem si moc jistej, co vlastně mám udělat. V novém administrátorském rozhraní se vůbec nevyznám, viděl jsem ho jen na prezentacích v rámci schůzek vývojového týmu, tj. určitě nezvládnu zohlednit rozdíly oproti stávajícímu rozhraní. Nejsem si taky jistej, kde mám tu issue založit. Tipuju v https://github.com/ceskaexpedice/kramerius-web-client/issues, ale píšete, že by to měla bejt issue pro nové administrátorské rozhraní - nevím, ve které repository se skrývá.

Mám prostě jen otevřít znova issue s tím samým textem v https://github.com/ceskaexpedice/kramerius-web-client/issues?

**Comment by pavel-stastny** [comment]
@svetlym Dobrý den, vyčkal bych na  build beta K7 a pak bych to případně otevřel.  Buď znovu otevřel toto issue nebo pozměněné nové.

**Comment by pavelkocourek** [comment]
Dobře, zavírám ... bud úplně nebo dočasně
