### ISSUE TITLE
chyba v zobrazení názvových údajů u přehledu výsledků v rozhraní DK

### ISSUE THREAD

**Issue by helena-oks** [ceskaexpedice/kramerius#687]
U vícesvazkového díla s vlastním názvem částí se v přehledu výsledků zobrazuje pouze název části, nikoli název souboru. Viz:

 http://kramerius5.nkp.cz/search?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=hospod%C3%A1%C5%99sko-politick%C3%A1%20rukov%C4%9B%C5%A5

V rozhraní původního krameria se to zobrazovalo správně:

http://kramerius4.nkp.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=hospodářsko-politická+rukověť

**Comment by pavel-stastny** [comment]
Klient ma samostatny repozitar. Presunte, prosim, issue tam. (https://github.com/ceskaexpedice/kramerius-web-client)
