### ISSUE TITLE
Kódování znaků v RESTHelper.java pro autorizaci v Solru

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#688]
Dobrý den, máme krameria na verzi 5.4.2 a zdá se že jsme narazili na problém při zabezpečování konzole Solru. Konkrétně při autorizaci knihovna `com.google.gwt.user.server.Base64Utils` v  `kramerius/common/src/main/java/cz/incad/kramerius/utils/RESTHelper.java`  nekóduje některé znaky standardním způsobem kvůlli jejich použití v URL. (viz. https://code.google.com/archive/p/google-web-toolkit/issues/6308)

Když se kramerius autorizuje např. v  `kramerius/common/src/main/java/cz/incad/kramerius/utils/solr/SolrUtils.java`:
```
public static Document getSolrDataInternal(String query) throws IOException, ParserConfigurationException, SAXException {
        String solrHost = KConfiguration.getInstance().getSolrHost();
        String uri = solrHost +"/select?" +query;
        InputStream inputStream = RESTHelper.inputStream(uri, "<no_user>", "<no_pass>");
        Document parseDocument = XMLUtils.parseDocument(inputStream);
return parseDocument;
```
tak se autorizační údaje zakódují přes RESTHelper.inputStream() a odešlou takhle:
![Screenshot from 2019-07-15 11-21-28](https://user-images.githubusercontent.com/17568929/61206454-e8d3c580-a6f2-11e9-93cc-3280cd6f095f.png)
[solrdump.zip](https://github.com/ceskaexpedice/kramerius/files/3391722/solrdump.zip)

Když to porovnám s výstupem z terminálu tak to nejsem schopný dekódovat.
```
$ echo -en '<no_user' | base64 
PG5vX3VzZXI=

$ echo -en '<no_user>' | base64 
PG5vX3VzZXI+

$ echo -en '<no_user>:<no_pass>' |base64 
PG5vX3VzZXI+Ojxub19wYXNzPg==

$ echo -en 'PG5vX3VzZXI$Ojxub19wYXNzPg==' | base64 -d
<no_userbase64: invalid input
```

Napadá mě jestli by nebylo lepší použít jinou knihovnu, která používá standardní base64?

**Comment by MartinRumanek** [comment]
Tohle Java 8 to umí už sama od sebe.

Mělo by stačit nahradit řádek https://github.com/ceskaexpedice/kramerius/blob/master/common/src/main/java/cz/incad/kramerius/utils/RESTHelper.java#L53
na 
```
String encoded = Base64.getEncoder().encodeToString(userPassword.getBytes());
```
Můžete to prosím u sebe vyzkoušet?

**Comment by jdobiasovsky** [comment]
Jo, s touhle úpravou (ještě je potřeba teda přepsat import knihovny na `java.util.Base64;`) už nám to funguje, pokud je v solru udělaný uživatel "<no_user>" s heslem "<no_password>"
![Screenshot from 2019-07-17 13-22-04](https://user-images.githubusercontent.com/17568929/61371801-e52c7400-a895-11e9-9ac8-1d86ff48518a.png)

**Comment by pavel-stastny** [comment]
V buildu změníme knihovnu a přidáme možnost nastavení uživatele a hesla pro připojování se na solr.

**Comment by pavelkocourek** [comment]
@pavel-stastny Muzeem zavřít?

**Comment by zabak** [comment]
@pavel-stastny může se zavřít?
