### ISSUE TITLE
DNNT: zobrazení dokumentu v novém klientovi zobrazuje error 404

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#690]
Pokud dostanu odkaz na dokument, který má příznak DNNT - nový klient mi vyhodí Error 404 bez jakékoliv jiné informace. Pro uživatele je toto matoucí a měla by se zobrazovat informace, proč není dokument dostupný.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o reakciu

**Comment by pavel-stastny** [comment]
To souvisí s klientem, ne s jádrem.  Přenes, prosím, issue tam.  A ještě doplňující otázka:  

> "Pokud dostanu odkaz na dokument, který má příznak DNNT"

To znamená, že když se dostaneš k titulu proklikáním přes aplikaci, tak titul vidíš ale když dostaneš odkaz (třeba mailem) tak máš 404 ?

**Comment by JanMeritus** [comment]
@jahhoo zatvaram, postoval si do noveho klienta?
