### ISSUE TITLE
DNNT CSV export

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#693]
Narazil jsem na problém s CSV exportem. Po zvolení CSV export se nic nezobrazí, ani nikde nemohu najít vyexportovaný soubor.

**Comment by pavel-stastny** [comment]
Dokumentace k procesu: https://github.com/ceskaexpedice/kramerius/wiki/DNNT#proces-exportu-p%C5%99%C3%ADznak%C5%AF-dnnt

**Comment by JanMeritus** [comment]
Proces prebehne bez akejkolvek hlasky o uspesnosti. V defaultnim souboru dle dokumentace sa nic nenachadza, neexistuje ani dany subor.

~/.kramerius4/export-dnnt/

**Comment by pavel-stastny** [comment]
Rekl bych, ze testujete na starsi verzi ve ktere jeste nejsou  komity z 27.8

**Comment by jahhoo** [comment]
Testujeme na poslední dostupné verzi 5.4.4 ze 4.8. Jinou jsme neobdrželi.

**Comment by JanMeritus** [comment]
otestovano, zatvaram
