### ISSUE TITLE
DNNT: Seznam via OAI

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#696]
Ad #665  Melo by byt mozne via API vyvolat cely seznam vrchnich entit oznacenych ako DNNT

**Comment by pavel-stastny** [comment]
Pres API je mozno volat proces, ktery spusti zaroven je mozne vyuzit endpoint pro vyhledavani pripadne se podivat primo do dat.    Proc by melo API poskytovat specialni endpdoint pro DNNT?  (Priznak public a privat resi taky pres search + kombinace poskytnuti datovych streamu)

**Comment by zabak** [comment]
Domnívám se, že toto by mělo být součátí OAI - tj. mít v rámci OAI set public, private a dnnt.

**Comment by JanMeritus** [comment]
@pavel-stastny  @zabak to by bolo idealne. Ziadaju o to i ostatni uzivatelia, obzvlast kvoli integraci s dalsimi systemami. Upravujem nazov a znovuotvaram.

**Comment by zabak** [comment]
@kazooo šlo by to snadno udělat na našem oai?

**Comment by JanMeritus** [comment]
@pavel-stastny @zabak prosim o informaci jestli bylo v tomto smeru neco podniknuto?

**Comment by zabak** [comment]
oai4Solr umožňuje definovat jedno Solr pole, podle kterého se definují OAI sety. Abychom mohli sety definovat podle různých kritérií (např. modely, instituce, sbírky, práva), budeme potřebovat v solru speciální multivalued pole nazvané třeba oai, výhradně pro definici obsahu oai setů. Vzhledem k tomu, jak je oai4solr napsaný tak pokud chceme definovat hierarchické sety, musíme pro každý záznam definovat všechny úrovně hierarchie samostatně, tedy např: 

`"oai":["collection:moll", "collection:moll:austriacus", "collection:moll:austriacus:moravia", "rights:public", "model:map", "institution:MZK", "donator:europeanaTravel"]`

Pak se k tomu musí vyrobit něco, co bude to pole oai "krmit" podle požadovaných kritérií. První krok ale je to pole oai.

**Comment by pavel-stastny** [comment]
@zabak Ale to pole by mělo být přímo v datech, aby se to při první reindexaci nepřepsalo.

**Comment by zabak** [comment]
@pavel-stastny máme dvě možnosti: V každém případě musí to pole v solru vznikat při indexaci na základě dat. Navíc buď budou v Krameriu procesy, které v datech vytvoří to pole a budou ho plnit a pak další, které na základě jeho obsahu budou dělat partial update. Nebo budou muset být procesy které na základě pravidel to pole naplní cestou partial update z jiných polí Solru nebo přinejhorším i z dat. Já jsem pro druhou cestu: mít definovaná pravidla a podle těch sestavovat to pole během indexace, resp. dodatečně jako partial update. 

Pole OAI by mělo být jen na úrovni titulu - ale někdo může mít jiný názor.

Důležitá je taky otázka jaké sety chceme vytvořit. Navrhuji dělat sety podle: 

- práv (brát ale práva na úrovni titulu, stejnou logiku jako má zobrazování zámečku)
- donátora
- instituce (což se teď ale řeší formou sbírek a asi to tak i zůstane i pro účely oai setu)
- sbírky (to by byl asi jediný případ, kdy by se do oai setu dostalo i něco jiného než titul)

**Comment by JanMeritus** [comment]
idealne by bolo moznost brat to cisto dle titulu, prip dle titulu a jeho rocniku

prav vsech typu

**Comment by zabak** [comment]
@JanMeritus jaký je use-case pro to stahování podle práv? Co s tím pak ten kdo si to stáhne bude dělat? Pokud to chceš využít uvnitř NK, nebylo by lepší dotazovat se přes normální API Krameria?

**Comment by JanMeritus** [comment]
@zabak jedna vec je interni kontrola, ale druha vec je moznost verejne si prejst ake tituly su verejne, ake neverejne, co z nich je dnnt, pripadne nejaky iny status. S planovanym zavadzanim diel dnnt a dalsich pravnych statusu, bolo by skvele aby K mohol taketo info poskytovat i via oai

**Comment by zabak** [comment]
@JanMeritus To právě hodně záleží na tom co potřebuješ. Spolehlivější pro účel interní kontroly je ptát se přes API na primární data (protože v OAI to budou data odvozená a nemusí být v daný okamžik 100% aktuální v závislosti na tom jak poběží indexace). Pro externí využití pak stačí úroveň titulu, bál bych se, že smíchat knihy s čísly periodik by nedopadlo dobře, druhá strana by to nemusela pochopit, jak to zase sestavit zpět do nějaké hierarchie.

**Comment by zabak** [comment]
@janmeritus Nasdílel jsem ti dokument popisující jak probíhá sklízení Krameria do CPK, včetně dostupnosti (práv). V případě ndk.cz používáme pro úvodní sklizení OAI, u ostatních knihoven jen dotazy přes API.

**Comment by pavel-stastny** [comment]
@zabak V rámci issue #1034  je nyní možno definovat sety dotazem do solru.
