### ISSUE TITLE
DNNT: Oznacovani z jineho nez defaultne preddefinovaneho souboru

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#697]
Odznacovani funguju s moznosti zvolit si soubor zdrojovych UUID na servry. Oznacovani ma taky tuhle moznost, ale napriek tomu proces vybere defaultny soubor. Verze 5.45dnnt

**Comment by pavel-stastny** [comment]
Zkousim na dane verzi (commit 5f105c0a5324bf963ce0fb16e261a8be1f95f84e) a nedari se mi chybu nasimulovat.

**Comment by pavel-stastny** [comment]
Jak jsem psal.  U sebe se mi nedari chybu nasimulovat. Zaviram, pokud je potreba otevrit, tak, prosim, znovu otevri.
