### ISSUE TITLE
Issue 224:	Implementace zobrazení počtu DJVU/JPG/TXT do K4 dle K3

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#7]
Reported by vlahoda, Dec 6, 2011
Implementace zobrazení počtu DJVU/JPG/TXT do K4 dle K3

May 4, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
uz neni aktualni
