### ISSUE TITLE
V názvu VS, uložené v IE, se znaky s diakritikou zobrazují nekorektně  

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#70]
Když uložím název virtuální sbírky v IE (10, 11), nezobrazí se v názvu korektně diakritika. Kódování na to nemá vliv (chová se stejně s win-1250 i utf-8). 
V Chromu a FF je to OK.
(4.8.3, rev. 5076)

**Comment by pavel-stastny** [comment]
uz by melo byt opraveno.
