### ISSUE TITLE
články/kapitoly - zobrazení, dotaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#700]
Mám dotaz ohledně toho, jak Kramerius zobrazuje články, nebo kapitoly. 

Když naimportuji do Krameria NDK balíček, kde je buď monografie se záznamy kapitol nebo číslo periodika se záznamy článků, 
 
V NDK balíčku jsou strukturní mapy, kde je uvedeno, které stránky patří pod které články/kapitoly.  

Řídí se Kramerius tímhle nebo si skládá ty články a kapitoly sám podle rozsahu stran, který je uveden v záznamu článku, příp. kapitoly?

Díky

**Comment by pavelkocourek** [comment]
@honza-rychtar To se týká zobrazení, odpovíš?

**Comment by honza-rychtar** [comment]
Tohle je spíš na @vlahoda 
V Krameriovi jsou články i kapitoly jako obálku, která obsahuje stránky, které existují taky samostatně pod monografii/výtiskem.
Takže struktura je např.
Monografie
- kapitola 1
- kapitola 2
- strana 1
- strana 2
- strana 3
- strana 4

kapitola 1
- strana 1
- strana 2

Tohle už je interní struktura, se kterou klient pracuje. Ale jak probíha konverze NDK -> Kramerius si nejsem jistý.

**Comment by vlahoda** [comment]
Ano, konvertor NDK -> Kramerius mapovani clanku na stranky dela podle elementu `structLink`. Pokud atribut `from` odpovida elementu `ISSUE`, `VOLUME` nebo `SUPPLEMENT`, je cilova stranka pripojena  vazbou `hasPage`, v ostatnich pripadech (tedy u clanku) je vytvorena vazba `isOnPage`
