### ISSUE TITLE
K6 alpha

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#702]
Dobry den, robili sa nejake zatazove testy ohladom https://github.com/ceskaexpedice/kramerius/wiki/Kramerius-6-Akubra---instalace-a-konfigurace ?

**Comment by vlahoda** [comment]
Porovnaval jsem rychlost ingestu FOXML souboru K5/Fedora3.8 a K6/Akubra na stejnem serveru:
K5 importoval jeden FOXML soubor priblizne za 30 ms, K6 priblizne za 10ms.

Dalsi mereni se tykalo rebuildu processing indexu  (obdoba rebuildu resource indexu ve Fedore) - rebuild uloziste se 420 000 dokumenty trval asi 81 minut, coz je asi 84 dokumentu za sekundu. Test probihal na pomerne slabem virtualu s jednim CPU a 3GB RAM.

Rychlost indexace jsem nemeril, protoze stavajici implementace indexeru se nijak nemenila, novy indexer jeste neni hotovy.

**Comment by JanMeritus** [comment]
@vlahoda  nemyslel som ohladom ingestu, ale skor ohladom stability, eg. pri 100, idealne 150 mil. objektoch roznych typov a vrstvenia

**Comment by zabak** [comment]
@JanMeritus lze toto zavřít?

**Comment by zabak** [comment]
Týká se K6, zavírám
