### ISSUE TITLE
Akubra: ingest FOXML a property createdDate

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#703]
Pokud importuji Krameriovským procesem FOXML, které neobsahuje property createdDate, to se nevytvoří, přesto že se aktualizuje lastModifiedDate.
V ukázkových datech createdDate je, proto se to doteď neprojevilo. 
Dá se čekat, že se při výrobě foxml nebudou vytvářet property createdDate, lastModifiedDate, ownerId a state, protože ty souvisí se samotným úložištěm (dříve Fedora).
Neexistence createdDate pak shodí indexaci objektu. Viz kramerius/processes/indexer/src/cz/incad/kramerius/indexer/res/K4.xslt, kde se createdDate používá pro pole created_date.

Příklad:
z FOXML před ingestem:
```
    <objectProperties>
        <property NAME="info:fedora/fedora-system:def/model#label" VALUE="Deutsche Nachrichten"/>
        <property NAME="info:fedora/fedora-system:def/model#state" VALUE="Active"/>
    </objectProperties>
```
Ano, ten state bych měl taky dát pryč.
Z akubry:
```
    <objectProperties>
        <property NAME="info:fedora/fedora-system:def/model#label" VALUE="Deutsche Nachrichten"/>
        <property NAME="info:fedora/fedora-system:def/model#state" VALUE="Active"/>
        <property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" VALUE="2019-10-24T14:49:55.844Z"/>
    </objectProperties>
```

**Comment by rzeh4n** [comment]
Mimochodem asi by to chtělo label Akubra, já na to nemám práva.

**Comment by rzeh4n** [comment]
@vlahoda

**Comment by vlahoda** [comment]
@rzeh4n Pridal jsem te do tymu. A zitra tenhle problem opravim. Diky!
