### ISSUE TITLE
Akubra: item/PID/něco endpointy nefungují pro neindexované objekty

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#705]
Dokud není objekt indexován (v solr-core kramerius4), nefungují korektně endpointy pro objekt. Např.:
http://localhost:8080/search/api/v5.0/item/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6
```
{
"pid": "uuid:0eaa6730-9068-11dd-97de-000d606f5dc6",
"handle": {
"href": "http://localhost:8080/search/handle/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6"
},
"donator": "donator:norway"
}
```
(funguje, i když vrací minimální záznam, po zaindexování tam toho je víc).

http://localhost:8080/search/api/v5.0/item/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6/foxml
```
<message>
<status>403</status>
<message>access denied</message>
</message>
```
Tady je 403, ale proč? Tohle je čistě na Repository (Akubra) i bez Resource-indexu.

http://localhost:8080/search/api/v5.0/item/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6/children
http://localhost:8080/search/api/v5.0/item/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6/siblings
http://localhost:8080/search/api/v5.0/item/uuid:0eaa6730-9068-11dd-97de-000d606f5dc6/parents
```
[]
```
Http kód 200, ale žádná data. Tohle by zase s indexem (vyhledávácím solr core kramerius4) nemělo souviset, je to na Repository a Resource Index (solr core "processing").

**Comment by vlahoda** [comment]
Tyto endpointy prevzaly beze zmeny implementaci z K5, musim to projit s @pavel-stastny, proc tam vlastne bylo volani indexu.

**Comment by pavel-stastny** [comment]
Ahoj, pokusim se odpovedet.  

> Tyto endpointy prevzaly beze zmeny implementaci z K5, musim to projit s @pavel-stastny, proc tam vlastne bylo volani indexu.

Jo, jo.. vyuzivaji se data z indexu pro zjisteni deti potomku a taky pro cestu nahoru.  Pri tech moznostech, ktere s fedoru 3 byly, to byla vlastne jedina mozna cesta. Dotaz do resource indexu byl pro API prilis pomaly, stejne tak prochazeni RELS-EXT vazeb.

>  Tady je 403, ale proč? Tohle je čistě na Repository (Akubra) i bez Resource-indexu.

Po zaindexovani titulu uz to nehlasi ? Pri vyhodnocovani se taky vyuizva cesta nahoru, ktera se bere z indexu.  Mozna ze to s tim souvisi.
