### ISSUE TITLE
nový formát dátumu vydania výtisku

### ISSUE THREAD

**Issue by MirkaBenackova** [ceskaexpedice/kramerius#707]
Dobrý deň, 
mala by som otázku ohľadne zobrazovania dátumu vydania výtisku u periodík. Aktuálne pravidlá pre popis periodík povoľujú nasledovné formáty: 
DD.MM.RRRR
MM.RRRR
MM.-MM.RRRR
RRRR
V súvislosti s pripravovanou aktualizáciou pravidiel pre popis by sme radi zaviedli ako možný formát aj DD.MM-DD.MM.RRRR . Neviem ale, či by daný formát nespôsobil pri zobrazení/radení apod. v Krameriu problém. Myslíte, že by sme mohli daný tvar dátumu pridať do pravidiel pridať bez toho aby to spôsobilo problémy? 
Ďakujem za odpoveď!

**Comment by pavel-stastny** [comment]
Dobry den, 

v rámcí indexace není tento typ podporován. Měním issue na požadavek na rozšíření.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujem Vám za odpoveď. Dodatočne sme prišli ešte na ďalšie formáty, bolo by možné rozšíriť to aj o: 
DD.MM.RRRR-DD.MM.RRRR
MM.RRRR-MM.RRRR
DD.-DD.MM.RRRR
Ďakujem.

**Comment by pavelkocourek** [comment]
@rzeh4n Martine, vyřešil to prosím indexer K7?

**Comment by rzeh4n** [comment]
Indexer K7 podporuje všechny zmiňované formáty, tedy:

> DD.MM.RRRR - pokud známe den (např. 27.01.1998)
> MM.RRRR - pokud známe pouze měsíc (např. 01.1998)
> RRRR - pokud známe pouze rok (např. 1998 )
> MM.-MM.RRRR - vydání pro více měsíců (např. 01.-02.1998)
> MM.RRRR-MM.RRRR – vydání pro více měsíců (např. 12.1998-01.1999)
> DD.MM.-DD.MM.RRRR - vydání pro více dní (např. 31.01.-01.02.1998)
> DD.MM.RRRR-DD.MM.RRRR – vydání pro více dní (např. 31.12.1998-01.01.1999)
> DD.-DD.MM.RRRR – vydání pro více dní (např. 02.-03.02.1998)

**Comment by pavel-stastny** [comment]
Formáty jsou součástí indexace v K7.  Pokud by ještě něco chybělo, je možno issue otevřít v případě založit nové.
