### ISSUE TITLE
Testovanie K6 - Migračný nástroj

### ISSUE THREAD

**Issue by natal1H** [ceskaexpedice/kramerius#708]
Dobrý deň,
mala by som otázku ohľadom migračného nástroja, ktorý je dostupný na [https://github.com/ceskaexpedice/ceska-digitalni-knihovna/tree/mzkmigration/tools/migration](https://github.com/ceskaexpedice/ceska-digitalni-knihovna/tree/mzkmigration/tools/migration), konkrétne k jeho build pomocou gradle. Pri spustení gradle build je problém so závislosťou _'cz.incad.kramerius', name: 'common', version: '5.3.3'_ ktorú sa snaží nájsť najprv pomocou JCenter repozitára, kde avšak nie je. Preto sa chcem spýtať, či je potrebné vykonať ešte nejaké ďalšie kroky pred build prípadne ako inak poriešiť tento problém.
Ďakujem za odpoveď.

**Comment by pavel-stastny** [comment]
Dobry den, 

tento nastroj mel slouzit pouze pro prevod dat rucne prenesenych z MZK a je urceny pouze pro ucely CDK. Chel bych se zeptat, k cemu jej potrebujete ?

**Comment by fstepanovsky** [comment]
Dobrý den,
na tento nástroj jsme byli odkázáni, pro potřeby migrace z legacyfs do akubry a proto by bylo vhodné jej zprovoznit, v plánu je migrovat jak NKP, tak MZK.
Další otázkou je jak budeme efektivně plnit index akubry v Krameriu.

**Comment by JanMeritus** [comment]
@fstepanovsky diki. @pavel-stastny  pripajame sa, v NK kvoli procesom nutnym k prechodu na K6 budeme musiet tento nastroj testovat, aby sme mohli predikovat pouzitie na velkych datach, tak poprosime o pripadnu aktualizaciu a odladenie.

**Comment by vlahoda** [comment]
Funkce tohoto konvertoru chci v nejblizsi dobe integrovat primo do Krameria, jednak aby nebyl problem se samostatnym buildem a hlavne ho upravim tak, aby delal jen to, co potrebuje Kramerius - ted se v nem jeste navic delaji konverze dat potrebne pro CDK.
Index akubry (tedy jadro processing, ktere nahrazuje puvodni resource index) se bude vytvaret primo pri teto konverzi z legacy fs.
Predpokladam, ze bych to mohl mit pripravene do konce listopadu.

**Comment by fstepanovsky** [comment]
Dobrý den,
chtěl bych se zeptat, jestli je nutné nástroj integrovat přímo do Krameria, pokud by mělo jít o jednorázovou konverzi, respektive jestli máte s nástrojem poté i další plány v rámci Krameria.

Zároveň bych se chtěl zeptat jestli počítáte s nějakým _reportem progresu_ migrace tzn. že budeme vědět kolik už _bylo zpracováno / kolik zbývá_.
Od toho také vyvstává to, jestli tam bude nějaký záchytný mechanismus, když migrace padne, abychom nemuseli migrovat od počátku - přeci jen těch dat je hodně a mohlo by nastat taky to, že bychom kvůli pádům nemuseli zmigrovat vůbec.

**Důležité** je taky podotknout, že nám **testování stojí na migraci** a testů ohledně ji, ale i zmigrovaných dat.

**Comment by JanMeritus** [comment]
Dobry den, pan @vlahoda osobne by som bol za to aby migracny nastroj bol transparentny - v zmysle samostatny engine, plus transformacne sablony/kroky. 

Mal by sa navyse dat pustat samostatne, bez inicialnej zavislosti na Krameriovi.

**Comment by vlahoda** [comment]
Migracni nastroj je nyni soucast distirbuce Kramerius 7.0.0-beta1. Popis pouziti je uveden v release notes. Zaroven pripominam, ze Kramerius 7 podporuje i format uloziste legacy-fs, konverze do formatu akubra tedy neni nezbytne nutna.
