### ISSUE TITLE
Testování K6 - synchronizace processing indexu

### ISSUE THREAD

**Issue by xermak00** [ceskaexpedice/kramerius#709]
Dobrý den, 

třída [ProcessingIndexCheck.java](https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/cz/incad/kramerius/resourceindex/ProcessingIndexCheck.java), která (pokud se nemýlím) slouží k synchronizaci processing indexu, používá [ProcessingIndexFeeder.java](https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/cz/incad/kramerius/resourceindex/ProcessingIndexFeeder.java), konkrétně její metodu [iterateProcessing()](https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/cz/incad/kramerius/resourceindex/ProcessingIndexFeeder.java#L113-L133). Tato metoda prochází všechny záznamy v Solru podle dotazu <strong>"\*:\*"</strong>, a má ten problém že prochází indexem pomocí stránkování přes "rows" a "offset". Jak se ukázalo v provozu, při velkých objemech dát takové stránkování není efektivní, zabírá spoustu času, a má být implementováno pomocí cursoru.

Viz také #588 a [komentář](https://github.com/moravianlibrary/kramerius/issues/246#issuecomment-384286149)

**Comment by xermak00** [comment]
Chtěl bych ještě doplnit k té synchronizaci. [Pokud správně chápu](https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/cz/incad/kramerius/resourceindex/ProcessingIndexCheck.java#L34-L37), každý "triplet" z indexu se zpracovává tak, že se kontroluje přítomnost jeho "source", tedy uuid dokumentů, v úložišti. Každý takový dokument má minimálně **1** záznam "description" a ještě **n** záznamu relací se stejným "source" a proto by se jeden "source" kontroloval **n+1** krát, což by zbytečně prodlužovalo kontrolu a zabíralo zdroje. Šlo by to také nějak prosím zoptimalizovat? Děkuji

**Comment by pavel-stastny** [comment]
Dobrý den, 

proces vznikl při vývoji krameria pro fedoru 4. V implemnetaci pro akubru už není třeba.  Odstraníme z dialogu indexace (kde je použitý) a issue zavřeme.

**Comment by vlahoda** [comment]
ProcessingIndexCheck uz ve verzi Kramerius 7 neni. Pokud je nutne vytvorit nebo obnovit processing index, je k tomu urcen administratorsky proces Rebuild processing index  (je to obdoba puvodniho skriptu rebuild.sh ve fedore 3)
