### ISSUE TITLE
Generovanie štatistík

### ISSUE THREAD

**Issue by MarosGrm** [ceskaexpedice/kramerius#712]
Pri väčšom objeme štatistických údajov v DB môže generovanie štatistík trvať aj viac ako hodinu, čo je značne problematické pretože ak generovanie zlyhá v nejakom štádiu tak na výstup sa dostane iba prázdny graf/súbor. Taktiež toto generovanie môže byť prerušené kvôli http timeoutu, ktorý je štandardne 10 minút a meniť to zakaždým v configuration.properties nie je najlepšie riešenie.
Kvôli tomuto by bolo lepšie zmeniť generovanie štatistík na proces, toto by umožnilo sledovať priebeh v procesnej konzole a v prípade chyby by to poskytlo cenné informácie. Vďaka tomuto by sa odstránil aj problém s timeoutom.

**Comment by pavel-stastny** [comment]
@zabak Jak dlouho nyní zabere generování statitik v případě MZK na K7?

**Comment by r2it-git** [comment]
@pavel-stastny Petr mi poslal, že mám na to odpovedať. Podľa toho čo sa tam píše, predpokladám, že sa jedná o generovanie celoročných štatistík? V každom prípade, v MZK generujeme len denné NKP logy, a to trvá na deň cca 10 minút. Ale vzhľadom na to, že v K7 sa štatisitky generujú zo Solru a dávkujú sa, tak nemôže dôjsť k prerušeniu kvôli timeoutu.

Na druhú stranu k takémuto prerušeniu dochádza v K5, kde sa štatistiky generujú pomocou jedného query na postgres. V K5 Kramériu kvôli tomu musíme mať nastavenú životnosť db spojenia na viac ako 10 minút. Ale predpokladám, že táto implementácia sa v K5 už nebude meniť.

A celoročné štatistiky v K7 negenerujeme, keďže po novom na to existuje poltár statistiky.ndk.cz.

Za mňa sa môže zavrieť, je to outdated požiadavok.

**Comment by pavel-stastny** [comment]
Ok. Diky za odpověď
