### ISSUE TITLE
Řazení dle počtu výskytů

### ISSUE THREAD

**Issue by ochrpa** [ceskaexpedice/kramerius#713]
Zdravím,

mám návrh na vylepšení: **Řazení dle počtu výskytů**

Aktuálně je možné výsledky řadit:
- Podle relevance
- Abecedně
- Nově přidané
- Od nejnovějších
- Od nejstarších

Bylo by možné přidat volbu "Podle počtu výskytů"?

Např. u http://www.digitalniknihovna.cz/mzk/search?q=Sm%C3%ADchov&sort=relevance

Předem díky za vyjádření.

**Comment by pavel-stastny** [comment]
Dobrý den, toto issue spíš patří do klientské části (https://github.com/ceskaexpedice/kramerius-web-client).  Můžete to vytvořit tam?  

Děkuji.

**Comment by ochrpa** [comment]
Omlouvám se, vytvořeno [v klientské části](https://github.com/ceskaexpedice/kramerius-web-client/issues/279). Zde uzavírám.
