### ISSUE TITLE
statistiky - IP adresy

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#714]
Potřebovali bychom ve statistikách funkci, že se započítá unikátní IP adresa jen jednou za den. Takže, když přistoupí uživatel z jedné IP adresy vícekrát, bude se to počítat jen jednou.

**Comment by zabak** [comment]
Tohle nejde počítat jen přes IP adresy. Spousta firem nebo poskytovatelů používá NAT. Návštěvy na webu se zase obvykle počítají s třicetiminutovým timeoutem. Jaký je důvod toho jednodenního počítání?
