### ISSUE TITLE
DNNT - neefektivni oznacovani

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#718]
Proces pridelovani priznaku DNNT je neefektivni. Pro 1000 monografii trva v radu mnohych hodin (zatim 14h). Pre pridelenie c. 70 000 priznakov vcetne hlbokych periodik moze trvat vic nez dva mesice. 

Prosim o optimalizaci procedury.

EDIT>> 999 monografii a 1 periodikum (Na hlubinu)

**Comment by pavel-stastny** [comment]
Asi budu potrebovat konfiguraci procesu. Treba mailem.

**Comment by JanMeritus** [comment]
@jahhoo

**Comment by jahhoo** [comment]
@pavel-stastny stačí zaslat seznam UUID?

**Comment by jahhoo** [comment]
Označování nejvíce vytěžuje SOLR server. Server má 4 virtuální CPU, ty běží na 70%, RAM využívá 18GB, SSD disky. Stejně je proces dost pomalý, neefektivní.

**Comment by pavel-stastny** [comment]
add konfigurace: Slo mi predevsim o nastaveni procesu - properties soubory. Zejmena property typu: `dnnt.usecursor`, `.dnnt.solr.batchsize  `. Zaroven by bylo dobre poslat vypis z procesu a ten seznam uuid mozna taky.

**Comment by jahhoo** [comment]
Toto nemáme nastavené, takže je to v defaultu.

**Comment by pavel-stastny** [comment]
Jeste nez poslete log soubor, zmente prosim tu promennou `dnnt.usecursor`   na `dnnt.usecursor = true`  a spustete.  Pak jestli muzete poslat log z obou procesu.

**Comment by JanMeritus** [comment]
vyznamne to zrychlilo cely proces. @jahhoo prosim este dodaj log a mozme to uzavriet
