### ISSUE TITLE
Testování K7 - nefunguje mazání a změna viditelnosti

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#721]
Dobrý den, v K7 nefunguje mazání a změna viditelnosti, při posílání požadavku na mazání třeba

```
host/search/lr?action=start&def=aggregate&out=text&nparams={delete;{uuid\:1;uuid\:2}
```
K7 vyhazuje stacktrace, a níc se nenaplanuje

```
30-Jan-2020 12:56:15.539 INFO [http-nio-8080-exec-6] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:460)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Podle #470 a #637 jde o novější verzi Tomcatu, který zakazuje symboly '{' a '}' v requestu. Bylo to řešeno ve vetvi **fcrepo4** a chci se zeptat jestli tyto změny nahodou neztratily.

Děkuji

**Comment by pavel-stastny** [comment]
Zdravim,  probihal merge vetvi a je mozne, ze nekterych procesu doslo spatnemu zmergovani.  Podivame se na to.

**Comment by kazooo** [comment]
Dobrý den,

stejný problém se projevuje i při přiřazení dokumentů do virtuálních sbírek

```
host/search/lr?action=start&def=aggregate&out=text&nparams={virtualcollections;{add;uuid\:1;vc\:1}}&_=1582545409722
```
a také při aplikování pohyblivé zdi u dokumentů, u kterých by mělo dojit ke změně viditelnosti

**Comment by filak** [comment]
@kazooo Zkuste si nastavit Tomcat - relaxedQueryChars="{}\"

Viz https://github.com/ceskaexpedice/kramerius/issues/470#issuecomment-589650111

**Comment by kazooo** [comment]
@filak Dobrý den, děkuju za napovědu, nastavil jsem do server.xml **relaxedQueryChars="{}"**, v logach K7
```
WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'relaxedQueryChars' to '{}' did not find a matching property.
```
také jsem zkusil **relaxedPathChars="{}"**, výsledek je stejný
```
WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'relaxedPathChars' to '{}' did not find a matching property.
```
Podle [článku](https://www.programmersought.com/article/51421117822/;jsessionid=DD80F7EFB82A73EBEC0EA518ED02A2F9) jsem také zkusil nastavit **tomcat.util.http.parser.HttpParser.requestTargetAllow={}** do catalina.properties
Ve všech uvedených případech K7 stale vyhazuje stejnou chyby (IllegalArgumentException: Invalid character found in the request target.) a níc se neplanuje.

**Comment by filak** [comment]
@kazoo To spis vypada, ze mate nejaky starsi Tomcat - v 8.5 mi ty atributy funguji (v kombinaci s K5.4.2)

**Comment by kazooo** [comment]
@filak všechno bylo otestováno na Tomcat 9.0.2
Tak jsem zkusil 8.5.51, tam ty atributy fungují i pro K7, je také funkční poslední Tomcat [9.0.31](https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.31/) takže zatím zůstaneme u něj

**Comment by pavel-stastny** [comment]
U obou procesů jsem prolematické znaky enkódoval.
