### ISSUE TITLE
Import NDK balíku - úprava

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#723]
Když importuji do Krameria NDK balík, tak si Kramerius při importu vygeneruje uuid pro jednotlivé strany. Šlo by to udělat tak, že je vygeneruje, jen pokud je tam nenajde? Pokud tam budou, tak by si je vzal z toho importovaného balíčku?

**Comment by vlahoda** [comment]
Zmenim konvertor METS NDK tak, ze bude pro stranky prebirat cele elementy MODS a DC (tedy i s uuid), pokud uz v dane verzi METS dokumentu budou. 
@krizovj Narazili jste v nove verzi specifikace NDK jeste na nejaky dalsi problem, ktery by Kramerius nekonvertoval spravne?

**Comment by krizovj** [comment]
@vlahoda vyzkouším a dám vědět

**Comment by krizovj** [comment]
Ještě mám problém, že se mi nezobrazí čísla stran ani v jádru, ani v klientovi.
![chybejicisla](https://user-images.githubusercontent.com/21309201/74223627-6e364d00-4cb7-11ea-8bd3-03e7baca8173.jpg)

Což bude asi způsobeno tím, že dříve bylo číslo stránky i index stránky v MODS v jednom elementu part

![jedenpart](https://user-images.githubusercontent.com/21309201/74223509-27485780-4cb7-11ea-9a21-33e47738ec0b.jpg)

Ale teď podle standardu má být rozdělený do dvou
![dvaparty](https://user-images.githubusercontent.com/21309201/74223534-34654680-4cb7-11ea-8b80-0452fc97fcbe.jpg)

**Comment by vlahoda** [comment]
Hm, to uz neni problem konvertoru METS-> Kramerius, ale buyde potreba upravit XSLT sablonu indexeru. Zalozim k tomu samostatne issue.
