### ISSUE TITLE
Statistiky - roční výkaz

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#724]
Potřebovali bychom přidat k ročnímu výkazu ve statistikách možnost filtrovat podle Akcí, viditelnosti a IP adres. 
U všech statistik, kde je možné vygenerovat xml nebo csv by mělo být v souboru uvedeno, jaké filtry byl použity.

**Comment by zabak** [comment]
Jak se bude ta viditelnost posuzovat? Pokud přistupuji z IP adresy, ze které je viditelné všechno a koukám na něco co je zamčené, bude se to počítat jako viditelné nebo neviditelné?

**Comment by krizovj** [comment]
Bere se to podle příznaku public / private, takže IP adresy na to nemají vliv.
