### ISSUE TITLE
K7 SOLR managed-chema - pole text_lemmatized... 

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#726]
Proč jsou tato pole zakomentovaná, když se na ně pak dále odkazuje ? SOLR pak samozřejmě vyhodí výjimku při vytváření jádra kramerius...

https://github.com/ceskaexpedice/kramerius/blob/master/installation/solr-7.x/kramerius/conf/managed-schema

    
    <field name="text" type="text_general_not_lemmatized" indexed="true" stored="true" multiValued="true" />

**Comment by vlahoda** [comment]
Lemmatizovana pole neunosne zvetsovala velikost indexu. Chybne jsme to ale opravili jen ve schematu pro SOLR cloud.

**Comment by kazooo** [comment]
Zvetsovalo se to kvuli ukladani fulltextu do indexu. Po vypnuti *stored="false"*, jako treba u [text_ocr poli](https://github.com/ceskaexpedice/kramerius/blob/master/installation/solr-7.x/kramerius/conf/managed-schema#L506-L508), tento problem uz neni. Slo by to take rozkomentovat a upravit i v aktualni testovaci K7?

**Comment by rzeh4n** [comment]
@kazooo  Pro nový index, který je v testovací instalaci K7 v MZK je stored jen pole text_ocr, další pole (text_ocr.lemmatized, text_ocr.lemmatized_ascii, text_ocr.lemmatized_ascii, text_ocr.lemmatized_nostopwords) mají stored="false".
U toho text_ocr je to potřeba pro zobrazení kontextu ve fulltext vyhledávání.

https://github.com/ceskaexpedice/kramerius/blob/indexer/search-index/src/main/resources/solr_core/solr7x/search/conf/managed-schema
