### ISSUE TITLE
Indexer nepodporuje novy standard NDK MODS s opakovanym vyskytem elementu mods:part

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#727]
Oteviram komentar @krizovj z issue #723 jako samostatne issue: 

Ještě mám problém, že se mi nezobrazí čísla stran ani v jádru, ani v klientovi.
![chybejicisla](https://user-images.githubusercontent.com/21309201/74223627-6e364d00-4cb7-11ea-8bd3-03e7baca8173.jpg)

Což bude asi způsobeno tím, že dříve bylo číslo stránky i index stránky v MODS v jednom elementu part

![jedenpart](https://user-images.githubusercontent.com/21309201/74223509-27485780-4cb7-11ea-9a21-33e47738ec0b.jpg)

Ale teď podle standardu má být rozdělený do dvou
![dvaparty](https://user-images.githubusercontent.com/21309201/74223534-34654680-4cb7-11ea-8b80-0452fc97fcbe.jpg)

_Originally posted by @krizovj in https://github.com/ceskaexpedice/kramerius/issues/723#issuecomment-584539211_

**Comment by krizovj** [comment]
Ten opakovaný výskyt elementu part má být také u kapitol a článků (ale ProArc to ještě nedělá správně, takže nemám příklad), viz tady: https://github.com/proarc/proarc/issues/1098

**Comment by zabak** [comment]
@vlahoda je tohle vyřešené?

**Comment by kerschfilip** [comment]
Myslím, že tohle je v K7 v pořádku.
