### ISSUE TITLE
Přidání dalších dvou parametrů do migračniho skriptu ?

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#733]
Nevime, jak dopadne migrace, kdyz migr. skript má číst tabulky (datastreampaths, objectpaths) a má je čist celé naráz najednou a ukládat do polí.
V tabulce 'objectpaths' mame okolo 57 mil. zaznamu, v tabulce 'datastreampaths' mame okolo 117 mil. zaznamu.
Co takhle pridat tomu migr. skriptu dalsi parametry (za posledni parametr 'processing index' (tru/false) ) dalsi dve cisla, ktera by rikala, kde (pred cim) to stopnout (skoncit select).
V souboru 
https://github.com/ceskaexpedice/kramerius/blob/master/processes/migration/src/main/java/cz/incad/migration/LegacyMigrationParts.java
by se pak na řádku 55 jednoduše rozšířil sql dotaz:
select * from datastreampaths where tokendbid > " + args[1] + " and tokenbid < " + args[4] + " order by tokendbid;
a na řádku 91 analogicky
select * from objectpaths where tokendbid > " + args[2] + " and tokenbid < " + args[5] + " order by tokendbid", consumer;
a tak bychom si sami určovali, kolik toho najednou chceme zmigrovat.
args[3] by musel byt vzdy FALSE.

**Comment by vlahoda** [comment]
Ten skript ale necte zminene tabulky cele najednou ani je neuklada do zadnych poli. Iteruje pomoci resultset.next() a zpracovava kazdy radek zvlast - v podstate jen presouva odpovidajici soubor do jineho adresare, nic vic. Moznost spustit ho od nejakeho konkretniho id je tam pridana proto, aby bylo mozne preskocit objekt fedory, ktery by zpusoboval nejakou neocekavanou chybu (treba kvuli vadnemu sektoru na disku), ale nevidim duvod proc predem omezovat horni mez iterace.

**Comment by zabak** [comment]
@hlavacekrene prosím doplň info o aktuálním stavu, případně otestuj na nové verzi Krameria.

**Comment by zabak** [comment]
@hlavacekrene můžu tohle uzavřít?
