### ISSUE TITLE
Pridat do migrace kopirování objectů a streamů

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#734]
Dobry den,
meli bychom prosbu. V soucasne dobe migracni skript presouva soubory (objectFile.renameTo(targetFile))  - řádek 131 v souboru
https://github.com/ceskaexpedice/kramerius/blob/master/processes/migration/src/main/java/cz/incad/migration/LegacyMigrationParts.java
objectStream nebo dataStream z fedory do akubry na urovni filesystemu. 
Potrebovali bychom, kdyby to bylo rozsirene o kopirovani souborů. (stejne na urovni filesystemu). 
Doplnit tam neco jako... ze tridy FileUtils.java - copyFile(objectFile, targetFile);
A dale, aby se dalo vstupnim parametrem urcit, jetli se soubory budou tedy prejmenovavat-presouvat nebo prekopirovavat (bud jedno nebo druhé). 
Dale potrebujeme, aby se pri kazdem presunu (nebo prekopirovani provedl) LOGGER.info. Vy ho mate na řádku 132 a 133 zakomentarovany (prosime odkomentovat) a jeste je potreba, 
aby se zalogovalo, co se presunulo (nebo prekopirovalo), cili tam jeste doplnit treba tokendbid, path.
Dekuji

**Comment by vlahoda** [comment]
Jestli na tom opravdu trvate, casem to tam jako konfigurovatelnou moznost doplnim. Ale podle meho nazoru je mnohem efektivnejsi misto kopirovani jednotlivych souboru timto konvertorem udelat si kopii celeho uloziste najednou na urovni filesystemu a konvertorem nechat transformovat originalni uloziste funkci renameTo - tedy move. Totez se tyka logovani - nevidim jediny rozumny duvod logovat konverzi kazdeho jednotliveho souboru, staci logovani po blocich , abyste pripadne vedeli, kde restrtovat konverzi.
