### ISSUE TITLE
Testování K7 - Hazelcast komunikace mezi K7

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#737]
Dobrý den,

v rámci testování K7 potřebujeme vyzkoušet spolupráci víc instancí K7. Hazelcast bez problémů propojuje instance v rámci jedné docker sítě, avšak nedokáže spojit Krameria z různých serverů napříč sítí. To se dá řešit pomocí [konfiguraci](https://docs.hazelcast.org/docs/2.0/manual/html/ch13.html) Hazelcastu, ale kvůli tomu že v K7 Hazelcast je [konfigurován kódem](https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/cz/incad/kramerius/fedora/om/impl/HazelcastServerNode.java), nehledá ve filesystému další konfigurace. Tím pádem nejsme schopni vyřešit problém komunikace Krameriů, a chtěli bychom požádat o opravu kódu, aby bylo možné Hazelcast konfigurovat i pomocí [hazelcast.xml](https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-data-hazelcast-chemistry-sample/server/src/main/resources/hazelcast.xml), kde je možné specifikovat jednotlivé adresy ostatních instancí Hazelcastu.

Děkuji

**Comment by vlahoda** [comment]
Omlouvam se, to mi nedoslo, ze jsem konfiguraci pres xml zablokoval... 
Doplnil jsem ted dve property: hazelcast.config a hazelcast.clientconfig, kterymi je ted mozne definovat cestu ke konfiguracnimu souboru pro hazelcast server, resp. klient. Soubory mohou byt urceny bud absolutni cestou nebo relativne ke konfiguracnimu adresari .kramerius4.

**Comment by kazooo** [comment]
Dobrý den, děkuji za opravu, ale setkali jsme se s dalším problémem.

Daváme do configuration.properties **hazelcast.config=/root/.kramerius4/hazelcast.xml** a **hazelcast.clientconfig=/root/.kramerius4/hazelcast.xml** nebo jen **hazelcast.config=/root/.kramerius4/hazelcast.xml**, konfigurace se načte bez problémů, ale Kramerius píše:

```
27-Feb-2020 14:20:29.821 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
27-Feb-2020 14:20:29.824 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/search] startup failed due to previous errors
```
a */search* endpoint vrací 404 a níc nefunguje.

Když je v configuration.properties pouze **hazelcast.clientconfig=/root/.kramerius4/hazelcast.xml**, pak Kramerius vyhazuje 505 a stacktrace:

```
java.lang.NoClassDefFoundError: Could not initialize class cz.incad.kramerius.fedora.om.impl.AkubraDOManager
	cz.incad.kramerius.fedora.impl.FedoraAccessAkubraImpl.<init>(FedoraAccessAkubraImpl.java:42)
	cz.incad.kramerius.fedora.impl.FedoraAccessAkubraImpl$$FastClassByGuice$$6ed1eda7.newInstance(<generated>)
	com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
...
```
Podle [kodu](https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/cz/incad/kramerius/fedora/om/impl/AkubraDOManager.java#L76-L90), Hazelcast konfigurace v AkubraDOManager se načítá ve statickém kontextu třídy.

Používáme konfiguraci bud' prazdnou
```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
			       http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">
</hazelcast>
```
anebo s jednoduchým nastavením

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
			       http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">
  <properties>
        <property name="hazelcast.logging.type">jdk</property>
    </properties>
</hazelcast>
```

**Comment by vlahoda** [comment]
Kdyz je v logu hlaska  One or more listeners failed to start. Full details will be found in the appropriate container log file, znamena to, ze se nepodarilo spustit aplikaci, obvykle kvuli chybe v konfiguraci. Proto to hazelo chyby 404. Podrobnosti o pricinach lze obvykle najit v logu localhost.log. A tam byste se docetli, ze jste nemeli spravne nastavenou konfiguraci hazelcast i s uvedenim podrobnosti.

Predevsim neni mozne pouzit stejny konfiguracni soubor pro klient a pro server, maji jine schema. Dal nestaci pouzit prazdnou konfiguraci, je potreba minimalne nastavit instance-name a group/name. Pokud pouzijete defaultni hodnoty akubrasync a dev, nemusite vubec nastavovat hazelcast.clientconfig, staci nastavit jenom hazelcast.config

```
hazelcast.config=hazelcast-config.xml
#hazelcast.clientconfig=hazelcast-client-config.xml
```

Minimalni konfiguracni soubory vypadaji takto, parametry clusteru budete pridavat do konfigurace serveru, tedy hazelcast-config.xml:
```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.hazelcast.com/schema/config
          http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">
 <instance-name>akubrasync</instance-name>
 <group>
     <name>dev</name>
 </group>
</hazelcast>
```

Minimalni obsah souboru hazelcast-client-config.xml:
```
<hazelcast-client xmlns="http://www.hazelcast.com/schema/client-config"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                 http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.11.xsd">
   <instance-name>akubrasync</instance-name>
   <group>
       <name>dev</name>
   </group>
</hazelcast-client>
```
