### ISSUE TITLE
Kramerius 5.4.2 - indexační proces - ošetření nevalidních XML znaků při indexování TXT streamů

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#738]
Reindexoval jsem teď komplet periodika (SOLR 7.7.2) a často se v logu procesu objevují chyby typu:

[Fatal Error] :32:42: Character reference "`&#25`" is an invalid XML character.
... DOP. cz.incad.kramerius.indexer.SolrOperations indexByPid
SEVERE: Error indexing document uuid:168c2a04-e46e-11e8-bdc5-d485646517a0. Continuing.
org.xml.sax.SAXParseException; lineNumber: 32; columnNumber: 42; Character reference "`&#25`" is an invalid XML character.

Našel jsem zatím v lozích následující znaky:

    &#25

    &#1

    &#7

    &#12

V Kram 5.2.4 se SOLR 3.5 to zaindexovalo normálně:
https://kramerius.medvik.cz/search/i.jsp?pid=uuid:168c2a04-e46e-11e8-bdc5-d485646517a0

**Comment by vlahoda** [comment]
To by melo uz byt opravene od srpna 2019 v commitu d3d6f75e

**Comment by filak** [comment]
No release https://github.com/ceskaexpedice/kramerius/releases/tag/5.4.2 se tak rozhodně nechová.

**Comment by vlahoda** [comment]
No to bude asi tim, ze je starsi nez ta oprava. 
@pavel-stastny Musime mergovat ty zbyvajici pull-requesty a vydame posledni verzi K5.

**Comment by filak** [comment]
S K5.5.0 už je to OK.
