### ISSUE TITLE
Testování K7 - synchronizace mezi procesy v rámci jednoho Krameria

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#743]
Dobrý den,

spustil jsem několik procesů nad jednou monografií v rámci jednoho Krameria. Podle logů vypadá, že procesy nejsou synchronizovány mezi sebou. Jeden z procesů vyhazuje vyjímky při pokusu o načtení dat uuid, který momentálně zpracovává jiný proces. Do *AkubraDOManager* jsem také přidal logovací vypisy aby bylo vidět kde se jednotlivá uuid zamykají.

process-1:
```
...

Mar 06, 2020 10:58:43 AM cz.incad.kramerius.service.impl.PolicyServiceImpl setPolicyForNode
INFO: Set policy pid: uuid:27334810-4535-4103-a0f2-51dadf5f7ba7 policy: private
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getWriteLock
INFO: Writing lock for pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7
Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager releaseWriteLock
INFO: Unlock pid uuid:27334810-4535-4103-a0f2-51dadf5f7ba7

...
```

process-2:
```
...

Mar 06, 2020 10:58:43 AM cz.incad.kramerius.fedora.AbstractFedoraAccess processSubtreeInternal
WARNING: could not read RELS-EXT, skipping branch [1] and pid (uuid:27334810-4535-4103-a0f2-51dadf5f7ba7):java.io.IOException: Datastream not found: uuid:27334810-4535-4103-a0f2-51dadf5f7ba7 - RELS-EXT

...
```
Přikládám logy z daších testování, tam se stejné chyby také objevují.

[06-03-2020-10:58-process-1.txt](https://github.com/ceskaexpedice/kramerius/files/4311444/06-03-2020-10.58-process-1.txt)
[06-03-2020-10:58-process-2.txt](https://github.com/ceskaexpedice/kramerius/files/4311446/06-03-2020-10.58-process-2.txt)

[09-03-2020-13:01-process-1.txt](https://github.com/ceskaexpedice/kramerius/files/4311450/09-03-2020-13.01-process-1.txt)
[09-03-2020-13:01-process-2.txt](https://github.com/ceskaexpedice/kramerius/files/4311453/09-03-2020-13.01-process-2.txt)

[09-03-2020-13:19-process-1.txt](https://github.com/ceskaexpedice/kramerius/files/4311455/09-03-2020-13.19-process-1.txt)
[09-03-2020-13:19-process-2.txt](https://github.com/ceskaexpedice/kramerius/files/4311457/09-03-2020-13.19-process-2.txt)
[09-03-2020-13:19-process-3.txt](https://github.com/ceskaexpedice/kramerius/files/4311458/09-03-2020-13.19-process-3.txt)

**Comment by vlahoda** [comment]
Procesy jsou synchronizovany i mezi sebou navzajem, ale je to jen write lock, cteni zamek nevyzaduje. Vyzkousim nejakou implementaci distribuovaneho ReadWriteLocku (analogicky tomu, co je v java.concurrent), ale trochu se bojim, ze to bude zpomalovat cteni nad unosnou uroven. Myslel jsem, ze se bez read locku obejdeme, ale zda se tedy, ze ne. Vyzkousime, uvidime...

**Comment by vlahoda** [comment]
Implementoval jsem read-write locky, muzete overit, jestli to opravdu pomohlo v tomto konkretnim pripade?

**Comment by kazooo** [comment]
@vlahoda děkuju, ale bohužel procesy stále vyhazují chyby

[process-1.txt](https://github.com/ceskaexpedice/kramerius/files/4317247/process-1.txt)

[process-2.txt](https://github.com/ceskaexpedice/kramerius/files/4317248/process-2.txt)
```
Mar 11, 2020 10:04:40 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getReadLock
INFO: Lock (getReadLock) uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6
Mar 11, 2020 10:04:40 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager readObjectFromStorage
INFO: Unlock (getReadLock) uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6
Mar 11, 2020 10:04:40 AM cz.incad.kramerius.fedora.AbstractFedoraAccess processSubtreeInternal
WARNING: could not read RELS-EXT, skipping branch [1] and pid (uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6):java.io.IOException: Datastream not found: uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6 - RELS-EXT
```

[process-3.txt](https://github.com/ceskaexpedice/kramerius/files/4317249/process-3.txt)
```
Mar 11, 2020 10:05:00 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getReadLock
INFO: Lock (getReadLock) uuid:b916aa0e-08d8-40a6-b05d-bb0fed3a1586
Mar 11, 2020 10:05:00 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager readObjectFromStorage
INFO: Unlock (getReadLock) uuid:b916aa0e-08d8-40a6-b05d-bb0fed3a1586
Mar 11, 2020 10:05:00 AM cz.incad.kramerius.fedora.AbstractFedoraAccess processSubtreeInternal
WARNING: could not read RELS-EXT, skipping branch [1] and pid (uuid:b916aa0e-08d8-40a6-b05d-bb0fed3a1586):java.io.IOException: Datastream not found: uuid:b916aa0e-08d8-40a6-b05d-bb0fed3a1586 - RELS-EXT
```

[process-4.txt](https://github.com/ceskaexpedice/kramerius/files/4317250/process-4.txt)
```
Mar 11, 2020 10:05:10 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager getReadLock
INFO: Lock (getReadLock) uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6
Mar 11, 2020 10:05:10 AM cz.incad.kramerius.fedora.om.impl.AkubraDOManager readObjectFromStorage
INFO: Unlock (getReadLock) uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6
Mar 11, 2020 10:05:10 AM cz.incad.kramerius.fedora.AbstractFedoraAccess processSubtreeInternal
WARNING: could not read RELS-EXT, skipping branch [1] and pid (uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6):java.io.IOException: Datastream not found: uuid:e8248ecb-c322-4fd4-af8d-0f5a6a3200e6 - RELS-EXT
```
[Problém](https://github.com/ceskaexpedice/kramerius/issues/742), když dokončené procesy zůstavaly v OS, je odstraněn, děkuju.

**Comment by vlahoda** [comment]
Aha, diky za overeni. Uz asi chapu, kde porad zustava problem - ty zamky se nastavuji na prilis nizke urovni, takze se nektery FOXML objekt mohl ocitnout v nekonzistentnim stavu, kdy z nej jeden proces odstranil RELS-EXT, ale jeste nezapsal novy obsah - a mezi temi dvema operacemi se uvolnil zamek a druhy proces si v tu chvili mohl nacist FOXM s chybejicim RELS-EXT. 

Zkusil jsem pro ten proces PolicyService (set public/private) nastavit ziskavani write locku na vyssi urovni, po celou dobu modifikace jednoho FOXML (commit 9a19efea). V mych testech se zda, ze to pomohlo. Jestli to pomuze i u vas a nenarazime na nejake dalsi problemy, udelam to stejne i pro vsechny ostatni neatomicke operace. 

Ale stejne to neni uplne stoprocentni reseni - pokud pobezi soucasne nad stejnym titulem dva procesy, jeden set private a druhy set public, stejne nakonec zustanou pomichane nektere objekty jako private a nektere jako public. Musel by se na zacatku procesu ziskat write lock pro cely strom dokumentu a to by u vetsich titulu zablokovalo cely titul na dlouhou dobu, to neni schudne reseni. 

V kazdem pripade moc dekuji za pomoc a rychlou odezvu!

**Comment by kazooo** [comment]
@vlahoda děkuju, funguje to bez chyb. Pozdější procesy jsou trochu zpomalené kvůli čekání na uvolnění uuid, ale zatim neplanujeme spouštět zároveň více různých procesů nad jedním dílem.

**Comment by vlahoda** [comment]
@kazooo Diky za zpravu, snad to tedy bude ok.
