### ISSUE TITLE
Akubra nevrací obsah datastreamu (ve specifických situacích)

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#745]
Ve Akubře mám  objekt s následujícím datastreamem TEXT_OCR:
```
<datastream ID="TEXT_OCR" CONTROL_GROUP="M" STATE="A" VERSIONABLE="false">
<datastreamVersion ID="TEXT_OCR.0" LABEL="" CREATED="2010-12-16T15:59:56.000Z" MIMETYPE="text/plain" SIZE="282">
<binaryContent>
77u/UG8gdsWhZWNoIGNlc3TDoWNoIG5hIG1vZGxpdGJ1IGRiZWptZTsNClYgIGR1Y2h1IFDDoW7EmyBqaSB2xaFhayB2eWtvbmVqbWUhDQpKYWvDqSBrb2xpdiBuYcWhZSB1dHJwZW7DrSwNClYgIG1vZGxpdGLEmyB2xb5keSBuYWpkZW0gdWxldmVuaS4NCk/FoWtsaXbDqSB0bywga2R5xb4gc2Uga2x1Y2kgcGVyb3UsDQpOYSBzZWJlIHNlIGpha28gZHJhY2kgZGVyb3U6DQpIbGUsIGtkecW+IGJlemJvxb5uxJsgc2UgcG90xZnDrXNrYWrDrSwNCk1vZMWZaW55IGEgYm91bGUgemEgdG8gbWFqw60h
</binaryContent>
</datastreamVersion>
</datastream>
```

Při specifickém pořadí operací docílím toho, že AkubraUtils.getStreamContent() vyhazuje vyjímku tvrdící, že datastream(version) neexistuje. 
Ilustruje to následující bash skript:
```
#!/bin/bash

BASE_URL=http://localhost:8080/search

function fetch() {
  PID=$1

  #wget "$BASE_URL/api/v5.0/item/${PID}" -O "${PID}_item.xml"
  wget "$BASE_URL/api/v5.0/item/${PID}/foxml" -O "${PID}_foxml.xml"
  wget "$BASE_URL/api/v5.0/item/${PID}/parents" -O "${PID}_parents.xml"
  wget "$BASE_URL/api/v5.0/item/${PID}/streams/RELS-EXT" -O "${PID}_RELS-EXT.xml"
  wget "$BASE_URL/api/v5.0/item/${PID}/streams/BIBLIO_MODS" -O "${PID}_BIBLIO_MODS.xml"
  wget "$BASE_URL/api/v5.0/item/${PID}/streams/TEXT_OCR" -O "${PID}_TEXT_OCR.xml"
}

#fetch uuid:0eaa6730-9068-11dd-97de-000d606f5dc6
fetch uuid:4a8cf730-af36-11dd-ae88-000d606f5dc6
```

Pro poslední wget dostávám vždy 404. A několik následujících sekund až minut to stejné dostávám při otevření v prohlížeči:
http://localhost:8080/search/api/v5.0/item/uuid:4a8cf730-af36-11dd-ae88-000d606f5dc6/streams/TEXT_OCR
```
{
"message": "java.io.IOException: Unsupported datastream content type: TEXT_OCR.0",
"status": 404
}
```
Po několika reloadech se interní stav změní a konečně dostanu správná data:
```
Po všech cestách na modlitbu dbejme;
V  duchu Páně ji však vykonejme!
Jaké koliv naše utrpení,
V  modlitbě vždy najdem uleveni.
Ošklivé to, když se kluci perou,
Na sebe se jako draci derou:
Hle, když bezbožně se potřískají,
Modřiny a boule za to mají!
```
Pokud ale v ukázkovém bash skriptu zakomentuju 2. wget řádek (/foxml), tak dostávám vždy rovnou data. Takže ta chyba je to deterministická, i když se jeví náhodně.

**Comment by rzeh4n** [comment]
Opravil jsem tuhle konkrétní chybu. Ale ne zdroj problému, může se to zas projevit v jiné specifické situaci. Moc teda nechápu, jakto, že getStreamContent() tady někdy vracel korektní data pro binaryContent. Jakoby se tam děla nějaká manipulace s "DOMem", ve smyslu, že se binaryContent převáděl na contentLocation s INTERNAL_ID, ale ne úplně spolehlivě.

**Comment by vlahoda** [comment]
DIky za upozorneni. Skutecna pricina te chyby je v metode FedoraAccess.getFoxml(), ktera chybne nedela klon toho FOXML objektu, ale resolvuje binarni datastreamy objektu, kyery je drzen v cache AkubraDOManageru. Objekt, ktery je v ulozisti ve skutecnosti nikdy nema mit datastreamy  s obsahem binaryContent - to je jen transportni format pri serializaci do FOXML, v ulozisit je nahrazen prave tim contentLocation s INTERNAL_ID - a skutecny  obsah binarniho streamu je ulozen v samostatnem souboru v datastream storage. 
Opravim to getFoxml, pak ten tvuj fix bude zbytecny, ale klidne tam muze zustat...

**Comment by rzeh4n** [comment]
Ok, díky. Tak tím pádem po opravě prosím můj fix zase odstraň a spíš tam nech trochu jinou chybovou hlášku a v komentáři odkaz na tohle issue. Aby to nemátlo, že to takto fungovat má.

**Comment by vlahoda** [comment]
Nechal jsem tam i ten tvuj fix a pridal k nemu do logovani warning, ze by to sem nemelo zabloudit.
