### ISSUE TITLE
Při ingestu foxml se nastaví CREATED datastreamu ve špatném formátu (Akubra)

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#746]
Po ingestu foxml do Fedory při nepřítomnosti časových známek, budou ty vygenerovány ve stejném formátu, jak pro objekt, tak pro verze datastremů. Např.:
 ```
<foxml:property NAME="info:fedora/fedora-system:def/model#createdDate" 
     VALUE="2020-03-17T12:10:24.038Z"
/>
<foxml:property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" 
     VALUE="2020-03-17T12:10:24.038Z"
/>

<foxml:datastreamVersion ID="BIBLIO_MODS.0" LABEL="MODS Record" 
     CREATED="2020-03-17T12:10:24.038Z" 
MIMETYPE="text/xml" FORMAT_URI="http://www.loc.gov/mods/v3" SIZE="487">
 ```
Pro repozitáři postaveném v Krameriovi nad Akubrou jsou vyrobené časové známky v různých formátech:
 ```
<property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" 
     VALUE="2020-03-30T22:47:32.109Z"
/>
        <property NAME="info:fedora/fedora-system:def/model#createdDate" 
     VALUE="2020-03-30T22:47:32.109Z"
/>
<datastreamVersion ID="BIBLIO_MODS.0" LABEL="BIBLIO_MODS description of current object" 
     CREATED="2020-03-30T22:47:32" 
MIMETYPE="application/xml" FORMAT_URI="http://www.loc.gov/mods/v3">
 ```
Mělo by to být jednotně a ve formátu **2020-03-30T22:47:32.109Z**, ne **2020-03-30T22:47:32**, protože tak budou vypadat existující data z různých instalací Fedory.

**Comment by rzeh4n** [comment]
Bude souviset s opravou #704 .

**Comment by vlahoda** [comment]
@rzeh4n Opravil jsem to formatovani pro chybejici CREATED atribut nebo pro nove pridavany datastream. Myslim, ze i ten problem v #704 je ted OK - last modifiedDated i CREATED pro RELS-EXT se pri mergovani dvou objektu taky nastavuje spravne. Jedine, co asi zustava spatne, jsou datastreamy, ktere maji uz CREATED u datastreamu nastavene v chybnem formatu. Jestli dobre rozumim kodu fedory, prepisuje je vsechny natvrdo do formatu UTC pri kazdem zapisovani obejktu do repository. Ja tady nechava formatovani na JAXB, takze se nezmeni. Nevim ale, jestli je to potreba resit, narazil jsi na nejaky realny problem, ktery to zpusobuje?

**Comment by rzeh4n** [comment]
@vlahoda Já jsem to částečně vyřešil vypnutím toho doplnění CREATED v AkubraDOManager.ensureDsVersionCreatedDate(). Dívám se ale teď, že ve špatné branchi. 
Tak si zase mergnu mater do branche indexer a  sloučím oba fixy - buď zase povolím volání ensureDsVersionCreatedDate(), pokud tvoje řešení funguje, nebo to nechám vypnuté. 
U těch foxml properties createdDate a lastModifiedDate to funguje správně a máš pravdu, že to CREATED vlastně nepoužíváme, na rozdíl od createdDate/lastModifiedDate. 
K tomu, jak jsem na to narazil a proč to řeším se ti rozepíšu dnes večer/zítra, ale hlavně šlo o to, aby se do repozitory nedostávala data v neočekávané podobě, což by u Fedory nemělo nastat, teď si to musíme víc hlídat.

**Comment by rzeh4n** [comment]
@vlahoda Tvoje oprava funguje.
vstup (do Akubry přes Kramerius Import FOXML proces):
```
 <foxml:datastream ID="TEST-A" STATE="A" CONTROL_GROUP="X" VERSIONABLE="true">
        <foxml:datastreamVersion ID="TEST-A.0" MIMETYPE="application/xml" CREATED="2020-03-30T22:47:32">
            <foxml:xmlContent>
                <testa>blabla</testa>
            </foxml:xmlContent>
        </foxml:datastreamVersion>
    </foxml:datastream>

    <foxml:datastream ID="TEST-B" STATE="A" CONTROL_GROUP="X" VERSIONABLE="true">
        <foxml:datastreamVersion ID="TEST-B.0" MIMETYPE="application/xml" CREATED="2020-03-17T12:10:24.038Z">
            <foxml:xmlContent>
                <testb>blabla</testb>
            </foxml:xmlContent>
        </foxml:datastreamVersion>
    </foxml:datastream>

    <foxml:datastream ID="TEST-C" STATE="A" CONTROL_GROUP="X" VERSIONABLE="true">
        <foxml:datastreamVersion ID="TEST-C.0" MIMETYPE="application/xml">
            <foxml:xmlContent>
                <testc>blabla</testc>
            </foxml:xmlContent>
        </foxml:datastreamVersion>
    </foxml:datastream>
```
Výstup (z AkubraRepository.getObject(pid).getFoxml():
```
 <datastream ID="TEST-A" CONTROL_GROUP="X" STATE="A" VERSIONABLE="true">
        <datastreamVersion ID="TEST-A.0" CREATED="2020-03-30T22:47:32" MIMETYPE="application/xml">
            <xmlContent>
                <testa xmlns="">blabla</testa>
            </xmlContent>
        </datastreamVersion>
    </datastream>
    <datastream ID="TEST-B" CONTROL_GROUP="X" STATE="A" VERSIONABLE="true">
        <datastreamVersion ID="TEST-B.0" CREATED="2020-03-17T12:10:24.038Z" MIMETYPE="application/xml">
            <xmlContent>
                <testb xmlns="">blabla</testb>
            </xmlContent>
        </datastreamVersion>
    </datastream>
    <datastream ID="TEST-C" CONTROL_GROUP="X" STATE="A" VERSIONABLE="true">
        <datastreamVersion ID="TEST-C.0" CREATED="2020-04-02T09:26:44.639Z" MIMETYPE="application/xml">
            <xmlContent>
                <testc xmlns="">blabla</testc>
            </xmlContent>
        </datastreamVersion>
    </datastream>
```
Tj. doplnění časové známky, pokud není, funguje (TEST-C). Ale pokud je to ve špatném formátu už na vstupu (TEST-A), do úložiště se to dostane.

Upřímě mě to trochu překvapilo, že tvůj fix funguje. Jakože si XMLGregorianCalendar interně drží Stringovou reprezentaci, namísto parsování, a tu pak použije v toString(). 
Já jsem na to chtěl jít přes XmlAdapter a změnu marshalování toho CREATED, jenže to nešlo přes @XmlJavaTypeAdapter v třídě DatastreamVersionType, která ja generovaná (z XSD?). Navíc tak hrozilo, že bych někde jinde něco rozbil.
