### ISSUE TITLE
Dotaz k migraci Akubra

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#748]
Dobrý deň, 

toto je hlavne na p. Lahodu @vlahoda na uvedený popis : https://github.com/ceskaexpedice/kramerius/wiki/Kramerius-7-Akubra-instalace-a-konfigurace#konverze-akubra---akubra 

Dľa dokumentácie je nutné použiť Konvertor formátu úložišťa aj v prípade ak už používate Akubra úložište? Alebo je konvertor nutné použiť len v prípade ak chcete zmeniť štruktúru uložišťa?

**Comment by vlahoda** [comment]
@JanMeritus Pokud nechcete menit adresarovou strukturu uloziste, konverze neni potreba, staci spravne nastavit cesty k ulozistim a  strukturalni patterny, jak je popsano v uvodu te zminovane dokumentace.
