### ISSUE TITLE
Dotaz k migraci Akubra II

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#749]
@vlahoda @hlavacekrene @fstepanovsky @rzeh4n  Potrebujeme zmeniť štruktúru akubra na aktuálnej verzii kraméria core (5.4.2), aktuálnu verziu kraméria core chceme však ponechať. Aktuálne používame default štruktúru, 256 složiek pattern ##, chceme to zmeniť na pattern ##/## prípadne iný. Je na to možné použiť Konvertor formátu úložište https://github.com/ceskaexpedice/kramerius/wiki/Kramerius-7-Akubra-instalace-a-konfigurace#konvertor-form%C3%A1tu-%C3%BAlo%C5%BEi%C5%A1t%C4%9B ? Prípadne viete doporučiť iný postup?

**Comment by JanMeritus** [comment]
navazuje na #748

**Comment by vlahoda** [comment]
@JanMeritus Melo by to fungovat, ale nezkousel jsem to. Fedora ma krome souboroveho uloziste jeste nejake informace o cestach k souborum v databazi. Pro legacy-fs tam je ulozena opravdu fyzicka cesta k souboru, pro Akubru ale obsahuje jen nazev souboru, ktery se zmenou struktury nemeni. V kazdem pripade ale doporucuji, abyste postup nejdriv vyzkouseli na nejake male testovaci instalaci.
