### ISSUE TITLE
Nestabilita appky: Too many open files iipforward.stg

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#750]
Tomcat pada na too many open files z aplikacie, limit sa pre to navysoval, pricom jeden file je otvoreny 2287 krat z nejakeho dovodu. Pre stabilitu aplikacie s vacsim poctom uzivatelov by to bolo vhodne poriesit

java    8487 kramerius 1007r      REG              253,2       1141  50342609 /home/kramerius/apache-tomcat-xoxo/webapps/search/WEB-INF/classes/cz/incad/Kramerius/imaging/iipforward.stg

**Comment by vlahoda** [comment]
u jake verze krameria?

**Comment by JanMeritus** [comment]
@vlahoda 5.4.5-dnnt, revision: 5f10..

**Comment by JanMeritus** [comment]
@vlahoda mate k tomu nieco? pre vacsi pocet uzivatelov ktory zazivame to prinasa vyznamny problem so stabilitou

**Comment by pavel-stastny** [comment]
comitnem rychlou zmenu, kdy se soubor nacte jenom jednou.  Nicmene  je divne, ze to driv problemy neprinaselo.  (Stejny kod se vyuzival i drive a vyuziva se i v jinych knihovnach)

**Comment by zabak** [comment]
@pavel-stastny myslím, že zatím nedošlo u žádného Krameria k takovémuto zatížení.

**Comment by JanMeritus** [comment]
@pavel-stastny diki moc, ono myslim ze treba pocitat ze Kramerius bude obecne vic navstevovan a idealne poladit podobne procesy, ak este nieco niekde take je.
