### ISSUE TITLE
DNNT: Pravidlo 10 let

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#751]
Poprosim este pridat nastavitelne pravidlo typu moving wall 10 let pro vsechny periodika. 

Scenar - periodikum sa oznaci ako DNNT standardnym procesom.

Vyuzitie:
Vsetky ich casti starsie tnow-10 let by mali byt automaticky oznacenne ako DNNT. Vsetky novsie casti ostanu neverejne.

**Comment by JanMeritus** [comment]
edit: moving wall by sa mal vztahovat i na spodnu hranicu - tj ked dielo prechadza z DNNT do verejneho

tuto veci by si mal v buducnu osetrit aj SDNT v ramci zavedenia granularity na rocniky a prip niz (viz. vylucovanie stati ze serialu), zatial je to ale najelegantnejsie a implementacne najrychlejsie riesenie celeho problemu

**Comment by pavel-stastny** [comment]
U tohoto issue vidim problem s implementaci.  Mohli bychom se o tom pobavit po mailu / telefonu ?

**Comment by JanMeritus** [comment]
souvis s #781 

u periodik (skutecnych, ne vicesvazku) typu DNNT to vyzera, ze bylo potvrzena licence dostupnosti Y-10let.

**Comment by JanMeritus** [comment]
@pavel-stastny  @vlahoda prosim a dekuji vopred za urychlenou reakci. Tyka se to periodik ktere by meli byt v pristupu po 1.2.2021, su vedeny v seznamu DNNT jako root UUID ale jejich vydavani pokracovalo i po roku 2010, do kdy by meli byt pristupny.

**Comment by pavel-stastny** [comment]
@JanMeritus Na přidělování dnnt by šla použít ta samá logika, která se teď používá u MovingWall. Můžeš se, prosím Tě, podívat sem (https://github.com/ceskaexpedice/kramerius/wiki/Prava#pozn%C3%A1mky-k-implementaci)  a případně napsat zda to rozhodovací pravidlo zdá být úplné s ohledem na DNNT?  Pokud ano, připravíme samostatný proces.

**Comment by zabak** [comment]
@pavel-stastny  Nebylo by lepší mít to jako proces, který jednou za rok spustím a nastaví ta práva u příslušných objektů natvrdo?

**Comment by pavel-stastny** [comment]
Pro synchronizaci se SDNNT máme v K5 i K7 samostatný proces.  Implementace mw není potřeba.
