### ISSUE TITLE
Přepis metadat při importu

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#757]
Vypadá to, že s novou verzí (5.5.0) zmizela možnost importu s přepisem metadat. Proč už tam s touto verzí tahle funkce není? Docela dost by se nám hodila. Díky!

https://github.com/ceskaexpedice/kramerius/issues/598

**Comment by pavel-stastny** [comment]
Vypadlo při řešení podpory novějšího tomcatu #470

**Comment by pavel-stastny** [comment]
Jenom aby nedošlo k mýlce. Ten komit spojený s issue přepis metadat opravoval. V příštím buildu bude možnost opět přístupná.

**Comment by tumovam** [comment]
Dobrý den, počítá se s touto funkcí i v dalším oficiálním buildu? Děkuji, MT
