### ISSUE TITLE
DNNT: logování uživatele

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#759]
Dobrý den,

v [ShibbolethUtils](https://github.com/ceskaexpedice/kramerius/blob/master/security/authfilters/src/main/java/cz/incad/kramerius/auth/thirdparty/shibb/utils/ShibbolethUtils.java) ve funkci **isUnderShibbolethSession** probíhá [case sensitive porovnání](https://github.com/ceskaexpedice/kramerius/blob/master/security/authfilters/src/main/java/cz/incad/kramerius/auth/thirdparty/shibb/utils/ShibbolethUtils.java#L45) při vyhledávání Shib-Identity-Provider hlavičky. Zjistili jsme, že ve skutečnosti ty hlavičky jsou lowercase, proto při zminěném porovnání s *"Shib-Identity-Provider"*  **isUnderShibbolethSession** vždy vrací false.

![dnnt](https://user-images.githubusercontent.com/22412267/85383440-3a5e1480-b540-11ea-8933-c33f326e050d.png)

 Kvůli tomu [ShibbolethAuthFilter](https://github.com/ceskaexpedice/kramerius/blob/master/security/authfilters/src/main/java/cz/incad/kramerius/auth/thirdparty/shibb/ShibbolethAuthFilter.java#L13-L22) pak [neuloži Shibb. usera](https://github.com/ceskaexpedice/kramerius/blob/master/security/authfilters/src/main/java/cz/incad/kramerius/auth/thirdparty/ExtAuthFilter.java#L54) do sessiony a ten následně [nebude logovan](https://github.com/ceskaexpedice/kramerius/blob/dnnt/common/src/main/java/cz/incad/kramerius/security/impl/http/AbstractLoggedUserProvider.java#L89-L96).
```
1592559396302 I access {"date":"2020-06-19T11:36:36.276",
"rootTitle":"Šachy","rootModel":"monograph","dcTitle":"[1a]",
"pid":"uuid:71a80bc3-9361-4d5e-8207-179aba225342",
"pids_path":["/uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23/uuid:71a80bc3-9361-4d5e-8207-179aba225342"],
"rootPid":"uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23",
"models_path":["/monograph/page"],"remoteAddr":"*.*.*.*","username":"not_logged"}
```

K tomu ještě Shibb. hlavičky obsahují prazdné hodnoty položek jako **eduPersonUniqueId**, a chtěl bych požadat o konzultaci jak by to šlo opravit a v jakém směru hledat. A poprosím **eduPersonUniqueId** zařadit také do logování.

Děkuju

**Comment by pavel-stastny** [comment]
Dobry den, 

ohledne hlavicek a case sensitive. To je jednoducha zmena, to muzeme vyresit. Ohledne prazdne hlavicky **eduPersonUniqueId** . Abych se priznal, ted tomu moc nerozumim... muzeme mozna pokracovat mailem ? 

Diky a zdravim

**Comment by pavel-stastny** [comment]
Dobry den, 

zatim jsem komitnul tu zmenu porovnani z case sensitive na insensitive.

**Comment by pavel-stastny** [comment]
Zdravím,  nejak se mi nepodařilo svázat komit.  Dodávám ručně 82a48a632ed5e60ae4b575e7eca30c0604b593db

**Comment by pavel-stastny** [comment]
Nyní je možno přes opearci `user("xxxx"` definovat jakoukoliv hodnotu z hlavičky. `Firstname` a `surname` jsou parametry, které se ukládají i do databáze, ostatní "žijí" pouze v http session. (Pokud uživatel spustí proces, tak proces už hodnoty z hlaviček mít nebude.)
