### ISSUE TITLE
Import FOXML s články - co je špatně?

### ISSUE THREAD

**Issue by krizovj** [ceskaexpedice/kramerius#760]
Mám problém s importem FOXML čísla periodika, které je zpracované na úroveň článků. 

Když naimportuji NDK balíček, tak jádro i klient zobrazí stránky i články správně, ale je tam problém s čísly stran, viz. toto issue: https://github.com/ceskaexpedice/kramerius/issues/727

Když tedy naimportuji FOXML, tak v jádru je to teoreticky zobrazeno správně (ale jinak než když importuji NDK balíček), nejdřív jsou stránky a pod tím články. Ale když rozkliknu jednotlivé články, tak pod nimi žádné stránky nejsou, což v případě NDK balíčku byly.
![krameriusndkclanky](https://user-images.githubusercontent.com/21309201/87912075-fe4d9f00-ca6c-11ea-8341-66cc92fcdbbf.jpg)

Když překliknu z jednoho článku na jiný, tak je pořád zobrazena první stránka čísla a Kramerius na to nijak nereaguje. 
V klientovi to je to samé, vidím články a na druhé záložce články, ale nereaguje na překlikávání mezi články. 

Oba importy, jak NDK, tak FOXML můžu poslat. Oba vyrobil ProArc a potřebovala bych vědět, jestli je něco špatně v ProArcu nebo je potřeba upravit Kramerius. Kam je mám případně poslat? 
Děkuji!

**Comment by pavel-stastny** [comment]
Mozna pres uschovnu s emailem na me (@pavel-stastny) a Vladu (@vlahoda)

**Comment by krizovj** [comment]
Odesláno

**Comment by vlahoda** [comment]
V FOXML vygenerovanych Proarcem chybi v RELS-EXT clanku vazby na stranky ( kramerius:isOnPage). Konzultoval jsem to s Lukasem Sykorou a tento problem by uz v novejsich verzich Proarcu mel byt opraven.
Poskytnuty NDK balicek se naimportoval spravne vcetne cisel stran, issue 727 se ho netyka, protoze neobsahuje MODS pro stranky a convertor NDKMETS->FOXML generuje FOXML stranek, ktere kramerius indexuje spravne.

**Comment by krizovj** [comment]
@vlahoda pardon, moje chyba, šlo o export ze staré verze ProArcu. Poslala jsem přes FileSender foxml z ProArcu 3.6.  Do Krameria (máme verzi 5.5.0) se naimportuje v pohodě, jen tam nejsou ta čísla stran. Co je tam tedy přesně špatně? Děkuji.

**Comment by vlahoda** [comment]
V tomto novem exportu jsou zdvojene elementy <part> v MODS, takze si s tim neporadi indexer Krameria, issue #727

**Comment by krizovj** [comment]
a nevadí tomu taky atribut "page number" (místo "pageNumber")?

**Comment by vlahoda** [comment]
To uz je v kodu Krameria doplnene od 29.3., takze dalsi release uz to bude umet. Pripadne staci jednoducha uprava indexacni sablony, kterou muze udelat administrator bez nutnosti noveho buildu.
