### ISSUE TITLE
Problém s indexací virtuálních sbírek

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#761]
- Dielo sa do zbírky pridá ale následne batch process spadne na reindexácii
- Pri spustení reindexacie sa na začiatku nastaví status na FAILED (log [cz.incad.kramerius.processes.GCCheckFoundCandidatesTask run] WARNING: changing state of process '7646ad7b-50f2-44c0-ba0e-732d19ce934b' to FAILED) ale ak to úspečne dobehne, tak sa status zmení
- Pri spustení reindexácie nad dielom, ktoré je pridané pod zbirku ale nezobraruje sa v nej, sa dielo do zbírky priradi. Reindexacia diela vyrieši tento problém nezobrazovania v zbírke
- Pri spusteni reindexacie nad zbirkou sa diela z nej odstrania a je nutne spustit reindexaciu nad jednostlivymi dielami

**Comment by vlahoda** [comment]
K prvnim dvema bodum: problem nedokazu reprodukovat, na testovaci instalaci Krameria proces zarazeni do sbirky vcetne nasledne reindexace funguje spravne. Z uvedenych informaci nedokazu posoudit, proc ke spusteni indexacniho procesu ve vasem pripade nedojde.

K druhym dvema bodum: to je ocekavane chovani, pri zarazeni objektu do sbirky se zapisuje reference na sbirku do stream RELS-EXT v objektu, takze reindexovat je treba objekt a ne sbirku. Toto se zmeni v chystanych hierarachickych sbirkach ve verzi Kramerius 7.
