### ISSUE TITLE
modely pro určení typu dokumentu

### ISSUE THREAD

**Issue by PavlinaKocisova** [ceskaexpedice/kramerius#763]
Dobrý den,
v současné době kvůli vývoji nových standardů řešíme, jakým způsobem v v Krameriu fungují modely v DC a podle čeho rozlišuje typy dokumentu. Z pozorování se nám podařilo určit, že ve starší verzi Kramerius modely využívá pouze k distinkci mezi textovým dokumentem/ hudebninou/ kartografickým dokumentem, zatímco v současné k tomu samému využívá hodnotu v mods:typeOfResource (?). Mezi typy dokumentu tak Kramerius podle všeho v současné době rozhoduje hlavně podle toho, co je za hodnotu v mets:mets TYPE? (tj., zda je příslušný hlavní mets pro periodikum, e-monografii či zvukový dokument) Mají na to vliv ještě další elementy a jejich hodnoty? A na kterých úrovních popisu?

Děkuji za osvětlení a přeji hezký den!

**Comment by vlahoda** [comment]
Typy objektu jsou urceny vyhradne atributem TYPE v elementu mets:div v mets:structMap. Obsah DC je irelevantni.
