### ISSUE TITLE
Akubra - import věcí s PDF

### ISSUE THREAD

**Issue by rzeh4n** [ceskaexpedice/kramerius#764]
Když se pokusím nahrát (přes "Import FOXML" v core adminovi) monografii, která má přímo IMG_FULL jako managed stream s odkazem na lokální pdf soubor, tak se nevytvoří IMG_FULL, dokonce ani IMG_THUMB a IMG_PREVIEW, které mají odkazy na obrázek někde venku.
Tady jsou vstupní data:
[m3_katalog_vystavy_1_pdf.zip](https://github.com/ceskaexpedice/kramerius/files/5233401/m3_katalog_vystavy_1_pdf.zip)
Výstup z http://localhost:8080/search/api/v5.0/item/uuid:6c270600-d243-11ea-9c41-005056827e52/foxml s chybějícími datastreamy:
[api_v5.0_item_uuid-6c270600-d243-11ea-9c41-005056827e52_foxml.xml.zip](https://github.com/ceskaexpedice/kramerius/files/5233436/api_v5.0_item_uuid-6c270600-d243-11ea-9c41-005056827e52_foxml.xml.zip)

**Comment by vlahoda** [comment]
Problem je zpusobeny tim, ze FOXML unmarshaller (tedy trida vygenerovana frameworkem JAXB podle schematu FOXML1-1.xsd) na radku 261 ve tride org.kramerius.Import precte ten tvuj foxml soubor, nevyhodi zadnou vyjimku, ale ten naparsovany DigitalObject uz neobsahuje zadny z tech IMG_* datastreamu. Zatim jsem neprisle na to, proc - zrejme nejak neodpovidaji schematu foxml, ale proc to tedy nevyhodi nejakou vyjimku, nechapu. Budu patrat dal :-(

**Comment by vlahoda** [comment]
Tak uz vidim pricinu - ty 3 chybejici datastreamy nemely v xml uvedeny u zadneho elementu namespace foxml: , takze je ten parser proste ignoroval. Po doplneni namespace se uz objekt naimportoval spravne. Zbyva tedy jeste doresit, jak se ma zpracovat contentLocation s referenci do lokalniho filesystemu. Ted se proste zkopiruje tak, jak je uveden, tedy <contentLocation TYPE="URL" REF="file://./SURSUM.pdf"/>, ale ta relativni adresa se nebude spravne vyhodnocovat.

**Comment by rzeh4n** [comment]
Aha, to jsem přehlédl, jak jsem to vyráběl z různých příkladů, evidentně v některých byl namespace pro foxml defaultní a definovaný na úrovni foxml object. Opravím, otestuju a potvrdím, že vše funguje.

**Comment by rzeh4n** [comment]
K tomu managed datastreamu s odkazem na lokální soubor, stejně to tuším funguje na webové url.
Vidím tu 3 varianty:

1. dodržet tady kontrakt Fedory a FOXML a pokud je to na vstupu Managed, tak to sklidit a uchovat interně
2. nepodporovat Managed + contentLocation a vyhodit chybu, povolit jen binaryContent a data v base64 přímo ve foxml
3. tvářit se, že se oproti Fedoře nic nezměnilo, ale interně se to chová jinak a Managed + contentLocation funguje jako Externally refernced + contentLocation

Teď je to 3, což je podle mě nejhorší řešení a projevuje se to právě takhle, že někdo jako já teď importuje datastraemy s contentLocation na dočasném umístění na souborovém systému, případně url, odkud se to ale následně smaže.
Příjde mi nejlepší jít cestou 2 a pokud se někdo ozve, že vyžadují dodržení kontraktu Fedory i v tomhle, tak to předělat na řešení 1.

**Comment by rzeh4n** [comment]
Tak po opravě funguje podle očekávání. Teda až na to Managed datastream s contentLocation, kde se to fakt chová, jako by to bylo Externally referenced namísto Managed.
Tady je jsou opravená vstupní data a vrácené foxml od rezpozitáře + jiný příklad, kde je vše v binaryContent:
[monographs_in_pdf_examples.zip](https://github.com/ceskaexpedice/kramerius/files/5238080/monographs_in_pdf_examples.zip)
