### ISSUE TITLE
Kramerius 5 - nekonzistentní výsledky z API /v5.0/user

### ISSUE THREAD

**Issue by dzatloukal** [ceskaexpedice/kramerius#768]
Dobrý den, máme problém s voláním kramerius API /v5.0/user.

Po přihlášení do DNNT přes Shibboleth dochází k nekonzistentům výsledkům při volání Kramerius API pro získání informací o uživateli - search/api/v5.0/user

Ihned po úúspěšné autentikaci dojde k dotazu na API search/api/v5.0/user s nastaveným JSESSIONID, API však vrací "Not Logged" objekt viz níže.:

```
{lname: "not_logged", firstname: "not_logged", surname: "not_logged", session: {},…}
firstname: "not_logged"
id: -1
lname: "not_logged"
roles: [{name: "common_users", id: 1}]
session: {}
surname: "not_logged"
```

O chvilku později však stejný dotaz se stejnými parametry (stejné JSESSIONID, stejné _shibsession) vrací korektní informace o uživateli.

Důsledkem tohoto se po přihlášení na stránce informace o uživateli nezobrazují a je nutný udělat refresh stránky, po kterém se request na API pošle znovu, aby se informace korektně zobrazily

Jedná se o DNNT konkrétně lištu s vypsaným uživatelem.

Stav po přihlášení a korektní autentikaci:

<img width="512" alt="dnnt-problem" src="https://user-images.githubusercontent.com/36470282/95304113-6c437e80-0884-11eb-913f-9000c44e84f1.PNG">
<img width="591" alt="dnnt-cookies-fail" src="https://user-images.githubusercontent.com/36470282/95304132-72d1f600-0884-11eb-9be0-10a31b5f7c6a.PNG">

Stav po refreshi stránky:

<img width="314" alt="dnnt-ok" src="https://user-images.githubusercontent.com/36470282/95304413-e07e2200-0884-11eb-8340-a6d94c000edf.PNG">
<img width="614" alt="dnnt-cookies-success" src="https://user-images.githubusercontent.com/36470282/95304430-e542d600-0884-11eb-8ec8-70f6fc6a35d8.PNG">

Mohl bych poprosit o prověření, případně o informaci, jak se informace ohledně uživatele z API /uuser dostávájí a proč ihned po autentikaci vrací "not logged" objekt?

**Comment by pavel-stastny** [comment]
Šlo by vysledovat, zda letí na Krameria všechny hlavičky ze SP během těch dvou dotazů ?

**Comment by dzatloukal** [comment]
Nevím přesně co znamená všechny hlavičky, ale porovnal jsem oba dotazy na síťové vrstvě a posílají se úplně stejné hodnoty, nic nepřebývá ani nic nechybí.

**Comment by jahhoo** [comment]
@pavel-stastny Prosím o reakci. V NK je to pro provozování DNNT důležité.

**Comment by pavel-stastny** [comment]
@jahhoo Nedaří se mi to u sebe reprodukovat.  Šlo by zapnout logování na úrovni tomcatu hlaviček dotazu ?  To by mi pomohlo. (Jaké hlavičky posílá service provider do tomcatu)

**Comment by dzatloukal** [comment]
@pavel-stastny na úrovni tomcatu jsem se snažil zapnout logování requestů a response dle https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#Request_Dumper_Filter ale vypadá to, že se  neloguje do souboru vše, protože tam vidím requesty pouze na zoomify ale už ne requesty např. na kramerius api. Můžete mi poradit, kde lze logování všech dotazů zapnout?

**Comment by pavel-stastny** [comment]
@dzatloukal Opss.. S request dumperem neporadím ale ono by stačilo zapnout pouze ty hlavičky, které jsou v hlídané v `shibrules.txt` a ty pak dopropagovat do access logu.  A na to by mělo stačit obohatit pattern pro logování v AccessValve.  Něco na způsob `affilation:%{affilation}i eppn:%{eppn}i eduPersonUniqueId:%{eduPersonUniqueId}i cn:%{cn}i sn:%{sn}i` (Pro hlavičky: affilation, eppn, eduPersonUniqueID, cn a sn)

**Comment by dzatloukal** [comment]
@pavel-stastny díky za tip, přidal jsem tyto hodnoty do AccessValve, do logu se vypisují. Porovnal jsem, co se posílá po přihlášení a po refreshi a v obou případech se posílá vyplněné jen eppn. Affilation, eduPersonUniqueId, cn a sn jsou prázdné.

**Comment by pavel-stastny** [comment]
@dzatloukal Ok.  Zkusim to u sebe nejak nasimulovat.

**Comment by dzatloukal** [comment]
@pavel-stastny povedlo se něco zjistit? Co všechno musí letět z IdP do Shibbolethu, aby se tyto údaje o uživateli v krameriovi zobrazily?

**Comment by pavel-stastny** [comment]
@dzatloukal  Bohužel nepodařilo.   Ad atributy z Idp. Záleží na tom, co je definováno shibrules.txt. Ten mapuje shib uživatele na role v krameriovi na základě attributů z Idp.

**Comment by pavelkocourek** [comment]
Viz #774 : Nelze reprodukovat. Lze zavřít ?
Případně je potřeba, abyste obecně popsali čeho chcete dosáhnout

**Comment by JanMeritus** [comment]
@jahhoo poprosim o odpoved

**Comment by dzatloukal** [comment]
Je možno uzavřít. Problém byl nakonec vyřešen přidání rewrite rule do httpd configu tak, aby se api /v5.0/user provolalo znovu a dostali jsme potřebný výsledek.

**Comment by zabak** [comment]
@dzatloukal @JanMeritus jaký je vlastně use-case? Kdy se to api takto využívá?

**Comment by pavel-stastny** [comment]
@zabak Já jsem to pochopil tak, že se jim shibboleth uživatel po přihlášení nejevil jako přihlášený.  (v klientovi). Jevil se přihlášený až po reloadu.   Nicméně já nedokážu toto chování u sebe reprodukovat.   V MZK jste takový problém pozorovali ?
