### ISSUE TITLE
Nezobrazení role v Editoru rolí ve verzi 5.3.6 i 5.5.0

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#771]
Dobry den,
zjistili jsme, ze po prihlaseni do Krameria 5.5.0 i 5.3.6 se v Editoru roli nezobrazuje jedna z roli. Pritom je ale prirazena k danemu uzivateli v Editoru uzivatelu a take je prirazena dokumentum v Zobrazeni prav.

Ani v jedné verzi se mi nedaří vytvořit novou roli. Existuje maximum možných rolí? Několik měsiců zpět jsem vytvarel novou roli ve verzi 5.3.6

Dekuji

A. Drahotussky

**Comment by Drahotussky** [comment]
Dobry den,
prosim o reakci/radu, jak máme postupovat?

Děkuji

**Comment by Drahotussky** [comment]
Je tento problém v řešení nebo se se to plánuje?
Děkuji

**Comment by pavel-stastny** [comment]
@Drahotussky Editor rolí již není součástí distribuce. V rámci K7 se přešlo na keycloak. Dopručuji upgrade na K7.
