### ISSUE TITLE
Podivné chování DNNT periodika (Melodie)

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#772]
U periodika Melodie se jako DNNT zobrazuje jen část ročníků. Některé ročníky, které mají na úrovni ročníku šedý zámeček mají pak jednotlivá čísla s oranžovým zámečkem (např ročníky 1977-84). Pak další zvláštnost je např. u ročníku 1985, který má jako DNNT nastavena všechna čísla s výjimkou obsahu ročníku. Ročník 1986 pak nemá čísla v režimu DNNT vůbec a další pak zase ano. 

https://ndk.cz/uuid/uuid:eeb9b200-25cd-11e7-b650-5ef3fc9ae867

**Comment by pavel-stastny** [comment]
Divam se na kam smeruji dotazy z klienta na API.  Jste si jisti, ze na strane API bezi verze krameria s podporou DNNT?  Mne to prijde jako verze 5.4.2.

**Comment by jahhoo** [comment]
@pavel-stastny pro zobrazení DNNT verze je potřeba se přihlásit, jinak se zobrazuje klasická verze Krameria.

Přikládám snímky obrazovky, kde je vidět, že ročník není označený jako DNNT, ale jednotlivá čísla DNNT jsou.

![Snímek z 2020-10-23 09-45-59](https://user-images.githubusercontent.com/33415849/96971007-c98e2f80-1514-11eb-90fb-a3c2d952223e.png)
![Snímek z 2020-10-23 09-46-15](https://user-images.githubusercontent.com/33415849/96971003-c7c46c00-1514-11eb-9470-1b13b515a9fd.png)

**Comment by pavel-stastny** [comment]
@jahhoo A jakym zpusobem je to udelane? Protoze kdyz se podivam do indexu (i jako neprihlaseny) tak u oranzovych zamecku vidim priznak dnnt u tmavych ne.  API mi nic nepodava ale to je dano tou verzi 5.4.2.

**Comment by pavel-stastny** [comment]
@jahhoo Ještě doplňující otázka: Pokud obě instance ukazují na stejný solr, nemohlo dojít k reindexaci titulu z ne DNNT instance?  To by pak odpovídalo tomu, proč některé tituly namají oranžové zámečky.

**Comment by jahhoo** [comment]
@pavel-stastny pokud nejsem přihlášen, tak se využivá jádro a klient kramerius5.nkp.cz 
Pokud se přihlásím, dostanu se na server, kde běží jádro i klient pro DNNT - na tomto serveru zároveň probíhá i indexace DNNT děl - takže rozdílné SOLR v tomto případě nepřipadá v úvahu..

**Comment by pavel-stastny** [comment]
@jahhoo Nicméně jsem data jsou v nekonzistentním stavu.  Jediné co může teď doporučit je data znovu reindexovat.

**Comment by pavelkocourek** [comment]
Viz #774 : Nelze reprodukovat. Zabrala reindexace? Lze zavřít ?

**Comment by jahhoo** [comment]
Zreindexoval jsem jednotlivé ročníky a pak celé dílo. Vypadá to již v pořádku. Díky za pomoc.
