### ISSUE TITLE
DNNT a II vlna Krize: Doplneni logu statistics

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#774]
Dobry den, pokud je mozno poprosim o pokud mozno rychle doplneni funkcionality logu statistics v zmyslu:

- doplnit do statistik generovanych z Krameria pro DNNT -  rok vydani dila, autor, vydavatel 
- moznost  (pro krizove stavy) zapnuti generovani statistik (rovnakeho data typu jako pro DNNT statistics), tentoraz pro dila neverejne, ktera ale nejsou DNNT do samostatnyho souboru (NDNNT) a jejich logovani. 
EDIT
- priznak verejnosti dila, rsp licenci pristupu {public, dnnt, private}
- identifikátory (eppn a eduPersonUniqueID)

Oprava nad logikou logovani, po spusteni plneho pristupu se prestalo logovat dnnt statistics, ale stale byly zaply. Poprosim o napravu, aby logovani pristupu k dilam bylo zaply bez ohledu na jejich skutecnou dostupnost.

**Comment by pavel-stastny** [comment]
@JanMeritus Dobra, pokusime se.  A jedna otazka. Co  s temi predchozimi issues ohledne DNNT ?  Rozhodne nejsem schopen to u sebe reprodukovat.  (#768  a #772).  Zavřít ?

**Comment by pavelkocourek** [comment]
Poslal jsem dotaz na Slack dnnt ... at se zkompletují požadavky na logy.

**Comment by JanMeritus** [comment]
@pavelkocourek ahoj, nevidim ho. ale bolo by to fajn.

**Comment by pavelkocourek** [comment]
Stávající logování dnnt je popsané zde:  https://github.com/ceskaexpedice/kramerius/wiki/DNNT#logován%C3%AD

**Comment by zabak** [comment]
Ještě doplním: údaje o uživateli by měly obsahovat i identifikátory (eppn a eduPersonUniqueID)

**Comment by JanMeritus** [comment]
doplnuji do uvodniho komentu - logika logovani

**Comment by pavel-stastny** [comment]
Provedené změny: 

1. Přidané informace do logování 
2. Logují se nyní všechny přístupy. (Ne jenom DNNT přístup) 
3. Vzhledem k tomu, že se logují všechny přístupy:  Byl změněn název loggeru  `kramerius.access`  (Místo `dnnt.access`)
3. Logované příznaky: `dnnt`, `policy`, `providedByDnnt`  - Přičemž význam příznaků je stejný jako poskytuje API. (`dnnt `- příznak, který říka zda má titul nastaveno dnnt, `policy` - pokud je dokument veřejně přístupný nebo nikoliv, `providedByDnnt` - Poskytnuto v režimu DNNT)
4. Identifikátory uživatele se logovaly již dříve.

**Comment by pavel-stastny** [comment]
Bude připraven build.

**Comment by JanMeritus** [comment]
@pavel-stastny omlouvam se, ale potrebujeme k otestovani a nasazeni ten build NK unikaji dulezita data

**Comment by pavel-stastny** [comment]
Večer zveřejníme build.

**Comment by pavel-stastny** [comment]
@JanMeritus  Ještě se objevila chyba ve statistikách #777. Možná se vydání buildu posune

**Comment by jahhoo** [comment]
@pavel-stastny lze logování po "ukončení Covidu" zas omezit na DNNT nějakou konfigurací? Nebo je potřeba se vrátit ke staršímu jádru?

**Comment by pavel-stastny** [comment]
@jahhoo Nedělal bych ani jedno.  Pouze bych v logstash konfgiuraci (pokud logy posíláte přes logstash do kibany) filtroval jenom ty zprávy, které jsou pro vás důležité.
