### ISSUE TITLE
Kramerius a Kramerius klient

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#776]
@pavelkocourek @vlahoda @honza-rychtar bolo by mozne pripravit zverejnit release plan s predbeznymi terminy (dny, mesice, kvartaly) planovanych releasu a jejich strucneho popisu? potreboval by som to kvuli lepsimu planovani akci ze strany participantov

**Comment by pavelkocourek** [comment]
Plánování probíhá na schůzkách vývojového týmu (kterých se většinou za NK účastníš).
A to včetně probírání issues, která se budou zapracovávat.

Nejbližší plánovaný release bude verze 7, která se nyní nasazuje na testování společně s MZK.
