### ISSUE TITLE
Import NDK balíčku (balíček z ProArcu) s prázdným OCR

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/kramerius#778]
Při importu NDK balíčku, který jsme vytvořili v ProArcu, nám padá import. Na vině je nejspíše prázdný .txt 
Prosím o opravu. Problém není v indexeru, ale ve Fedoře. 

Řešilo se několikrát jak na GitHubu ProArcu, tak Krameria.

U foxml (K4 exportů) se vyřešilo v ProArcu, kdy se vygeneruje OCR s jedním prázdným řádkem: https://github.com/proarc/proarc/issues/658. 
U NDK a archivních balíčků se řeší zde: https://github.com/proarc/proarc/issues/886
V Krameriovi též: https://github.com/ceskaexpedice/kramerius/issues/644

**Comment by vlahoda** [comment]
Opraveno v #644
