### ISSUE TITLE
Označení děl DNNT přes API

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#779]
Pokud zavolám proces reindexace přes API 
`curl -u krameriusAdmin:heslo -H "Content-Type: application/json" -d '{"parameters":["uuid:d246d350-452f-11de-8fb1-0013d398622b"]}' -X POST http://10.0.0.1:8080/search/api/v4.6/processes?def=dnntset`

skončí to chybou
`Caused by: java.io.IOException: not exist or cannot read from /home/kramerius/.kramerius4/lp/45569b5c-9565-4e6d-85fb-042b669d8cdb/uuid:d246d350-452f-11de-8fb1-0013d398622b`

Očekával bych, že toto volání označí dokument jako DNNT a nebude prohledávat importní adresář. Takto mi volání api nedává smysl...

**Comment by pavel-stastny** [comment]
Parametrem procesu není titul ale csv soubor se seznamem titulů.  Proto ta hláška o tom, že nemohl najít soubor.

**Comment by pavel-stastny** [comment]
Pokud je potřeba takový proces, prosím, zadejte nové issue. Toto zavírám.
