### ISSUE TITLE
Označení děl DNNT přes API dle UUID

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#780]
Prosím o vytvoření procesu, který umožní označovat díla jako DNNT dle jejich UUID a procesu, který umožní odebrat označení DNNT dle jejich UUID.

Jako UUID lze zadávat i pole s více UUID.

**Comment by pavel-stastny** [comment]
https://github.com/ceskaexpedice/kramerius/wiki/DNNT#procesy-ozna%C4%8Dov%C3%A1n%C3%AD-p%C5%99es-api-z-p%C5%99%C3%ADkazov%C3%A9-%C5%99%C3%A1dky
