### ISSUE TITLE
Rozvojovy pozadavek: Univerzalni prava pristupu, znaceni licenci a aplikace globalnich akci (nejen DNNT)

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#781]
V souvislosti s diskutovanym rozvojem spristunovani del (nejen dle DNNT) prosim o zavedeni moznosti univerzalniho labelovani prav a nastaveni rozsahu odpovidajicich akci, tak aby nebylo nutne do budoucna pro tyto veci upravovat primo zdrojovy kod Krameria.

- **Univerzalni znaceni liceni** Moznosti pridelovat prava formou libovolnych univerzalnich labelu znacicich licence, anebo specificky pristupne dokumenty dle casu, mista a urovne prav pristupujici osoby (aktualne je tam **samostatna vrstva** `verejne` a `neverejne` a **vrstva** `dnnt`, budeme potrebovat jeste `dnnt-na-miste` a kdovi co vznikne v budoucnu)
- **Univerzalni pravidla pristupnosti pro jednotlive typy licencovanych dokumentu** Pravidla ktora slouzi k vyhodnoceni pristupnosti dokumentu by mela byt univerzalnejsi a transparentnejsi. Tj. pro kazdy label se dale da dokonfigurovat v **nastaveni globalnich akci** (pripadne xml) libovolna kombinace globalnich akci, typu `cteni`, `export`, zobrazeni pro:
  -  `IP filtre`
  - `plovouci zed`
  - `plovouci zed pro typ dokumentu`
  - `povolena instituce`
  - `token`
  -  `vlastnost "po prihlaseni"` apod. 
 Na zaklade techto prav by mel Kramerius API umet pro klienta poskytovat a neposkytovat dane elementy univerzalne. Tj. Aktualni pravidla pristupu (IP, user group atd) potrebujeme rozsirit o pravidla, ktere by vyhodnocovali hodnotu libovolne hodnoty atributu v SOLR (eg. labely `dnnt`,` dnnt-na-miste`, `jine`). Pravidla `IP`, `user group`, `hodnota atributu` a dalsi by malo byt mozne libovolne kombinovat. EDIT: + melo by byt mozne stanovovat a upravovat precedenci labelu
 - **Pravidla via kontext ze skriptu** Uvitali bychom, kdyby vzniklo pravidlo, ktere by umoznilo **vyhodnotit skript** (napr. javascript, lua, python, webhook). Kramerius by pri vyhodnocovani do skriptu poslal cely `kontext dokumentu ze SOLR` a informace u uživateli. Skript by vrátil hodnotu `OK/NOOK` na zaklade toho by se rozhodlo, zda ma uzivatel pravo na prohlizeni dokumentu. Timto zpusobem by v budoucnosti administratori Krameria mohli definovat slozita pravidla pro pristup uživatelu k dokumentu bez nutnosti upravy kodu Krameria. Priznaky o dostupnosti del by meli byt dostupne via OAI, nebo API.
 -  - **Popis precedence a vyhodnocovani roli** dle vyssiho upravit popis vyhodnocovani roli, pripadne nastaveni mechanizmu precedence

EDIT: moving wall, muze byt klidne implementovana v statickom zmysle

**Comment by zabak** [comment]
@JanMeritus u pravidel via kontext ze skriptu bych byl opatrný - aby to nemělo výrazně negativní dopad na rychlost. Obecně: neexistuje na tohle nějaké existující použitelné řešení? Nebo alespoň už vymyšlený způsob, jak ta pravidla zapisovat.

**Comment by JanMeritus** [comment]
poprosim o vyjadreni p. @vlahoda nebo @honza-rychtar

**Comment by vlahoda** [comment]
Schuzka 25.1.: V navaznosti na implementaci noveho pravidla DNNT  #785 bude implementovano zobecnene reseni umoznujici definovat (staticke) pravidlo pristupu podle admoinistratorem definovaneho pole v indexu.  Dynamicky vyhodnocovana kriteria neni mozne pouzit kvuli vykonnosti a facetum.

**Comment by pavel-stastny** [comment]
@vlahoda @zabak Myslim, ze by se mohlo zavrit.  Jak bylo napsano vyse.. Nyni je mozno definovat vlastni labely/licence  a skriptovani mimo krameria neni mozne.

**Comment by zabak** [comment]
@pavel-stastny ano, tohle by šlo zavřít.
