### ISSUE TITLE
Solr: partial update dokumetů s geografickými souřadnicemi

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#782]
V MZK aktivně používáme [partial update](https://lucene.apache.org/solr/guide/7_0/updating-parts-of-documents.html), kterým velmi rychle opravujeme určitá pole v indexu, namísto reindexace celých dokumentů. Však ale pokud dokument má zaindexovane pole **range** (jako třeba u map), partial update padá s chybou bez ohledu na to, jaké pole bylo updatovano. V [dokumentaci](https://lucene.apache.org/solr/guide/7_0/updating-parts-of-documents.html#field-storage) je také popsáno toto omezení a je řečeno, že by pole typu BBoxField nemělo byt *stored*, aby vše fungovalo (otestováno, pravda).

Jak a kde se prosím používájí hodnoty tohoto pole? Dalo by se to nastavit na *stored=false*? Existuje nejaký jiný typ, kterým by se dal nahradit ten BBoxField? Partial update je vyborný nástroj, a bylo by smutně, pokud by se ho nedalo využit i pro mapy.

**Comment by zabak** [comment]
@honza-rychtar využíváš údaje z toho pole pro nějaké další věci? Bylo by složité mít ty hodnoty stored v jiném poli (jiného typu) a to stávající range nechat jen jako indexed?

**Comment by honza-rychtar** [comment]
Pole _range_ se používá jako filtr na objekty, jejichž souřadnice (bounding box) má neprázdný průnik s vybranou plochou na mapě.
Klidně může být `stored=false`

@rzeh4n V novém schématu už je _range_ (nově _coords.bbox_) `stored=false` že?

**Comment by pavel-stastny** [comment]
@honza-rychtar @rzeh4n  Jenom, prosím, uložte tu informaci do jiného pole, aby šel replikovat obsah indexu bez nutnosti nahlížení do Akubry.

**Comment by rzeh4n** [comment]
Popisuju jen situaci u nového indexu a indexeru.
Takto to funguje:
```
<fieldType name="bbox" class="solr.BBoxField" geo="true" numberType="_bbox_coord" storeSubFields="false" stored="true"/>
<fieldType name="_bbox_coord" class="solr.TrieDoubleField" precisionStep="8" docValues="true" stored="false"/>
<field name="coords.bbox" type="bbox"/>
```
Změna je akorát **stored="true"** u **fieldType name="bbox"**, tedy u definice typu, ne pole.
Otestováno i na K7 MZK, že partial (atomic) update funguje na takových objektech, co mají něco v poli coords.bbox.

Teď jediné, u čeho by partial update neměl projít, jsou pole text_ocr.lemmatized, text_ocr.lemmatized_ascii, text_ocr.lemmatized_nostopwords. Ty nejsou ani stored ani docValues, tedy nesplňují podmínku, aby ten atomic update prošel. Atomic update dělá interně reindexaci celého objektu na základě částečných vstupních dat, proto musí být data pro všechna pole nějak uložena, tedy buď _stored="true"_, nebo _docValues="true"_.
Ty ocr pole pak naruší částečné reindexace na základě třeba přidání příznaku dnnt někam výš do stromu. Kvůli filtrování private/dnnt, apod. musí být ta informace až ve stránkách.

**Comment by pavel-stastny** [comment]
@honza-rychtar @rzeh4n @zabak Již změněno v novém indexu.  Ohledně atomic update, je možné ho použit jenom vždy se musí myslet na to, že je potřeba updatovat nejenom to inkriminované pole ale taky pole `indexed`.
