### ISSUE TITLE
Umožnit přihlašování uživatelů z klienta na jiné doméně

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#783]
Přejít na přihlašování přes tokeny, aby se čtenáři mohli přihlašovat do Krameria běžícího na jiné doméně než klient.

**Comment by pavelkocourek** [comment]
Je třeba při přihlašování mezi Digitální knihovnou a jednotlivým Krameriem. Bude obdobné na ČDK.

**Comment by zabak** [comment]
Pomohl by keycloak?

**Comment by zabak** [comment]
Nebo JWT? Nebo JWT v keycloaku?

**Comment by zabak** [comment]
kolega ještě upřesňuje: OIDC - https://auth0.com/docs/protocols/openid-connect-protocol , JWT je jenom přenosová technologie pro token. Navrhují ještě SCIM - http://www.simplecloud.info/

**Comment by pavel-stastny** [comment]
@zabak Můžeme zavrít?
