### ISSUE TITLE
K5.5 - generování PDF neproběhne kvůli chybějící property pdf.fp.publishers

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#784]
Stejný problém jako https://github.com/ceskaexpedice/kramerius/issues/739 akorát klíč je jiný:  pdf.fp.publishers

**Comment by filak** [comment]
Mohl by prosím tedy tento chybějícící klíč pdf.fp.publishers někdo přidat do https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/base.properties
https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/base_cs.properties
?

**Comment by pavel-stastny** [comment]
@filak Doplněno.  Bude přítomno v další verzi.

**Comment by filak** [comment]
OK, chvíli to sice trvalo, ale je to doplnene, zaviram.
