### ISSUE TITLE
DNNT rozdeleni licencnich kategorii - hori

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#785]
Tady vybiram z univerzalniho pozadavku, pokud je  #781 slozity na implemantaci, potrebujeme rozdelit v Kramerius DNNT dila poskytovany na miste samem (vsechny dnnt) a vzdalene (jenom ty co nejsou na miste samem). Obidve su dnnt ale meli by byt odliseny specialnimi priznaky.

Zaroven nad kazdym samostatne by mal byt mozno aplikovat raz za cas moving wall (viz #751 ) specificky nad periodiky 
- a zaroven pro kazdy priznak specificky -
na miste samem - 2000
vzdalene 2007

- Do budoucna pro kazdy z techto priznaku by mela byt moznost povolit vlastni sadu povolenych IP adres, pristupovych tokenu na API, nebo shibboletich instituci

**Comment by pavel-stastny** [comment]
Připravíme build.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim jeste o uvedeni, jakym zpusobem bude pak prebihat oznacovani pro dila vzdalene pristupna a dila pristupna na miste samem, pripadne jak bude resen konflikt s puvodnim oznacenim `"dnnt:true"`

**Comment by pavel-stastny** [comment]
@JanMeritus 

> prosim jeste o uvedeni, jakym zpusobem bude pak prebihat oznacovani pro dila vzdalene pristupna a dila pristupna na miste samem,

To jsou jenom priznaky (labely), prida se label a vybrane skupine  uzivatelu se priradi pravo DNNT label.  Jestli narazis na MovingWall, tak na to bohuzel pri implementaci nedoslo.  Zatim je mozno oznacovat pouze standardnim "cvs" souborem. 

>pripadne jak bude resen konflikt s puvodnim oznacenim "dnnt:true"

Neni konflikt.   `dnnt:true`  oznacuje vsechny dnnt dokumenty.   V ramci teto mnoziny lze definovat podmnoziny, ktere se oznaci priznakem a pro ne definovat pristup pres` DNNT label`.  Uzivatel, ktery je svazany s timto pravem, muze videt pouze jenom tuto cast.

**Comment by zabak** [comment]
Bylo by pro dobré pro celostátně platná práva definovat závazné labely.

**Comment by JanMeritus** [comment]
rsp je jiz mit jako moznost preddefinovane

**Comment by zabak** [comment]
@JanMeritus navrhni autoritativně nějaké hodnoty

**Comment by jahhoo** [comment]
@pavel-stastny prosím o popis, jak ve verzi 5.4.7 nastavit, aby všechny DNNT díla BEZ labelu byly přístupné přes proxy na web 
a aby na terminálech byly přístupné všechny DNNT díla + díla s labelem (label např. terminal)

**Comment by pavel-stastny** [comment]
@jahhoo Nevim, jestli si rozumime....  DNNT jsou vsechny dokumenty (s labelem i bez) .  Label umoznuje vybrat cast dnnt dokumentu a tu zverejnit pres dnnt label.   

Pokud na terminalu by mely byt pristupne vsechny dnnt dokumenty, pak je to standardni dnnt .   Pokud na webu ma byt zverejneno jenom neco, pak je to ten dnnt-label. Pokud chcete mit na terminalu jenom neco a na webu taky jenom neco, pak jsou to dva ruzne labely.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o popis a explikacit implementovane precedence opravneni, z reakce se domnivam ze je to implementovano nasledovne:

1. public 
1. private  - filters (eg. IP)
1. moving wall - standard
1. dnnt  - filters (eg. IP)
1. labels - filters (eg. IP) - jakasi vyssi vrstva dnnt
1. labels moving wall


- od nejzakladnejsi vrstvy se zpristupnuje, pokud uzivatel splnuje dana opravenie, tj ma danou roli, nebo naplnuje pro roli podminky 

https://github.com/ceskaexpedice/kramerius/wiki/DNNT#rozšíření-systému-práv-o-značkylabels

```
Uživatel, který má roli user_role_1 má právo na DNNT dokumenty (v indexu jsou zaindexované jako dnnt:true) a pouze, pokud mají značku priznak_jedna.

Druhá možnost je kombinovat značku s IP filterem. Pro tyty účely slouží DNNT značka kombinovaná s IP filtrem.

Uživatel, který má roli user_role_2 má právo na DNNT dokumenty (v indexu jsou zaindexované jako dnnt:true) a pouze, pokud mají značku priznak_jedna a uživatel se připojuje z adresy 192.168.*.

Standardní DNNT přístup zůstáva nezměněn. Tedy uživatel, který má nadefinované právo DNNT Flag, má právo na všechny DNNT dokumenty. Bez ohledu na naindexované značky.
```

souvis s #791 

nicmene dle testu (@jahhoo prosim o specifikaci ktere, pripadne dalsi popis) se nektere dokumenty ktere sou nastaveny private chovaji jako volne

**Comment by pavel-stastny** [comment]
@JanMeritus 

> public
private - filters (eg. IP)
moving wall - standard
dnnt - filters (eg. IP) *
labels - filters (eg. IP) - jakasi vyssi vrstva dnnt *
labels moving wall *

Respektive dnnt pravo (pava) jsou vyhodnocovana jako posledni. MovingWall, bude to pouze jako process.  (Myslim, ze se to resilo v nejakem issue) 

> ? PDFDNNTFlag*
> exkluzivni
> interpretace je zostupna, pokym se nenajde TRUE, od nejzakladnejsi vrstvy se zpristupnuje, pokud uzivatel splnuje dana opravenie, tj ma danou roli, nebo naplnuje pro roli podminky

Sleduje, pokud uzivatel je uzivateli poskytnuto dilo v rezimu dnnt, zakazuje.  Jinak vraci NOT_APPICABLE 

> nicmene dle testu (@jahhoo prosim o specifikaci ktere, pripadne dalsi popis) se nektere dokumenty ktere sou nastaveny private chovaji jako volne

Popiste scenar, ja to u sebe vyzkousim.

**Comment by jahhoo** [comment]
@pavel-stastny scénář je popsán v #791
