### ISSUE TITLE
DNNT statistiky odliseni

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#789]
prosim pri implementaci #785  a zejmena #781 bude potrebne aby bylo mozno statistiky  (rsp exportni soubory) vest oddelene nebo dostatecne dobre oddelit pro pripadny rozpad statistik tykajicich se specialnich pristupu:

Use case 
- pozadavek drzitelu kolektivnich licenci v ramci uzivani
  -  log na miste samem
  - log vzdaleny pristup

**Comment by JanMeritus** [comment]
@pavel-stastny muze byt vyreseno i prostrednicvim evidence priznaku (odlisuje si nasledne spracovatel logu)

**Comment by pavel-stastny** [comment]
@JanMeritus Již od začátku to bylo zamýšleno tak, že rozdělení na jednotlivé kategorie bude až při zpracovávání logů.  V logu jsou přítomna informace o tom, podle kterého label bylo dílo poskytnuto.   To by pro konfiguraci například logstash mělo stačit.
