### ISSUE TITLE
Problém s načítáním procesů - K5.4.7

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#790]
V nové verzi 5.4.7 máme problém se zobrazením administrátorských procesů procesů. 
Adresa search/inc/admin/_processes_data.jsp?size=20&ordering=PLANNED&type=DESC&_=1612200000473 - vrací Error 500
![Snímek z 2021-02-01 18-20-23](https://user-images.githubusercontent.com/33415849/106494300-8734a100-64ba-11eb-8ae1-9748a4385731.png)

**Comment by pavel-stastny** [comment]
Nedari se mi u me nasimulovat, muzu poprosit o chybovou hlasku z logu cataliny ?

**Comment by jahhoo** [comment]
@pavel-stastny log posílám v příloze
[catalina_DNNT47.txt](https://github.com/ceskaexpedice/kramerius/files/5921228/catalina_DNNT47.txt)

**Comment by pavel-stastny** [comment]
@jahhoo Změnil jsem název procesů.  Můžete si do lp.xml přidat následující řádky ? To by mělo pomoct.  

```xml
  <process>
        <id>dnntset</id>
        <description>Set the DNNT flag </description>
        <mainClass>cz.incad.kramerius.csv.DNNTCSVFlag</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <parameters>true</parameters>
        <securedaction>dnnt_admin</securedaction>
    </process>

    <process>
        <id>dnntunset</id>
        <description>Unset the DNNT flag</description>
        <mainClass>cz.incad.kramerius.csv.DNNTCSVFlag</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <parameters>false</parameters>
        <securedaction>dnnt_admin</securedaction>
    </process>
```

**Comment by jahhoo** [comment]
@pavel-stastny Kde prosím najdu soubor lp.xml?

**Comment by pavel-stastny** [comment]
@jahhoo V **~/.kramerius4/lp.xml**.   Pokud tak není, tak ho můžete normálně vytvořit akorát výše zmíněný obsah musí být zabalený do tagů processes. Viz: 

```xml
<processes> 
   <process>
        <id>dnntset</id>
        <description>Set the DNNT flag </description>
        <mainClass>cz.incad.kramerius.csv.DNNTCSVFlag</mainClass>
        <standardOs>lrOut</standardOs>
        <errOs>lrErr</errOs>
        <parameters>true</parameters>
        <securedaction>dnnt_admin</securedaction>
    </process>
....
```

atd..

**Comment by jahhoo** [comment]
@pavel-stastny Soubor jsem vytvořil (přikládám v příloze, z důvodu uploadu jsem musel přidat ještě příponu .txt). Procesy se stále nezobrazují.

[lp.xml.txt](https://github.com/ceskaexpedice/kramerius/files/5926202/lp.xml.txt)

**Comment by pavel-stastny** [comment]
A hlaska v logu je porad 'cannot find definition 'dnntset'' ?

**Comment by jahhoo** [comment]
@pavel-stastny Ano, log je stejný

`TID: [2021-02-05 02:38:40,025] SEVERE [cz.incad.kramerius.auth.thirdparty.ExtAuthFilter doFilter] () - An exception occurred processing JSP page /inc/admin/_processes_data.jsp at line 489
`

**Comment by jahhoo** [comment]
Vyřešeno. Díky za spolupráci. 
Včera jsem ještě zjistil, že se nevytváří nové procesy.

Řešení:
- vypnul jsem tomcat
- odstranil jsem složku search z tomcat/webapps
- spustil jsem změnu práv (chown) na složku kramerius
- rebootoval jsem server a nahodil tomcat

Nyní mám problém s označením dokumentů - řešeno v #792
