### ISSUE TITLE
Problém se zobrazením dokumentů - nastavení labelu

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#791]
- V Krameriovi v nastavení práv jsem nastavil dodatečnou podmínku "DNNT značka kombinovaná s IP filtrem" a zadal IP adresu proxy serveru. Zároveň jsem zadal značku "dnntonline"
- Označil jsem vzorek 8 dokumentů labelem "dnntonline"
- Očekával jsem, že na proxy serveru dostanu jako DNNT výstup pouze 8 označených dokumentů. Zobrazily se mi všechny DNNT dokumenty - label není vůbec brán v potaz (viz. screen)

![Snímek z 2021-02-01 18-50-57](https://user-images.githubusercontent.com/33415849/106497866-e2689280-64be-11eb-9980-638564024210.png)

To není správné chování, že?

**Comment by pavel-stastny** [comment]
Po telefonickem hovoru s @honza-rychtar  jsme se domluvili, ze do klienta pribude moznost facetu pro jednotlive labely.

**Comment by jahhoo** [comment]
@pavel-stastny Díky, ale my nepotřebujeme facetu, ale potřebujeme, aby se v Krameriovi, který je za proxy serverem, zobrazily jen díla označená daným labelem. Jiné se zobrazovat nemají.

**Comment by pavel-stastny** [comment]
@jahhoo  Já myslím, že potřebujete.  Při zobrazení výsledků fitrů, faset či při výsledcích hledání se práva neuplatňují. Je to čistě dotaz do solru na data  a je to plně v režii klienta. K vyhodnocení práv dochází až při dotazu na chráněný obsah (obrázek, text_ocr, alto, atd..) 

Faseta na dnnt-labels je potřeba aby šlo vůbec data podle labels filtrovat.  Zobrazení či nezobrazení konkrétních filtrů je pak na konfiguraci klienta ale tady to fakt musí odpovědět Honza.  Toto není záležitost jádra.

**Comment by zabak** [comment]
@pavel-stastny Jak je to vlastně s vyhodnocováním práv v K7? Vychází se z údajů v rels-ext nebo z údajů v solru?

**Comment by pavel-stastny** [comment]
@zabak  Záleží na pravidlu.  U dnnt pravidel se kontrolují příznaky brané ze solru, u IP filtru zase z requestu, atd...

**Comment by pavel-stastny** [comment]
@zabak Ale to je stejne jak U K5 tak i u K7, vždycky ta dodatečná podmínka si šáhne pro informaci, kterou potřebuje pro vyhodnocení.

**Comment by honza-rychtar** [comment]
Jakmile to zobecníme a budeme mít libovolný počet labelů, tak už se nedají dělat kombinace v Dostupnosti.
**Všechny dostupné dokumenty** pak s více labely taky nebudou dávat smysl, protože bude záležet na dynamickém vyhodnocení a uživatel bude mít právo jen k některým labelům.
Nejjednodušší řešení, resp. krok číslo jedna na cestě k zobecnění DNNT na straně klienta, je přidání fasety **Licence** pod Dostupnost, kde v tuhle chvíli budou dvě: **DNNT na místě** a **DNNT vzdáleně**.
A odebrání **DNNT** a **Všechny dostupné dokumenty** z Dostupnosti.
Vypadalo by to nějak takto
<img width="301" alt="dnnt" src="https://user-images.githubusercontent.com/1178142/106888408-cfd0a200-66e6-11eb-8e15-caa157255ff0.png">
Později se příznak DNNT kompletně odebere a bude se to řídit pouze tím labelem. Labely pak můžou být jednak různé formy DNNT, ale také jiné licence nebo prostě štítky vymezující kolekci dokumentu dostupnou vybraným uživatelům a/nebo stanicím (IP).

Potom bychom mohli doplnit i to dynamické vyhodnocení. Klient by se mohl po startu aplikace a po přihlášení zeptat API Krameria na labely, které ma daný uživatel dostupné. Kramerius pro všechny labely (předpokládám, že jich budou jednotky) zjistí, ke kterém labelům má daný uživatel přístup a pošle klientovi seznam těchto labelů.
Klient by pak mohl
- vrátit **Všechny dostupné dokumenty** do dostupnosti a výsledek by byl **dokument je public nebo dokument obsahuje alespoň jeden label, ke kterému má uživatel přístup**.
- pod Licence zvýraznit labely, ke kterým má uživatel přístup.

@pavel-stastny To by neměl být problém že?

@JanMeritus Co myslíš? Mám teď přidat tu fasetu Licence? DNNT bych u dostupnost zatím nechal, protože label není zatím povinný.

Jinak jak psal @zabak někde, pojďme se dohodnout na identifikátorech pro DNNT na místě samém a DNNT se vzdáleným přístupem. Např. `dnnt_na_miste`, `dnnt_vzdalene`
Aby se to už mohlo začít používat napříč knihovnami a aby se to mohlo hodit do lokalizačních souborů - což bychom si taky měli říct, jak se tyto 2 labely/licence budou jmenovat česky a anglicky.

**Comment by JanMeritus** [comment]
@jahhoo  co myslis ?

@honza-rychtar tj uz implementujes do klienta neco v zmysle #781 ?

@pavel-stastny urcite by prava melo taky overovat API jadra, jestli z klienta nejdou uzivatelske blafy (ale form u registrace na ockovani)

@zabak @pavelkocourek @MLhotak  muzeme k tomu dat nejaky kratky impromptu **technicky** meeting ? jsme pripraveni klidne kdykoli

**Comment by pavel-stastny** [comment]
@honza-rychtar  Pro přihlášené uživatele jo ale co s těmi, co dostanou dnnt labels na základě IP adresy?

**Comment by honza-rychtar** [comment]
@pavel-stastny Pak je to ok. Protože až si později otevřou dokument s těmito labely, tak ho budou mít skutečně dostupný, protože stále přistupují se stejné IP adresy.

**Comment by pavel-stastny** [comment]
@honza-rychtar Ok. Probereme později 

@JanMeritus Nemyslím si.... práva opravdu končí tam, kde se chce získat chráněný obsah.

**Comment by honza-rychtar** [comment]
@JanMeritus Jen mi potvrď, že začneme tou fasetou. A jak ji pojmenujeme (licence?) a jak budeme říkat těm dvěma základním labelům/licencím dnnt_na_miste, dnnt_vzdalene a jaké jim dáme ID/kódy.

**Comment by jahhoo** [comment]
@honza-rychtar v NK již máme připravené dva labely dnnto (=online) a dnnt (=terminál)

Také si myslím, že by toto měla filtrovat hlavně API. Uživatel se nesmí k datům mimo dnnto z webu vůbec dostat...

**Comment by JanMeritus** [comment]
@honza-rychtar @jahhoo dle dnesnyho meetingu,  labely by mali byt

- dnnto - online pro vzdaleny pristup
- dnntt - terminal na miste samem (at se neplete s dnnt)
- covid - dokumenty pristupne v specialnim rezimu (implementace ale az nasledne)

Interpretaci na filtre by meli definovat obsahovy spravci

**Comment by jahhoo** [comment]
@honza-rychtar Jak to prosím časově vypadá s úpravou klienta?

**Comment by zabak** [comment]
Jak píše @honza-rychtar

> Později se příznak DNNT kompletně odebere a bude se to řídit pouze tím labelem. Labely pak můžou být jednak různé formy DNNT, ale také jiné licence nebo prostě štítky vymezující kolekci dokumentu dostupnou vybraným uživatelům a/nebo stanicím (IP).

Myslím, že je načase, aby se i ověřování public/private při zpřístupňování obrázků v jádře koukalo do solru a ne do Fedory. Stejně se do Solru dívá kvůli DNNT, takhle by bylo spolehlivěji zajištěno, že jsou konzistentní fasety apod. Ve Fedoře by ty údaje být měly taky, ale jen pro případ reindexace, nesloužily by pro ověřování při zpřístupňování uživatelům. Jako vedlejší efekt by to asi celý proces ověření o kousek urychlilo.

**Comment by vlahoda** [comment]
@zabak Petre, zrovna public/private se vyhodnocuje podle SOLR, jinak by nefungoval ten prislusny facet. Obecne, kterakoli data jsou indexovana, berou se prednostne z indexu. Ale nektera pravidla jen z indexu proste vyhodnotit nejdou

**Comment by zabak** [comment]
@vlahoda Že se ze solru berou fasety, to je jasné, ale myslel jsem, že jádro se o tom, jestli má pustit konkrétní obrázek z imageserveru ven rozhoduje stále podle obsahu rels-ext.

**Comment by annie-cz** [comment]
Zdravím, šlo by prosím k těm labelům přidat i licence?

Máme trošku problém, že máme na spoustu věcí licence a když se dělají tyhle hromadné změny, musíme to pak řešit dodatečně a trošku zbytečně :) Díky moc!

**Comment by JanMeritus** [comment]
@annie-cz #781  puvodni systemovy pozadavek z ktereho to cele vychazi, pocita s tim ze nakonec to vsechno co se ted nazyva label =licence, implementace se ubira smerem ze budou vicenasobne a proste na zaklade ty pro uzivatele v tou chvili nejvyhodnejsi je mu dilo poskytnuto. Tzn kazda DK ma dalsi specificke licence pro spristupnovani a na zaklade nich muze dilo poskytovat. Ke konci by se ze vsech licenci meli dat delat interne v dane organizaci statistiky plneni. Jestli ty licence budu natvrdo, nebo zo SOLR je uz skor uvaha k implementaci, nicmene urcite by meli nekde byt perzistente.

**Comment by pavel-stastny** [comment]
Po dohodě s @honza-rychtar přibyla do API možnost získání všech labels, které jsou svázané s daným uživatelem a to jak přes roli tak i přes IP adresu.  To by mělo stačit pro doplnění možnosti filtrovaní.

**Comment by pavel-stastny** [comment]
Řešeno komitem 54e6279.  Souvisí s #802.
