### ISSUE TITLE
K5 - Nežádoucí přesměrování z portu 8080 na port 80 při přihlašování do backendu

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius#793]
Aktuálně používám pro spuštění Krameria Docker image kramerius:latest a upravenou verzi docker-compose [z projektu s2i-kramerius](https://github.com/moravianlibrary/s2i-kramerius) a směruji pomocí traefiku. Kdykoliv se snažím nějak interagovat s loginem (přihlašování/odhlašování), tak se aplikace přesměruje z portu 8080 na port 80. Bohužel port 80 aktuálně používám pro frontend. Dal by se vymyslet nějaký rychlý fix nebo něco co s tím udělat, aby aplikace zůstala celou dobu na portu 8080? Předem děkuji.

Backend: https://ds-coil.uibk.ac.at:8080
Frontend: https://ds-coil.uibk.ac.at/
docker-compose: https://github.com/SPXcz/kramerius_fb/blob/main/docker-compose.yml

**Comment by vlahoda** [comment]
Bohuzel nevim, jak byl vytvoren image moravianlibrary/kramerius:latest, ale standardne kramerius urcite zadne presmerovani na port 80 pri loginu nedela, problem bych tedy hledal spis v nastaveni vasich routovacich pravidel. Traefik neznam, pouzivame apache httpd s mod_proxy, resp. mod_proxy_ajp a komunikace s backendem bezi pres AJP na portu 8009. Image pro krameria pouzivame ceskaexpedice/kramerius:5.5.0

**Comment by kazooo** [comment]
Zdravím, jde tady o to, že při pokusu o přihlašování, tedy click na tlačitko Login, Kramerius směruje do login formuláře s adresou https://ds-coil.uibk.ac.at:8080/search/redirect.jsp?redirectURL=https://ds-coil.uibk.ac.at/search/ a po přihlášení směruje do https://ds-coil.uibk.ac.at/search/ podle *redirectURL* parametru. Dá se tento parameter změnit přes nějaký konfig?

**Comment by vlahoda** [comment]
Podle meho nazoru staci https://ds-coil.uibk.ac.at/search/ presmerovat na http://localhost:8080/search/ nebo lepe ajp://localhost:8009/search/ a port 8080 vubec ven neotevirat.

**Comment by SPXcz** [comment]
No na 80 a 443 máme právě frontend, který má i subdirectory /search, takže takhle by nám to nefugovalo. Spíš by nám opravdu pomohlo, kdyby někde existoval nějaký config nebo místo, kde je ten statický redirect nastavený.

**Comment by vlahoda** [comment]
Tam neni staticky redirect ani zadny config, URL redirectu se sestavuje dynamicky z URL originalniho requestu.

Mate dve moznosti, jak vyresit konflikt s kontextem /search ve frontendu:
1. provozujte backend na jinem URL (napr. ds-coil-backend.uibk.ac.at), ktere nakonfigurujete jako virtual host na vasem frontendovem webserveru 
2. nakonfigurujte pravidlo mod_proxy pro kontext search s lomitkem na konci:
```
ProxyPass "/search/" "ajp://127.0.0.1:8009/search/" 
ProxyPassReverse "/search/" "ajp://127.0.0.1:8009/search/" 
```
URL backendu pak je pristupne take pomoci zadani toho lomitka. Je to osklive, ale jednoduche reseni. Vzhledem k tomu, ze backend je urcen pro admina a ne pro verejnost, myslim, ze je to prijatelne.

Pak je samozrejme jeste treti moznost, presvedcit @honza-rychtar, aby ten kontext /search prestal ve frontendu pouzivat. To se mi zatim nepodarilo :-)
