### ISSUE TITLE
API nevrací hodnotu dnnt-labels (5.4.7)

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#796]
API nevrací hodnotu dnnt-labels.
U dokumentu je v SOLR správně uložen štítek, ale API ho nezobrazí.

**Comment by pavel-stastny** [comment]
Mohl bych poprosit o json, ktery vraci API a zaroven: ktere pravidlo pouzivate? (dnnt-labels nebo dnnt-labels s IP filtrem) ?

**Comment by jahhoo** [comment]
API:
`{"datanode":false,"context":[[{"pid":"uuid:a2894d20-1d4b-11e8-bdb0-005056827e51","model":"monograph"}]],"pid":"uuid:a2894d20-1d4b-11e8-bdb0-005056827e51","model":"monograph","handle":{"href":"http://10.5.1.35:8080/search/handle/uuid:a2894d20-1d4b-11e8-bdb0-005056827e51"},"title":"Metodologie optimálního plánování","root_title":"Metodologie optimálního plánování","root_pid":"uuid:a2894d20-1d4b-11e8-bdb0-005056827e51","policy":"private","dnnt":true}`

Screen ze SOLR:
![Snímek z 2021-02-10 11-19-15](https://user-images.githubusercontent.com/33415849/107496667-e3ba4f00-6b91-11eb-85d3-d13b0fee60f3.png)

**Comment by jahhoo** [comment]
@pavel-stastny jaký je prosím časový odhad úpravy?

**Comment by pavel-stastny** [comment]
@jahhoo  Ke konci tydne.    

Jenom doplnim:  Nyni se dnnt label v API objevuje pouze pokud je dilo poskytnuto podle tohoto labelu/licence.  Po uprave pribude do API informace i ktere vsechny labely ma k sobe titul pripojene.
