### ISSUE TITLE
Označení dokumentů dnnt labelem přes API

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#797]
Prosím o popis, jak je možné označit dokumenty labelem přes API

**Comment by pavel-stastny** [comment]
Viz:  https://github.com/ceskaexpedice/kramerius/wiki/DNNT#procesy-ozna%C4%8Dov%C3%A1n%C3%AD-p%C5%99es-api-z-p%C5%99%C3%ADkazov%C3%A9-%C5%99%C3%A1dky
