### ISSUE TITLE
Uprava logovani Statistics - vicesvazky a periodika

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#798]
Dobry den, chtel bych v souvislosti s DNNT ale taky univerzalne navrhnout upravu generovani logu statistiscs: 

- pridat nove UUID - u vicesvazku a periodik bude nutny logovat do zaznamu nejen rootPID a PID (stranku), ale aj svazek / rsp idealne rocnik UUID
-  `publishedDate`  zachovat jak je pro mono, ale nahradit hodnotu u periodik a vicesvazku datePublished vychadzeni periodika issued date dane casti (idealne ve formatu YYYY) - tj misto Rude Pravo 1950-1992 -> 1991
- - zde je k posouzeni jestli nepridat cislo rocniku / svazku

pokracovani #774

**Comment by zabak** [comment]
@JanMeritus to publishedDate jsi myslel tak, že u monografií zůstává tak jak je, ale u periodik a vícesvazků by se měl udávat rok vydání konkrétního svazku nebo čísla periodika, že?

**Comment by JanMeritus** [comment]
@zabak jop, upravujem vyse carku, at je to jednoznacnejsi

**Comment by pavel-stastny** [comment]
> pridat nove UUID - u vicesvazku a periodik bude nutny logovat do zaznamu nejen rootPID a PID (stranku), ale aj svazek / rsp idealne rocnik UUID

V logu je již nyní vidět celá cesta od stránky až po top level model (`pids_path`).

> publishedDate zachovat jak je pro mono, ale nahradit hodnotu u periodik a vicesvazku datePublished vychadzeni periodika

Nyní se `publishedDate ` bere přímo z indexu z pole `datum_str`.    Bude nahrazeno získáváním dat přímo z BIBLIO_MODS z položek  `//mods:part/mods:date`   nebo   `//mods:originInfo/mods:dateIssued`.  Vyhodnocovat se bude od spodu, tedy v logu se objeví ten datum, který bude v metadatatech blíž dané zobrazované stránce.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o update, jestli to je zarazeno k pripravovanemu builud, je to dulezite k monitorovani uziti del a licence

**Comment by pavel-stastny** [comment]
@JanMeritus Ano
