### ISSUE TITLE
Režim dostupnosti pro obálky/obsahy - volné zobrazení bez stahování

### ISSUE THREAD

**Issue by vjirousek** [ceskaexpedice/kramerius#799]
Dávám k diskusi návrh na nový režim zobrazení děl (mimo stávající dostupné / nedostupné / dnnt vzdáleně/ dnnt na místě), který by umožnil zobrazit dokument bez přihlašování, bránil by ale stahování a pořizování výstřižků. Primární užití vidím pro obálky a obsahy, na jejichž zpřístupnění pamatuje AZ v knihovní licenci, ale pod podmínkou zamezení zhotovení rozmnoženiny. Do budoucna si umím představit širší možnost využití třeba v případě části jinak licencovaného obsahu. 

AZ: "Do práva autorského nezasahuje osoba uvedená v odstavci 1, která za účelem nabídky k půjčení a zpřístupnění obsahu svých sbírek užije rozmnoženinu díla či jeho části obsažené na obálce, případně včetně tematického obsahu díla v katalogu sbírek; tento katalog sbírek může také zpřístupňovat veřejnosti, zamezí-li zhotovení rozmnoženiny výtvarného díla, která by mohla být užita k přímému či nepřímému hospodářskému nebo obchodnímu účelu..."

Souvisí s obecným požadavkem https://github.com/ceskaexpedice/kramerius/issues/781.

**Comment by JanMeritus** [comment]
@vjirousek ma jit o rezim nebo feature pro vsechny knihy? pripadne o jaky pomer objemu z DK?

 na zaklade ceho by se rozhodovalo kde se obalky smi a kde ne?

**Comment by filak** [comment]
@vjirousek Tady https://github.com/ceskaexpedice/kramerius/pull/863 + https://github.com/ceskaexpedice/kramerius/pull/864 ctu, ze to neplati pro periodika... 

Pokud to tak skutecne je (?), tak by to chtelo mergovat a vydat novy release K5, protoze ten aktualni release zrejme tedy pousti obalky periodik volne...

**Comment by filak** [comment]
Ještě si říkám, že by to mělo být nějak konfigurovatelné 

1. globálně povolit/zakázat
2. povolit/zakázat pro konkrétní model
3. povolit/zakázat pro konkrétní titul

Protože problém to může být u novin, ale u časopisů s klasickou obálkou a obsahem by zase byla škodat to zakázat.

**Comment by filak** [comment]
Pokud to zpřístupnění titulní strany/obálky skutečně neplatí pro periodika - pak to aktuálně obálky leakuje, např.:

http://www.digitalniknihovna.cz/mlp/uuid/uuid:877263ba-b968-11eb-9864-001b63bd97ba

**Comment by honza-rychtar** [comment]
@filak jo no, i MZK má otevřené všechny titulní strany u periodik http://www.digitalniknihovna.cz/mzk/view/uuid:c74f0f40-7a81-11dd-a1a9-000d606f5dc6?page=uuid:004f7210-745d-11dd-b9d3-000d606f5dc6

Můžete někdo specifikovat ten autorský zákon? Ale dává smysl, že se to novin netýká, na té titulce je čtvrtina obsahu.

**Comment by pavel-stastny** [comment]
@vjirousek @filak  Je toto issue aktuální?  Filtr pro obálky a obsahy je v Krameriovi přítomný delší dobu.

**Comment by filak** [comment]
Vypadá to, že se titulky periodik aktuálně nezobrazují, např.

https://www.digitalniknihovna.cz/mlp/view/uuid:cf34d81f-4d00-49d4-80f6-4746022b5b56?page=uuid:7f55d48f-81ce-11ec-b27f-001b63bd97ba

https://www.digitalniknihovna.cz/mlp/uuid/uuid:7f55d48f-81ce-11ec-b27f-001b63bd97ba

Takže to zřejmě funguje dobře.

**Comment by vjirousek** [comment]
V NDK to naneštěstí stále nevyužíváme, ale obecně mi taky přijde že to např. v MZK funguje dobře. Takže souhlas s uzavřením :)
