### ISSUE TITLE
Issue 307:	Implementace našeptávače

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius#8]
Reported by xrosecky, Apr 5, 2012
Naimplementovat našeptávač do Krameria, jako inspirace může posloužit ten náš (https://github.com/moravianlibrary/Autocomplete), co máme ve VuFindu (https://vufind.mzk.cz/).
Jul 25, 2012 Delete comment Project Member #1 vlahoda
(No comment was entered for this change.)
Status: OnHold

**Comment by pavel-stastny** [comment]
Neni aktualni.. reseno v ramci noveho klienta
