### ISSUE TITLE
Přidat podporu pro přívazky

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#801]
V návaznosti na https://github.com/proarc/proarc/issues/1270 přidat podporu pro přívazky i do Krameria

**Comment by fstepanovsky** [comment]
Testovací server je na https://client.infrahost.eu a https://kramerius.infrahost.eu.
Na https://kramerius.infrahost.eu/search/handle/uuid:861a1a9a-760c-4d2f-95a4-8cb2eb677a1f je vidět, že se konvolut nezobrazuje správně.

**Comment by erikamirova** [comment]
Nezobrazuje se to správně ani v klientovi a ani v Krameriovi. Je tedy potřeba úprava na obou stranách.

Potřebujeme, aby to vypadalo podobně jako články - viz zde: https://dnnt.mzk.cz/view/uuid:66096e04-d0a3-48a4-a7e9-1a0cacb4ab44

Tady je odkaz na základní dílo: http://www.digitalniknihovna.cz/mzk/uuid/uuid:badc5f6f-7cb4-4def-9f8c-f431b8be7a05
Tady je odkaz na přívazek: http://www.digitalniknihovna.cz/mzk/uuid/uuid:badc5f6f-7cb4-4def-9f8c-f431b8be7a05

Divně se tam zobrazují i metadata. U základního díla i u přívazku vidím v metadatech jen poznámky, žánr a typ dokumentu. Nevidím např. název přívazku.

**Comment by honza-rychtar** [comment]
Ty linky nefungují.
V kramerius.mzk.cz jsou konvoluty pořád špatně zaindexované, viz email.

**Comment by fstepanovsky** [comment]
Konvolut `uuid:badc5f6f-7cb4-4def-9f8c-f431b8be7a05` je zaindexovaný.

Kontroloval jsem i děti root pidu a mělo by být vše v pořádku.

**Comment by zabak** [comment]
@honza-rychtar můžeš se na to podívat? Teď se zobrazí jen panel s metadaty, ale konvolut samozný ne.

**Comment by erikamirova** [comment]
@honza-rychtar Ahoj, můžu se zeptat, jak to vypadá? Měl jsi čas se na to mrknout?

**Comment by honza-rychtar** [comment]
@erikamirova

**Comment by honza-rychtar** [comment]
@erikamirova v pondělí bych měl mít první verzi s podporou konvolutů.
