### ISSUE TITLE
Problémy s replikací dokumentů z jiné instalace Krameria 5

### ISSUE THREAD

**Issue by jdobiasovsky** [ceskaexpedice/kramerius#803]
Dobrý den, 
snažím se replikovat dokumenty mezi dvěma našimi instancemi krameria (obě jsou verze 5.5.0). Proces v pořádku získá deskriptor ale replikace objektů spadne v bodě kdy se API dotáže na:
`https://kramerius.techlib.cz/search/api/v4.6/replication/uuid:bebd0aab-c067-11e1-8bdd-001b63bd97ba/img_original`, který vrátí status kód 404

Úplně se mi nedaří najít, co by to mělo přesně znamenat. Podle [dokumentace](https://github.com/ceskaexpedice/kramerius/wiki/RemoteAPI) rozhraní pro replikace umožňuje pouze tři operace, které všechny pro daný dokument fungují. 
- Získání popisu replikovaného objektu 
- Získání seznamu všech objektů zahrnutých do replikace
- Získání FOXML dat. Vygenerované foxml se zdá taky být v pořádku.

Mohl bych poprosit o radu kde to dohledat, případně co by mohlo být špatně?

Na zdrojové instanci je použit imageserver pokud to pomůže, rádi bychom byli schopni zreplikovat dokument vč. obrazů.

**Comment by vlahoda** [comment]
Ten endpoint img_original je do API pridan dodatecne prave kvuli podpore prenosu originalnich zdrojovych jp2 obrazku z imageserveru (ktere jinak standardne pristupne nejsou). Funguje tak, ze z datastreamu RELS-EXT nacte URL dlazdic imageseveru (z elementu kramerius:tiles-url) a k ni prida /original. Aby to tedy fungovalo, musi byt tiles-url nastavene spravne (co z tedy asi bude) a musite mit imageserver nakonfigurovan tak, aby tu adresu koncici na /original podporoval.

**Comment by jdobiasovsky** [comment]
Super, díky moc za upřesnění. Teď už si snad poradím.
