### ISSUE TITLE
K5 DNNT - Chyba při použití API Krameria za proxy

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#804]
Dobrý den,

při dotazování na _thumbnail_ datastream přes endpoint `https://dnnt.mzk.cz/item/uuid/thumb` Kramerius (za Apache proxy) vyhazuje následující chybu
```
cz.incad.kramerius.rest.api.k5.client.item.ItemResource.thumb Illegal character in authority at index 8: https://dnnt.mzk.cz, localhost:81/search/img?pid=uuid:fbc42b10-5f03-11eb-b4d1-005056827e51&stream=IMG_THUMB&action=GETRAW
java.net.URISyntaxException: Illegal character in authority at index 8: https://dnnt.mzk.cz, localhost:81/search/img?pid=uuid:fbc42b10-5f03-11eb-b4d1-005056827e51&stream=IMG_THUMB&action=GETRAW
		at java.net.URI$Parser.fail(URI.java:2848)
		at java.net.URI$Parser.parseAuthority(URI.java:3186)
		at java.net.URI$Parser.parseHierarchical(URI.java:3097)
		at java.net.URI$Parser.parse(URI.java:3053)
		at java.net.URI.<init>(URI.java:588)
		at cz.incad.kramerius.rest.api.k5.client.item.ItemResource.thumb(ItemResource.java:514)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
Chyba vzníká [tady](https://github.com/ceskaexpedice/kramerius/blob/dnnt/rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/item/ItemResource.java#L511-L514) a objevila se při pokusu o nasazení novějšeho web klienta. Debugování ukázalo, že starý web klient ty endpointy (full, preview, thumb) nepoužívá, a zpracování requestu v Krameriu probíhá přes [HandleDecorate](https://github.com/ceskaexpedice/kramerius/blob/dnnt/rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/item/decorators/HandleDecorate.java#L61-L64), kde už není ta URI konverze.

Máme DNNT verzi 5.4.8, dalo by se to opravit v dalším releasu (i v K5/K7), prosím?

Děkuju

**Comment by pavel-stastny** [comment]
Opravíme při merge DNNT větve do K5

**Comment by zabak** [comment]
@pavel-stastny jak to vypadá časově? Speciálně tohle nám hodně hoří a řešíme jestli to obejít v klientovi nebo máme čekat na fix jádra.

**Comment by pavel-stastny** [comment]
@zabak Udělám tedy commit ještě do DNNT větve.  Časově: Tak příští týden.
