### ISSUE TITLE
Označení dokumentů labelem přes API - CSV soubor

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#806]
Prosím o popis do wiki, jak označit DNNT dokumenty v CSV souboru požadovaným labelem přes API.

**Comment by JanMeritus** [comment]
@pavel-stastny prosim o ASAP odpoved, bez toho se nepohneme s implementaci

**Comment by pavel-stastny** [comment]
@JanMeritus @jahhoo   Dal jsem popis na wiki: 

https://github.com/ceskaexpedice/kramerius/wiki/DNNT#procesy-ozna%C4%8Dov%C3%A1n%C3%AD-p%C5%99es-api-z-p%C5%99%C3%ADkazov%C3%A9-%C5%99%C3%A1dky

**Comment by jahhoo** [comment]
Díky! :)
