### ISSUE TITLE
Kramerius embedded reader (lehká čtečka vložitelná do externích stránek)

### ISSUE THREAD

**Issue by mjtecka** [ceskaexpedice/kramerius#807]
Bylo by možné vytvořit javascriptovou čtečku, která by se vkládala do stránky a zobrazovala dokumenty z Krameria podobně jako bývají vkládaná videa z Youtube, mapy z Google Maps apod. 

Čtečka by mohla nahradit současnou praxi, kdy si uživatelé vytvoří lokální kopii obrázku a digitální knihovnu přinejlepším odkazují

Nástřel návrhu je tu: https://docs.google.com/document/d/1yLNVQvuvfg0WZNKmvo76XteTUDodjrgBfGgQmiWIm1M/edit?usp=sharing (komentovat může kdokoli)

příklady potenciálního využití
- prezentace historického fondu na stránkách knihoven
- výukové materiály (včetně e-learningu - Moodle apod.)
- soukromé blogy

Využití by bylo spíš pro volné dokumenty (autentizace je v tomhle případě asi dost nešikovná/složitá)

**Comment by pavelkocourek** [comment]
Propojuju : https://github.com/ceskaexpedice/kramerius-web-client/issues/380

**Comment by zabak** [comment]
Zde zavírám, patří do propojeného issue výše, stačilo by taky pro tento účel využít IIIF manifest daného dokumentu a Mirador nebo Universal Viewer jako čtečku.
