### ISSUE TITLE
Vysoke zatizeni bazy kontrolou uzivatelu

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#808]
V kontextu mozneho vysokeho zatizeni PG bazy pristupy uzivatelu prosim o pridani doporuceni vydavatele i pre ostatni instituce do dokumentace specifikaci nastaveni poolingu konexi v search.xml

**Comment by zabak** [comment]
Z toho co jsem o tom slyšel mám doplňující otázku: co konkrétně (jaké akce uživatele) to zatížení databáze generují? Nedala by se daná věc řešit jinak?

**Comment by JanMeritus** [comment]
@zabak ide skor o dodporuceni vydavatele SW implementaci poolingu u konektovani aplikace na bazu:

```
<Context path="/search">
  <Resource auth="Container" 
		  driverClassName="org.postgresql.Driver" 
		  factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
```

**Comment by pavel-stastny** [comment]
@zabak Není mi jasné čeho se to týkalo.  Má smysl toto issue mít otevřené?

**Comment by vlahoda** [comment]
Doovolim si rozhodnout za Petra a uzaviram :-)
