### ISSUE TITLE
Labelovani: Dark Label a Dark Archive

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#809]
prosim o zalozeni labelu negativne oznacujicimu dostupnost del:

UC: Je nutno ridit uzkou ad hoc kuratorskou selekci del, ktere by se:
- meli zobrazovat ctenarum jenom z urcity IP adresy
- nemeli zobrazovat nikomu

UC: Odstraneni hudebnin a jednotek del z Kramerius NDK

**Comment by pavel-stastny** [comment]
Zatim jsme se domluvili, že se nebude implementovat

**Comment by JanMeritus** [comment]
@pavel-stastny prosim neuzavirat, jenom oznacit jako zatim neimplementovany navrh rozvoje

**Comment by pavel-stastny** [comment]
@zabak @pavelkocourek Pro případy, kdy se nemá část díla zobrazovat je plánovaná striktní licence (#1040).
