### ISSUE TITLE
DNNT logování - chybí label

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#811]
@pavel-stastny U logování prohlížených děl chybí informace na základě jakých labelů bylo dílo poskytnuto. Pokud se nepletu, diskutovali jsme o tom, že by to měl vracet parametr provided by DNNT. (Labelu může být zároveň více.)

Bylo by prosím možné to v blízké době implementovat? Obávám se, že bez této funkce nemůžeme lablování aktuálně nasadit.

Díky

**Comment by JanMeritus** [comment]
@pavel-stastny log vypada to takhle, pokud mozno, poprosim o hotfix, jinak to nemuzeme nasadit:

```json
1615830328529 I access 
{
 "date":"2021-03-15T18:45:28.528",
 "session_eppn":"xxx@nkp.cz",
 "rootTitle":"Mladý svět: týdeník",
 "dcTitle":"7",
 "pid":"uuid:8cbcb170-c994-11e9-99c2-005056825209",
 "rootPid":"uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c",
 "type":"validuser",
 "models_path":["periodical/periodicalvolume/periodicalitem/page"],
 "rootModel":"periodical",
 "providedByDnnt":true,
 "dnnt_user":"",
 "publishers":["Mladý svět","Mladá fronta","FTV Premiéra","Mladý svět, a.s."],
 "publishedDate":"2005",
 "pids_path":["uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c/uuid:1508c630-be92-11e9-8fdf-005056827e52/uuid:f0422930-c982-11e9-b24b-5ef3fc9ae867/uuid:8cbcb170-c994-11e9-99c2-005056825209"],
 "solrDate":"2005",
 "remoteAddr":"X.X.X.X",
 "username":"xxx@nkp.cz",
 "dnnt":true,
 "policy":"private"
}
```

**Comment by pavel-stastny** [comment]
@JanMeritus @jahhoo A je možno ještě přihodit výpis z API ? (/search/api/v5.0/item/uuid:8cbcb170-c994-11e9-99c2-005056825209) ?

**Comment by jahhoo** [comment]
V api je to správně:

```json 
{"dnnt-labels":["covid", "dnnto"],
"datanode":true,
"pid":"uuid:8cbcb170-c994-11e9-99c2-005056825209",
"handle":{"href":"http://127.0.0.1:8080/search/handle/uuid:8cbcb170-c994-11e9-99c2-005056825209"},
"zoom":{"type":"zoomify",
"url":"http://127.0.0.1:8080/search/zoomify/uuid:8cbcb170-c994-11e9-99c2-005056825209"},
"title":"7",
"iiif":"http://127.0.0.1:8080/search/iiif/uuid:8cbcb170-c994-11e9-99c2-005056825209",
"context":[[{"pid":"uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c",
"model":"periodical"},
{"pid":"uuid:1508c630-be92-11e9-8fdf-005056827e52",
"model":"periodicalvolume"},
{"pid":"uuid:f0422930-c982-11e9-b24b-5ef3fc9ae867",
"model":"periodicalitem"},
{"pid":"uuid:8cbcb170-c994-11e9-99c2-005056825209",
"model":"page"}]],
"model":"page",
"details":{"type":"NormalPage",
"pagenumber":"7 \n                        "},
"root_title":"Mladý svět: týdeník",
"root_pid":"uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c",
"policy":"private",
"dnnt":true}
```

**Comment by pavel-stastny** [comment]
@jahhoo  Ne, ne... dnnt-labels řiká, které všechny labels jsou na titul navázány.  Pokud je poskytnutý v režimu dnnt měl by mít `"providedByDnnt":true` a pokud byl navíc poskytnut podle určiteho labelu, tak by měl mít ještě klíč `"providedByLabel":"dnnto"`. 

Z toho api jsem chtěl právě zjistit, jestli mu to náhodou nebylo poskytnuto jenom podle toho příznaku dnnt. (To je to původní pravidlo - bez labels)

**Comment by JanMeritus** [comment]
@jahhoo prosim o overeni jestli to ty labely vypisuje nebo ne do pole `providedByLabel`

**Comment by jahhoo** [comment]
Omlouvám se, dal jsem výpis api přímo ze serveru, nikoliv přes proxy.. ProvidedByDnnt tady je, ale providedByLabel chybí.
Přístup z proxy je nastavený jako "DNNT příznak kombinovaný s IP filtrem", jsou povoleny na zobrazení labely covid a dnnto.

```json
{"dnnt-labels":["covid","dnnto"],
"datanode":true,
"pid":"uuid:8cbcb170-c994-11e9-99c2-005056825209",
"handle":{"href":"http://kramerius5.nkp.cz,
 kramerius5.nkp.cz/search/handle/uuid:8cbcb170-c994-11e9-99c2-005056825209"},
"zoom":{"type":"zoomify",
"url":"http://kramerius5.nkp.cz,
 kramerius5.nkp.cz/search/zoomify/uuid:8cbcb170-c994-11e9-99c2-005056825209"},
"title":"7",
"iiif":"http://kramerius5.nkp.cz,
 kramerius5.nkp.cz/search/iiif/uuid:8cbcb170-c994-11e9-99c2-005056825209",
"providedByDnnt":true,
"context":[[{"pid":"uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c",
"model":"periodical"},
{"pid":"uuid:1508c630-be92-11e9-8fdf-005056827e52",
"model":"periodicalvolume"},
{"pid":"uuid:f0422930-c982-11e9-b24b-5ef3fc9ae867",
"model":"periodicalitem"},
{"pid":"uuid:8cbcb170-c994-11e9-99c2-005056825209",
"model":"page"}]],
"model":"page",
"details":{"type":"NormalPage",
"pagenumber":"7 \n                        "},
"root_title":"Mladý svět: týdeník",
"root_pid":"uuid:9a032970-1c99-11e4-a8ab-001018b5eb5c",
"policy":"private",
"dnnt":true}```

**Comment by JanMeritus** [comment]
@pavel-stastny je poskytovani labelu `providedByLabel` soucasti releasu? nebo chybi mu nejake nastaveni aby zacali tam byt data?

**Comment by pavel-stastny** [comment]
@JanMeritus Neni to o datech.... tohle je to na cem jsme se domlouvali, dokonce spolu, na telefonu.  API vraci seznam vsech labelu, ktere jsou navazany na titul a v druhem parametru "providedByLabel"  label, podle kterého bylo dílo poskytnuto.    Je to v nastavení práv.  Není někde po cestě právo DNNT flag ?

**Comment by pavel-stastny** [comment]
@jahhoo @JanMeritus Případně, nešlo by poslat screenshot z nastavení práv mailem ?
