### ISSUE TITLE
Nefunguje hledání se symbolem „&“

### ISSUE THREAD

**Issue by dominikmatus** [ceskaexpedice/kramerius#812]
Ahoj,
na ndk.cz mi nefunguje vyhledávání s ampersandem. Načítá se to, ale nic se nestane. Předpokládám, že to bude globální problém Krameria.

**Comment by filak** [comment]
Ahoj, 
jak to přesně myslíš? 

Například tady to funguje:
https://www.digitalniknihovna.cz/nlk/search?q=Pe%C4%8Djak%20%26%20Mohorko

https://www.digitalniknihovna.cz/nlk/search?q=%22Pe%C4%8Djak%20%26%20Mohorko%22

(akorát se to nedá pak prokliknout na PDF - ale to je jiný problém)

**Comment by dominikmatus** [comment]
Ahoj, 
teď už mi to funguje. Ale tehdy když jsem zkoušel hledat cokoli s ampersandem tak to nešlo a musel jsem jej smazat. A jelikož je to speciální symbol, tak mě napadlo, že b to mohl být bug.

**Comment by filak** [comment]
Dej sem prosím nějaké odkazy/příklady

**Comment by dominikmatus** [comment]
![pageshot of 'Zpr va o sv tov v stav v Chicagu 1893 N rodn digit ln knihovna Digit ln knihovna Kramerius' @ 2021-04-20-1304'38](https://user-images.githubusercontent.com/4519621/115385913-02177900-a1d9-11eb-9662-3ebdd1031161.png)

**Comment by JanMeritus** [comment]
@jahhoo FYI, pro @dominikmatus pokud jde o chybu na NDK a zda se ze je to jenom NDK, prosim hlasit na https://github.com/NLCR/ndk-supp

**Comment by filak** [comment]
To je asi obecné k hledání přes klienta v SOLR...

Mně se zdá, že to hledání s & ve frázi funguje:

https://ndk.cz/search?q=%22Donath%20%26%20Co%22

**Comment by jahhoo** [comment]
@JanMeritus u nás v NDK chybu nevidím. To nezvýraznění **&** se děje ve všech verzích klienta.

**Comment by zabak** [comment]
To výše je jiný problém - k téhle stránce chybí ALTO, je jenom TXT, proto se to nezvýrazní.

Jiná věc je toto: https://k7-test.mzk.cz/mzkk7/view/uuid:4b7a73b0-8dd8-11ea-a354-005056827e51?page=uuid:85d5f59b-4bcf-4993-b56a-cb856b5874e1&fulltext=%22Donath%20&%20Co%22

Tam není & ale vykřičník a přesto se to najde.

**Comment by pavel-stastny** [comment]
@zabak @dominikmatus @filak  Pokud je issue ještě aktuální, poprosím řešit na githubu klienta https://github.com/ceskaexpedice/kramerius-web-client/issues

**Comment by filak** [comment]
Jenom to tady pro úplnost propojím na https://github.com/ceskaexpedice/kramerius-web-client/issues/545
