### ISSUE TITLE
Nový indexer - existuje v novém schématu ekvivalent údaje rok(int) ?

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#813]
Podle dokumentace "Kramerius 7 - popis Solr schématu nového vyhledávacího indexu" není úplně jasné, zda bude v novém indexu existovat nějaký ekvivalent údaje rok (integer) - ten je označený jako zrušený.

Výhodu tohoto údaje vidím zejména v tom, že existuje v objektu typu page, takže je nezávislý na "containeru" a dá se podle něj dobře dobře filtrovat. Také se s ním dají jednoduše dělat vizualizace a grafy různého typu, což v kombinaci s fulltextem dává zajímavé možnosti pro analýzu apod.

````
/search/api/v5.0/search?q=*.*&fq=fedora.model:page AND rok: [1 TO 3000]&fl=rok&rows=0&facet.field=rok&facet=true&facet.mincount=1&facet.sort=asc&facet.limit=500

/search/api/v5.0/search?q=peroutka&fq=fedora.model:page AND rok: [1 TO 3000]&fl=rok&rows=0&facet.field=rok&facet=true&facet.mincount=1&facet.sort=asc&facet.limit=500
````

**Comment by filak** [comment]
Použitelné by zřejmě byly nové údaje date_range_start.year a date_range_end.year - ale ty bohužel v indexačním schématu nemají docValues=True - takže je nelze pro fasety aktuálně použít - viz:

````
https://k7-test.mzk.cz/search/api/client/v6.0/search?q=peroutka&fq=fedora.model:page AND model_path:*page&fl=date_range_start.year&rows=0&facet.field=date_range_start.year&facet=true&facet.mincount=1&facet.sort=asc&facet.limit=500&wt=json
````

**Comment by honza-rychtar** [comment]
`docValues=true` není podmínka pro možnost faset nad polem. 
https://k7-test.mzk.cz/search/api/client/v6.0/search?q=text_ocr:peroutka&fq=model:page&rows=0&facet.field=date_range_start.year&facet=true&facet.mincount=1&facet.sort=index&facet.limit=500
A ano `date_range_start.year` a `date_range_end.year` je obdoba pole `rok` ze starého indexu. Analogicky jsou tam pole pro měsíc a den, které pak budou sloužit např. pro možnost nalezení výtisků z konkrétního data bez ohledu na rok a s případnou odchylkou (21.8 +/- 2 dny).

Nebo třeba fasety přes typ strany, který se teď nově indexuje a který má explicitně `docValues=false`
https://k7-test.mzk.cz/search/api/client/v6.0/search?q=*:*&fq=model:page&rows=0&facet.field=page.type&facet=true&facet.mincount=1&facet.sort=count&facet.limit=500
vypíše všechny výskyty typů stran s četnostmi

**Comment by filak** [comment]
OK, fajn.
