### ISSUE TITLE
adHoc statistics Kram 5: Reexport uziti del pro vykaz a rozuctovani kolektivnich licenci

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#814]
@pavel-stastny prosim o zacleneni do Kram 5.6 (merge) moznost pro admina expost rekonstruovat a exportovat statistiky del poskytovanych v souvislosti s mimoradnou covidovou licenci od 1.2.2021 dle pritomnych informaci v hlavni vetvy krameria do 5.5 vcetne

UC - zavedeni je v souvislosti s provozováním DK s COVID je nutné z aprobované verze generovat interní statistiky počtu užití jednotlivých stránek (idealne jednotlivými přihlášenými uživateli dle (ala Kram 5.46-dnnt az 5.48-dnnt)

- kedze hlavni linie nepracuje s logovanim uzivatelu a nejsou o nich ani informace bude stacit zavest rekonstrukci zbyvajicich dat v souvislosti s konzumaci stranky
- melo by je moznost byt souhrnne vyexportovat z admin rozhrani dle zvolenych dat
- export pro kazdy den v zvolenom pasmu probehne do samostatneho souboru jmenem - instituce.statistics.YYYY-MM-DD 
-formatove by meli byt shodne s plnymi statistikami (ala Kram 5.48-dnnt) (jenom proste pole co nemaj nebudou)
- jednotlive zaznamy obsahuji nezbytne udaje pro rozuctovani kolektivni licence (viz ala https://github.com/ceskaexpedice/kramerius/wiki/Provozován%C3%AD-DK-s-DNNT)
- minimalne:
   -  cas uziti, 
   -  typ  (model path)
   -  PIDy (stranka az vrchny objekt) 
   -  Jmeno autora (z DC)
   -  Rok vydania (idealne standardizovane cislo ala pozadavek na vroceni materialu #800 ) 
   -  Nazev resp. nazvy casti z DC
   -  Nakladatel
   - Uzivatel (pokud je k dispozici) - toto neni nutne
- pokud statistiky obsahuji shibboleti atribut - identifikator eduPersonUniqueId - (tj logy od 5.6 dal s aktivovanym shibbolethem, exportovat v zahashovanem formatu kde uzivatel a instituce budu hashovane via md5 `md5(uzivatelID)@md5(example.org) `)

**Comment by pavel-stastny** [comment]
> pokud statistiky obsahuji shibboleti atribut - identifikator eduPersonUniqueId - (tj logy od 5.6 dal s aktivovanym shibbolethem, exportovat v zahashovanem formatu kde uzivatel a instituce budu hashovane via md5 md5(uzivatelID)@md5(example.org) )

To znamená, že proces bude standardní způsob vykazování i ve verzi 5.6 ?  Ty standardní logy (ty co jsou na filesystému) se používat nebudou ?

**Comment by md5** [comment]
Please stop @-ing me. Thanks!

**Comment by JanMeritus** [comment]
@pavel-stastny logy typu statistics se pouzivat budou dal, ale pokud je 
- system nema k dispozici (tj nejsou vytvoreny) proces by to za dane obdobi mel zrekonstruovat zpetne
- pokud je ma k dispozici pouzit je jako vstup

**Comment by pavel-stastny** [comment]
> pokud je ma k dispozici pouzit je jako vstup

Opps.. to ne.  Ten proces bude standardně pracovat s databází přístupů, pokud by měl kombinovat nebo párovat s tím co rozparsuje z logu, přinese to zbytečné komplikace. 

Pokud bude potřeba tu funkcionalitu zachovat i pro období po nasazení 5.6, tedy potřeba zrekonstruovat logy za určité období i když už měly být k dispozici,  tak bych navrhoval pouze rozšířit databázi o dané atributy (Vidím tam pouze shibboleth atributy a dnnt labels).   Proces by generoval pořád stejné logy jenom od doby nasazení 5.6 by v generovaném výstypu přibyly ty chybějící informace..

**Comment by JanMeritus** [comment]
ok

**Comment by pavel-stastny** [comment]
Popis procesu [zde](https://github.com/ceskaexpedice/kramerius/wiki/DNNT#proces-pro-generov%C3%A1n%C3%AD-p%C5%99%C3%ADstup%C5%AF)
