### ISSUE TITLE
Statistics: Kramerius 7

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#815]
Prosim o zavedeni tvorby statistickych logu (ve stejnem formatu jako 5.48-dnnt a prip. 5.6) do Krameria 7 a moznosti jejich sdileni.

- logy by v pripade nastaveni adminem (pro urcite typy licenci) meli byt cez FileBeat, nebo jinou podobnou technologii posilany do agregacniho Logstashu 
- slo by o vzajemnou autentifikaci endpointu prostrednictvim certifikatu, klicu apod.
- logy by byly zakryptovane
viz napr. https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
- bola by je moznost odesilat na nakonfigurovatelne adresy

**Comment by pavel-stastny** [comment]
V rámci řešení Issue #814 vzniklo API pro poskytování logů. Popis je [zde](https://github.com/ceskaexpedice/kramerius/wiki/DNNT#api-pro-v%C3%BDpis-statistik).   Pro přístup je potřeba mít uživatele s oprávněním `SHOW_STATISTICS`.  

Napojení na filebat / logstash je možno udělat tak, že se v pravidelných intervalech bude z cílových stanic statistiky stahovat.

**Comment by pavel-stastny** [comment]
Proces pro generování logů je součástí distribuce.
