### ISSUE TITLE
API procesů

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#819]
U nejnovějšího Krameria (5.5.0) nefunguje získávání procesů s podmínkou "state" přes API. Vrací jen hodnoty bez parametru.

GET http://xxx.xxx.xxx.xxx/search/api/v4.6/processes?state=FAILED
GET http://xxx.xxx.xxx.xxx/search/api/v4.6/processes?state=KILLED
GET http://xxx.xxx.xxx.xxx/search/api/v4.6/processes?state=PLANNED
atd.

Dále nejde zobrazit procesy od nejnovějšího.

Také nejde vyhledávat dle názvu s UUID.

Toto API je aktuálně naprosto nepoužitelné :( Bylo by prosím možné toto opravit v plánované verzi? @pavel-stastny  @pavelkocourek 

![Snímek z 2021-04-07 15-07-45](https://user-images.githubusercontent.com/33415849/113871539-4ce5c980-97b3-11eb-9de5-1cf9890e9b1f.png)
![Snímek z 2021-04-07 15-08-06](https://user-images.githubusercontent.com/33415849/113871524-49ead900-97b3-11eb-991a-d9166b3a11ca.png)

**Comment by vlahoda** [comment]
V tomto pripade je chyba v nekonzistenci mezi nazvy poli v JSON reprezentaci procesu a parametry filtru, ktere musi odpovidat nazvum poli v databazi - tady konkretne musite misto state pouzit status=FINISHED apod.
Ostatni zminovane funkce (razeni, vyhledavani pres castecnou shodu) myslim toto API nepodporovalo nikdy, v nejblizsi planovane verzi 5.6 to urcite zmenene nebude. Pripadne upravy budou soucasti implementace noveho administratorskeho rozhrani ve verzi 7

**Comment by pavel-stastny** [comment]
Jak již psal Vládˇa. Větší změny mohou přijít až s verzí 7. 

Zatím jsem provedl následující menší změny/opravy: 

1. Měl by fungovat filtr `state` a `batchState`      
2. Řazení dle času naplánování (To již tam bylo dřív)  `&ordering=ASC | DESC`
3. Operátory  > < pro datumové a int pole. Musí být uvozeno mezerou.      `planned=  >  01/28/2021 00:08:19:147`   `planned=  <  01/28/2021 00:08:19:147`

**Comment by jahhoo** [comment]
@pavel-stastny ano, děkuji, uzavírám
