### ISSUE TITLE
Statistics: Nevalidni json

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#820]
Dle recentnich informaci od zpracovatele z DILIE:

- narazili jsme na zasadni problem, data nejsou ve validnim formatu. Konkretne se jedna o :
```
"rootTitle":"Zamrzlá loď kapitána Flinta: Zimní prázdniny hrdinů knih: "Boj o ostrov", "Trosečníci z Vlaštovky" a "Prázdniny na moři"",
```

> Tedy uvozovky jsou zaroven jako dodelovac a zaroven pouzite v textu, coz neni mozne oddelit ( jedna se o souboru statistics/statistics/statistics* )

Prosim o upravu nebo hotfix

**Comment by pavel-stastny** [comment]
Tak to je zvláštní.  Ty logovací informace se necpou přímo do logu a vytváří se JSONObject (`org.jsonJSONObject` z knihovny 
 `org.json:json:20140107`) a ten se vypisuje do logu.  Vyzkoušel jsem si teď u sebe vypsat stejný root Title a to dopadlo dobře.  Kterou verzí krameria byl ten daný log vygenerován?

**Comment by JanMeritus** [comment]
@pavel-stastny muze to byt implementaci tvorby statistics u nas

@jahhoo muzes to overit taky s podporou, jde o logy za prosinec, je to dulezity

**Comment by JanMeritus** [comment]
uzaviram, je to otazka implementace
