### ISSUE TITLE
Označení dokumentů DNNT labelem - chybí ochrana násobného označení

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#821]
Chybí ochrana násobného označení labelem. Dost často se nám stává, že dokument má několikanásobně přidělený třeba štítek "covid"

**Comment by JanMeritus** [comment]
@pavel-stastny resi to uvolnene verze 5.6 ?

**Comment by pavel-stastny** [comment]
@JanMeritus Promiň za pozdní odpověď.  To issue vzniklo až po releasu 5.6.  

@jahhoo Zdvojení labelů v SOLRu nebo ve FOXML ?

**Comment by jahhoo** [comment]
@pavel-stastny v SOLR. Ve FOXML jsem to nezkoumal

**Comment by pavel-stastny** [comment]
Osetreno sub query, u novejsich verzi solru je mozno zaroven povolit konfiguracni promennou: `dnnt.solr.label.distinctsupport=true`, ktera misto prikazu `add`  posila [`add-distinct`](https://solr.apache.org/guide/7_3/updating-parts-of-documents.html#atomic-updates) 

Upozorneni: V posledni verzi Solr 8 je chyba ktera se tyka partial update obecne (tedy i labelu).   Chovani a workaround je popsan zde: 
https://stackoverflow.com/questions/66335803/solr-throws-error-on-partial-update-after-upgrade-to-8-8
