### ISSUE TITLE
Registrace  nezobrazení CAPTCHA kodu

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#823]
Dobry den,
zjistili jsme, ze pokud se nekdo chce zaregistrovat do naseho Krameria (5.5.0), tak se nezobrazuje ve formulari CAPTCHA kod.
Muzete nam prosim poradit, jak problem odstranit?
https://kramerius.svkos.cz/search/

Dekuji

A. Drahotussky

**Comment by vlahoda** [comment]
V Docker image, pouzite ve vasi instalaci, chybi podpora pro X11 a tak se obrazek s textem pro captcha nemuze vygenerovat. Pripravime novy image pro verzi 5.6.0. Diky za upozorneni.

**Comment by Drahotussky** [comment]
Takže v naší verzi s tím nemůžeme nic dělat?
