### ISSUE TITLE
K7 - ověřování přístupnosti/dostupnosti dokumentu

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#829]
Proč se v nové verzi stále ověřuje v klientovi aktuální dostupnost dokumentu GET požadavkem na ImageProperties.xml resp. info.json (v případě PDF to zřejmě bude nějak podobně jako v K5 - /streams/IMG_PREVIEW) a to opakovaně **pro každou stranu** dokumentu ?

Nešlo by to dělat nějak robustněji ? 

Třeba alespoň v jasných případech, kdy je vzhledem k uživateli komplet dokument (nebo svazek, číslo, článek) private, tak už dále zbytečně neověřovat ? 

V K5-API je třeba endpoint /search/api/v5.0/rights (/search/api/v5.0/rights?actions=read&pid=uuid:...), který se ovšem ani v aktuálním web klientovi nevyužívá. 

Existuje nějaká taková metoda v K6 API ?

Stačilo by přece kontrolovat aktuální právo uživatele (read=false) + informaci z indexu (accessibility=private) - a dál už nic neověřovat...

**Comment by zabak** [comment]
@honza-rychtar to je otázka hlavně na tebe, předpokládám

**Comment by filak** [comment]
Samozřejmě by tam měly být nějaké výjimky, např. u monografií pro strany typu obálka, obsah, které mohou být přístupné "navzdory" private labelu.

**Comment by zabak** [comment]
@pavel-stastny @honza-rychtar prosím o vyjádření

**Comment by pavel-stastny** [comment]
@filak No, ověřovat každou stranu zvášť je nutnost. Mohou nastat případy, kdy část celku (z monografie nebo z výtisku) je volná a část chráněná.  A nejde jenom o ty obálky ale třeba i tu již distukovatnou "striktní" licenci. Kdy je potřeba něco dočasně zakázat. (článek, zadní stranu pohlednice, atd.. )

**Comment by filak** [comment]
Těší mě zájem o kabinetní issues :o]

Chápu, že je aktuálně situace složitější vzhledem k zavedení licencí a identit atp.

Každopádně si ale pořád myslím, že je tu prostor pro optimalizaci.

Požadavek na ověření aktuální přístupnosti stránky pro klienta by se snad dal realizovat pomocí metody HEAD na jeden endpoint a to jednotně pro všechny typy streamů. A to bez toho, aby se například získával náhled nebo se parsovala metadata nebo jiné streamy stránky, ke které přístup v danou chvíli nemám, což zbytečně obtěžuje všechny subsystémy.

V případě otevřených licencí by se třeba nemuselo ověřovat vůbec a pokud by se v dokumentu objevila třeba nepřístupná stránka,  tak to má klient ošetřené už teď.

**Comment by honza-rychtar** [comment]
Opravdu je nutné každou stranu ověřit zvlášť (licence na úrovni stran, pravidla na typech stran, striktní licence vylučující strany. ...).

Optimálnější je to dělat až při přístupu k dané straně, ne předem pro všechny strany naráz.

Pokud se kontrola dostupnosti dělá přímo přes přístup k streamu (který je v případě úspěchu využitý), tak je to přece nejoptimálnější řešení.
A) Stream je dostupný 
- pak na straně klienta i jádra je to nejoptimálnější cesta 

B) Stream není dostupný
- pak to jádro vyhodnotí bez přístupu k streamu a zpět na klienta ho nepošle, pošle 403.
- zase je to nejoptimálnější způsob na klientovi i v jádře co se týče zdrojů

K tomu ty http statusy slouží. Mít jeden request a stav rozlišit přes response status. Ne že dopředu ověřím všechny stavy přes různé requesty.

Kde HEAD reaquest smysl dává, je ověření dostupných stran pro účely generování PDF.
Tady klient dopředu neví, které strany jsou uživateli dostupné. To bychom ale chtěli upravit a uživateli při výběru stran vizuálně odlišit nedostupné strany a ani je nenechat vybrat. 
Tady se právě hodí ten HEAD na jednotlivé strany, protože není potřeba ty streamy, jen informaci o dostupnosti jednotlivých stran.

**Comment by filak** [comment]
Tak je otázka, jak se ten přístup ke streamu na straně jádra řeší - zda se nejdřív ověřuje uživ. kontext a licence a podle výsledku se pak buď stream teprve získává, nebo se získává vždycky - pak v případě, že přístup uživatel nemá, tak i zbytečně.

**Comment by honza-rychtar** [comment]
@pavel-stastny potvrď prosím, že jádro u requestu na chráněný stream nejdřív ověřuje práva a že je tedy u nedostupného streamu režie stejná u GET i HEAD jak na straně klienta, tak na straně jádra.

**Comment by filak** [comment]
OK, tak zaviram.
