### ISSUE TITLE
Generování přístupových logů - možnost pouze neveřejné

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#830]
Prosím o přidání zaškrtávacího pole, které vyfiltruje veřejné dokumenty z přístupových logů - uloží do souborů tedy pouze neveřejné.

**Comment by pavel-stastny** [comment]
Do dialogu pridan combobox, ktery umozni generovat logy s viditelnosti : Vsechny, Verejne, Neverejne
