### ISSUE TITLE
Generování přístupových logů - nefunguje filtrování username

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#831]
U generování přístupových logů nefunguje anonymizace pole **username**

![Snímek z 2021-05-17 15-00-00](https://user-images.githubusercontent.com/33415849/118492796-ac26ea00-b720-11eb-9db3-f18c94295e1c.png)

Výstup:
`{"date":"2021-05-17T14:52:45Z","rootTitle":"Mährisch-schlesischer Correspondent","dcTitle":"7","pid":"uuid:d8791f81-75f6-11e6-97fa-001018b5eb5c","rootPid":"uuid:80e1aea0-fa27-11e4-9f08-005056825209","models_path":["periodical/periodicalvolume/periodicalitem/page"],"rootModel":"periodical","providedByDnnt":false,"publishers":["Albin Müller","Albin Müller"],"publishedDate":"2021","pids_path":["uuid:80e1aea0-fa27-11e4-9f08-005056825209/uuid:90024780-68fa-11e6-9f9c-001018b5eb5c/uuid:d10ed720-6936-11e6-abea-5ef3fc9ae867/uuid:d8791f81-75f6-11e6-97fa-001018b5eb5c"],"solrDate":"2021","remoteAddr":"172.16.3.68","username":"7W7pSY6CBfG8uGha0wH+rQ==","dnnt":true,"policy":"public"}`

**Comment by pavel-stastny** [comment]
Nedarilo se mi chybu reprodukovat. (PS: zajimave je, ze v prilozene ukazce je username anonymozovany)
