### ISSUE TITLE
DNNT statistiky - chyba 500

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#834]
Zdravím,

nasadil jsem poslední jádro K5 (5.6.0) na produkční server, kde je relativně velké množství záznamů (~900tis.) v tabulce `statistics_access_log` v databázi `kramerius4`, abych otestoval generování přístupových logů pro účely vyhodnocování statistik přístupů k neveřejným dokumentům.

Spuštěný proces, který data z výše uvedené tabulky "vytahuje", zpracuje a uloží do textového souboru, se při tomto nasazení ukázal jako poměrně nestabilní. Pro některé dny se výstupní log vůbec nevytvoří, protože proces nepěkně  "upadne" se statusem 500 (internal server error). V logu to pak vyhodí `NullPointer` výjimku bez bližšího vysvětlení příčiny pádu.

MD

**Comment by pavel-stastny** [comment]
Reseno komitem 0d45a31eed292e941ebd676c992ebaa845b8f7e1
