### ISSUE TITLE
DNNT statistiky - pomalost

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#835]
Zdravím,

z testování generování logů plyne, že u některých dnů, kdy byl velký traffic (hodně záznamů v databázové tabulce), trvá zpracování opravdu hodně dlouho - zatím jsem dosáhl cca 60 minut na jeden den, kdy výsledný log má objem cca 19MB.

Možná bude potřeba nějaká optimalizace u SQL dotazů...nebo někde jinde...v této chvíli nejasné, možná až to otestuje více správců u velkých instancí Krameria s velkým trafficem.

MD

**Comment by pavel-stastny** [comment]
- Zpusobeno predevsim dotazovanim do Fedory pro informace, ktere nejsou v db (publisher)
- Databazove schema rozsireno o vsechny informace tak, aby se logy generovane ve verzi 5.7 nemusely nadale fedory dotazovat
- Pridana properta `nkp.logs.disablefedoraaccess`, ktera umoznuje zakazat pristup do fedory pri generovani logu.
