### ISSUE TITLE
DNNT statistiky - ISBN, ISSN

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#838]
Prosim o pridani identifikatoru ISBN, ISSN do generovanych + dogenerovavanych statistik

**Comment by pavel-stastny** [comment]
@JanMeritus Zkousel jsem si vylistovat tituly, ktere maji prirazene ISBN ze solru. V celem NKP indexu je jich jenom 113. ISSN ma prirazeno 147317 titulu.   U toho ISBN se jeste navic nezridka objevuji tvary: 

- isbn:(Brož.)
- isbn: Váz.

Co s tím ?

**Comment by pavel-stastny** [comment]
@JanMeritus  Ještě poznámka. V indexu jsou identifikátory z DC ale myslím, že BIBLIO_MODS na tom bude stejně (co se týče issn a isbn).

**Comment by pavel-stastny** [comment]
Do logu a databaze bylo pridano ISSN, ISBN a CCNB
