### ISSUE TITLE
Nutné přihlášení při přístupů z terminálů

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#840]
Možnost nakonfigurovat kombinaci přihlášení + povoléných IP adres, aby se zobrazil label (dnntt). Tzn. pokud uživatel nebude přistupovat z povolené IP adresy - daný label nebude přístupný. Stejně tak je nutné, aby byl uživatel přihlášený. Pokud nebude přihlášený a bude na povolené IP adrese - label se mu také nezobrazí.

**Comment by pavel-stastny** [comment]
@jahhoo  https://github.com/ceskaexpedice/kramerius/wiki/DNNT#pr%C3%A1va

**Comment by pavel-stastny** [comment]
Toto bylo mozne jiz od zacatku jenom se driv michaly ip adresy a labels dohromady jako parametry.   Nyni ma label samostatny tab.   Prihlaseni uzivatele je ostreno roli.
