### ISSUE TITLE
Správa uživatelů - Shibboleth uživatelé

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#841]
Ve správě uživatelů vyskakuje mnoho uživatelů "shibboleth_*" - listování v seznamu je tedy nereálné a nemohu v něm najít administrátory Krameria a spravovat je. Aplikace by měla možnost odfiltrovat shibboleth uživatele. Případně možnost vyhledávat dle jména uživatele.

**Comment by vlahoda** [comment]
Uzivatele shibboleth asi v nejake dalsi verzi odfiltrujeme. Ale vyhledavat podle loginu muzete uz ted, vpravo nahore je toto policko: 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/1308698/122050592-e351ef00-cde3-11eb-83a1-d36acfcf96fa.png">

Uzivatele jsou razeni podle loginu a zadanim pocatecniho znaku nebo retezce se seznam posune na prvni zaznam, ktery tim retezcem zacina.

**Comment by jahhoo** [comment]
@vlahoda vyhledávání mého jména mi nefunguje :( - jen refreshne uživatele (vypíše všechny znovu), nevyhodí žádnou chybovou hlášku.

**Comment by vlahoda** [comment]
hledate jmeno nebo login? funguje jen login. zkuste zadat jen prvni pismeno, seznam by mel zacinat od nej.

**Comment by jahhoo** [comment]
Hledám podle loginu. Pokud zadám první písmeno - opět proběhne jen refresh a zobrazí se všechny loginy

**Comment by vlahoda** [comment]
Problem nedokazu reprodukovat. Vyhledavani spolehlive funguje na nekolika instalaci Krameria, ktere mam k dispozici. Mohl byste poslat log Tomcatu z chvile, kdy to vyhledavani spustite?

**Comment by jahhoo** [comment]
![Snímek z 2021-06-15 16-21-09](https://user-images.githubusercontent.com/33415849/122069765-bad2f080-cdf5-11eb-9055-b220f383a21c.png)



```
16:19:01.597 [http-bio-8080-exec-19] DEBUG org.apache.empire.db.DBDatabase - executeQuery successful in 13 ms
TID: [2021-06-15 16:19:01,597] INFO [org.aplikator.server.persistence.empiredb.EmpireDbPersister getRecords] () - executed in 13 ms
16:19:02.368 [http-bio-8080-exec-19] DEBUG o.j.r.core.SynchronousDispatcher - PathInfo: /aplikatorService/getPage/UserView:Users_table
TID: [2021-06-15 16:19:02,368] INFO [org.aplikator.server.persistence.empiredb.EmpireDbPersister getRecords] () - GETPAGE Query: SELECT t1.USER_ID, t1.LOGINNAME, t1.NAME, t1.SURNAME
FROM USER_ENTITY t1
WHERE t1.LOGINNAME>='holomekj'
ORDER BY t1.LOGINNAME
LIMIT 15 OFFSET 15
16:19:02.368 [http-bio-8080-exec-19] DEBUG org.apache.empire.db.DBDatabase - Executing: SELECT t1.USER_ID, t1.LOGINNAME, t1.NAME, t1.SURNAME
FROM USER_ENTITY t1
WHERE t1.LOGINNAME>='holomekj'
ORDER BY t1.LOGINNAME
LIMIT 15 OFFSET 15

```

**Comment by pavel-stastny** [comment]
Shibboleth uzivatele se nyni nedrzi v databazi. Editor zustava beze zmen.  Pro smazani jiz vytvorenych uzivatelu byl pripraven sql script (pro pouziti pres prikaz psql).

**Comment by JanMeritus** [comment]
@pavel-stastny v statistics na FS ostavaji?
