### ISSUE TITLE
Regulacia rychlosti prezerania

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#843]
Kramerius by mal mat mozne regulovat rychlost prezerania jednotlivych stranok. V pripade ze identifikovany uzivatel prezera konzistentne rychlejsie stranky nez jednoducho konfigurovatelna hodnota (x stranok za y sekund) mal by dostat upozornenie (konfigurovatelna hlaska) o zatazi ktoru sposobuje. 

(v pripade ze nadalej bude "notified" uzivatel pokracovat v prezerani, dojde bud zo strany krameria / alebo skriptov k zablokovaniu uzivatela. To uz je ale iny case, tu ide o upozornenie.)

**Comment by zabak** [comment]
Co bys ale konkrétně odchytával? Jedna stránka je buď jeden request, nebo taky spousta požadavků na hromadu dlaždic. Thumbnaily tahané z imageserveru ti vygenerují sérii požadavků na různé stránky najednou... To už je tak na nějaký zcela nezávislý systém (proxy), který bude sedět mezi API Krameria a světem, bude sledovat provoz, vyhodnocovat ho a případně zasáhne. Něco co by případně uvnitř mělo systém strojového učení, který by tu komunikaci vyhodnocoval.

**Comment by JanMeritus** [comment]
@zabak kontrolujeme dle databaze pristupu, ktera rovnez slouzi pro generovani statistik. Zde staci si prozatim definovat horni limit kolik je mozne za 1, 2, nebo 3 hranicni pravidla - x stranek za 1 min, za 5 min, x stranek za 60 min a nasledne vypsat pro uzivatele upozorneni. 

Pripadna blokace se muze resit s tim, nebo externimi skripty se slozitejsimi pravidlami.

**Comment by VerosK** [comment]
FYI: nginx umí rate-limiting podle všecho přímo v základu. [link](https://www.nginx.com/blog/rate-limiting-nginx/)

Při troše dobré vůle je možné ověřovat i pomocí [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) handleru a posílat při přetížení 429 - too many requests.

Neznám implementační detaily, takže neodhadnu do které části aplikace to ověřování/rate zasadit. Pokud budou ale koncoví DK provideři nasazení ze podobné šablony, tak by to mohlo jít postupně nasadit s rozumným úsilím.

**Comment by mduda100871** [comment]
Zdravím,

přispěji také svou "troškou do mlýna". Pokud jsem požadavek uvedený výše dobře pochopil, tak jde primárně o "regulaci" počtu přístupů k plnému obrázku/pdf/něco za jednotku času, kterou by mohl řídit admin.

Pokud ano, tak si myslím, že tím správným místem by mohl být endpoint jádra Krameria, kde sídlí `img` servlet:

https://github.com/ceskaexpedice/kramerius/wiki/Servlety#img

a pak už jen hlídat/filtrovat requesty, kde bude atribut např. `stream=IMG_FULL&action=GETRAW` a na takový request pak aplikovat příslušnou politiku, buď v předřazeném webserveru/proxy, nebo to doimplementovat do jádra Krameria.

MD

**Comment by pavel-stastny** [comment]
@zabak @mduda100871  Je ten požadavek ještě relevantní ?

**Comment by zabak** [comment]
V téhle chvíli to není urgentní, ale nezavíral bych. Dám tam zatím Odloženo.

**Comment by zabak** [comment]
Na poslední schůzce diskutováno řešení cestou zpětného sledování logů, proto zavírám.
