### ISSUE TITLE
5.7.1 - error 500

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#844]
Po upgrade na jednom ze serverů se vyskytl tento problém: 

![Snímek z 2021-06-28 01-30-24](https://user-images.githubusercontent.com/33415849/123562814-5464af80-d7b1-11eb-985a-5607f6732575.png)

Na jiném serveru nám nová verze 5.7.1 funguje bez problémů. Kde by prosím mohl být problém?

**Comment by pavel-stastny** [comment]
@jahhoo Podle hlášky mi to připadá, že neproběhl korektně deploy.  Zkusil bych smazat adresář search  a znovu nadeployovat.

**Comment by jahhoo** [comment]
Díky, smazáno, vyřešeno.
