### ISSUE TITLE
Filtr obálek a obsahů - potíže s nastavením

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#846]
Dobrý den,

zapnul jsem v Kramériovi filtr obálek a obsahů, ale obálky a obsahy jsou stále neveřejné, viz: https://www.digitalniknihovna.cz/mlp/view/uuid:aff69c66-4f3f-4938-828a-cf3201fe3643?page=uuid:b166f31f-90b0-11eb-8861-001b63bd97ba

Stránka má typ "frontCover", takže by se na ni filtr vztahovat měl.

Práva jsou nastavena takto:
![prava](https://user-images.githubusercontent.com/11628774/123637265-19e52c00-d81e-11eb-8aa9-46d79be7bdca.png)

Po přístupu na odkazovaný dokument v logu tomcatu není žádná nová chyba.

V čem by mohl být problém?

**Comment by filak** [comment]
Tak to by nás také zajímalo, jak se dá tohle zprovoznit. Už jsem to nastavil před nějakou dobou, ale nezdá se, že by to mělo nějaký efekt...

**Comment by pavel-stastny** [comment]
@filak @svetlym  Problém bude ve v malém počátečním písmenu.  V pravidle se kontrolují typy začínající velkým písmenem, viz: 
https://github.com/ceskaexpedice/kramerius/blob/master/shared/common/src/main/java/cz/incad/kramerius/security/impl/criteria/CoverAndContentFilter.java#L38 

Provedeme změnu aby pravidlo bylo case insenstive.

**Comment by svetlym** [comment]
Děkuju za opravu, už nám to funguje.

**Comment by filak** [comment]
Je to ale v souladu s AZ v případě např. novin ?
