### ISSUE TITLE
Problém s přihlášením uživatelů - 5.7.1

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#847]
Po aktualizaci na 5.7.1 se nelze přihlásit přes Shibboleth. 
/Shibboleth.sso/Session se zobrazí v pořádku, ale klient nabízí pořád možnost "Přihlásit" (nikoliv možnost odhlásit).

Samozřejmě se nezobrazují povolená díla.

**Comment by kazooo** [comment]
Máme stejný problém i v MZK

**Comment by jahhoo** [comment]
Je potřeba změnit nastavení práv globalních akcí - read - ze seznamu IP adres smazat labely + do pole asociovat label - vybrat požadovaný label.

Před úpravou vrací https://kramerius5.nkp.cz/search/api/v5.0/user - error 500. Po úpravě již vrátí informace o uživateli.

**Comment by pavel-stastny** [comment]
@kazooo a pokud je to nasazeni z dockeru, prosim, zkontroluj zda je image zbuildovany s poslednim komitem f30b12d
