### ISSUE TITLE
Generovani statistik 5.7.1 - data = mix

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#849]
V datech u instanci se znacenim labelu chybi : 
U exportovanych statistik prostrednictvim UI:
- providedByLabel

U internich statistik
 - chybi uzivatelske jmeno@instituce, doslo obcas k jejich vymizeni (?) - v statistikach se objavuji jako `username":"not_logged"`, bez toho neni mozno generovat report kolik unikatnich uzivatelu z ktory instituce navstivilo instanci DK
- zda se ze poskytuje jenom dnnt: false

Generovany zaznam:
`
{"date":"2021-06-28T07:49:00Z","rootTitle":"Bonaparte","isbn":["80-7217-352-9"],"dcTitle":"[1a]","pid":"uuid:bff081d0-ba35-11e3-9d7d-005056827e51","rootPid":"uuid:d7ac0f70-9a22-11e3-a744-005056827e52","models_path":["monograph/page"],"rootModel":"monograph","providedByDnnt":false,"publishers":["Jota"],"ccnb":["cnb001581442"],"pids_path":["uuid:d7ac0f70-9a22-11e3-a744-005056827e52/uuid:bff081d0-ba35-11e3-9d7d-005056827e51"],"publishedDate":"2005","solrDate":"2005","remoteAddr":"k+sC4D0mo3PdARJjxs80IQ==","dnnt":false,"policy":"private","authors":["Barnett, Correlli"]}
`
- navyse pro tento pid neni v DB reprezentace

Zaznam sbirany do ELK - nekruje se s generovanymi zaznamni a ani soupis poli nesedi (zda se ze vynechava export vsechny pole DNNT true)

`1624859334671 I access {"date":"2021-06-28T07:48:54.671","dnnt-labels":"dnnto","session_eppn":"xxx@vse.cz","rootTitle":"Česko-finská konverzace","dcTitle":"68","pid":"uuid:53303dd2-8e1c-42df-9d75-91456ac029ab","rootPid":"uuid:048aaed0-d941-11e9-84ef-005056827e51","type":"validuser","models_path":["monograph/page"],"rootModel":"monograph","providedByDnnt":true,"dnnt_user":"xyzid@vse.cz","publishers":["SPN"],"publishedDate":"1982","pids_path":["uuid:048aaed0-d941-11e9-84ef-005056827e51/uuid:53303dd2-8e1c-42df-9d75-91456ac029ab"],"solrDate":"1982","remoteAddr":"10.5.1.40","username":"_shibboleth__xxx@vse.cz","dnnt":true,"policy":"private","authors":["Kučerová, Hana"]}`

- v generovanych logach chybi data (zakryptovana) pro `session_eppn`, `dnnt_user`, `username`

**Comment by pavel-stastny** [comment]
@JanMeritus Shrnutí o čem jsme se bavili po telefonu. 

Chybějící informace `providedByLabel `, `session_eppn`, `dnnt_user` je způsobeno starší verzí, která hodnoty nezaznamenávala do db.   

`dnnt:false` a `provideByDnnt:false` způsobeno opět null hodnotami v db. 

Po domluvě bude postup následující: 

- Statistiky se rozšíří o pole obsahující všechny labels přiřazené k dílu. Při generování se bude číst záznam z db a pokud bude null, vezme se aktualní stav z indexu.
- Příznak dnnt - pokud je v db null, vezme se aktuální stav z indexu. 
- providedByDnnt - pokud je sloupec false nebo null, je providedByDnnt false

**Comment by pavel-stastny** [comment]
Upraveno dle domluvy. Pro přesnější rozpoznání záznamu přibyly navíc atributy: 

- `missingAttributes`  - Přidává k záznamům generovaným verzí starší než 5.7.0. Obsahuje pole atributů, které nemůže získat. (informace nebyly ukládány a nejsou součástí metadat.   Shibboleth atributy a providedByLabel)

- `runtimeAttributes`  - Přidává k záznamům verzí starší než 5.7.0/1 a obsahuje pole atributů, které nejsou uloženy v db ale jdou získat z fedory / indexu (ISBN, CCNB, publishers, dnnt-labels, atd..)
