### ISSUE TITLE
Výsledky - možnost seřadit podle data přidání dokumentu do DK

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#85]
Bylo by možné u výsledků vyhledávání přidat (k "abecedně" a "podle relevance") ještě možnost seřazení vyhledaných dokumentů podle data přidání do DK?

**Comment by zabak** [comment]
Tohle je vyřešeno v novém klientovi. Myslím si, že by se to mohlo zavřít.
