### ISSUE TITLE
K5.7.1 - není možne otevřit Editor labelů

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#850]
Při pokusu otevřit Editor labelů v konzoli vzníká chyba
```
Uncaught ReferenceError: labelsManager is not defined
    at <anonymous>:1:1
```
a nic se neděje. Kde by prosím mohla byt chyba?

**Comment by pavel-stastny** [comment]
@kazooo když otevřeš konzoli prohlížeče, vidíš nějaké chyby ?

**Comment by kazooo** [comment]
@pavel-stastny Ahoj, chyba je právě v konzoli prohlížeče, v logach nic podezřelého není
