### ISSUE TITLE
Labelování v K7: label pro public - k diskusi

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#852]
Vzhledem  k tomu, jak se rozbíhá používání labelů by se hodilo mít v K7 i label pro public dokumenty. To, že je dokument volný je svým způsobem druh licence. Usnadnilo by to správu licencí umožňujících zpřístupňování obsahu. Teoreticky by se to dalo dotáhnout do extrému a aplikovat i #809 - nemuselo by to nutné být řešeno jako negativní label, ale prostě tak, že by dokument bez labelu byl vyhledatelný jen pro obsahové správce po přihlášení, jinak by vůbec nebyl vidět a k tomu aby byl vyhledatelný (i když bez přístupu) by sloužil label private. Stávající public / private údaje by se pak mohly přestat používat, protože by byly převedeny do labelů.

**Comment by mjtecka** [comment]
Mě dlouhodobě chybí v Krameriovi možnost přidat licenci (zejména nějakou Creative Commons v různých variantách). To labelování mi intiuitivně přijde jako způsob jak by se to dalo vyřešit (ale nevím nemůžu úplně vyloučit, že tam může být nějaký problém, který nevidím ;-)

Ta "public licence" z důvodu že už jde o volné dílo by pak byla jen jednou z množiny volných licencí - z pohledu Krameria volné (=> zobrazení bez omezení), z pohledu uživatele se pak můžou lišit v tom jak je může použít (např. CC-NC může [Kramerius] zobrazit stejně jako volné dílo, ale uživatel ho pak nemůže využít komerčně).

**Comment by honza-rychtar** [comment]
Ano, Public Domain i CC-NC je možné současnými labely/licencemi pokrýt.
Jen ještě musíme dořešit #853 - rozlišit objekty, které mají licenci a které pouze obsahují objekty s licencí (aby se daly vyhledat, filtrovat, vizuálně odlišit a zároveň se na ně nevztahovala licence tak, že by se propagovala na všechny podřazené objekty).

Dál ještě doplníme možnost vybrat ikonu (ne)dostupnosti pro každou licenci.
Teď mají všechny licence oranžový zámek, pokud **nemá** uživatel přístup k licenci a oranžový přeškrtnutý foťák, pokud **má** přístup k licenci.
Takže Public Domain licence by měla prázdnou ikonu - analogie současných public dokumentů bez zámečku.
Creative Commons licence by mohly mít ty jejich standardní ikonky a třeba DNNT online a terminál by se taky nějak rozlišily.

**Comment by zabak** [comment]
Další label by měl být použit pro zpřístupnění vlastních private dokumentů ve vlastní studovně.

**Comment by pavel-stastny** [comment]
Nyní licence `public` - Veřejné dokumenty de AZ,  licence `onsite` - dostupné v prostorách knihovny

**Comment by zabak** [comment]
Vyřešeno, zavírám
