### ISSUE TITLE
Indexace labelů do nadřazených uzlů u periodik a vícesvazků

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#853]
V současnosti funguje nastavování rights labelů tak, že se do nějaké úrovně (root, ročník apod.) dá do rels-ext vazby příslušné labely. Při reindexaci se pak tyto labely uloží do solru do všech podřízených uzlů. Informace o labelech se ale nepřenáší nahoru do root title. Důsledkem je, že pokud má periodikum všechny ročníky s labelem dnnto, ale root title ne, tak se toto periodikum nezobrazí ve fasetách jako dostupné. Potřebujeme proto dosáhnout toho, aby nadřazené uzly měly v Solru uvedeny všechny labely které se pod nimi vyskytují. Tím, že to bude jen v Solru bude zabráněno tomu, aby se při reindexaci nechtěně tyto labely rozšířily na celé periodikum, protože při reindexaci se vychází z rels-ext a pokud tam ten údaj není, tak se shora rozšířit nemůže.

K tomu ještě komentář od @pavel-stastny:
Dnnt-labels v solru je properta, ktera rozhoduje zda se dilo poskytne ci neposkytne podle daneho labelu (pokud jsou splneny vsechny ostatni podminky).  Ta informace v nadrazenem obektu by, podle me,  mela byt jinde. (v nove properte)   

Vyhovovalo by to i vyznamove: Pokud ma dilo label v dnnt-labels je dostupne plne pod lincenci, pokud je v te nove properte: Je dostupne castecne pod licenci (pouze nektera jeho cast). 

Z hlediska indexace a reindexace by to znamenalo, ze indexer vzdy doplni dnnt-labels dolu, a novou propertu smerem nahoru. 

Z hlediska dotazovani: 
Dotaz by byl pres dila ktera maji:

dnnt-labels:mojelicence AND "partial-dnnt-labels:"mojelicence.

**Comment by zabak** [comment]
Ještě doplním: v případě periodika které má alespoň jeden volný ročník by měl být titul graficky i ve fasetách prezentován jako volný.

**Comment by annie-cz** [comment]
O tomto issue jsme se bavili na schůzce kurátorů NK a MZK a vyšlo nám z toho následující:

- labely by se musely sčítat v rámci výsledků vyhledávání // kořen public by musel mít zároveň i label dnnt-o
- viditelnost kořenu by měl být vždy podle nejmírnější licence směrem k uživateli (tj. pokud bude v jednom dokumentu public - dnnt-o a private, zobrazí se na kořeni public)

**Comment by honza-rychtar** [comment]
Problém současného řešení je v tom, že licence z objektu X se při indexaci propisuje do všech podobjektů objektu X. 
Problematická je konkrétně situace, kdy periodikum má ročníky s licencí i bez licence.
V tomto případě se licence nastavuje přímo u ročníku a u těch se při indexaci propíše do všech podobjektů těchto ročníku.
Takto ale není nastavena licence na úrovni periodika a tedy periodikum nezobrazí mezi dostupnými dokumenty (pod licencí), i když obsahuje licenčně dostupné ročníky.
Pokud bychom však nastavili licenci přímo pro periodikum, tak se při indexaci propíše licence do všech ročníku, tedy i těch které do licence nespadají.

Takže nejde o to, jak to propsat nahoru ani jak to to použít a zobrazit na klientovi, ale jak odlišit dva různé příznaky licence
1. Objekt i má licenci a tedy i na všechny jeho podobjekty se vztahuje tato licence (důležité pro vyhodnocení přístupu)
2. Objekt obsahuje něco, co má licenci a je ho takto potřeba vyhledat/filtrovat/zobrazit (důležité pro filtrování a zámečky)

S @pavel-stastny jsme se domlouvali, že uděláme dvě pole pro licence pro ty dva případy výše. První případ zůstává stejný a druhý případ se použije pro propsání licence směrem nahoru (zatím stačí jen pro ročníky směrem do periodika). 
Klient se pak bude ptát na obě pole.

**Comment by JanMeritus** [comment]
@honza-rychtar toto reseni se mi libi

**Comment by pavel-stastny** [comment]
@zabak @honza-rychtar Již řešeno pro K5 i pro K7.  V K5 je informace držena v poli [contains-dnnt-labels](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/installation/solr-7.x/kramerius/conf/managed-schema#L562).  V K7 pak [contains_licenses](https://github.com/ceskaexpedice/kramerius/blob/master/installation/solr-7.x/search/conf/managed-schema#L684)

**Comment by zabak** [comment]
@pavel-stastny v K5 od které verze?

**Comment by pavel-stastny** [comment]
@zabak Je to komit z minulého roku 1d2eb841cb16363af47327ac73ef8a312531f62d.  Verze to je až ta poslední 5.8.0
