### ISSUE TITLE
K 5.5.0 - nemožnost nastavení práva čtení u knihy

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#854]
Dobrý den,
potřebujeme u jedné větší knihy (přes 700 stran) nastavit podmínku v Zobrazení práv - read. 
Okno ale ani po nekolika hodinach nenabehně. Stale se jen ukazuje Vyckejte prosim. 
U mensich knih tento problem neni, 
Mame nekde spatne nastavenou velikost, pameti, uloziste?

Dekuji za pomoc

**Comment by pavel-stastny** [comment]
Dobry den, 

tam nehraje roli velikost knihy. Zkuste se podivat do konzole prohlizece, jestli tam nevybehla nejaka chyba.

**Comment by Drahotussky** [comment]
Ve správě administrátorských procesu zadne hlaseni neni, pokud tim myslite konzoli prohlizece.

**Comment by pavel-stastny** [comment]
@Drahotussky  Dobrý den, důvodem je zařazení díla do sbírky, která neexistuje ve Fedoře. V novějších verzích krameria je tato situace již ošetřena. Pomůže upgrade na novější verzi nebo vyřazení díla ze sbírky.

**Comment by Drahotussky** [comment]
Problem je, ze ta virtualni sbirka uz neexistuje. Neobjevuje se v administraci virtualnich sbirek. Byla jiz smazana. Ale zobrazena u samotne knihy zustava.
Kdyz dam Odstranit knihu z virtualni sbirky, tak mi to nenabidne moznost vyskrtnout ji.
Da se ta prislusnost k virtualni sbirce odstranit nejak jinak?

Dekuji

**Comment by pavel-stastny** [comment]
@Drahotussky Pomůže upgrade.  Je možné issue uzavřít?
