### ISSUE TITLE
Solr - doplnění konfigurace

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#859]
Zdravím,

1. Bylo by dobré doplnit příslušná pole pro `dnnt` příznaky/značky v indexovacím schématu zde: https://github.com/ceskaexpedice/kramerius/blob/c3c9ad8fce3175ef2175af755cf7d8897b70b593/installation/solr-7.x/kramerius/conf/managed-schema
2. Přidat konfiguraci pro Solr 8 do: https://github.com/ceskaexpedice/kramerius/tree/c3c9ad8fce3175ef2175af755cf7d8897b70b593/installation

MD

**Comment by mduda100871** [comment]
Asi zapadlo...je tam stále jen verze pro řadu 7.x.

MD

**Comment by rzeh4n** [comment]
Aktuální schéma tam tady (pozor na odkaz přes konkrétní starý commit):
[https://github.com/ceskaexpedice/kramerius/tree/master/installation/solr-7.x](https://github.com/ceskaexpedice/kramerius/tree/master/installation/solr-7.x)
Licencí obecně (tj. i dnnt) se týkají pole _licenses_, _contains_licenses_, _licenses_of_ancestors_. Více k licencím [tady](https://github.com/ceskaexpedice/kramerius/wiki/Licence).
Vývoj a testování probíhá na Solr 7. Není vyloučené,, že na Solr 8 něco nebude fungovat podle očekávání.

**Comment by mduda100871** [comment]
A jak to s řadou 8.x vidíte? Protože dle oficiální zprávy je 7.x stále děravá...

https://solr.apache.org/downloads.html

MD

**Comment by honza-rychtar** [comment]
@mduda100871 na testovací instalaci k7.inovatika.dev je od začátku Solr 8.10.0 a všechny změny, na které jsme narazili, jsme  vyladili.

**Comment by mduda100871** [comment]
Dobrá zpráva, takže na novou instalaci K7, kterou připravuji, bych rád nasadil už Solr 8 - to schéma/konfigurace lze tedy použít z verze pro Solr 7, nebo mám čekat až to uvolníte oficiálně pro Solr 8?

Díky, MD

**Comment by honza-rychtar** [comment]
Jo jo, použít to samé.

**Comment by mduda100871** [comment]
OK
