### ISSUE TITLE
Normalizace do SOLR

### ISSUE THREAD

**Issue by MartinRumanek** [ceskaexpedice/kramerius#86]
Rád bych dosáhnul toho, aby například titul Archæologia historica byl dohledatelný alternativně pod názvem Archaeologia historica  - není jednoduché napsat znak æ.

Jedná se o dokument:
http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:d0becc00-3535-11e2-adb0-005056827e52&q=Arch%C3%A6ologia%20historica

Tato funkcionalita je funkční např. v našem VuFindu:
https://vufind.mzk.cz/Search/Results?lookfor=Archaeologia+historica&type=AllFields&submit=Hledat

V něm je to řešené už na úrovni indexace do solru velmi primitivním způsobem (řádek 141, funkce normalize, kterou se můžete inspirovat):
https://github.com/moravianlibrary/RecordManager/blob/master/classes/MetadataUtils.php

**Comment by albertoh** [comment]
Bude vyreseno v ramci prechodu do noveho SOLRu
