### ISSUE TITLE
Popis API K7

### ISSUE THREAD

**Issue by pavelkocourek** [ceskaexpedice/kramerius#861]

**Comment by zabak** [comment]
prostřednictvím openapi

**Comment by pavel-stastny** [comment]
@zabak Dle domluvy, do wiki doplněny obecné informace o [API](https://github.com/ceskaexpedice/kramerius/wiki/Kramerius-REST-API-verze-7.0) a živá dokumentace je vždy v jádře na následujících kontextextech: 

1. <core_url>/search/openapi/client/v7.0/index.html
2. <core_url>/search/openapi/admin/v7.0/index.html
3. <core_url>/search/openapi/exts/v7.0/index.html

  
Přičemž získání definice open api pro administrační rozhraní je chráněno akcí `a_admin_api_specification_read`. Standardně se počítá, že administrační api bude přístupné pouze v lokální síti.
