### ISSUE TITLE
K7 - Lidové noviny - některá čísla (v roč. 1939, 1940) se jeví jako veřejná ačkoliv je ročník neveřejný

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#866]
https://k7-test.mzk.cz/mzkk7/periodical/uuid:23e87270-4ebb-11dd-a91e-000d606f5dc6?accessibility=public

https://k7-test.mzk.cz/mzkk7/periodical/uuid:e62aac60-5323-11dd-9471-000d606f5dc6?accessibility=public

**Comment by zabak** [comment]
@hlavacekrene prosím zkontroluj to

**Comment by filak** [comment]
Zdá se vyřešeno, zavírám...
