### ISSUE TITLE
K7 MZK TEST - srovnání počtu objektů podle MIME typu - kam se poděla PDFka ?

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#867]
K5 (k 24.9.2021)
https://kramerius.mzk.cz/search/api/v5.0/search/?q=*:*&rows=0&facet.field=img_full_mime&facet=true&facet.mincount=1&wt=json

```
"numFound": 62207687,

"img_full_mime": [
"image/jpeg", 60602048,
"application/pdf", 554876,
"image/jp2", 52581,
"image/vnd.djvu", 8519,
"jpeg", 218
]
```

K7
https://k7-test.mzk.cz/search/api/client/v6.0/search?q=*:*&rows=0&facet.field=ds.img_full.mime&facet=true&facet.mincount=1&wt=json

```
"numFound": 60681295,

"ds.img_full.mime": [
"image/jpeg", 59133177,
"image/jp2", 13603,
"application/pdf", 13002,
"jpeg", 218
]
```

PDF **554876** vs **13002**

**Comment by hlavacekrene** [comment]
Většinu pdf máme v periodikách. Jsou to nové ročníky od roku 2007 a pdf-ka tam jsou jakok články - article. Periodika jestě všechna nejsou v K7, hodně jich nešlo v k7 reindexovat, to se musí ještě vyřešit. Takže až budeme mít všechna periodika v k7, tak pak bych to až na konci srovnal.

**Comment by filak** [comment]
OK tak ja to zaviram a vy si to uz pohlidate.
