### ISSUE TITLE
Spouštění update solr/processing na kořenech (všech datových modelů) nebo periodicalvolume, periodicalitem.

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#868]
Občas potřebujeme upravit kořen. přidat stránku (hasPage) nebo přidat jednotku do monografie-vicesvazku (hasUnit), stejně tak upravit volume nebo issue v periodikach.
Novou stránku do-importujeme bez reindexace, pak ručně přepíšeme daný kořen.
Dále pak je zapotřebí spustit update processing index. Nejlépe by bylo, kdyby se automaticky sám spouštěl před search indexem.
Měl by se projít kořen ve foxml v datastreamu rdf, porovnat se solr/processing a provést synchronizaci (nové přidat, již neexistujícíc smazat, osatní ponechat).
Bez této funkce nemůžeme v K7 provádět každodenní rutinní opravy, na které jsme v K5 byli zvyklí.
Samozřejmě můžete toto v budoucnu vyvést do grafické podoby (editace kořenů), ale není to úplně nutné, stačilo by to (spouštění) synchronizace solr/processing.

**Comment by hlavacekrene** [comment]
... s tím ne-míchání máte pravdu. 
Co se týká těch dvou možností na závěr, asi by bylo lepší rozšířit možnosti admin API. Tu drouhou možnost psaní skriptů, které by byly mimo krameria, to si dokážeme postupně zajistit sami (ale to je spíše pro nás zde pracovní a není to použitelné pro všechny, všude).

**Comment by zabak** [comment]
@hlavacekrene je to stále aktuální?

**Comment by hlavacekrene** [comment]
Tohle je vyřešené a používá se to běžně.
