### ISSUE TITLE
Nový label: LICENCE

### ISSUE THREAD

**Issue by annie-cz** [ceskaexpedice/kramerius#869]
Dle dohody kurátorů NK x MZK: Potřebujeme dost urgentně zavést do Krameria label "licence", který bude nasazován na public díla. Je to spíše informativní label pro uživatele, ale i další knihovny (např. R. Zahořík a souborný katalog/SDNNT), že dotyčná knihovna má na něco dojednanou vlastní licenci a zveřejnění takového dokumentu tedy není chybou.

Absence tohoto labelu je nyní dost problematická především v důsledku provozování DNNT, kdy to pak vypadá, že NK a MZK mají nekonzistentní a chybná data.

Navazuje na issue #852

**Comment by JanMeritus** [comment]
@annie-cz label public, private je v teorii mozne zavest jiz ted (a nastavit mu obdobne funkcnosti) - coz prave univerzalni licencni rezimi predpokladaji, predpokladam ale ze kvuli zachovani stavajici funkcnosti si "plne" zavedeni techto labelu vyzada prekopani systemu prav, viz @pavel-stastny

**Comment by zabak** [comment]
@pavel-stastny  Rádi bychom aby se definovalo, že některé licence jsou v Krameriu předdefinované, tj. na každém Krameriu mají dané labely shodné vlastnosti. Díky tomu budou srozumitelné pro někoho, kdo není z dané knihovny nebo pro ČDK. A label vyjadřující nejen, že dané dílo je public, ale že je public na základě nějaké smlouvy a asi jen z nějakého konkrétního krameria. Takové dílo bude asi v SDNNT, ale přitom bude veřejně dostupné, což jinak při kontrolách konzistence dat dělá problémy.

**Comment by honza-rychtar** [comment]
@zabak @annie-cz @zabak Moc nechápu problém. Máte teď někdo problém, který nejde vyřešit přes obecné labely/licence?
@annie-cz píše **urgentně**, @zabak plánuje na 10 kroků dopředu.

@annie-cz to co píšeš je možné přes labely v současném stavu udělat bez zásahu do Krameria

@zabak @JanMeritus licenci **public** a další specifické licence později můžeme vzít a zadrátovat do Krameria, ale ze začátku bych teda doporučoval si je vyzkoušet přes ty obecné licence - je v tom větší flexibilita a taky konkurence (když to bude zkoušet víc Krameriu jinak), což lépe povede k ideálnímu stavu, který se pak může po shodě převzít a použít jako předdefinovaná licence.
