### ISSUE TITLE
K5 - Remote API v5.0 - není možne získat kompletní seznam všech existujících virtuálních sbírek

### ISSUE THREAD

**Issue by kazooo** [ceskaexpedice/kramerius#872]
Dobrý den,

podle [zdrojového kodu](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/virtualcollection/ClientVirtualCollections.java#L147-L181), Kramerius skrz API sbírá seznam virtuálních sbírek za použití [Solr facet](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/common/src/main/java/cz/incad/kramerius/virtualcollections/impl/solr/SolrCollectionManagerImpl.java#L30-L59). Problém nastává když virtuální sbírka aktuálně nemá žadný přiřazený dokument a tím se nedostane do výsledků hledání přes API, i když ve skutečností existuje.

Může Solr implementace [manageru v ClientVirtualCollections.java](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/virtualcollection/ClientVirtualCollections.java#L65-L67) byt nahrazena [implementací pro Fedoru](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/common/src/main/java/cz/incad/kramerius/virtualcollections/impl/fedora/FedoraCollectionsManagerImpl.java)? Nebo něco tomu braní?

Děkuju

**Comment by kazooo** [comment]
Anebo je to zaměřené chování aby webový klient nezískával (a nezobrazoval) sbírky, které nemají pod sebou dokumenty? Jak v tomto připadě dokažu získat všechny sbírky přes API? Nějaké jiné cesty?

**Comment by pavel-stastny** [comment]
@kazooo Ahoj, promiň za pozdní odpověď.  Důvod byl v  resource indexu.  Původní implementace byla neúměrně pomálá při získávání sbírek a musela se nahradit tou SOLrovou.   

Seznam všech sbírek lze získat pouze přes administrátorský resource: [VirtualCollectionsResource.java](https://github.com/ceskaexpedice/kramerius/blob/kramerius5/rest/src/main/java/cz/incad/kramerius/rest/api/k5/admin/vc/VirtualCollectionsResource.java)  ale je potřeba mít admin přístup.

**Comment by pavel-stastny** [comment]
Nové sbírky jsou standardní objekt a lze je v K7 získávat přímo ze search endpointu: 

`https://<k7_instance>/search/api/client/v7.0/search?q=model:collection&wt=xml`

V indexu jsou všechy potřebné informace pro zobrazení.  

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/ca2e1b7c-c1a0-4f5e-804a-2559fb97fc58)


A reprezentativní náhled je vidět zde :

`https://<k7_instance>search/api/client/v7.0/items/<pid_sbirky>/image/thumb`
