### ISSUE TITLE
Sledovat vulnerability v používaných knihovnách např. přes SNYK

### ISSUE THREAD

**Issue by filak** [ceskaexpedice/kramerius#877]
https://app.snyk.io/ (free plan)

... a následně pak upgradovat projekt na novější záplatované verze.

Aktuálně např.:

- Upgrade xalan:xalan@2.7.1 to xalan:xalan@2.7.2
- Upgrade xerces:xercesImpl@2.9.1 to xerces:xercesImpl@2.12.2
- Upgrade commons-fileupload:commons-fileupload@1.3.2 to commons-fileupload:commons-fileupload@1.3.3

**Comment by filak** [comment]
GitHub take upozornuje na (nektere) zastarale knihovny, napr.:

https://github.com/ceskaexpedice/kramerius/pull/770

https://github.com/ceskaexpedice/kramerius/pull/758

- ale nikdo to tady nemerguje...

**Comment by vlahoda** [comment]
aktualizovano
