### ISSUE TITLE
Statisticke logy: Sifrovani instituci

### ISSUE THREAD

**Issue by JanMeritus** [ceskaexpedice/kramerius#879]
V ramci #814 se zavedlo sifrovani uzivatelu a instituci pomoci md5. Dle pozorovani mi prijde ze proces zakazdym pouziva nahodny klic v cehoz dusledku neni mozne generovat statistiky pro materske instituce pristupujicich uzivatelu 

> pokud statistiky obsahuji shibboleti atribut - identifikator eduPersonUniqueId - (tj logy od 5.6 dal s aktivovanym shibbolethem, exportovat v zahashovanem formatu kde uzivatel a instituce budu hashovane via md5 md5(uzivatelID)@md5(example.org) )

- je mozne s tim neco spravit, pripadne proces upravit ? Jde zejmena o to aby se dalo pracovat s logy generovanymi v dlouhych casovych radach konzistentne

**Comment by pavel-stastny** [comment]
@JanMeritus Kdepak, vyuziva se cista md5 bez nahodneho klice.

**Comment by pavel-stastny** [comment]
@JanMeritus Komentář výše.  Jedná se o čisté MD5.  Issue uzavírám
