### ISSUE TITLE
K7 - API nevrací výsledky ve formátu XML

### ISSUE THREAD

**Issue by daliboris** [ceskaexpedice/kramerius#882]
Při volání API (`api/client/v7.0/search`) s hlavičkou `Accept` nastavenou na `application/xml, text/xml` se vrací výsledky pouze ve formátu JSON.

Očekávám odpověď ve formátu dokumentu XML, podobně jako u API v5.

**Comment by honza-rychtar** [comment]
V K7 je výchozí formát JSON. 
Formát jde změnit přes parametr `wt` (`wt=json` nebo `wt=xml`)
Ale hlavička `Accept: application/xml` by měla xml vynutit taky, @rzeh4n koukni na to prosím.

**Comment by daliboris** [comment]
Děkuju za upozornění. Potvrzuju, že při použití parametru `wt=xml` se vrací dokument ve formátu XML.

Uvedené chování (zadání `application/xml` v hlavičce bez parametru `wt=xml`) funguje v API v5.
