### ISSUE TITLE
K7 - doplnění dokumentace na wiki

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#884]
Dobrý den, 

při lokální instalaci K7 jsme v KNAV narazili na některé nedostatky v dokumentaci na wiki, které by asi stálo za to opravit: 

### WIKI - nefunkční odkazy
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#kramerius---core
    * nefunkční odkaz pod slovem "konfigurace": “Pokud je potřeba zvolit jiný název nebo je nutno provozovat solr na jiném portu, je nutno změnit defaultní konfiguraci.”
    * https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/res/configuration.properties#L9
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#kramerius---core
    * nefunkční odkaz pod slovem "kramerius-7.x.y.zip/installation-7.x.y/solr-7.x/kramerius": “Nejdříve je nutno zkopírovat vše z instalačního adresáře kramerius-7.x.y.zip/installation-7.x.y/solr-7.x/kramerius do..”
    * https://github.com/ceskaexpedice/kramerius/tree/akubra/installation/solr-7.x/kramerius
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#processing---core
    * nefunkční odkaz pod slovem "konf. souboru": “Změna portu nebo názvu jádra je opět možná pomocí možná pomocí konf. souboru.”
    * https://github.com/ceskaexpedice/kramerius/blob/akubra/shared/common/src/main/java/res/configuration.properties#L12
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#processing---core
    * nefunkční odkaz pod slovem "kramerius-7.x.y.zip/installation-7.x.y/solr-7.x/processing": “Konf soubory pro jádro processing jsou v instalačním adresáři kramerius-7.x.y.zip/installation-7.x.y/solr-7.x/processing.”
    * https://github.com/ceskaexpedice/kramerius/tree/akubra/installation/solr-7.x/processing/
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#nastaven%C3%AD-single-sign-on
    * Odkaz pod slovem "zde": “Postupujte podle návodu zde”
    * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#autentizace-a-single-sign-on
    * asi spíš https://github.com/ceskaexpedice/kramerius/wiki/Instalace-verze-K5#autentizace-a-single-sign-on nebo https://github.com/ceskaexpedice/kramerius/wiki/Instalace#instalace-autentizace

### WIKI - instalační poznámky
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#kramerius---core
    * release kramerius-7.0.2.zip https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0 neobsahuje složku "kramerius" kramerius-7.0.2/installation-7.0.2/solr-7.x, ale "search"
    * !!! ale verze funguje jen s jádrem search !!!
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#instalace-sd%C3%ADlen%C3%BDch-knihoven
    * “Do adresáře <catalina_home>/libs zkopírujte soubor kramerius-7.x.y.zip/security-core.jar a kramerius-7.x.y.zip/postgresql-42.1.4.jar”
    * !!! je tam složka "lib" !!! 
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#instalace-editoru-u%C5%BEivatel%C5%AF
    * “Soubor kramerius-7.x.y.zip/rightseditor.war zkopírujte do adresáře <catalina_home>/webapps.”
    * Release kramerius-7.0.2.zip  https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0 neobsahuje soubor rightseditor.war
    * https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0.2 tady ale je
  * https://github.com/ceskaexpedice/kramerius/wiki/Instalace#konvertor-form%C3%A1tu-%C3%BAlo%C5%BEi%C5%A1t%C4%9B
    * “Konverzní nástroj je součást distribuce Krameria 7 v souboru migration-7.0.0-beta1.zip..”
    * Release kramerius-7.0.2.zip  https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0 neobsahuje soubor migration-7.0.0-beta1.zip
    * https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0.2 tady ale je "migration-7.0.2.zip"
  * na wiki obecně chybí zmínka, že by se měl instalovat keycloak, admin prostředí...

### WIKI - Keycloack
  * https://github.com/ceskaexpedice/kramerius/wiki/Keycloak/_compare/0c447417fbd31f9da638a26023eba0d44b39ee23...50e4bb7f00a2356940734961ca5efbe255f440dd
    * odstranění info navíc

### Admin prostředí
  * Padá formulář Import Foxml a Import Mets, protože v .kramerius4 chybí složky import, convert, converted-converted

### K7 client
...spíš asi k doplnění do příslušného repozitáře
  * Chybí info o možnostech nastavení globals.js - https://github.com/ceskaexpedice/kramerius-web-client/wiki/Nasazen%C3%AD-klienta
    * schemaVersion, aby se dotazovalo na API 7 musí být nastaveno takto:
schemaVersion: '2.0'
    * v APP_GLOBAL přidat k7:true

**Comment by vlahoda** [comment]
Diky za upozorneni.
Opravil jsem nefunkcni odkazy zminene v prvnim odstavci issue. Odstranil jsem nadbytecne zminky o nastaveni single sign on a editoru uzivatelu, ktere jiz nejsou potreba. 
@kerschfilip : nerozumim uplne poznamce "odstraneni info navic" - wiki stranka Keycloak je myslim spravne, ukazkovy soubor realmu kramerius byl z githubu odstranen na zaklade pozadavku NKP, protoze obsahoval i privatni klice a rpedstavoval tak bezpecnostni riziko.

Ostatni upravy souvisejici s novym indexem a prechodem z jadra kramerius na search jsou asi na @rzeh4n  - diky!

**Comment by rzeh4n** [comment]
Doplnil jsem ty věci ohledně solr. Ještě se podívám na padání admin rozhraní, pokud chybí adresáře "import", "convert" apo.d

**Comment by kerschfilip** [comment]
@vlahoda super, moc díky. Myslím, že tím odstraněným info navíc myslela programátorka, co to u nás instalovala, že [před poslední úpravou stránky o Keycloak](https://github.com/ceskaexpedice/kramerius/wiki/Keycloak/_compare/0c447417fbd31f9da638a26023eba0d44b39ee23...50e4bb7f00a2356940734961ca5efbe255f440dd) tam byly některé užitečné informace, které se jí hodily a po změně tam zůstal jen velmi stručný bod...

**Comment by vlahoda** [comment]
@kerschfilip Myslim, ze toto uz muzeme uzavrit. Ta odstranena cast informaci o Keycloaku uz nebyla platna, ostatni veci doplneny. K chybejicim adresarum pro importy v admin klientu zalozim samostatne issue.
