### ISSUE TITLE
K7 -indexace s parametrem  fromKrameriusModel

### ISSUE THREAD

**Issue by stanislavteplik** [ceskaexpedice/kramerius#885]
Dobrý den, jaký je postup, pokud na K7 chci reindexovat s parametrem fromKrameriusModel? Pokud volám api 4.6, tak mi SOLR vyhodí "undefined field pid_path" což počítám se týká starého schématu. 

Děkuji.

**Comment by rzeh4n** [comment]
Api 4.6 je zastaralé, některé procesy (jako zde reindexace) předpokládají strukturu starého indexu z K5. 
Obecně v K7 používejte nové API v7 https://github.com/ceskaexpedice/kramerius/wiki/API-v7#admin-api

Pro naplánování procesu indexace konkrétně:
`POST /api/admin/v7.0/processes`
a v těle něco jako:
```
{
    "defid": "new_indexer_index_object",
    "params": {
        "type": "TREE_AND_FOSTER_TREES",
        "pid": "uuid:fcf35088-0ea2-4f0d-a2dc-85cef425c91e",
        "title": "Breslau. Rathaus", //nepovinný parametr
        "ignoreInconsistentObjects": true //nepovinný parametr
    }
}
```
Parametr _ignoreInconsistentObjects_ určuje, co má proces udělat, pokud narazí na chybu v datech v Repozitáři - typicky nesoulad mezi daty v Akubře ve FOXML a Processing indexu. Jestli přeskočit chybný objekt a pokračovat dál, nebo ukončit proces s chybou.

Typy indexace jsou:
1. úplná (TREE_AND_FOSTER_TREES, dříve _fromKrameriusModel_), tedy objekt a veškerý jeho obsah
2. jen objekt (OBJECT, dříve _reindexDoc_), čili jen samotný objekt

Je možné, že z optimalizačních důvodů ještě přibudou specifické typy indexací. Ale tohle jsou ty základní.

Pokud nemáte specifický use-case a nepotřebujete volat spouštění procesů přes API, je vhodnější pro (re)indexace použít Administrační rozhraní. Je tam i možnost nahrát seznam pidů z textového souboru a proces je projde a indexuje všechny, pro každý z nich v módu indexace úplná/jen objekt podle vaší volby ve formuláři.

**Comment by stanislavteplik** [comment]
Děkuji za odpověď a konkrétní případ. 

Jde mi hlavně o to, že při mazání z objektů jsem použil api v4.6, jak mi bylo doporučeno v issue 867 (oproti volání delete ve verzi v7 je ukázka dohledatelná pro v4.6). To mi objekt smaže, ale neproběhne následná indexace. Při novém importu objektu je všechno zdvojené s tím, že stará verze je v db nedostupná, existuje pouze v indexu a přetrvá i po úplné reindexaci. Je potřeba provést reindexaci jednotlivých uuid smazaných stránek, a to by u perodik zabralo docela dost času. 

Číslo periodika nemá starou stránku v childs, ale stránka má číslo v parents. Je možné toto opravit, nebo musím rebuildit celý search index?


Děkuji za odpověď.

Příklad : https://kramerius.svkpk.cz/view/uuid:acc4ebb2-fd73-421d-9824-0ae1a797e1b0?page=uuid:429fa245-b4b9-11ec-a03e-001b63bd97ba

**Comment by rzeh4n** [comment]
I pro to mazání doporučuju nové API. Je tam endpoint na mazání konkrétního objektu (z repozitáře i indexu)
`DELETE /api/admin/v7.0/items/{pid}`

Pokud se u některého objektu dostanete do stavu, že foxml je smazáno, v processing indexu ale zůstaly záznamy (1 description, několik relation pro všechny vazby z/na objekt), tak pak je to buď skutečně na celý rebuild processing indexu, nebo ruční promazání těch description a relation záznamů.

Pro vyhledávácí index tam je na smázání jeden záznam per objekt, kromě specifických situací (např. kdyby to bylo pdf).
