### ISSUE TITLE
K5 - zastaralá verze knihovny PDFBox

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#886]
Zdravím,

při testovacím importu NDK dokumentu s PDF nam vypadla následující chybová hláška a importní proces zhavaroval:

![k4test-00](https://user-images.githubusercontent.com/8750622/164002787-b9809e1e-9576-4f73-8d13-052c6fcc7f71.png)

Hledal jsem někoho s podobným problémem, nakonec jsem našel, a "oprava" této chyby spočívala v upgradu na novější verzi knihovny.

Takže jsem stáhl poslední verzi (2.0.25) odtud:

https://pdfbox.apache.org/download.cgi

nainstaloval do rozbaleného jádra Krameria a další opakovaný import téhož NDK balíčku již prošel bez problému.

Otázka teď zní - lze takto "podstrčit" novější verzi knihovny jádru Krameria bez nějakých následků? Je to stejná řada (2.0.x) jako oficiálně použitá (2.0.2) v distribučním jádře K5 .

Pokud ještě vyjde další jádro K5, je možné tam provést i upgrade této knihovny? Jak je na tom jádro K7?

Díky, MD

**Comment by vlahoda** [comment]
Diky za upozorneni. Updatoval jsem tuto zavislost ve vetvi kramerius5 i master, objevi se to v pristim buildu. "Rucni" aktualizace v nainstalovanem jadre by mela byt ok.

**Comment by mduda100871** [comment]
Fajn, díky za rychlou reakci.

MD

**Comment by mduda100871** [comment]
Mezitím vydali zase další verzi 2.0.26.

**Comment by vlahoda** [comment]
aktualizovano
