### ISSUE TITLE
K7 - mazání statistik + obrázky v imageserveru

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#888]
Zdravím,

do jádra K7 a zároveň i do admin rozhraní klienta je potřeba přidat minimálně dvě následující funkčnosti:

1. Možnost promazávat statistiky přístupů v databázi. Možnost spouštět příslušný mazací proces by měla být vázána na přidělení příslušné role, a zároveň by měla být zavedena na úrovni konfigurace jádra properta, která by ani po přidělení role neumožnila mazat data mladší než nastavená hranice (rozlišení by asi stačilo na roky s tím, že např. hodnota  '0' by znamenala neomezené mazání a hodnota větší než '0' by znamenalo povolení mazat pouze data starší než uvedená hranice - to je jen návrh). 
2. Možnost mazat, volitelně, i ve webrootu imageserveru obrázky, pokud na něj jádro K7 "vidí" na souborové úrovni. Globálně by tato funkčnost měla jít aktivovat/deaktivovat na úrovni konfigurace jádra K7 příslušnou propertou. Pokud bude funkčnost globálně povolena, tak by se pak v admin rozhraní (v klientovi) K7 mělo příslušné roli, kterou bude mít uživatel přidělenou, zobrazit "zaškrtávátko", umožňující lokální/dynamické rozhodnutí, zda-li opravdu chci mazat i v imageserveru, nebo nechci. Mazací proces v imageserveru musí zohlednit zároveň využití již zavedené property `convert.imageServerDirectorySubfolders=true` => musí být schopen promazat data rekurzivně.

MD

**Comment by mduda100871** [comment]
Doplnění - mazací proces v imageserveru by měl dle mého názoru mazat nejprve obrázky a teprve potom až metadata.

Pokud by to bylo obráceně, tak hrozí, že při pádu/přerušení procesu ztratím odkazy v datastreamech metadat, kde jsou cesty do webrootu imageserveru a u opravdu velkých objemů dat pak prakticky nebudu schopen ztracené/nesmazané obrázky dohledat a domazat ručně.

Určitě by bylo dobré v každém případě do logu procesu na začátku zalogovat místo/cestu kde se bude mazat.

A zároveň by asi měl být mazací proces nepřerušitelný uživatelem/běžným správcem s rolí mazání z admin rozhraní K7 - ale jen superadminem pro případ zablokované procesu...

MD

**Comment by zabak** [comment]
mazání jp2 je řešeno v #679, tady prosím řešme jen mazání statistik

**Comment by pavel-stastny** [comment]
@zabak @mduda100871 V K7 je již řešeno. Dostupné pod tlačítkem "Promazat statistiky" 

![image](https://github.com/ceskaexpedice/kramerius/assets/675753/72841574-b3b1-4b97-b6d6-ac2eb06d3233)

**Comment by zabak** [comment]
@pavel-stastny cílem bylo mazat ty statistiky v databázi. To co popisuješ maže janom ty vygenerované balíčky s logy, nebo se mýlím?

**Comment by pavel-stastny** [comment]
@zabak Z databáze se logyvpřesunuly do solru a proces maže záznamy v solru.
