### ISSUE TITLE
Import zvukových dokumentů podle nového standardu

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#893]
Prosíme o implementaci importu zvukových dokumentů podle nového standardu.

**Comment by pavel-stastny** [comment]
@svetlym Dobrý den, pro toto existuje již starší issue #671.  Toto uzavřu z důvodu duplicity. Pokud byste měl pocit, že to tak není, tak issue prosím znovu otevřete s vystvětlujícím komentářem.  Díky
