### ISSUE TITLE
K5 proxy

### ISSUE THREAD

**Issue by AndreaBockova** [ceskaexpedice/kramerius#894]
Dobrý den moc prosím o pomoc. Máme K5 na krajských serverech a v nastaveních zadanou ip adresu institucí, kterým se zobrazí všechny dokumenty, včetně těch pod autorským právem. Kraj nám ( po 8 měsících) přehodil Krameria na zabezpečené připojení a rázem se přestaly zobrazovat dokumenty pod autorským právem. Pravděpodobně je to jejich proxy serverem. Po mém dotazu co s tím, mi přišla tato odpověď: 

Všechny požadavky z internetu jdou přes proxy a na webserver Krameria se dostanou všechny požadavky z adresy té proxy, nikoliv z veřejné adresy klienta.Jediná možnost je na proxy nastavit přidání IP adresy klienta do http hlavičky přes X-Forwarded-For – to umíme. To ale musí umět zpracovat webserver na Krameriu.Ověřte zda Kramerius umí zpracovat http hlavičku s parametrem X-Forwarded-For. Jestli ne, tak tato funcionalita už není možná. 
Můžete mi prosím poradit, co s tím? 
Děkuji

**Comment by pavel-stastny** [comment]
@AndreaBockova Hlavicka X-forwared-for by mela byt podporovana. Http proxy bezi na stejnem stroji jako kramerius?

**Comment by AndreaBockova** [comment]
99 % na jiném.

**Comment by pavel-stastny** [comment]
Dobrý den,  mělo by stačit dát do konfigurace následující nastavení:

`x_ip_forwared_enabled_for=<adresa_proxy> `

Pak by měl  být schopen přepbírat hlavičku z dotazu.

**Comment by AndreaBockova** [comment]
Moc děkuji a přeji hezký víkend.

**Comment by AndreaBockova** [comment]
Dobrý den,  nefunguje to.. z IT kraje,  na jehož serverech je náš Kramerius mi napsali: 
je potřeba Kramerius nastavit, aby s tou hlavičkou začal pracovat.
Jestli je již zpracování XFF na Krameriu nastavený a dokumenty se nezobrazí je potřeba kontaktovat vývojáře s tím, že nastavení nefunguje. Můžete mi prosím poradit, jak dál?

**Comment by vlahoda** [comment]
Mate opravdu spravne nastavenou tu property "x_ip_forwared_enabled_for" v .kramerius4/configuration properties? V jejim nazvu v kodu je preklep a chybi tam d, takze se opravdu musi jmenovat takto "chybne"

**Comment by mduda100871** [comment]
Mám dojem, že podobný problém jsem někde vyřešil až tím, že jsem do konfigurace tomcatu přidal nastavení:

`<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="x-forwarded-for"/>`

v

`$CATALINA_BASE/conf/server.xml`

![server-xml-00](https://user-images.githubusercontent.com/8750622/172127423-b45a6920-96d0-48e7-b976-feb7976d5655.png)

MD
