### ISSUE TITLE
Import NDK eMonografie s epubem selhává

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#900]
Zkoušel jsem importovat NDK eMonografii s epubem, kterou jsem vytvořil v ProArcu, ale proces vždy selže. 

Vypadá to, že problém je v konvertoru z NDK balíčku do FOXML. Podle chybové hlášky je chyba v tom, že v elementu datastream, chybí atribut MIMETYPE, takže na tom kolabuje zřejmě XML validátor fedory. Když jsme ten atribut do FOXML ručně doplnili, tak import prošel.

Přikládám výstupy:
[659ee7dd-87d3-4768-943a-fedd01576807_standardni_vystup.txt](https://github.com/ceskaexpedice/kramerius/files/8919795/659ee7dd-87d3-4768-943a-fedd01576807_standardni_vystup.txt)
[659ee7dd-87d3-4768-943a-fedd01576807_chybovy_vystup.txt](https://github.com/ceskaexpedice/kramerius/files/8919796/659ee7dd-87d3-4768-943a-fedd01576807_chybovy_vystup.txt)

Můžu poprosit o úpravu konvertoru? 

Zároveň bylo ještě potřeba do konfigurace Fedory přidat tento novy MIMETYPE, protože ho jinak nezná.

Děkuji, FK

**Comment by kerschfilip** [comment]
v K7 import proběhne v pořádku, ale v klientovi (v2.3.8) se epub nezobrazuje, jen metadata. Při přístupu přes API se k datům dostat dá, takže v Krameriovi to uložené je.   
Admin klient ukazuje, že indexace proběhla v pořádku, fulltextové vyhledávání v klientovi ale nefunguje.

![image](https://user-images.githubusercontent.com/57805328/194100541-f7de9d34-553d-43be-9351-626dd766bdf9.png)

**Comment by honza-rychtar** [comment]
Klient zatím není napojený na Krameria. Testovací epuby se načítaly lokálně.
Jsme domluveni s @pavel-stastny, že si od vás vezme jeden ukázkový balíček s epubem a importuje ho do naši testovací insltalace. Já to pak napojím v klientovi a odzkouším a vydám novou verzi.

**Comment by pavel-stastny** [comment]
@kerschfilip @honza-rychtar https://k7.inovatika.dev/view/uuid:c9b6c867-6d60-4a64-9519-95f5e66ea910

**Comment by kerschfilip** [comment]
znovu jsem to vyzkoušel na jádře 7.0.27 s web-clientem 2.5.0 a epuby se importují i zobrazují.
