### ISSUE TITLE
Zranitelnost Krameria

### ISSUE THREAD

**Issue by petrkukac** [ceskaexpedice/kramerius#906]
Žádám o rychlou odpověď na následující zprávu, která byla zaslána do Národní knihovny.

Zpráva o zranitelnosti systému Národní digitální knihovny (NDK)
Dne 18.9.2022 byla studentem naší školy objevena následující zranitelnost systému NDK, v jejímž důsledku jsou v potenciálním ohrožení všechny neveřejné dokumenty NDK (dokumenty, které jsou volně přístupné pouze na PC v knihovně).
Postup pro replikaci zranitelnosti
1.	Otevřeme stránku neveřejného dokumentu, třeba https://kramerius5.nkp.cz/view/uuid:bbad0370-2da2-11e8-9dd8-005056827e51?page=uuid:84b38770-5856-11e8-983f-005056827e51
2.	Na stránce otevřeme možnosti pro vývojáře, pomocí kterých můžeme v levém panelu najít UUID jednotlivých stránek viz. obr. níže
 
3.	Jednotlivá UUID můžeme dosadit za URL:
https://kramerius5.nkp.cz/pdf/download/?id=
Což nám umožní stáhnout jednotlivé NEVEŘEJNÉ stránky ve formátu JPG
Tato zranitelnost umožňuje útočníkům skriptované stahování neveřejných dat z NDK.

**Comment by vlahoda** [comment]
Toto je problem specificke instalace Krameria v NKP, standardni verze Krameria vubec URL /pdf/download nepodporuje.
