### ISSUE TITLE
K7 - připomínky/problémy/návrhy

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#908]
Zdravím,

založil jsem tuto issue z důvodu potřeby určitého soupisu problémů a poznatků z instalace a konfigurace K7 na "zelené louce", tedy úplně od začátku.

Není to jen o jádře, ale i o admin klientovi a uživatelském klientovi, nicméně založil jsem to "pod jádrem", protože některé záležitosti zřejmě souvisí se všemi komponentami Krameria.

1. Při smazání záznamu v logu procesů neproběhne zároveň i smazání odpovídajícího podadresáře, kde je v souboru uložen standardní a chybový výstup příslušného proběhlého procesu. Jde o adresář `$HOME/.kramerius4/lp/`. Výsledkem je hromadící se počet podadresářů pojmenovaných podle id procesu, takže je to poměrně nepřehledné. Je to jen konfigurační záležitost nebo opravdu chyba?
2. Nepromazává se automaticky podadresář `$HOME/.kramerius4/convert-converted`, takže se tam opět postupně hromadí dočasná data. Běžný subadmin/správce obsahu Krameria o tom samozřejmě neví a ani tam na souborové úrovni nemá přístup, takže by to musel ručně promazávat přímo správce serveru, což je špatně. Stejně jako v bodě 1. je to jen konfigurační záležitost, nebo opravdu chyba?
3. Aktuální release admin klienta nekontroluje validitu/expiraci přiděleného tokenu, takže když tento token vyexpiruje, nedá to uživateli smysluplně vědět a začne se chovat nepředvídatelně/chaoticky. Je to potřeba vyřešit minimálně tak, že při expiraci tokenu automaticky skočí na přihlášení - samozřejmě by bylo lepší, kdyby token obnovoval automaticky, ale to je otázka, zda-li půjde implementovat. V každém případě je výše popsaný problém velice frustrující a matoucí, sám jsem s tím strávil dost času hledáním, než jsem to zjistil.
4. V admin rozhraní po vyvolání volby [Objekt] se objeví pole pro zadání PID objektu nad kterým hodlám provádět nějakou akci, ale 
chybí tam tlačítko pro odeslání formuláře např. myší, funguje jen [enter] tlačítko na klávesnici - velmi matoucí:

![k7-admin-00](https://user-images.githubusercontent.com/8750622/191804725-14823149-0c87-441b-937f-b8f270ec7fc4.png)

5. Nefunguje/zatím není zahrnuto mazání jp2 obrázků z adresáře imageserveru (i s ohledem na propertu `convert.imageServerDirectorySubfolders=true`), takže při smazání NDK dokumentu z Krameria, zůstávají jp2 obrázky na úložišti jako sirotci a zabírají místo - nežádoucí.
6. Stejně tak není zahrnuta do importního formuláře možnost dočasně deaktivovat použití imageserveru - za KNAV tento bod, a předchozí bod 5., implementovala kolegyně, ale zatím to pořád nepropadlo do hlavní větve. Opravdu bychom to potřebovali. Není zahrnuto ani v posledním releasu K5.
7. Problém při načítaní importních podadresářů v případě, že jsou v nich na unixovém filesystému symlinky - nespustí se importní proces. Reportováno vývojářům, v neoficiálním buildu už ošetřeno propertou `io.canonical.file=false`, nicméně by toto mělo být možná ještě podrobeno nějaké diskusi s ohledem na bezpečnost. V KNAV jsou symlinky v importních adresářích využívány z důvodu šetření písmenek disků při mapování importních adresářů jako síťové disky na win stanicích správců obsahu.
8. Neoficiální build (dnešní) už zdá se, že jede bez problému na JDK11.
9. Měli bychom se "odpoutat" v názvech např. filtrů/podmínek od DNNT a zobecnit to prostě na filtrování podle licencí - DNNT je v tomto kontextu jen jedna z řady licencí, je to celkem matoucí, příklad:

![k7-admin-01](https://user-images.githubusercontent.com/8750622/191819565-303564fe-1ad6-44f4-b97a-3201607b0dad.png)

kde chci využít svou licenci "vip", která vůbec nesouvisí s DNNT, ale přesto musím použít podmínku `ReadDNNTLabelsIPFiltered`.

10. Do wiki doplnit všechny zatím nezdokumentované property.
11. Stává se, že nejdou smazat vlastní založené role - admin klient při pokusu o smazání takové role hlásí, že nejde smazat, přestože role u žádné akce nefiguruje. Analýzou se ukázalo, že smazání blokuje navázání na záznamy o proběhlých procesech v databázi, které ale z admin rozhraní není zřejmé/dohledatelné. Nastává deadlock a řešení je zatím pouze nízkoúrovňové, spočívající ve smazaní obsahu souvisejících tabulek v databázi `kramerius4` - nutné vyřešit.
12. Doplnit možnost definovat vlastní/jinou JVM (JAVA_HOME) v konfiguraci procesů v souboru `$HOME/.kramerius4/lp.xml`. V současnosti se forknutý proces spouští s JVM na globální/systémové cestě, což není rozhodně optimální z různých důvodů.
13. Celkem by se hodilo mít možnost pro admin rozhraní nakonfigurovat jiný realm než pro běžné uživatelské rozhraní. Obecně by se asi do budoucna hodila možnost mít podporu pro teoreticky neomezený počet realmů, což by šlo využívat např. pro členění uživatelů z různých organizací/institucí.

Až narazím na něco dalšího, doplním...

**Comment by mduda100871** [comment]
14. V admin klientovi nejde umožnit subAdminům přidat k dokumentu licenci aniž by měli zároveň přiděleno právo prostřednictvím příslušné role k akci `rights_edit`. To bych řekl, že je nežádoucí chování, protože ne vždy chci aby subAdmin měl právo modifikovat (zakládat, mazat atd.) samotné licence. Licence může spravovat nějaký vyhrazený subAdmin a ostatní subAdmini je mohou jen "konzumovat" -> read only, tedy přiřadit je jen k dokumentu a konec.

**Comment by mduda100871** [comment]
Bod 14. v novém neoficiálním buildu je zdá se opraven, jako subAdmin jsem již schopen přiřadit dokumentu licenci aniž bych potřeboval právo k akci `rights_edit`.

**Comment by pavel-stastny** [comment]
@mduda100871 Pro každý bod (nebo skupinu bodů) vytvořím samostatné issue aby se s tím dalo lépe pracovat.

**Comment by pavel-stastny** [comment]
@mduda100871 Je pokryto samostatnými issues, myslím, že můžeme uzavřít.

**Comment by pavel-stastny** [comment]
Bod 2.  K7 / Import METS balčků - po ukončení procesu smazat data z adresáře converted - Issue #1005
