### ISSUE TITLE
Možnost vypnout iip server  při importu

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#915]
Přebráno z #908 od @mduda100871

Stejně tak není zahrnuta do importního formuláře možnost dočasně deaktivovat použití imageserveru - za KNAV tento bod, a předchozí bod 5., implementovala kolegyně, ale zatím to pořád nepropadlo do hlavní větve. Opravdu bychom to potřebovali. Není zahrnuto ani v posledním releasu K5.

**Comment by pavel-stastny** [comment]
řešeno v rámci komitu  d9356bdcfc6cc640cce9804017c5e5451f6b6e9e a d9356bdcfc6cc640cce9804017c5e5451f6b6e9e

**Comment by kerschfilip** [comment]
Otestováno na verzi 1.3.0 - commit: [977fad5](https://github.com/ceskaexpedice/kramerius-admin-client/commit/977fad5), funguje. Moc díky!
