### ISSUE TITLE
K7 - právo Číst a uživatelská role

### ISSUE THREAD

**Issue by stanislavteplik** [ceskaexpedice/kramerius#918]
Dobrý den, 
pokud si do práva Čtení přidám uživatelskou roli a přihlásím se mimo intranet, tak se mi zobrazí plný náhled a mohu generovat pdf (uživatelská role přidána i do Pdf a tisk). Ale při pokusu tisku nebo generování JPG dostanu 403. Všechny možnosti mám v klientovi nastaveny na available a tlačítka nejsou zašedlá, takže mám dojem, že by to mělo jít.

Můžete prosím ověřit, zda se to tak opravdu chová nebo mám někde chybu v právech.

Děkuji.

Kramerius v 7.0.3, client v 2.3.8 a admin v 1.3.0

Teplík

**Comment by pavel-stastny** [comment]
@stanislavteplik Dobrý den, pokud mi můžete poslat (třeba mailem) seznam jak máte nastavena práva, tak to můžu zkusit u nás  nasimulovat.

**Comment by stanislavteplik** [comment]
@pavel-stastny Děkuji, napíšu email.

**Comment by pavel-stastny** [comment]
@stanislavteplik Klient otevírá JPEG v novém okně a jádro tedy neodstane token - neresolvuje uživatele.  Již se to řeší s @honza-rychtar.

**Comment by pavel-stastny** [comment]
Presunto [sem ](https://github.com/ceskaexpedice/kramerius-web-client/issues/649)
