### ISSUE TITLE
úprava zobrazovacích šablon pro tituly dle NDK spec.

### ISSUE THREAD

**Issue by luckajirku** [ceskaexpedice/kramerius#92]
Tituly dle NDK specifikace se v K4 chovají jinak než postaru popsané věci. Bylo by možné upravit šablony tak, aby se tam popis neskládal z DC, ale z MODS? 

Příklady:
Záložka Nejnovější (http://kramerius4.svkhk.cz/search/#intro2): 
-když najedu myší na titul, který má kromě hlavního názvu i podnázev nebo třeba variantní název, tak u těch po staru popsaných se ukáže Název: podnázev (http://kramerius4.svkhk.cz/search/handle/uuid:254c172a-7f3e-49ed-9a77-67ad1b743373), u těch podle NDK jen podnázev/variantní název (http://kramerius4.svkhk.cz/search/handle/uuid:797a088f-6a37-4854-878b-9962190706d8)
- řazení v Nejnovějších – nevím, jestli je to náhoda, ale co jsme zkoušeli, tak na začátek se po importu vždy řadí jen ty tituly, které mají JEN hlavní název. Jak mají i podnázev nebo variantní nebo jiný název, už se řadí tak porůznu, a to i když jde jen o název edice. 

Periodika
- zobrazení vlevo ve stromu:
- titul: u těch, co mají podnázev, dřív ukazoval Název: podnázev, teď jen Název
- ročník: nezobrazuje se pořadové číslo ročníku, pouze rok vydání (u těch dřívějších se ukazoval Rok vydání Číslo ročníku)  
- výtisk: u těch dřívějších byl u výtisku Rok vydání Číslo. U těch nových se ukazuje Název periodika Číslo - ale jen u těch titulů, která mají podnázev nebo variantní název (např. http://kramerius4.svkhk.cz/search/handle/uuid:8a6dc0d5-c2f0-4af0-b24f-8c3ced320e00), tam se u výtisku zobrazí název - Název Číslo. Ale u těch, která mají jen hlavní název (např. http://kramerius4.svkhk.cz/search/handle/uuid:0df929d3-a0ab-4f39-86a2-2985e85e744b), se ten název nezobrazuje, je tam jen Číslo.
- když mám vyplněné datum vydání výtisku, v mods je dateIssued, tady se to nezobrazí (rozdíl u Zpravodaje Klubu sběratelů – postaru http://kramerius4.svkhk.cz/search/handle/uuid:02f05b7b-d695-4a7e-85b9-ff2fd15fbc64 a dle NDK http://kramerius4.svkhk.cz/search/handle/uuid:2bd2a6ab-27b9-4ea5-b033-fda65fec7bb4)
- nad náhledy skenů se spojuje název periodika a číslo, liší se to zas u těch s podnázvem x těch jen s názvem.

u  monografií:
- ve stromu zobrazuje pouze název, ne podnázev  
- v náhledech se u těch, co nemají jen hlavní název, zobrazuje pouze podnázev nebo variantní název

Navigace – typ dokumentu:
- u starších dat se tam zobrazovalo poměrně přehledně pár typů (sice třeba typ „stránka“ je nepoužitelný  a i „interní součást“ je pro uživatele spíš matoucí, ale jinak to bylo pro uživatele přehledné a využitelné). U nových dat, co máme podle NDK specifikace, se nám v typech dokumentů zobrazují třeba i všechny výrazy zřejmě původně z mods:genre authority =>  seznam je dlouhý a nepřehledný.

**Comment by Jenyk** [comment]
Je tahle úprava v dohledné době v plánu? V MZK jsme na to narazili kvůli API: https://github.com/moravianlibrary/kramerius/issues/83

**Comment by LenkaDamborska** [comment]
Jak psala @luckajirku a ostatní, datum vydání čísla se dle NDK specifikace ukládá v poli dateIssued, což se nepropaguje do API. Bude se s tím, prosím, něco dělat? V popisu čísla v Krameriu se zobrazí název titulu a číslo, ale datum ne. Způsobuje to trable ve všech klientech.

**Comment by pavel-stastny** [comment]
Dobry den, 

propagovani pole dateIssued pro modely periodical, periodicalItem a periodicalVolume do indexu a nalsedne do API bylo reseno v ramci komitu:

https://github.com/ceskaexpedice/kramerius/commit/b5f1596e10ff791c6688692ef971f846afd5300

Muzete zkusit reindexovat danou cast periodika?

**Comment by LenkaDamborska** [comment]
Díky za informaci. To je dobrá zpráva. Vyzkoušela jsem ročník a je to tam.
