### ISSUE TITLE
K7 - zobrazování foxml přes API

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#920]
Dobrý den,
chtěl bych se zeptat, jestli plánujete, jestli bude někdy fungovat, tak jako v K5 zobrazování foxml přes API.
V K5, když jsou dokumenty public, tak např. přes 
https://kramerius.mzk.cz/search/api/v5.0/item/uuid:b231a40c-435d-11dd-b505-00145e5790ea/foxml
se foxml zobrazí. 
Když je dokument private, např.
https://kramerius.mzk.cz/search/api/v5.0/item/uuid:3ad6e389-abf6-46f3-bc4c-7e6a55538937/foxml
tak dojde k přesměrování na 403, což je v pořádku, protože dokument může mít vložené ALTO nebo (kdo nemá imageserver) tak i obrázky.
Plánujete v K7 totéž?
https://k7-test.mzk.cz/search/api/v7.0/item/uuid:b231a40c-435d-11dd-b505-00145e5790ea/foxml
Zatím to v K7 vrací v hlavičce 404 Not Found.

**Comment by vlahoda** [comment]
Spravne endpointy jsou : 
https://k7-test.mzk.cz/search/api/client/v7.0/items/uuid:b231a40c-435d-11dd-b505-00145e5790ea/info
https://k7-test.mzk.cz/search/api/client/v7.0/items/uuid:b231a40c-435d-11dd-b505-00145e5790ea/foxml

**Comment by vlahoda** [comment]
na k7-test.mzk.cz jeste neni aktualni verze K7. Je to implementovano teprve asi tyden. Tady to uz funguje:
https://k7.inovatika.dev/search/api/client/v7.0/items/uuid:27e8598c-59d8-11ed-a227-001b63bd97ba/foxml
