### ISSUE TITLE
V K7 klient nezobrazí FOXML

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/kramerius#925]
Např.  https://k7-test.mzk.cz/mzkk7/view/uuid:60447ee0-4f90-11ed-ad9c-5ef3fc9bb22f by mělo být foxml na adrese https://k7-test.mzk.cz/search/api/client/v7.0/items/uuid:96bc21d0-1232-11ed-8dc2-5ef3fc9bb22f/foxml ale kramerius vrací 404

**Comment by vlahoda** [comment]
Opraveno v commitu 4ecb499d7c18f33cc00f7cce97b28dcd4a34ad14 20.10.2022
