### ISSUE TITLE
U nově nastavených DNNT se nezobrazuje lišta

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#927]
Zdravím,

ve verzi jádra 5.8.1 jsme narazili na problém, kdy u dokumentů, kde jsme nově přidali DNNT-O licenci se v klientovi ukazuje pouze ikona DNNT, ale chybí lišta s identifikací uživatele a informace "Zpřístupněno pod licencí" v pravém panelu. 

prosím o opravu, @pavel-stastny

Díky!

**Comment by pavel-stastny** [comment]
Opraveno.  Uzavírám.
