### ISSUE TITLE
K5 - filtr obálek funguje jen pro knihy (model:monograph)

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#930]
Zdravím,

po upgradu jádra K5 na verzi 5.8.2, resp. 5.8.3 nefunguje filtr obálek pro periodika (model:periodical), resp. funguje jen pro knihy (model:monograph).

Příklady

KNAV (5.8.2) / kniha (funguje):
https://kramerius.lib.cas.cz/uuid/uuid:e7ddba6c-2765-4c30-88de-5a49e3ec087f

KNAV (5.8.2) / časopis (nefunguje):
https://kramerius.lib.cas.cz/uuid/uuid:8352fd1e-4e1b-4f16-8525-a26206956e5d

NULK (5.8.3) / kniha (funguje):
https://kramerius.nulk.cz/uuid/uuid:895a4b33-b96a-11eb-8c12-000c29086a30

NULK (5.8.3) / časopis (nefunguje):
https://kramerius.nulk.cz/uuid/uuid:94f6b48b-b96a-11eb-8c12-000c29086a30

Ve zdrojovém kódu třídy `CoverAndContentFilter`, v metodě `isNotPeriodical` dochází k testování, zda-li je vracený model `periodical`, a pokud ano, tak metoda vrací status `EvaluatingResultState.NOT_APPLICABLE` - přidal jsem si tam ladicí hlášky, třídu přeložil, nahrál do ostré instance K5 na server a sledoval odezvy.

![k5-00](https://user-images.githubusercontent.com/8750622/209813736-f4bb9a24-4fb2-475b-a470-da1564ff3782.png)

Rád bych věděl, zda-li je toto chování záměrné (obálky/obsahy časopisů se neposkytují), nebo je to nějaký bug? Případně je to jen nějaká konfigurační záležitost?

Díky,MD

**Comment by pavel-stastny** [comment]
Ahoj, 

jedná se o záměr, resp. o následující pullrequesty:   

https://github.com/ceskaexpedice/kramerius/pull/863
https://github.com/ceskaexpedice/kramerius/pull/864.

**Comment by mduda100871** [comment]
Ahoj,

tak fajn, já jen abych měl v případě potřeby relevantní odpověď.

Diky, MD
