### ISSUE TITLE
Nevytvoření PDF u veřejného periodika

### ISSUE THREAD

**Issue by Drahotussky** [ceskaexpedice/kramerius#931]
Dobrý den, máme verzi Krameria 5.5.0 a narazili jsme na to, že (zatím) u jednoho periodika nelze vygenerovat PDF u veřejných stran. U jiného periodika, monografie to ale jde.
Bohužel zatím v logu cataliny nic nevidim, melo by to byt tam?
Pri snaze stahnout obrazek jako JPG vykočilo toto:
<!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;fcgi-bin&#47;iipsrv.fcgi</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.51</h3></body></html>

Děkuji za pomoc

**Comment by pavel-stastny** [comment]
@Drahotussky Dobrý den.  Z popisu chyby to vypadá, že není správně vyplněná reference na IIP server v FOXML souboru.

**Comment by Drahotussky** [comment]
Jak to můžeme opravit?

Děkuji

**Comment by vlahoda** [comment]
Uz to funguje, tento titul mel jiny format URL do imageserveru, nez ostatni - zrejme nejaky starsi import. Aktualizoval jsem vam take backend Krameria na verzi 5.8.3
