### ISSUE TITLE
Zatuhávání Kraméria

### ISSUE THREAD

**Issue by svetlym** [ceskaexpedice/kramerius#934]
Dobrý den,

Kramérius má tendenci zatuhávat. Tomcat stále běží, ale K4 klient se nenačte a K5 klient nezobrazí žádný data.

Problém je starej několik let, prakticky od doby, kdy jsme K4 poprvé nainstalovali. Stávalo se to ale obvykle nejvýš několikrát za měsíc, v poslední době se to ale výrazně zhoršilo, Kramérius zatuhne občas i několikrát za den.

Zátuh neprovází žádná chyba v logu Tomcatu.

Budeme určitě hledat řešení pro naši instalaci, nehledě na to si ale myslím, že tohle je třeba opravit na úrovni jádra - v případě chyby by ji měl Kramérius zalogovat, nezobrazit případně dokument, u kterýho nastala, ale fungovat dál, nebo přinejhorším ukončit proces, aby mohl zafungovat automatickej restart. Zatuhnutej stav totiž pro čtenáře znamená výpadek služby do chvíle, než si toho někdo všimne a Kramérius restartuje ručně.

PS: Asi by taky bylo fajn zjistit, jestli se tohle stává i u jinejch instalací. Jsem si celkem jistej, že ano (stačí se podívat na sledování výpadků v registru Kramériů), ale nikdy se o tom vlastně pořádně nemluvilo.

**Comment by vlahoda** [comment]
Meli jste neudrzovanou instalaci s chybne nastavenou velikosti pameti.
