### ISSUE TITLE
Update 7.0.3 -> 7.0.14

### ISSUE THREAD

**Issue by stanislavteplik** [ceskaexpedice/kramerius#935]
Dobrý den, 
po updatu na verzi 7.0.14 se mi v Krameriovi nezobrazí jednotlivé stránky, pouze thumbnaily, další problémy jsem nezkoumal a zatím rollbacknul zpět na 7.0.3

Do configuration.properties jsem na začátek přidal požadované nastavení s naším userem a heslem (kontrola dle starého context.xml)

V logu Tomcatu:

`Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class cz.incad.kramerius.processes.database.Kramerius4ConnectionProvider`

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class cz.incad.kramerius.processes.database.Kramerius4ConnectionProvider`

Nějaké nápady, kde může být chyba? Případně co zkontrolovat? Vypadá to právě na nové připojení do databáze.

Postgresql je ve verzi 42.1.4

Děkuji.

Teplík

**Comment by vlahoda** [comment]
Nemate v tomcat/webapps starsi rozbalenou verzi search? Zkusil jsem cistou instalaci buildu 7.0.14 stazeneho z releases, funguje bez problemu.

**Comment by stanislavteplik** [comment]
Smazáno jak ve webapps, tak ve work/Catalina/localhost

**Comment by vlahoda** [comment]
jak vypada cely stacktrace te chyby? a neni jeste nejaka informace v localhost.log? vic vam asi neporadim

**Comment by stanislavteplik** [comment]
Hmm, změnila se minimální verze Javy? Instalaci mám z dob kdy se chtěla 8 a teď je tam 11. Tak to možná bude tím. Odzkouším a dám vědět.

**Comment by stanislavteplik** [comment]
@vlahoda Tak issue můžeme zavřít. Je to opravdu Javou. Kramerius ve verzi 7.0.14 vyžaduje JDK verze 11. Kvůli HikariDataSource, který na nižších neběží.
