### ISSUE TITLE
Kramerius 7 - konfigurace jádra search pro Solr 9

### ISSUE THREAD

**Issue by Sanqui** [ceskaexpedice/kramerius#936]
Zdravím,

Návod na [instalaci verze 7](https://github.com/ceskaexpedice/kramerius/wiki/Instalace) doporučuje použít Solr verze 8.0 a vyšší.  Za využití verze Solr 9 není zřejmé, kterou konfiguraci jádra `search` použít. Instalační návod odkazuje na složku [installation/solr-7.x/search](https://github.com/ceskaexpedice/kramerius/tree/master/installation/solr-7.x/search).  Přidání takového jádra selhá s následující chybou:
`Error CREATEing SolrCore 'search': Unable to create core [search] Caused by: solr.GeoHashField`
Zřejmě proto, že [GeoHashField je deprecated](https://solr.apache.org/docs/8_6_0/solr-core/org/apache/solr/schema/GeoHashField.html).  Ve složce [installation](https://github.com/ceskaexpedice/kramerius/tree/master/installation) existuje také složka [solr-9.x.cloud](https://github.com/ceskaexpedice/kramerius/tree/master/installation/solr-9.x.cloud).  Ačkoliv jméno `.cloud` již naznačuje, že není vhodná pro lokální instalaci Solru, vyzkoušel jsem ji a nelze ji načíst s následující chybou:
`Error CREATEing SolrCore 'search': Unable to create core [search] Caused by: Can't find resource 'schema.xml' in classpath or '/var/solr/data/search'`

Existuje konfigurace vhodná pro verzi Solr 9 (či 8)?  V případě že ne, bude fungovat použít Solr 7, ačkoliv návod doporučuje verzi alespoň 8?  Děkuji.

**Comment by pavel-stastny** [comment]
@Sanqui Dobrý den, doplníme schéma pro solr 9.

**Comment by sczther** [comment]
Dobrý den, nastal ve věci nějaký posun?
Děkuji.

**Comment by pavel-stastny** [comment]
@Sanqui @sczther 

Nastaveni jader pro solr 9 leží zde:  https://github.com/ceskaexpedice/kramerius/tree/master/installation/solr-9.x

**Comment by Sanqui** [comment]
Děkuji, Solr jádro nyní šlo vytvořit.
