### ISSUE TITLE
Rozšíriť K7 API o možnosť zápisu RELS-EXT

### ISSUE THREAD

**Issue by rrandiak** [ceskaexpedice/kramerius#939]
Zdravím,
chceli by sme rozšíriť API call k7 o metódu PUT RELS-EXT.
Viem, že sa s k7 smerujeme k tomu aby táto metóda nebola potrebná a na konkrétne použitia existovali zvlášť procesy, ale momentálne tomu tak nie je a bolo by fajn aby sa dalo RELS upravovať aj iným spôsobom ako reimportom.
Momentálne neexistujú procesy na zmenu donátora a zmenu typu dokumentu a určite sa nájdu aj iné použitia kde by sa táto metóda využila aj v budúcnosti.
Ďakujem.
Róbert Randiak, MZK

**Comment by pavel-stastny** [comment]
Pro potřeby MZK vyřešeno, bude zařazeno do dalšího releasu.

**Comment by pavel-stastny** [comment]
Souvisí s [#1109 ](https://github.com/ceskaexpedice/kramerius/issues/1109 )
