### ISSUE TITLE
Jiny realm pro admina

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#940]
Zkopírováno z #908 

Celkem by se hodilo mít možnost pro admin rozhraní nakonfigurovat jiný realm než pro běžné uživatelské rozhraní. Obecně by se asi do budoucna hodila možnost mít podporu pro teoreticky neomezený počet realmů, což by šlo využívat např. pro členění uživatelů z různých organizací/institucí.

**Comment by zabak** [comment]
Nebude to problém pokud budeme řešit třeba virtuální sbírky v ČDK, kde se možná budou zapojovat lidi z různých knihoven a budou se potřebovat hlásit do admina i web klienta?
