### ISSUE TITLE
Problém s indexací nových dokumentů

### ISSUE THREAD

**Issue by jahhoo** [ceskaexpedice/kramerius#941]
Některé importy z linky padají na batch failed. Po zavolání reindexace vše doběhne v pořádku.

V logu bývá chyba s neexistujícím objektem ve Fedoře - např:

```
SEVERE: Error indexing document uuid:15eac170-537c-11ed-8291-5ef3fc9bb22f
java.lang.Exception: java.lang.Exception: Fedora Object uuid:d7983b56-298a-4c35-9444-248ba119050a not found. 
```

![Snímek obrazovky z 2023-03-08 16-45-26](https://user-images.githubusercontent.com/33415849/223760576-ad736f5a-a957-4c27-bb6f-017b654ac51a.png)

Možná to souvisí s #53 - kde byl "Chybně spuštěný Indexer". - Ale již nikdo nenapsal, jak to řešit :(

**Comment by pavel-stastny** [comment]
@jahhoo Tezko soudit.  Dle screenshotu to vypada, ze import dobehl ale fedora jeste "**neumela**" podat dany objekt. Je realne v lince nastavit ty procesy separatne?  Tedy nejdrive spustit import a az potom naplanovat samosatne indexer  ?

**Comment by pavel-stastny** [comment]
@jahhoo Je stále platně?

**Comment by zabak** [comment]
Řešením je přechod na K7
