### ISSUE TITLE
Mezi distribučními soubory chybí `security-core.jar`

### ISSUE THREAD

**Issue by Sanqui** [ceskaexpedice/kramerius#944]
Zdravím,

[instrukce na instalaci K7](https://github.com/ceskaexpedice/kramerius/wiki/Instalace#instalace-sd%C3%ADlen%C3%BDch-knihoven) předepisují:

>Do adresáře `<catalina_home>/libs` zkopírujte soubor `kramerius-7.x.y.zip/security-core.jar` a `kramerius-7.x.y.zip/postgresql-42.1.4.jar`

Zaprvé je Postgres knihovna v [současné distribuci](https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0.14) (7.0.14) ve verzi `postgresql-42.3.1.jar`.  Větší problém je absence souboru `security-core.jar`.

Našel jsem soubor [security-core/build.gradle](https://github.com/ceskaexpedice/kramerius/blob/master/security/security-core/build.gradle) a pokusil jsem se zbuildit `security-core` sám, ale bohužel moje Java-fu je neostatečné:

```
sanqui@hiyu ~/k/k/s/security-core (master)> /usr/local/gradle/bin/gradle build

Welcome to Gradle 7.0!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/sanqui/kramerius/kramerius/settings.gradle' (/home/sanqui/.gradle/caches/7.0/scripts/56a73b92dc6qacpafutf1kaj8).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

Prosím proto o doplnění `security-core.jar`, nebo o instrukce na zbuildění.

**Comment by vlahoda** [comment]
Diky za upozorneni, opravil jsem instrukce, security-core ani postgresql driver uz neni potreba instalovat zvlast - bylo to tak kvuli single-sign-on, ale to uz s prechodem na OAuth a Keycloak nepouzivame. Staci tedy jen search.war. Omlouvam se za opomenuti.
