### ISSUE TITLE
Solr 9 Cloud - vyhodit lemazační slovníky a upravit konfiguraci

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#950]
- [x] Slovniky pro lematizaci (cs_CZ.* a en_US.*) dělají v solr cloud problém  a nepoužívají se, je třeba je vyhodit
- [x] Konfigurace jader je postavena na starším lucene jadru  `<luceneMatchVersion>6.2.1</luceneMatchVersion>`
- [x] Z konfigurace je třeba vyhodit knihovny, které se nepoužívají

**Comment by pavel-stastny** [comment]
@mduda100871 Pokud jsem na něco zapomněl, tak mě, prosím, doplň.

**Comment by mduda100871** [comment]
Myslím, že na nic jiného jsem už nenarazil.

**Comment by pavel-stastny** [comment]
Při použití sorl cloudu je třeba použít `solrSearch.useCompositeId=true`
