### ISSUE TITLE
K7/ licence -  Proces přidávání licencí nemění příznak indexed 

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#952]

**Comment by pavel-stastny** [comment]
@rzeh4n  U verze indexeru to chápu, u timestampu je to problém.  ČDK nedokáže pak synchronizovat změny v licencích.

**Comment by rzeh4n** [comment]
@pavel-stastny Jasně, chápu. Tak jen jestli se význam pole změní na "timestamp poslední změny" z nynějšího "timestamp poslední úplné indexace", mělo by se to opravit v _cz.incad.kramerius.SetLicenseProcess_ pro přidávání, ale i odebírání licence. 
Pro přidávání do/odebírání ze sbírky to není potřeba měnit. Teda za předpokladu, že se k manipulaci se sbírkami používá stále jen API na _api/admin/v7.0/collections_. Protože tam se následně naplánuje úplná reindexace dotčených objektů.

**Comment by zabak** [comment]
@pavel-stastny je to vyřešené?
