### ISSUE TITLE
Absence možnosti zavřít textový přepis v horní části okna

### ISSUE THREAD

**Issue by jankanka** [ceskaexpedice/kramerius#953]
Okno s textovým přepisem stránky (T) nemá ve své horní části žádnou možnost zavření - musí se odrolovat až zcela dolů, kde je "tlačítko" Zavřít. Ideální by bylo umístit do pravého horního rohu obvyklé X.
Asi by mohlo být okno i užší - reflektovat šíři textového sloupce.
A dolní hrana okna by neměla být zarovnaná s dolní hranou browseru, ale končit spíše kousek nad ním.
![kramerius_textovy_prepis](https://github.com/ceskaexpedice/kramerius/assets/16186956/85b5baf3-7586-4c48-83d3-49f4f85d74c7)

**Comment by pavel-stastny** [comment]
@jankanka Issue jsem přesunul do issues pro klienta.
