### ISSUE TITLE
K5/ Import z NDK METS v Krameriu 5.8 - nezobrazí se formulář

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#955]
Přesunuto z [45](https://github.com/ceskaexpedice/ceska-digitalni-knihovna/issues/45)

Při volbě administrační funkce "Import z NDK METS formátu" se nenačte formulář pro zadání procesu.

Zobrazí se pouze okno s textem

_"Sestavuje se formulář pro spuštění procesu"_

A to zůstane beze změny. Při downgrade na 5.7.2 import funguje.

**Comment by pavel-stastny** [comment]
Dialog se zobrazuje.

**Comment by klodner** [comment]
V 5.8.4.1 stále chyba nastává.

V logu je že nemůže najít template importFedoraStartIndexerNDK.st


> 10-Aug-2023 17:18:38.436 SEVERE [ajp-nio-9009-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [lr] in context with path [/search] threw exception [java.lang.IllegalArgumentException: Can't find template importFedoraStartIndexerNDK.st; context is [form]; group hierarchy is [processes metsimport]] with root cause
>  java.lang.IllegalArgumentException: Can't find template importFedoraStartIndexerNDK.st; context is [form]; group hierarchy is [processes metsimport]

**Comment by pavel-stastny** [comment]
@klodner Je stále aktuální ?

**Comment by klodner** [comment]
Ano, je možné že to nastává ze stejného důvodu jako chyba #1002, tedy nevyhovující verze JDK.

Je možné uzavřít, v případě přetrvávající chyby na podporovaném JDK bych založil nový případ. Děkuji.
