### ISSUE TITLE
Selhává přihlášení do Krameria

### ISSUE THREAD

**Issue by Sanqui** [ceskaexpedice/kramerius#960]
Zdravím,

v současnosti mám již běžící jádro Kramerius a pokouším se přihlásit do adminského rozhraní kramerius-admin.
![image](https://github.com/ceskaexpedice/kramerius/assets/289437/f968212b-be3d-492a-a15f-9f62488e6453)

Po přihlášení se skrz Keycloak mě ovšem admin redirectuje ihned na stránku pro odhlášení.

![image](https://github.com/ceskaexpedice/kramerius/assets/289437/fc4afc9c-b21a-4314-8a7b-95059e915102)

Služby běží na následujících adresách:
```
http://kramerius.hiyu.owlo.sanqui.net:8080 - jádro (tomcat)
http://hiyu.owlo.sanqui.net:8081 - keycloak
http://kramerius-admin.hiyu.owlo.sanqui.net - statický web pro kramerius-admin
```
Toto jsou interní adresy v rámci mé osobní VPN.

Když se podívám v prohlížeči na monitor síťové aktivity, vidím následující transakci:

![image](https://github.com/ceskaexpedice/kramerius/assets/289437/fb142da9-126b-45b6-8541-010924e19098)

V odpovědi na žádost `GET http://kramerius.hiyu.owlo.sanqui.net:8080/search/api/client/v7.0/user/auth/token?code=6d8a685d...` vidím, že Kramerius správně dodá prohlížeči přihlašovácí token:
`{"access_token":"[...]","token_type":"Bearer","not-before-policy":0,"session_state":"39de8a3a-36cc-4151-861d-f96e07fc46bc","scope":"email profile"}`

Ten také prohlížeč správně přidá do headerů při následující transakci:
`GET http://kramerius.hiyu.owlo.sanqui.net:8080/search/api/client/v7.0/user?sessionAttributes=true` má header `Authorization: Bearer [...]`.

Na tuto žádost ale Kramerius odpoví s obsahem `{"uid":"not_logged","authenticated":false,"licenses":[],"session":{},"roles":["common_users"]}`, což má za důsledek to, že kramerius-admin uživatele přesměruje na stránku pro odhlášení.

Příčina mi není jasná.  Přihlašuji se uživatelem `krameriusadmin`, kterému jsem v Keycloaku nastavil roli `kramerius_admin`:
![image](https://github.com/ceskaexpedice/kramerius/assets/289437/b7e6d0de-b93a-410c-8a13-10569257a0db)

V administraci Keycloaku vidím, že pro uživatele `krameriusadmin` vznikl session.

Kramerius vytvořil tabulky v Postgresql databázi, ale v současnosti jsou všechny prázdné s výjimkou `criterium_param_entity`, `dbversions`, `group_entity`, `labels_entity`, `rights_entity`, `rights_criterium_entity` (poznamenávám, že `user_entity` a `session_keys` jsou prázdné).

V logách Krameria (`/usr/share/tomcat/logs/localhost.2023-05-28.log`) se také neobjevuje žádná chyba.

Předem děkuji za pomoc s řešením tohoto problému (pomohlo by vědět jak např. povolit debug logování).

**Comment by vlahoda** [comment]
Diky za podrobny bugreport. Na podobny problem jsme nedavno narazili pri provozu Keycloaku za proxy, ktera nebezela na https, ale http, coz je mozna i tento pripad. Muzete prosim vyzkouset, jestli problem vyresi verze 7.0.25? Pripravil jsem pre-release build na https://github.com/ceskaexpedice/kramerius/releases/tag/v7.0.25 nebo pouzijte image z docker hubu ceskaexpedice.

Debug logovani se ridi nastavenim prislusnych urovni loggeru v souboru `tomcat/conf/logging.properties`. Priklad nastaveni pro debugovani autentizacniho filtru Keycloaku:

```
cz.incad.kramerius.keycloak.level = FINE
org.keycloak.adapters.level = FINE
cz.incad.kramerius.auth.thirdparty.keycloack.level = FINE
```

**Comment by Sanqui** [comment]
Děkuji za odpověď.  Zjistil jsem mezitím, že lze nalézt užitečné logy i v `catalina.2023-05-28.log`.  Tam jsem našel následující chyby:

```
28-May-2023 20:15:58.151 SEVERE [http-nio-8080-exec-4] org.keycloak.adapters.OAuthRequestAuthenticator.resolveCode Adapter requires SSL. Request: http://kramerius.hiyu.owlo.sanqui.net:8080/search/api/client/v7.0/user/auth/token?code=520b9f77-b7a2-47c0-a8e6-d812de5b6090.39de8a3a-36cc-4151-861d-f96e07fc46bc.e18d3f98-e4be-4ac5-b65c-5b7094d9e352&redirect_uri=http://kramerius-admin.hiyu.owlo.sanqui.net/keycloak
28-May-2023 20:31:12.594 WARNING [cz.incad.kramerius.processes.cdk.KeycloakCDKCache-thread] cz.incad.kramerius.processes.cdk.KeycloakCDKCache$KeycloakCDKCacheTask.run Missing attributes: 'cdk.keycloak.url', 'cdk.keycloak.adminuser', 'cdk.keycloak.adminpass' in configuration
```

Můj realm má SSL mode "external requests", což by podle [dokumentace](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/realms/ssl.html) mělo umožnit přístup přes `http` pro lokální adresy (včetně localhost a 10.0.x.x).  Zkusil jsem i tak nastavení přepnout na `none` a upravit `keycloak.json`.  Přihlášení se stále chová stejně, ale již nenastává `SEVERE` chyba se SSL.  Objevuje se jen nové varování:
```
28-May-2023 20:29:06.350 WARNING [cz.incad.kramerius.processes.cdk.KeycloakCDKCache-thread] cz.incad.kramerius.processes.cdk.KeycloakCDKCache$KeycloakCDKCacheTask.run Missing attributes: 'cdk.keycloak.url', 'cdk.keycloak.adminuser', 'cdk.keycloak.adminpass' in configuration
```

Vyzkouším nový release, děkuji.

**Comment by Sanqui** [comment]
Nový release bohužel problém neřeší, ale s `FINE` logováním vidím další potenciálně užitečné informace.

```
28-May-2023 20:48:37.721 FINE [http-nio-8080-exec-4] cz.incad.kramerius.keycloak.KrameriusKeycloakFilter.doFilter Keycloak OIDC Filter
28-May-2023 20:48:37.721 FINE [http-nio-8080-exec-4] org.keycloak.adapters.PreAuthActionsHandler.handleRequest adminRequest http://kramerius.hiyu.owlo.sanqui.net:8080/search/api/client/v7.0/user/auth/token?code=63d5c59a-17c3-4066-8ae3-4ece547950a0.02c13705-0017-403b-acbd-1f672c517292.e18d3f98-e4be-4ac5-b65c-5b7094d9e352&redirect_uri=http://kramerius-admin.hiyu.owlo.sanqui.net/keycloak
28-May-2023 20:48:37.721 FINE [http-nio-8080-exec-4] org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate Authorization header not present
28-May-2023 20:48:37.722 FINE [http-nio-8080-exec-4] org.keycloak.adapters.QueryParameterTokenRequestAuthenticator.authenticate Token is not present in query
28-May-2023 20:48:37.722 FINE [http-nio-8080-exec-4] org.keycloak.adapters.OAuthRequestAuthenticator.authenticate there was a code, resolving
28-May-2023 20:48:37.722 FINE [http-nio-8080-exec-4] org.keycloak.adapters.OAuthRequestAuthenticator.resolveCode checking state cookie for after code
28-May-2023 20:48:37.722 WARNING [http-nio-8080-exec-4] org.keycloak.adapters.OAuthRequestAuthenticator.checkStateCookie No state cookie
28-May-2023 20:48:38.007 FINE [http-nio-8080-exec-5] cz.incad.kramerius.keycloak.KrameriusKeycloakFilter.doFilter Keycloak OIDC Filter
28-May-2023 20:48:38.007 FINE [http-nio-8080-exec-5] org.keycloak.adapters.PreAuthActionsHandler.handleRequest adminRequest http://kramerius.hiyu.owlo.sanqui.net:8080/search/api/client/v7.0/user?sessionAttributes=true
28-May-2023 20:48:38.008 FINE [http-nio-8080-exec-5] org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate Found [1] values in authorization header, selecting the first value for Bearer.
28-May-2023 20:48:38.008 FINE [http-nio-8080-exec-5] org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken Verifying access_token
28-May-2023 20:48:38.059 FINE [http-nio-8080-exec-5] org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest Realm public keys successfully retrieved for client krameriusClient. New kids: [B0OnqOjZagNBDqjcDlrZDZ6RWzkO1Ud5xfqJPHzk7vA]
28-May-2023 20:48:38.061 FINE [http-nio-8080-exec-5] org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken Failed to verify token: Expected audience not available in the token
28-May-2023 20:48:38.061 FINE [http-nio-8080-exec-5] org.keycloak.adapters.RequestAuthenticator.authenticate Bearer FAILED
```
Konrkétně `Failed to verify token: Expected audience not available in the token`.

**Comment by Sanqui** [comment]
Na základě této informace jsem upravil v `keycloak.json` ` verify-token-audience` z `true` na `false` a přihlášení nyní probíhá v pořádku.  Děkuji za asistenci!

**Comment by vlahoda** [comment]
Diky za potvrzeni, je to tedy zrejme opravdu stejna situace, jakou jsem zminoval na zacatku, vcetne te chyby `Expected audience not available in the token.` Pri komunikaci pres https se tento problem neprojevuje.
