### ISSUE TITLE
K7 / Špatné kódovaní znaků v Solru

### ISSUE THREAD

**Issue by SPXcz** [ceskaexpedice/kramerius#968]
České znaky se zobrazují jako otazníky při zobrazení díla v katalogu. Pokud se dílo rozklikne, tak už se v pravém sloupci zobrazují správně.

V MODS i DC jsou české znaky správně zobrazené. Problém je jen v Solru.

Problém jsem zaznamenal na lokálu na verzi 7.0.25 i 7.0.26, i na serveru Honzy Rychtáře.

![image](https://github.com/ceskaexpedice/kramerius/assets/55412542/d7795ad9-9cb0-4153-9860-f5a5bbc15f03)

![image](https://github.com/ceskaexpedice/kramerius/assets/55412542/57ff8701-e3ba-46d1-a607-be0b4b2c32ef)

Verze: 7.0.25+

**Comment by honza-rychtar** [comment]
Prosím odkaz na konkrétní doukument.

**Comment by SPXcz** [comment]
Katalog: http://mzk.kramerius.rychtar.cloud/k7/search
Konkrétní dílo: http://mzk.kramerius.rychtar.cloud/k7/view/uuid:90080e99-d631-439c-bd8e-64b6a793fe37?page=uuid:fe906922-909a-4378-918d-fc50ad258e0a

**Comment by SPXcz** [comment]
Solr: https://k7.inovatika.dev/search/api/client/v7.0/search?q=pid:%22uuid:90080e99-d631-439c-bd8e-64b6a793fe37%22
MODS: https://k7.inovatika.dev/search/api/client/v7.0/items/uuid:90080e99-d631-439c-bd8e-64b6a793fe37/metadata/mods
DC: https://k7.inovatika.dev/search/api/client/v7.0/items/uuid:90080e99-d631-439c-bd8e-64b6a793fe37/metadata/dc

**Comment by pavel-stastny** [comment]
@SPXcz  @honza-rychtar  Máme podezření, že to dělá docker image K7.

**Comment by honza-rychtar** [comment]
Tohle je specifické pro tuhle instalaci. Jinde se to takto nechová. Nejsou to jen názvy, ale všechny hodnotu v solru.

**Comment by SPXcz** [comment]
Jelikož já používám ceskaexpedice/kramerius:7.0.25, tak je to možné

**Comment by vlahoda** [comment]
Je to opravene ve verzi 7.0.27.
(pricina chyby: kontejner bitnami, na kterem je postavena verze 7.0.25 a vyssi, nema defaultni file.encoding UTF-8, takze vsechny procesy vcetne indexeru nemely spravne kodovanou cestinu, nikde)
