### ISSUE TITLE
Endpoint pro epuby

### ISSUE THREAD

**Issue by honza-rychtar** [ceskaexpedice/kramerius#970]
@pavel-stastny jak jsme se domlouvali, přidat endpoint který bude přistupovat ke struktuře obsahuju epubu - zipu.

**Comment by pavel-stastny** [comment]
@honza-rychtar Pokud je `IMG_FULL` typu  `application/epub+zip`, pak je k dispozici endpoint `epub/*` . Jde testovat na pidu 

**uuid:c9b6c867-6d60-4a64-9519-95f5e66ea910**

`curl --verbose https://k7.inovatika.dev/search/api/client/v7.0/items/uuid:c9b6c867-6d60-4a64-9519-95f5e66ea910/epub/OEBPS/content.opf
`
`curl --verbose https://k7.inovatika.dev/search/api/client/v7.0/items/uuid:c9b6c867-6d60-4a64-9519-95f5e66ea910/epub/mimetypes
`

**Comment by honza-rychtar** [comment]
@pavel-stastny s tou prohlížečkou mi to nefunguje. Načte ty základní soubory, ale pak s tím má problém.
Nejspíš to bude chybným mime-typem, resp. content-typem v response
Vše má `Content-Type: application/octet-stream`

Přitom jsou to skoro všechno textové soubory xml, xhtml, html.
Pokud vezmu ten originální epub, rozbalím ho a nahraju obsah na statický server a na něj nasměruju tu prohlížečku, tak to funguje. Tam má ale každý soubor správný content-type.
