### ISSUE TITLE
Upravený skript pro automatické generování DNNT statistik -> NKP

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#975]
Zdravím,

pro účely generování statistik přístupů do K5, které jsou zasílány pravidelně a automatizovaně do NKP, jsem převzal původní skript a z větší části jsem ho upravil - první **beta verze** zde (bash + Debian, vše běží pod uživatelem **kramerius**):

[generateStats.sh.zip](https://github.com/ceskaexpedice/kramerius/files/12003676/generateStats.sh.zip)

```
# chown kramerius. /home/kramerius/bin/generateStats.sh
# chmod 750 /home/krameriu/bin/generateStats.sh
```

Úpravy spočívají zejména v tom, že skript aktivně sám kontroluje zpětně stav příslušného procesu který spustil pomocí volání API K5.

Jsou tak ošetřeny do jisté míry stavy, kdy před procesem mohou být naplánovány nebo v běhu jiné procesy, které než se provedou, tak vyexpiruje interně sám skript (původní skript čeká defaultně 300 sekund).

Aby upravený skript s aktivní kontrolou sám sebe nezacyklil, je tam nastaven samozřejmě deadline (lze měnit -> defaultně je 2 hodiny), po jehož překročení skončí aktivní kontrola stavu příslušného procesu v jádře K5, a skript se sám ukončí bez pokusu kopírovat export do NKP.

Pro toto rozšíření je potřeba do systému doinstalovat utilitu `jq`:

`# apt-get install jq`

V konfigurační sekci skriptu:

![obr-00](https://github.com/ceskaexpedice/kramerius/assets/8750622/b7d8b9f4-0028-43cc-a20e-22775f3a54f5)

je potřeba nastavit příslušné parametry podle konkrétních podmínek nasazení.

Zároveň doporučuji (není podmínkou) při naplánování do cronu využít utility `flock` a `chronic` z balíku `moreutils`:

`# apt-get install moreutils`

a naplánovat automatické spouštěni:

`# crontab -e -u kramerius`

![cron-00](https://github.com/ceskaexpedice/kramerius/assets/8750622/72422145-91b8-4599-a576-54e0b575a9b4)

Kdo má zájem, může otestovat. Vše je samozřejmě na vlastní nebezpečí a bez záruky!

MD

**Comment by zabak** [comment]
Doplnil jsem odkaz na tohle issue do wiki
