### ISSUE TITLE
K5/ Podpora SOLR6 pro Issue 919

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#978]
viz komentář od @mduda100871 k issue #919

**Comment by pavel-stastny** [comment]
@mduda100871 Konfigurace jádra pro solr 6 je [zde ](https://github.com/ceskaexpedice/kramerius/tree/kramerius5/installation/solr-6.x/sdnnt-sync)

**Comment by mduda100871** [comment]
Je tam ještě jeden "drobný" problém.

Po nasazení na naší ostrou instanci Krameria všechno funguje (zatím).

Nicméně po nasazení na testovací instanci Krameria pokus o vyvolání procesu kontroly oproti SDNNT končí chybou (příklad):

![sdnnt-00](https://github.com/ceskaexpedice/kramerius/assets/8750622/a33b19b5-b13c-4e1f-b1e4-6fb9184e64cc)

Jediný rozdíl mezi testovací a ostrou instancí Krameria je v tom, že u ostré instance je mezi jádro Krameria a Solr vložena forward proxy (apache s příslušným modulem http proxy), u testovací není (je to na loopbacku).

U testovací instance jsem tedy pokusně zvedl příslušné buffery u jetty:

![jetty-00](https://github.com/ceskaexpedice/kramerius/assets/8750622/e445e4f5-9e02-4af2-9b39-c3703392186b)

a kontrolní proces byl úspěšně dokončen.

Znamená to tedy, že ta forward proxy u ostré instance to nějak "vyžehlí" (lepší výraz mě teď nenapadá) než request předá do Solru.

MD
