### ISSUE TITLE
K7 Akce čtení, Podmínka Licenses* - nedá sa priradiť licencia

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius#985]
Zdravím,
po niektorom update (neviem presne ktorom), nám nefunguje v admin rozhraní, pridávanie licencií k podmienkam LicensesIPFiltered a Licenses. Testované na admin - verze: 1.4.2 - commit: [geaa9c90](https://github.com/ceskaexpedice/kramerius-admin-client/commit/geaa9c90) a jadro - verze: 7.0.27 - commit: [36371](https://github.com/ceskaexpedice/kramerius/commit/363719fa3171c2d94a87515bf95c595787822fce).
Chyba, ktorá nastáva v jadre je:
`Class cz.incad.kramerius.security.impl.RightCriteriumWrapperImpl has no such attribute: labelAwareCriterium in template context [insertRightCriterium if(criteriumWrapper.criteriumParams)_subtemplate]
java.lang.NoSuchFieldException: labelAwareCriterium`
Prikladám aj celý Kramérius log. [kramerius (1).txt](https://github.com/ceskaexpedice/kramerius/files/12402320/kramerius.1.txt)
Teoreticky to môže byť issue aj na admin klienta, ale nebol som si istý tak to dávam tu.

Róbert MZK

**Comment by pavel-stastny** [comment]
@r2it-git Na problém jsme již narazili. Je řešený commitem https://github.com/ceskaexpedice/kramerius/commit/23a5f439125aefae4d4d554334cec27c44432707

**Comment by r2it-git** [comment]
Funguje, zatváram.
