### ISSUE TITLE
K7 / Chyby v SDNNT implementácií

### ISSUE THREAD

**Issue by r2it-git** [ceskaexpedice/kramerius#991]
Ahoj,
v SDNNT implementácií som našiel dve chyby.
Za prvé podľa admina aj podľa popiskov, by malo change_dnnto_dnntt meniť dnnto na dnntt, tz. remove dnnto a add dnntt. Momentálne je to naopak, ako to vidno aj tu v kóde. (change_dnntt_dnnto je taktiež naopak)

https://github.com/ceskaexpedice/kramerius/blob/d6b941d214182ec59b811ab0a9738ee89b333579/rest/src/main/java/cz/incad/kramerius/rest/apiNew/admin/v70/sync/SDNNTSyncResource.java#L95-L99
A vidno to aj v adminovi, keď má dokument licenciu dnnto v sdnnt a v Kramériu dnntt, tak sa v adminovi zobrazí informácia naopak:
![Screenshot 2023-09-04 at 13-25-20 K7 Admin](https://github.com/ceskaexpedice/kramerius/assets/65346739/f7e75bf6-9262-4881-b25b-884d710e14b4)
[Teorie práva - sdnnt](https://sdnnt.nkp.cz/sdnnt/search?q=oai:aleph-nkp.cz:SKC01-000995958)
[Teorie práva - dk](https://www.digitalniknihovna.cz/mzk/view/uuid:90f6b690-b74d-11e4-a7a2-005056827e51?page=uuid:6be5a690-d949-11e4-b880-005056825209)

Druhá chyba je, že sa pri obidvoch chybách dnnto -> dnntt a dnntt -> dnnto prideľuje záznamu príznak sync_action change_dnnto_dnntt.
https://github.com/ceskaexpedice/kramerius/blob/d6b941d214182ec59b811ab0a9738ee89b333579/processes/sdnnt/src/main/java/cz/inovatika/sdnnt/SDNNTFetch.java#L243-L265

Róbert, MZK - OSDD

**Comment by pavel-stastny** [comment]
Mělo by být opraveno.
