### ISSUE TITLE
K7 / fulltextové vyhledávání u epubů

### ISSUE THREAD

**Issue by kerschfilip** [ceskaexpedice/kramerius#996]
Zdravím, 

u epubů importovaných do K7 se mi nedaří fulltextově vyhledávat. Postup:

- zkopíruju slovo/více slov z epubu, který máme v testovací K7 (k7Admin, 1.4.2 jádro: 7.0.27, klient: 2.5.0)
- vložím zkopírované slovo do vyhledávacího pole
- výsledky vyhledávání neobsahují zmíněný epub

Umí K7 indexovat u epubů fulltext podobně jako u PDF? A pokud ano, dalo by se, prosím, ověřit, jestli tam s tím není nějaký problém?

Děkuji

**Comment by pavel-stastny** [comment]
Opraveno komitem [099b2a2](https://github.com/ceskaexpedice/kramerius/commit/099b2a282bbb1230016b1254c092a99b908b2645).  Bude potřeba reimport balíčků

**Comment by kerschfilip** [comment]
Funguje, díky!
