### ISSUE TITLE
K7 / Podpora více jazyků ve sbírkách

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/kramerius#997]
Ve sbírkách je možno zadat jméno, krátký popis a dlouhý ale popis pouze v češtině nebo v angličtině.   Je nutné podporovat všechny jazyky.

**Comment by rzeh4n** [comment]
Doplnil jsem popis změny ve verzi 18 Indexeru tady:
https://github.com/ceskaexpedice/kramerius/wiki/Vyhled%C3%A1vac%C3%AD-index#verze-18
