### ISSUE TITLE
K7 návrat po přihlášení do stejného místa

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/kramerius#998]
Zdravím,

výše uvedený problém bude souviset i s klientem pravděpodobně.

Komplikace spočívá v tom, že pokud se uživatel přihlásí někde hlouběji, většinou na konkrétní stránce (kde ho k tomu instruuje nápověda), která je chráněná nějakou licencí, tak je přesměrován standardně na Keycloak.

Tam proběhne autentizace a autorizace, a pokud je úspěšná (a asi i v případě neúspěšné), tak by se uživatel měl vrátit na stejné místo v digitální knihovně, kde přihlášení inicioval - tedy většinou zase na konkrétní stránku.

To se ale teď neděje, uživatel se z Keycloaku vrací na úvodní stránku digitální knihovny, což není optimální.

V K5 se používal atribut `?target=...`, takže IdP věděl, kam poslat uživatelovu prohlížeči přesměrování. To ale v K7/Keycloaku nefunguje.

Jsme schopni to vyřešit?

Díky, MD

**Comment by vlahoda** [comment]
V Keycloaku je na totez potreba pouzit atribut redirect_uri. Otazka na @pavel-stastny - podporuje to API endpoint token? A otazka na @honza-rychtar - posila to klient?

**Comment by annie-cz** [comment]
Mělo by být součástí releasu v2.5.1. na klientovi. Můžeme zavřít @vlahoda ?

**Comment by vlahoda** [comment]
Funguje to,  muzeme zavrit
